elastic/elasticsearch-net

src/Elasticsearch.Net/Connection/RequestHandlers/RequestHandler.cs
src/Elasticsearch.Net/Connection/RequestHandlers/RequestHandlerAsync.cs
src/Tests/Nest.Tests.Integration/Reproduce/Reproduce1176Tests.cs

When using connection pooling (and retrying), `WebException`s fall out of the normal exception handling in `RequestHandler` and weren't being added to `SeenExceptions`, ultimately causing `MaxRetryException.InnerException` to be null.
Closes #1176

Fix null inner exception when retrying on WebException

---

src/Nest/DSL/Aggregations/TopHitsAggregationDescriptor.cs
src/Nest/Domain/Aggregations/AggregationsHelper.cs
src/Nest/Domain/Aggregations/TopHitsMetric.cs
src/Nest/Resolvers/Converters/Aggregations/AggregationConverter.cs
src/Tests/Nest.Tests.Integration/Aggregations/MetricAggregationTests.cs

Highlighting, explain, script fields, fielddata fields, and include
versions
Closes #1168

Top hits: add support for options that were missing

---

src/Connections/Elasticsearch.Net.Connection.Thrift/ThriftConnection.cs
src/Connections/Elasticsearch.Net.Connection.Thrift/Transport/TSocket.cs

because it used the request timeout for connect timeout, transport will kill coordinated requests if the total running time takes longer then the specified timeout as introduced here:
https://github.com/elasticsearch/elasticsearch-net/pull/1093

Fix #1166 failing thrift test

---

src/Connections/Elasticsearch.Net.Connection.Thrift/ThriftConnection.cs
src/Elasticsearch.Net/Connection/Configuration/ConnectionConfiguration.cs
src/Elasticsearch.Net/Connection/Configuration/IConnectionConfigurationValues.cs

Which required adding `ConnectTimeout` to `ConnectionSettings`.  Now the timeout options are a bit more consistent between `ConnectionSettings` and `RequestConfiguration`.
Also cleaned up the xmldocs a bit.

Use ConnectTimeout instead of PingTimeout for thrift connections

---

src/Nest/Domain/Aggregations/BucketAggregationBase.cs
src/Nest/Domain/Aggregations/SingleBucket.cs
src/Tests/Nest.Tests.Unit/Nest.Tests.Unit.csproj
src/Tests/Nest.Tests.Unit/Search/Aggregations/SingleBucketAggregationTests.cs

When I want to test a function that converts aggregation results into something else I need to set the inner aggregations of a `SingleBucket` in order to set up the test data. This class however doesn't currently expose the constructors of its base classes so it's not possible.

Expose constructor with inner aggregation dictionary

---

src/Nest/DSL/Query/FunctionScoreQueryDescriptor.cs
src/Nest/DSL/Query/Functions/IFunctionScoreFunction.cs
src/Tests/Nest.Tests.Unit/Search/Query/Singles/FunctionScoreQueryJson.cs
src/Tests/Nest.Tests.Unit/Search/Sorting/FunctionScoreTests.cs

fix #1210 fix #1087 
Both of the previous PR's submitted a sane way to fix this issue but break backward compatibility. 
This PR is a bit of a hack to make sure if you are using the object initializer syntax we don't break your code. 
Fluent syntax remains `.Weight(long|double)`

Floating weights on function score query / functions

---

src/Nest/Domain/Analysis/Analyzers/Language.cs

Elastic Search has support for a built in Irish language analyzer but NEST is missing the enumeration value. 
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html#irish-analyzer

Added support for the Elastic Search Irish language analyzer.

---

src/Nest/DSL/UpdateSettingsDescriptor.cs
src/Tests/Nest.Tests.Unit/Core/UpdateSettings/AllUpdateSettings.json
src/Tests/Nest.Tests.Unit/Core/UpdateSettings/UpdateSettingsTests.cs
src/Tests/Nest.Tests.Unit/ObjectInitializer/UpdateSettings/UpdateSettingsBody.json
src/Tests/Nest.Tests.Unit/ObjectInitializer/UpdateSettings/UpdateSettingsRequestTests.cs

Add index-settings for index.cache.query.enable

---

src/Nest/DSL/Paths/IndexTypePathDescriptor.cs
src/Tests/Nest.Tests.Unit/BigBadUrlUnitTests.cs

on untyped IndexTypePaths steal the type's type information and use it to infer index as well if no index has been explicitly set.

fix #1251 Smarter untyped baseindextypepath

---

src/Nest/DSL/Aggregations/TermsAggregationDescriptor.cs
src/Nest/Enums/TermsAggregationCollectMode.cs
src/Nest/Nest.csproj
src/Tests/Nest.Tests.Integration/Aggregations/TermsAggregationTests.cs

Support for __collect_mode__ in terms aggregation descriptor
---------------------------------------------------
**"collect_mode"** on a terms aggregation specifies, to use either __depth first__ or __breadth first__ evaluation of nested terms aggregations.
In __breadth_first__ mode, Elastic search supports calculation of child aggregation, after the pruning of parent aggregation is done, this can prevent certain combinatorial explosions child aggs can bring in depending on your data mappings and queries.
[Details from Elasticsearch documentation](
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_collect_mode)

Adding collect_mode to terms aggretation descriptor

---

src/Connections/Elasticsearch.Net.Connection.HttpClient/HttpClientConnection.cs
src/Elasticsearch.Net/Connection/Configuration/ConnectionConfiguration.cs
src/Elasticsearch.Net/Connection/Configuration/IConnectionConfigurationValues.cs
src/Elasticsearch.Net/Connection/HttpConnection.cs

so you do not need to subclass HttpConnection and override `AlterServicePoint()` to set it.
Sidenote:
I also added an Obsolete on `HttpClientConnection` indicating its not as well tested as `HttpConnection` and as a heads up that with Elasticsearch.NET/NEST 2.0 we'll be moving the default `HttpConnection` over to `HttpClient` anyway. 
Im still not totally sure about moving over to `HttpClient` though, yes its a nicer interface, but there is a real benefit of having a **true** synchronous code path without the overhead of async dispatching even if that happens on IOCP threads. Calling `.Result` on a task is not really equivalent.
We might endup ifdeffing `HttpConnection` specifically for `aspnetcore50`, still lots to research and measure :)

expose SetTcpKeepAlive() on ConnectionSettings 

---

src/Elasticsearch.Net/Connection/Transport.cs
src/Elasticsearch.Net/ConnectionPool/IConnectionPool.cs
src/Elasticsearch.Net/ConnectionPool/SingleNodeConnectionPool.cs
src/Elasticsearch.Net/ConnectionPool/StaticConnectionPool.cs
src/Nest/Domain/Observers/RestoreObservable.cs
src/Nest/Domain/Observers/SnapshotObservable.cs
src/Tests/Elasticsearch.Net.Tests.Unit/ConnectionPools/Sniffing/SniffingConnectionPoolTests.cs

All the time it will resend a sniff on each `new()` :cry: , this fixes that by doing additional bookkeeping on IConnectionpool.
ty @poulfoged for reporting this [on twitter](https://twitter.com/Mpdreamz/status/570590301041123328)

When using SniffOnStartup() and newing clients

---

src/Connections/Elasticsearch.Net.Connection.Thrift/Transport/TSocket.cs

This was happened when a lot of simulating non framed thrift connection try to open. When we rebuild our indexes (worker threads - builds index).
After one testing day, a exception described in issue #1254 didn't raise.

Develop - problem with opening thrift connection

---

src/Nest/Domain/Aggregations/ExtendedStatsMetric.cs
src/Nest/Resolvers/Converters/Aggregations/AggregationConverter.cs
src/Tests/Nest.Tests.Integration/Aggregations/StatsAggregationTests.cs

Added in ES 1.4.3.  This consequently fixes a deserialization
exception that occurs when running against an ES version earlier
than 1.4.3.
Closes #1281

Add support for standard deviation bounds to extended stats

---

docs/contents/nest/core/percolate.markdown

Very small fix for a broken url in NEST documentation

Fixed link to official documentation for Percolate in NEST core documentation.

---

src/Nest/DSL/PutMappingDescriptor.cs
src/Nest/Resolvers/Writers/TypeMappingWriter.cs
src/Tests/Nest.Tests.Unit/Core/Map/Enums/EnumCanBeOverriddenAfterMapFromAttributes.json
src/Tests/Nest.Tests.Unit/Core/Map/Enums/EnumMappingTests.cs
src/Tests/Nest.Tests.Unit/Core/Map/Enums/EnumShouldMapToIntByDefault.json
src/Tests/Nest.Tests.Unit/Core/Map/Structs/EnumMappingTests.cs
src/Tests/Nest.Tests.Unit/Core/Map/Structs/StructWithAttributeButNoTypeInformationThrows.json
src/Tests/Nest.Tests.Unit/Core/Map/Structs/StructWithNoAttributeSetIsIgnored.json
src/Tests/Nest.Tests.Unit/Nest.Tests.Unit.csproj
src/Tests/Nest.Tests.Unit/Reproduce/Reproduce901Tests.cs

They are now mapped to integers by default (as per json.net defaults). 
You can still remap them to (not_analyzed) strings after a `MapFromAttributes()` call.
fixes #901

fixes enums being skipped when calling MapFromAttributes()

---

docs/contents/elasticsearch-net/handling-responses.md

Just two minor link typos in docs.

[Docs] fixed link typos

---

src/Nest/DSL/Query/FunctionScoreQueryDescriptor.cs

Allows you to specify e.g: `.ConditionlessWhen(string.IsNullOrEmpty(query))` on a function score query to prevent functions to be applied in case of an empty query or fixed references inside the functions

ConditionlessWhen on function_score query

---

src/Nest/Domain/Mapping/Attributes/ElasticPropertyAttribute.cs
src/Nest/Domain/Mapping/Attributes/IElasticPropertyAttribute.cs
src/Nest/Resolvers/Writers/WritePropertiesFromAttributeVisitor.cs
src/Tests/Nest.Tests.Integration/Mapping/MapFromAttributeTests.cs
src/Tests/Nest.Tests.Integration/Nest.Tests.Integration.csproj
src/Tests/Nest.Tests.Unit/Core/AttributeBasedMap/IncludeInParentTests.cs
src/Tests/Nest.Tests.Unit/Core/AttributeBasedMap/TestIncludeInParent.json
src/Tests/Nest.Tests.Unit/Nest.Tests.Unit.csproj

PR contains fix for https://github.com/elastic/elasticsearch-net/issues/1307.
I modified `IElasticPropertyAttribute` and `WritePropertiesFromAttributeVisitor` to handle missing property.

IncludeInParent elastic property in NEST #1307

---

src/Nest/DSL/Query/MatchQueryDescriptor.cs
src/Nest/Resolvers/Converters/Queries/MatchQueryJsonConverter.cs
src/Tests/Nest.Tests.Unit/QueryParsers/Queries/MatchQueryTests.cs
src/Tests/Nest.Tests.Unit/Search/Query/Singles/MatchQueryJson.cs

PR for https://github.com/elastic/elasticsearch-net/issues/1333.
Looks like [fuzzy_transpositions](https://github.com/elastic/elasticsearch/pull/6300) parameter is available since 1.1.3 ES version. Would be great to prepare hot fix for previous versions of NEST? I'm not quite sure if I have such skill to do this.

Missing fuzzy_transpositions support in MatchQuery #1333

---

src/Nest/ExposedInternals/ElasticInferrer.cs
src/Nest/Resolvers/IdResolver.cs
src/Nest/Resolvers/TypeNameResolver.cs
src/Tests/Nest.Tests.Unit/Internals/Inferno/IdLookupTests.cs
src/Tests/Nest.Tests.Unit/Internals/Inferno/MapIdPropertyForTests.cs

not utilizing idlookup delegate cache and doing reflection on each lookup :cry:

fix id properties configured on connection settings

---

build/Elasticsearch.Net.Connection.Thrift.nuspec
build/Elasticsearch.Net.JsonNET.nuspec
build/Elasticsearch.Net.nuspec
build/NEST.nuspec

resolve #1346 NEST and Elasticsearch.NET bad nuspec files that makes the package not usable in .NET 4.0

Fix bad nuspec output path for .NET 4.0 nuget packages

---

src/Nest/DSL/Query/FunctionScoreQueryDescriptor.cs
src/Tests/Nest.Tests.Unit/QueryParsers/Queries/FunctionScoreQueryTests.cs
src/Tests/Nest.Tests.Unit/Search/Sorting/FunctionScoreTests.cs

PR for https://github.com/elastic/elasticsearch-net/issues/1344 issue.

Support for `min_score` parameter on function score query #1344

---

src/Nest/DSL/Aggregations/SignificantTermsAggregationDescriptor.cs
src/Nest/Domain/Aggregations/ISignificantTermsHeuristic.cs

Add percentage and scripted heuristics to significant terms

---

src/Nest/DSL/RestoreDescriptor.cs
src/Nest/DSL/UpdateSettingsDescriptor.cs
src/Tests/Nest.Tests.Integration/Core/Repository/RestoreTests.cs
src/Tests/Nest.Tests.Unit/Core/Repository/Restore.json
src/Tests/Nest.Tests.Unit/Core/Repository/RestoreTests.cs
src/Tests/Nest.Tests.Unit/Nest.Tests.Unit.csproj

PR for https://github.com/elastic/elasticsearch-net/issues/1362 issue.
For `IndexSettings` property on `IRrestoreDescriptor` I reused `IUpdateSettingsRequest`, but I'm not sure if this name fits in this context. Way how we can combine `RestoreDescriptor` with `UpdateSettingsDescriptor` is really nice.
Moreover, I've extracted all setting names to separate class. Avoiding googling for each plain index setting is really convenient.
Any thoughts? Let me know.
Thanks.

Support for supplying index settings on restore #1362

---

src/Elasticsearch.Net/Connection/Configuration/ConnectionConfiguration.cs
src/Elasticsearch.Net/Connection/Configuration/IConnectionConfigurationValues.cs
src/Elasticsearch.Net/Connection/RequestHandlers/RequestHandlerBase.cs
src/Elasticsearch.Net/Serialization/ElasticsearchDefaultSerializer.cs

fixes https://github.com/elastic/elasticsearch-net/issues/1316

Added UsePrettyRequests() and PrettyJson() to connectionsettings

---

src/Nest/DSL/Query/HasChildQueryDescriptor.cs
src/Nest/Domain/DSL/ChildScoreType.cs
src/Nest/Enums/TopChildrenScore.cs
src/Tests/Nest.Tests.Unit/QueryParsers/Queries/HasChildQueryTests.cs

While adding `min` score type, also discovered that we were missing the `min_children` and `max_children` parameters on `has child`.
Closes #1360

Has child/top children: support for min score type and min/max_children

---

src/CodeGeneration/CodeGeneration.LowLevelClient/Overrides/Descriptors/SearchDescriptorOverrides.cs
src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
src/Nest/DSL/Search/IGlobalInnerHit.cs
src/Nest/DSL/Search/InnerHitsDescriptor.cs
src/Nest/DSL/SearchDescriptor.cs
src/Nest/DSL/_Descriptors.generated.cs
src/Nest/DSL/_Requests.generated.cs
src/Nest/Domain/RequestParametersExtensions.Generated.cs
src/Tests/Nest.Tests.Integration/Search/FieldTests/FieldsTest.cs
src/Tests/Nest.Tests.Integration/Search/InnerHitsTests.cs

This was largely implemented already but with a few issues.  I had to modify the code gen to skip the fielddata_fields param in order to work around https://github.com/elastic/elasticsearch/issues/11025.
Also modified the implementation on inner hits to be more consistent with search (i.e. `IList<PropertyPathMarker>` vs `IEnumerable<string>` and added an overload that accepts property path expressions).
Closes #1366

Fix fielddata fields on search and inner hits

---

src/Nest/Domain/Mapping/SpecialFields/TimestampFieldMapping.cs

See also: http://www.elastic.co/guide/en/elasticsearch/reference/1.5/mapping-timestamp-field.html#mapping-timestamp-field-default

fix #1105 add default and ignore_missing to timestamp mappings

---

src/Nest/DSL/SuggestDescriptor.cs
src/Tests/Nest.Tests.Unit/Nest.Tests.Unit.csproj
src/Tests/Nest.Tests.Unit/Search/suggest/SuggestUrlTest.cs

Fix for default index on suggests

---

src/Nest/DSL/Query/DismaxQueryDescriptor.cs

This allows it to act like other descriptors that get formatted into an array, such as Bool Query's Should, if you've already composed your QueryContainers elsewhere.

Added overload to DismaxQueryDescriptor's Queries method to take QueryContainer[]

---

src/Nest/DSL/MultiGet/IMultiGetOperation.cs
src/Tests/Nest.Tests.Unit/Search/Query/Singles/MoreLikeThisQueryJson.cs

MultiGetOperation can now be deserialized as MultiGetOperationDescriptor<object> is now default
JsonConverter.
Resolved https://github.com/elastic/elasticsearch-net/issues/1415
Added unit tests to verify the outcome.

IMultiGetOperation can now be deserialized

---

src/Elasticsearch.Net/Connection/RequestHandlers/RequestHandlerAsync.cs
src/Elasticsearch.Net/Elasticsearch.Net.csproj
src/Elasticsearch.Net/Extensions/ExceptionExtensions.cs
src/Nest/ElasticClient.cs
src/Nest/Extensions/ExceptionExtensions.cs
src/Nest/Nest.csproj
src/Tests/Nest.Tests.Integration/Exceptions/ElasticsearchExceptionTests.cs

This pull request aim to fix #1399 by using the internal `InternalPreserveStackTrace` method of `Exception`.
There is a clean non-reflection way to do in in .Net 4.5 using `ExceptionDispatchInfo` (See [this blog](http://blogs.microsoft.co.il/sasha/2011/10/19/capture-transfer-and-rethrow-exceptions-with-exceptiondispatchinfo-net-45/)) but it would require changing the target version.
The unit test wouldn't catch all causes of exception callstack being erased, only a direct regression.

Keep exceptions stack trace in NEST ElasticClient Async calls

---

src/Nest/DSL/Query/MoreLikeThisQueryDescriptor.cs
src/Tests/Nest.Tests.Unit/Search/Query/Singles/MoreLikeThisQueryJson.cs

Hello guys,
Right now we are unable to run query like this one:
````
var searchResponse = client.Search<Document>(s => s.Query(q => q
.MoreLikeThis(mlt => mlt.Documents(docs => docs.Document(new Document {Id = 1})))));
````
It sends empty query to elasticsearch:
````
StatusCode: 200, 
Method: POST, 
Url: http://localhost:9200/my_index/document/_search, 
Request: {}, 
````
[Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html#_parameters_8) stays that
> The only required parameters are either docs, ids or like_text
so I think this PR should resolve the issue.
Reported on [SO](http://stackoverflow.com/questions/30598932/elasticsearch-nest-dismax-morelikethis-query).
Thanks.

MoreLikeThis query should accept documents or ids

---

src/Nest/DSL/Reindex/ReindexDescriptor.cs
src/Nest/Domain/Observers/ReindexObservable.cs
src/Tests/Nest.Tests.Integration/Index/ReindexTests.cs

The current scroll search size for reindexing is hard coded. Allow the size to be changed using the ReindexDescriptor.

Add size parameter to reindex descriptor

---

src/Nest/Domain/Mapping/Descriptors/CorePropertiesDescriptor.cs
src/Nest/Domain/Mapping/Descriptors/MurmurHashMappingDescriptor.cs
src/Nest/Domain/Mapping/Descriptors/PropertiesDescriptor.cs
src/Nest/Domain/Mapping/Descriptors/SingleMappingDescriptor.cs
src/Nest/Domain/Mapping/Types/Murmur3HashMapping.cs
src/Nest/Enums/FieldType.cs
src/Nest/Nest.csproj
src/Nest/Resolvers/Writers/TypeMappingWriter.cs
src/Tests/Nest.Tests.Unit/Core/Map/FluentMappingFullExampleTests.cs
src/Tests/Nest.Tests.Unit/Core/Map/Properties/MultiFieldProperty.json
src/Tests/Nest.Tests.Unit/Core/Map/Properties/MurmurHashProperty.json
src/Tests/Nest.Tests.Unit/Core/Map/Properties/PropertiesTests.cs
src/Tests/Nest.Tests.Unit/Nest.Tests.Unit.csproj

Adding support for the mumur3 mapping type, mainly for use with the cardinality aggregation as explained here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html#_pre_computed_hashes
This feels a bit dirty though IMO, since we have to treat it as an `IElasticCoreType` in order for it to work as a multi field.
We need to rethink the current object graph for mapping types for 2.0, but that's a separate issue.
Closes #1441

Support for murmur3 mapping type

---

src/Nest/Domain/Responses/UpgradeStatusResponse.cs
src/Nest/Domain/Status/UpgradeStatus.cs
src/Nest/ElasticClient-Upgrade.cs
src/Nest/Nest.csproj
src/Nest/Resolvers/Converters/UpgradeStatusResponseConverter.cs

The _upgrade response has changed in ES 1.6.  This commit adds a custom
JSON converter in order to support the ES <= 1.5 response as well as the
newer 1.6 response.
ES <= 1.5.x
```json
{
"nest_test_data-11800": {
"size_in_bytes": 153183,
"size_to_upgrade_in_bytes": 0
}
}
```
versus
ES 1.6
```json
{
"size_in_bytes": 153218,
"size_to_upgrade_in_bytes": 0,
"size_to_upgrade_ancient_in_bytes": 0,
"indices": {
"nest_test_data-10872": {
"size_in_bytes": 153218,
"size_to_upgrade_in_bytes": 0,
"size_to_upgrade_ancient_in_bytes": 0
}
}
}
```
I hate writing code like this, and adding another custom converter, but I don't see another way around it for now.  Please review @Mpdreamz.

Add custom converter for UpgradeStatusResponse

---

src/Nest/Enums/FieldType.cs
src/Nest/Resolvers/Writers/TypeMappingWriter.cs
src/Tests/Nest.Tests.Unit/Core/AttributeBasedMap/AllTypesTest.cs
src/Tests/Nest.Tests.Unit/Core/AttributeBasedMap/TestAllTypes.json
src/Tests/Nest.Tests.Unit/Nest.Tests.Unit.csproj

Fix #1479: Full integral type coverage for field type serialization

---

src/Nest/Nest.csproj

File \src\Nest\Resolvers\Converters\UriJsonConverter.cs was in Nest.csproj but wasn't on disk.
I started #1477 from branch 2.0 and noticed this little error.

Build error in 2.0 due to missing file

---

src/Nest/Domain/Responses/MultiTermVectorResponse.cs
src/Nest/Domain/Responses/TermVectorResponse.cs
src/Tests/Nest.Tests.Integration/Core/TermVectors/MultiTermVectorsTests.cs

Obsoleted `.Documents` in favor of `.Docs` in 1.x. 
In `2.0` we'll switch back to `.Documents`

Fix #1484 Added document metadata to multitermvectors response

---

src/Nest/Domain/Responses/UpdateResponse.cs
src/Tests/Nest.Tests.Integration/Core/UpdateTests.cs

Update API allows you to get the `_source` or `fields` in one go, this was blatantly missing from our mappings thanks @jcachat for reporting.
For backwards compat reasons this object is untyped.

fix #1296 map get response on the update response

---

src/Nest/DSL/Reindex/ReindexDescriptor.cs
src/Nest/Domain/Observers/ReindexObservable.cs
src/Nest/ElasticClient-Reindex.cs
src/Nest/IElasticClient.cs
src/Tests/Nest.Tests.Integration/Index/ReindexTests.cs

Support reindex with to better syntax

---

src/Nest/Domain/Mapping/SpecialFields/TimestampFieldMapping.cs
src/Tests/Nest.Tests.Unit/Core/Map/TimestampField/TimestampFieldTests.cs
src/Tests/Nest.Tests.Unit/Core/Map/TimestampField/TimestampFieldUsingString.json

#1533  Any unit tests to implement?

add store to timestamp field mapping #1533

---

src/Nest/DSL/Search/HighlightFieldDescriptor.cs

There are missing HighlightQuery method in HighlightFieldDescriptor and we cannot set query for every highlight field. I fixed that missing behavior.

Added HighlightQuery to HighlightFieldDescriptor

---

src/Nest/Cluster/NodeStats/NodeStats.cs

As discussed previously, here is the clean PR for the 2.0

NodeStats: fix typo + add HeapMax to JVM Mem stats

---

src/Nest/Domain/Property.cs

Hi all, 
Noticed the following while looking at some intellisense using NEST:
Figured I'd patch up the typo quickly and contribute something back, however minor, to this awesome library.
Resolves #1568.

Fix minor typo in xmldoc comments

---

src/Tests/Tests.csproj

Ups ... Tests.csproj was referencing Indexing.url.cs instead of Index.url.cs.

Index.url.cs added to Tests.csproj

---

src/Tests/Modules/Scripting/ScriptingCrudTests.cs
src/Tests/Tests.csproj

Hi,
PR contains crud tests for scripts https://github.com/elastic/elasticsearch-net/issues/1586.
Don't know why `DeleteCallsIsValid` don't pass. Any ideas?
Any feedback appreciated.

Crud tests for scripting module

---

src/Nest/QueryDsl/TermLevel/Ids/IdsQuery.cs

The `Values(params long[] values)` method in the IdsQueryDescriptor wasn't setting the `IIdsQuery.Values` property with the passed in array of long. This was causing a NullReference exception to be thrown when calling this method.

IdsQueryDescriptor.Values(params long[] values) isn't assigning to Values correctly

---

src/Nest/DSL/Query/BoolQueryDescriptor.cs

Should and MustNot methods had their documentation reversed.

Fix mixed up doc comments

---

src/Nest/DSL/PutAliasDescriptor.cs
src/Nest/Domain/Cat/CatAliasesRecord.cs
src/Tests/Elasticsearch.Net.Tests.Unit/Elasticsearch.Net.Tests.Unit.csproj
src/Tests/Nest.Tests.Integration/Nest.Tests.Integration.csproj
src/Tests/Nest.Tests.Integration/Reproduce/Reproduce1591Tests.cs

Hi,
This PR fixes #1591.
One more thing fixed - there was no way to specify `search_routing` and `index_routing` parameters when [creating alias](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-aliases.html#aliases-routing).

Fix for CatAliases API #1591

---

src/Nest/Search/Search/Hits/Hit.cs

Cannot find any reasons for removing it.
This prevents getting Score by interface.

- re-add Score property to IHit interface

---

src/Nest/CommonAbstractions/Infer/Fields/Fields.cs

For example, given a `SearchRequest`, I'd like to be able to determine which fields were included in the request (using `Source.Include`)

I'd like to be able to iterate fields from outside nest.

---

src/Nest/DSL/MultiPercolate/IPercolateOperation.cs
src/Nest/Domain/Responses/PercolateResponse.cs

When serializing the PercolateDescriptor, the sort property was
incorrectly being serialized as 'score' and not 'sort'. This is now
fixed.
When Percolating with a query, size and trackscores=true, the raw
response contains a score, but the PercolateResponse class does not.
This is now fixed/added.

PercolateDescriptor serialization bug fix and addition of Score to PercolateResponse

---

src/Elasticsearch.Net/Purify/Purify.cs

This is  a re-submit of PR #1651 against the master branch. I've also submitted this change as another pull request to the [PUrify-net](https://github.com/Purify-net/PUrify) repository.
----
It looks like commit 5b0bd6c refactored this class and lost pieces of the code that respect port numbers as well as the absence of query strings in the given URI.
This was causing `System.ArgumentOutOfRangeException : StartIndex cannot be less than zero.` exceptions to be thrown from my project which is targeting .NET 4.6.
I just took the same code in the UriInfo class prior to commit 5b0bd6c and re-added it to the refactored class.

UriInfo class is improperly parsing URIs

---

src/Elasticsearch.Net/Serialization/ElasticsearchDefaultSerializer.cs
src/Elasticsearch.Net/Serialization/IElasticsearchSerializer.cs
src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettings.cs
src/Nest/CommonAbstractions/Infer/Field/FieldResolver.cs
src/Nest/CommonAbstractions/SerializationBehavior/JsonNetSerializer.cs
src/Nest/Document/Multiple/MultiGet/ElasticClient-MultiGet.cs
src/Nest/Mapping/AttributeBased/ElasticsearchPropertyAttribute.cs
src/Nest/Nest.csproj
src/Nest/Search/MultiSearch/ElasticClient-MultiSearch.cs
src/Nest/Search/MultiSearch/MultiSearchResponseJsonConverter.cs
src/Nest/Search/Search/ElasticClient-Search.cs
src/Nest/Search/SearchTemplate/ElasticClient-SearchTemplate.cs
src/Tests/ClientConcepts/HighLevel/Inferrence/FieldNames/FieldInference.doc.cs
src/Tests/ClientConcepts/HighLevel/Mapping/AutoMap.doc.cs
src/Tests/Framework/TestClient.cs
src/Tests/Mapping/Types/Geo/GeoPoint/GeoPointMappingTests.cs

Now we ask the configured `IElasticsearchSerializer` if it can resolve the `MemberInfo` to a fieldname.
Precedence:
* NEST mapping attributes
* Ask serializer (default looks for JsonProperty)
* PropertyNameInferrer(MemberInfo.Name) (default camelCase)
also renamed NestSerializer to JsonNetSerializer,

JsonProperty now taken into account when inferring properies

---

src/Elasticsearch.Net/Connection/RequestHandlers/RequestHandler.cs
src/Elasticsearch.Net/Connection/RequestHandlers/RequestHandlerAsync.cs
src/Elasticsearch.Net/Connection/RequestHandlers/RequestHandlerBase.cs

Service Unavailable can happen before shards are updates (creating
a new index, and then query it before it's created). These errors
are not reported as regular errors, and receives a very generic
errormessage. This commit improves the error message for these errors.
Closes #1596

Improve "Service Unavailable" error reporting

---

src/Nest/CommonAbstractions/SerializationBehavior/StatefulDeserialization/ConcreteTypeConverter.cs
src/Nest/Search/Search/Hits/Hit.cs

I noticed that the `_parent` and `_routing` fields for search responses were not being mapped to the Hit class. This commit simply adds the mapping for those two fields.

Added Parent and Routing fields to the Hit class

---

src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettings.cs
src/Nest/CommonAbstractions/ConnectionSettings/IConnectionSettingsValues.cs
src/Nest/CommonAbstractions/Extensions/TypeExtensions.cs
src/Nest/CommonAbstractions/SerializationBehavior/ElasticContractResolver.cs
src/Nest/CommonAbstractions/SerializationBehavior/JsonNetSerializer.cs
src/Nest/Search/MultiSearch/MultiSearchResponseJsonConverter.cs
src/Tests/ClientConcepts/LowLevel/Connecting.doc.cs

removed:
```diff
- JsonSerializerSettingsModifier(Action<JsonSerializerSettings> modifier)		
-AddContractJsonConverters(params Func<Type, JsonConverter>[] contractSelectors)		
```
From `ConnectionSettings`. 
It now takes a `Func<TConnectionSettings, IElasticsearchSerializer> factory` to inject subclasses of `JsonNetSerializer` e.g
```charp
public class MyJsonNetSerializer : JsonNetSerializer
{
public int X { get; set; } = 0;
public MyJsonNetSerializer(IConnectionSettingsValues settings) : base(settings) { }
protected override void ModifyJsonSerializerSettings(JsonSerializerSettings settings)
{
++X;
}
}
[U] public void IsCalled()
{
var connectionPool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
var settings = new ConnectionSettings(connectionPool, new …
```

Overriding of json net no longer a concern of connectionsettings

---

docs/build/nest/index-type-inference.html
docs/contents/nest/index-type-inference.markdown

Corrects code examples in Property Name Inference docs

---

src/Elasticsearch.Net/Elasticsearch.Net.xproj
src/Nest/Nest.xproj
src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
src/Nest/QueryDsl/Abstractions/Query/QueryDescriptorBase.cs
src/Nest/QueryDsl/Query.cs
src/Nest/QueryDsl/TermLevel/Prefix/PrefixQuery.cs
src/Nest/QueryDsl/TermLevel/Term/TermQuery.cs
src/Nest/QueryDsl/TermLevel/Terms/TermsQuery.cs
src/Nest/QueryDsl/TermLevel/Terms/TermsQueryJsonConverter.cs
src/Nest/QueryDsl/TermLevel/Wildcard/WildcardQuery.cs

Did a final pass over the convenience query methods (shortcuts into the selector overload). 
Sadly the intellisense experience for `q=>q.Term(p,` does not improve if we rename the `.Term(selector)` overload so `Term()` still has three overloads.
Opted out of created convenience overloads for Tersm because it will introduce
```csharp
.Terms<K>(string, IEnumerable<K>)
.Terms<K>(Expression, IEnumerable<K>)
.Terms<K>(string, params K[])
.Terms<K>(Expression, params K[])
```
And then intellisense will  show `.Terms` and `.Terms<>` as two distinct options.
Fixed a small issue with TermQueryBase not being abstract and not curiously revealing the right descriptor for the return type.

final passover the convenience methods, relates to #1612

---

src/Nest/Document/Multiple/Reindex/ReindexObservable.cs
src/Nest/Document/Multiple/Reindex/ReindexRequest.cs
src/Nest/Document/Multiple/Reindex/ReindexResponse.cs
src/Tests/Document/Multiple/Reindex/ReindexApiTests.cs

Current implementation takes a generic ReindexDescriptor<T> but specifies all types when performing the scan and scroll for retrieving documents to reindex. The type of T should be used as the type of documents to target in the reindex operation, with methods exposed to allow the consumer to specify other other types / all types.
See https://github.com/elastic/elasticsearch-net/issues/1433

Support specifying one or many types as part of Reindexing

---

src/Elasticsearch.Net/Exceptions/ElasticsearchClientException.cs
src/Elasticsearch.Net/Responses/ElasticsearchResponse.cs
src/Elasticsearch.Net/Responses/IApiCallDetails.cs
src/Elasticsearch.Net/Responses/ServerError.cs
src/Nest/Aggregations/Bucket/SignificantTerms/SignificantTermsAggregation.cs
src/Nest/Cluster/NodesStats/NodesStatsRequest.cs
src/Nest/CommonAbstractions/Response/ApiCallDetailsOverride.cs
src/Nest/CommonAbstractions/Response/ResponseBase.cs
src/Nest/CommonOptions/Failures/BulkError.cs
src/Nest/Document/Multiple/Bulk/BulkResponse.cs
src/Nest/Document/Multiple/Bulk/BulkResponseItem/BulkResponseItemBase.cs
src/Nest/Search/MultiSearch/MultiSearchResponse.cs
src/Nest/Search/Percolator/MultiPercolate/MultiPercolateResponse.cs
src/Tests/ClientConcepts/Exceptions/ExceptionTests.cs
src/Tests/Framework/ApiTestBase.cs
src/Tests/Framework/TestClient.cs
src/Tests/tests.yaml

This PR adds a `.DebugInformation` property on responses & exceptions which acts as the goto diagnosis tool both for devs using NEST and for us maintainers to ask for when we receive a bug report.
```
Valid NEST response built from a succesful low level call on POST: /project/project/nest-92a78d48/_update?pretty=true&fields=name%2C_source
- HealthyResponse: Node: http://ipv4.fiddler:9200/ Took: 00:00:00.0105188
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
```
Individual responses can explain why they marked …

DebugInformation property on responses and exceptions

---

src/Nest/QueryDsl/Compound/Bool/BoolQuery.cs
src/Tests/Aggregations/Bucket/Filter/FilterAggregationUsageTests.cs
src/Tests/Search/Search/SearchApiTests.cs

Closes https://github.com/elastic/elasticsearch-net/issues/1820
Additional tests to ensure parity between fluent and OIS

Handle collection of QueryContainer where the first item is null

---

src/Nest/QueryDsl/Geo/GeoLocation.cs

The ToString() must be in a specific format for lat long of which we know... 
Also there is only so much precision you can specify (http://www.geomidpoint.com/latlon.html)
You wouldn't want a number converted to 1.3e6 or 1.12345678901234545666666556 when 8 points of precision gets you to 1/16th of an inch

Added a null check to GeoLocation and updated ToString()

---

src/Nest/QueryDsl/Geo/GeoLocation.cs

References https://github.com/exceptionless/Exceptionless.Net/pull/80
https://github.com/elastic/elasticsearch-net/pull/1814

Fixed an issue with implicit conversion and culture formatting of geo coordinates

---

build/scripts/Paths.fsx
src/Benchmarking/project.lock.json
src/CodeGeneration/Nest.Litterateur/project.lock.json
src/Elasticsearch.Net/ConnectionPool/StickyConnectionPool.cs
src/Elasticsearch.Net/project.lock.json
src/Nest/project.lock.json
src/Tests/ClientConcepts/ConnectionPooling/Sticky/SkipDeadNodes.doc.cs
src/Tests/ClientConcepts/ConnectionPooling/Sticky/Sticky.doc.cs
src/Tests/Framework/VirtualClustering/VirtualCluster.cs
src/Tests/project.lock.json

See #1810
Not ready for merging and requires feedback. There's one skipped test which I wasn't sure how to do using your test framework, 
If you could take a look and provide feedback if their is a way. If not it might be worth investing in making a way as it's a slightly more advanced use case than the other tests I found, hopefully the test explains itself well enough, otherwise just ask.
Test can be found in this commit 8d1906a683e007e42429b05c5b1f83b8f1e285ba

Sticky Connection Pool

---

src/CodeGeneration/CodeGeneration.LowLevelClient/Views/_LowLevelDispatch.Generated.cshtml
src/Nest/CommonAbstractions/LowLevelDispatch/LowLevelDispatch.cs
src/Nest/_Generated/_LowLevelDispatch.generated.cs
src/Tests/ClientConcepts/Exceptions/ExceptionTests.cs

Dispatches into the low level client that do not have enough information to build a route will now indicate which values are missing
> Dispatching Index() from NEST into to Elasticsearch.NET failed
Received a request marked as POST
This endpoint accepts POST,PUT
The request might not have enough information provided to make any of these endpoints:
- /{index=`<NULL>`}/{type=project}
- /{index=`<NULL>`}/{type=project}/{id=`<NULL>`}
It now also throws an ArgumentException since its very much a "development time exception" and happens before we even establish a pipeline.

improved dispatch exception to indicate which values are missing

---

src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs

Calling a method on the low level client with Stream, VoidResponse, etc. fails with a NullReferenceException. This change fixes the reflection calls which (while seemingly correct) do not work at runtime.

Fix handling of return types.

---

src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
src/Tests/ClientConcepts/LowLevel/Connecting.doc.cs

Fix #1904 invoke OnRequestCompleted when exception is thrown

---

src/Elasticsearch.Net/Connection/InMemoryConnection.cs
src/Elasticsearch.Net/Responses/ServerError.cs
src/Profiling_Net45/Profiling.csproj
src/Tests/Framework/TestClient.cs
src/Tests/Reproduce/GithubIssue1901.cs
src/Tests/tests.yaml
src/Tests_Net45/Tests.csproj

Fixes #1901
Add ability to set a non-json fixed response and additionally an Exception when creating a FixedReturnClient.
Introduced async version of `ReturnConnectionStatus` on `InMemoryConnection` in order to use the async request/response pipeline (which is where the original issue manifests)

await CreateAsync() when try to create a ServerError asynchronously

---

src/Elasticsearch.Net/Elasticsearch.Net.csproj
src/Elasticsearch.Net/Exceptions/ResolveException.cs
src/Elasticsearch.Net/Transport/Transport.cs
src/Nest/CommonAbstractions/Infer/Field/FieldResolver.cs
src/Nest/CommonAbstractions/Infer/IndexName/IndexNameResolver.cs
src/Tests/ClientConcepts/HighLevel/Inferrence/IndexNameInference.doc.cs
src/Tests/ClientConcepts/HighLevel/Inferrence/PropertyInference.doc.cs
src/Tests/Tests.csproj
src/Tests/tests.yaml

Don't throw an ArgumentException if a field name contains a dot (.), instead let Elasticsearch decide.
Fixes #1889

Defer field naming conventions to Elasticsearch

---

src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
src/Elasticsearch.Net/Transport/Transport.cs
src/Tests/tests.yaml

The latter is only good for rethrowing inner exceptions, which no longer
serves a purpose in the refactored 2.x world`
ty for raising this @TioLuiso

fix #1947 favor throw; over e.RethrowKeepingStackTrace()

---

src/Nest/QueryDsl/TermLevel/Terms/TermsQuery.cs
src/Nest/QueryDsl/TermLevel/Terms/TermsQueryJsonConverter.cs
src/Tests/QueryDsl/QueryDslIntegrationTestsBase.cs
src/Tests/QueryDsl/TermLevel/Terms/TermsListQueryUsageTests.cs
src/Tests/QueryDsl/TermLevel/Terms/TermsQueryUsageTests.cs
src/Tests/Tests.csproj

When calling
```csharp
.Terms(new List<T>());
```
The user expects T[] to be written to elasticsearch but due to C#
resolution they end up calling
```csharp
.Terms<List<T>>(params List<T>)
```
and we serialize to T[][] which is not a valid terms query.
The fluent Terms() method now tries to preempt these cases and unwraps
to T[] when a single IEnumerable is passed as T, special casing `string`
to be exluded from the unwrapping behavior so we do not unwrap string to
char[]
This PR also introduces `QueryDslIntegrationTestsBase`, all of our QueryDSL tests are unit tests but with this new base class we can start introducing more integration tests for the query dsl over time /cc @gmarz @russcam

fix #1930 unwrap .Terms(new List<T>) to just T

---

src/Nest/Aggregations/Visitor/AggregationVisitor.cs
src/Nest/Aggregations/Visitor/AggregationWalker.cs

Forgot about these with #1967 . Maybe some tests to ensure correlation are in order?
Installed EditorConfig and now it shows the entire file as deletions and additions. Don't know why.

Added missing visitor implementations

---

docs/asciidoc/client-concepts/high-level/inference/field-inference.asciidoc
src/Nest/CommonAbstractions/Infer/Field/Field.cs
src/Tests/ClientConcepts/HighLevel/Inference/FieldInference.doc.cs

Throw an exception if more than one of Name, Property or Expression is set with a non-null value
Add documented tests for the changes
Regenerate docs
Fixes https://github.com/elastic/elasticsearch-net/issues/1964

Set ComparisonValue when using Field Constructor

---

src/Nest/Aggregations/Pipeline/BucketsPath.cs

Would like to be able to access the buckets path defined on SingleBucketsPath.
MultiBucketsPath already exposes this via dictionary.

Changed BucketsPath from internal to public

---

src/Nest/Mapping/NonStringIndexOption.cs
src/Nest/Mapping/Types/Core/Boolean/BooleanProperty.cs
src/Nest/Mapping/Types/Core/Date/DateProperty.cs
src/Nest/Mapping/Types/Core/Number/NumberProperty.cs
src/Nest/Mapping/Types/Specialized/Ip/IpProperty.cs
src/Nest/Mapping/Types/Specialized/TokenCount/TokenCountProperty.cs
src/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs

This PR is questionable because it changes the default behavior of `Index()`, which previously defaulted to `no`, but now will default to `not_analyzed`.
@Mpdreamz @russcam thoughts?
Closes #1979

Add not_analyzed to NonStringIndexOption and make it the default option

---

src/Nest/Mapping/Types/Core/String/StringAttribute.cs
src/Nest/Mapping/Types/Core/String/StringProperty.cs
src/Tests/Mapping/Types/Core/String/StringMappingTests.cs

Mark PositionOffsetGap as obsolete in favor of PositionIncrementGap

---

src/CodeGeneration/CodeGeneration.LowLevelClient/Domain/CsharpMethod.cs
src/Nest/CommonAbstractions/Infer/DocumentPath/DocumentPath.cs
src/Nest/CommonAbstractions/Request/RouteValues.cs
src/Nest/_Generated/_Descriptors.generated.cs
src/Tests/Document/Single/Get/GetUrlTests.cs
src/Tests/tests.yaml

```csharp
var response = await elasticClient.GetAsync<T>(id, s =>
s.Index(null));
```
Would not default index back to inferred type of T.
This PR makes specifying null for required route values a noop
For optional routevalues null still clears the routevalue so the
following still works
```csharp
c => c.Index(project, i => i.Id(null))
```
will reset the id on and send the index request to
`/inferredindex/inferredtype`

fix #1980 GetAsync fails when specifying a null index.

---

src/Nest/Indices/MappingManagement/PutMapping/PutMappingRequest.cs
src/Nest/Mapping/Transform/MappingTransform.cs
src/Nest/Mapping/Transform/MappingTransformJsonConverter.cs
src/Nest/Mapping/TypeMapping.cs

This is [deprecated in 2.0](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/mapping-transform.html) 
[Removed in 5.0](https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_mapping_changes.html#_source_transform_removed)
See https://github.com/elastic/elasticsearch-net/issues/2006

mark IMappingTransform as deprecated (obsolete)

---

src/Nest/Modules/Indices/Fielddata/String/StringFielddataFormat.cs

This looks to have been removed for Elasticsearch 2.0 -
[Exists in 1.7 docs](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/fielddata-formats.html#_string_field_data_types) 
[Missing in 2.0 docs]( https://www.elastic.co/guide/en/elasticsearch/reference/2.0/fielddata.html#fielddata-format)
Has been removed for NEST 5.x
Discovered as part of https://github.com/elastic/elasticsearch-net/issues/2005

mark doc_values obsolete for string field data format

---

src/Nest/CommonOptions/Fuzziness/Fuzziness.cs
src/Nest/CommonOptions/Fuzziness/FuzzinessJsonConverter.cs
src/Nest/CommonOptions/Fuzziness/IFuzziness.cs
src/Nest/QueryDsl/TermLevel/Terms/TermsQuery.cs
src/Nest/QueryDsl/TermLevel/Terms/TermsQueryJsonConverter.cs
src/Tests/QueryDsl/TermLevel/Terms/TermsListQueryUsageTests.cs
src/Tests/QueryDsl/TermLevel/Terms/TermsQueryUsageTests.cs

See https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_search_changes.html#_changes_to_queries for details.
See https://github.com/elastic/elasticsearch-net/issues/1997
deprecate fuzziness `ratio` and make setting it a **noop** - It looks like this was deprecated in 1.7 and should have been removed in 2.0 - https://www.elastic.co/guide/en/elasticsearch/reference/1.7/common-options.html#fuzziness

Changes to queries for 5.0

---

src/Nest/DSL/Suggest/Fuzziness.cs
src/Nest/DSL/Suggest/FuzzySuggestDescriptor.cs
src/Nest/DSL/Suggest/IFuzziness.cs
src/Nest/Resolvers/Converters/FuzzinessConverter.cs
src/Tests/Nest.Tests.Unit/ObjectInitializer/Search/SearchRequestTests.cs
src/Tests/Nest.Tests.Unit/ObjectInitializer/Suggest/SuggestRequestTests.cs
src/Tests/Nest.Tests.Unit/Search/InitializerSyntax/InitializerExample.cs
src/Tests/Nest.Tests.Unit/Search/Suggest/CompletionSuggestTests.cs

See https://github.com/elastic/elasticsearch-net/issues/1997
It looks like this was deprecated in 1.7 and removed in 2.0 - https://www.elastic.co/guide/en/elasticsearch/reference/1.7/common-options.html#fuzziness
Since it still exists in NEST 2.x, I've marked as deprecated here - will no-op in NEST 2.x

Deprecate fuzziness ratio

---

docs/breaking-changes.asciidoc
docs/client-concepts/high-level/inference/field-inference.asciidoc
docs/client-concepts/low-level/connecting.asciidoc
docs/common-options.asciidoc
docs/high-level.asciidoc
docs/low-level.asciidoc
docs/search-usage.asciidoc
docs/search.asciidoc
docs/search/request/from-and-size-usage.asciidoc
docs/search/search/rescoring/rescore-usage.asciidoc
src/CodeGeneration/CodeGeneration.LowLevelClient/CodeGeneration.LowLevelClient.project.lock.json
src/CodeGeneration/Nest.Litterateur/Nest.Litterateur.project.lock.json
src/CodeGeneration/Nest.Litterateur/Program.cs
src/Elasticsearch.Net/Elasticsearch.Net.project.lock.json
src/Nest/Search/Search/Rescoring/Rescore.cs
src/Nest/Search/Search/SearchRequest.cs
src/Tests/Search/Search/Rescoring/RescoreUsageTests.cs
src/Tests/Tests.csproj
src/Tests/search-usage.asciidoc

The interface for rescore, IRescore, cannot be changed in 2.x as it would break binary compatibility for 2.x.
A new concrete implementation of `IRescore`, `MultiRescore`, is introduced that allows for multiple rescore queries to be specified. When using OIS syntax, a new instance of `MultiRescore` should be used. When using the fluent API, the descriptor takes care of combining multiple rescore queries. A custom json converter takes care of serialization when a single or multiple rescore queries are specified.
The slightly awkward part with having `Rescore` and `MultiRescore` is that when an `IRescore` instance is deserialized from json, it is not known if this is a `Rescore` or `MultiRescore` without checking the type; a consumer would need to know to do this, as `MultiRescore` maps only …

Allow Rescore to accept multiple rescore queries

---

src/Nest/CommonAbstractions/Extensions/Extensions.cs
src/Tests/Reproduce/GithubIssue2101.cs
src/Tests/Tests.csproj
src/Tests/tests.yaml

The ToListOrNullIfEmpty() extension method called .Any() and .ToList()
which both evaluate the IEnumerable.  This caused funcs to be executed
twice when applied to an IEnumerable<Func<>>.
Closes #2101

Fix double evaluation of IEnumerable methods

---

src/CodeGeneration/CodeGeneration.LowLevelClient/CodeGeneration.LowLevelClient.project.lock.json
src/CodeGeneration/Nest.Litterateur/Nest.Litterateur.project.lock.json
src/Elasticsearch.Net/Elasticsearch.Net.project.lock.json
src/Nest/CommonAbstractions/Extensions/Extensions.cs
src/Nest/QueryDsl/Compound/And/AndQuery.cs
src/Nest/QueryDsl/Compound/Bool/BoolQuery.cs
src/Nest/QueryDsl/Compound/Boosting/BoostingQuery.cs
src/Nest/QueryDsl/Compound/ConstantScore/ConstantScoreQuery.cs
src/Nest/QueryDsl/Compound/Dismax/DismaxQuery.cs
src/Nest/QueryDsl/Compound/Filtered/FilteredQuery.cs
src/Nest/QueryDsl/Compound/Indices/IndicesQuery.cs
src/Nest/QueryDsl/Compound/Not/NotQuery.cs
src/Nest/QueryDsl/Compound/Or/OrQuery.cs
src/Tests/QueryDsl/Compound/Bool/BoolQueryUsageTests.cs
src/Tests/QueryDsl/Compound/Dismax/DismaxQueryUsageTests.cs
src/Tests/QueryDsl/QueryDslUsageTestsBase.cs
src/Tests/QueryDsl/Verbatim/VerbatimAndStrictQueryUsageTests.cs
src/Tests/tests.yaml

A compound query should only be conditionless when any of its inner
queries are not writable.  Previously we were only checking if the inner
queries were also not conditionless.
Closes #2086

Fix compound query conditionless logic

---

src/Nest/Document/Multiple/MultiGet/ElasticClient-GetMany.cs
src/Nest/Nest.csproj
src/Tests/Document/Multiple/MultiGet/GetManyApiTests.cs
src/Tests/Document/Multiple/MultiGet/GetManyUrlTests.cs
src/Tests/Framework/UrlTests.cs
src/Tests/Tests.csproj

Set Index and Type on MultiGetDescriptor. If they have values, the specific index and type will be overridden on each get operation with them.
Fixes https://github.com/elastic/elasticsearch-net/issues/2093

Infer index and type from T for GetMany

---

docs/aggregations-usage.asciidoc
docs/aggregations.asciidoc
docs/aggregations/metric/geo-centroid/geo-centroid-aggregation-usage.asciidoc
docs/client-concepts/connection-pooling/sniffing/role-detection.asciidoc
docs/query-dsl/compound/bool/bool-query-usage.asciidoc
docs/query-dsl/compound/dismax/dismax-query-usage.asciidoc
docs/query-dsl/verbatim/verbatim-and-strict-query-usage.asciidoc
src/Nest/Aggregations/AggregateJsonConverter.cs
src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/AggregationsHelper.cs
src/Nest/Aggregations/Metric/GeoCentroid/GeoCentroidAggregate.cs
src/Nest/Aggregations/Metric/GeoCentroid/GeoCentroidAggregation.cs
src/Nest/Aggregations/Visitor/AggregationVisitor.cs
src/Nest/Aggregations/Visitor/AggregationWalker.cs
src/Nest/Nest.csproj
src/Tests/Aggregations/Metric/GeoCentroid/GeoCentroidAggregationUsageTests.cs
src/Tests/Tests.csproj

Adds `geo_centroid` aggregation for 5.x
See https://github.com/elastic/elasticsearch-net/pull/2118

Add geo_centroid aggregation

---

src/Nest/Aggregations/AggregateJsonConverter.cs

The deserialization assumes that a property named "score" is an indicator that an aggregation is a significant terms aggregation, but this may not be the case; "score" could be a user-supplied name for an aggregation.

Check the token type of score property when deserializing aggregation

---

src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
src/Tests/ClientConcepts/Connection/HttpConnectionTests.cs
src/Tests/Framework/Integration/Process/ElasticsearchNode.cs
src/Tests/Tests.csproj

- Content-Encoding was being added to the wrong header
- Stream was being closed pre-maturely
Closes #2150

Fix gzip compression when running on .NET core

---

src/Nest/Cluster/NodesStats/NodeStats.cs
src/Tests/Cluster/NodesStats/NodesStatsApiTests.cs

Add Percent metric in OperatingSystemStats to solve this issue:
https://github.com/elastic/elasticsearch-net/issues/2181
In one commit so we can close this pull request: https://github.com/elastic/elasticsearch-net/pull/2185

Add Percent metric in OperatingSystemStats

---

src/Nest/Search/Suggesters/SuggestOption.cs

Fixed issue #2176 where the "collate_match" boolean wasn't accessible through the the SuggestOption.

"collate_match" for phrase suggestions

---

src/Nest/CommonAbstractions/Extensions/Extensions.cs
src/Nest/CommonOptions/Geo/GeoShapeRelation.cs
src/Nest/QueryDsl/Geo/Shape/Circle/GeoShapeCircleQuery.cs
src/Nest/QueryDsl/Geo/Shape/Envelope/GeoShapeEnvelopeQuery.cs
src/Nest/QueryDsl/Geo/Shape/GeoShapeQueryJsonConverter.cs
src/Nest/QueryDsl/Geo/Shape/IGeoShapeQuery.cs
src/Nest/QueryDsl/Geo/Shape/IndexedShape/GeoIndexedShapeQuery.cs
src/Nest/QueryDsl/Geo/Shape/LineString/GeoShapeLineStringQuery.cs
src/Nest/QueryDsl/Geo/Shape/MultiLineString/GeoShapeMultiLineStringQuery.cs
src/Nest/QueryDsl/Geo/Shape/MultiPoint/GeoShapeMultiPointQuery.cs
src/Nest/QueryDsl/Geo/Shape/MultiPolygon/GeoShapeMultiPolygonQuery.cs
src/Nest/QueryDsl/Geo/Shape/Point/GeoShapePointQuery.cs
src/Nest/QueryDsl/Geo/Shape/Polygon/GeoShapePolygonQuery.cs
src/Tests/QueryDsl/Geo/Shape/Circle/GeoShapeCircleUsageTests.cs
src/Tests/QueryDsl/Geo/Shape/Envelope/GeoEnvelopeUsageTests.cs
src/Tests/QueryDsl/Geo/Shape/IndexedShape/GeoIndexedShapeUsageTests.cs
src/Tests/QueryDsl/Geo/Shape/LineString/GeoLineStringUsageTests.cs
src/Tests/QueryDsl/Geo/Shape/MultiLineString/GeoMultiLineStringUsageTests.cs
src/Tests/QueryDsl/Geo/Shape/MultiPoint/GeoMultiPointUsageTests.cs
src/Tests/QueryDsl/Geo/Shape/Point/GeoPointUsageTests.cs
src/Tests/QueryDsl/Geo/Shape/Polygon/GeoPolygonUsageTests.cs
src/Tests/QueryDsl/Geo/Shape/ShapeQueryUsageTestsBase.cs

- Add `Relation` to geo_shape queries
GeoShapeRelation was in the codebase but looks like it was missed in the geo refactoring
- Add `contains` to geoshape relations.
Needs to be forward ported to 5.x

Add relation to geo_shape queries

---

src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
src/Tests/ClientConcepts/LowLevel/Connecting.doc.cs

This allows for setting things like the `ServerCertificateValidationCallback` on Core CLR which previously wasn't supported:
```csharp
public class SecureHttpConnection : HttpConnection
{
protected override HttpClientHandler CreateHttpClientHandler(RequestData requestData)
{
var handler = base.CreateHttpClientHandler(requestData);
handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, errors) => true;
return handler;
}
}
```
Closes #2198

Allow for modifying HttpClientHandler on .NET Core

---

src/Nest/Aggregations/Metric/TopHits/TopHitsAggregation.cs
src/Nest/CommonAbstractions/Infer/Fields/Fields.cs
src/Nest/Search/Search/InnerHits/GlobalInnerHit.cs
src/Nest/Search/Search/InnerHits/InnerHits.cs
src/Nest/Search/Search/SearchRequest.cs
src/Nest/Search/Search/SourceFiltering/SourceFilter.cs
src/Nest/Search/Search/SourceFiltering/SourceFilterJsonConverter.cs
src/Tests/Search/Request/SourceFilteringUsageTests.cs
src/Tests/tests.yaml

SourceFilter now has a Disable property which can be used to enable or
disable _source.  Instances that accepted Source(bool) now set this
property rather than ExcludeAll (which doesn't truly disable _source).
This is more of a workaround to maintain BWC in 2.x  In master, we will
use Union<bool, ISourceFilter> instead as proposed in #2200.

Backwards compatible solution for #2200

---

src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
src/Elasticsearch.Net/ElasticLowLevelClient.Generated.cs
src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
src/Nest/Nest.csproj
src/Nest/Search/MultiSearch/ElasticClient-MultiSearch.cs
src/Nest/Search/MultiSearch/MultiSearchResponseJsonConverter.cs
src/Nest/Search/MultiSearch/MultiSearchTemplate/ElasticClient-MultiSearchTemplate.cs
src/Nest/Search/MultiSearch/MultiSearchTemplate/MultiSearchTemplateJsonConverter.cs
src/Nest/Search/MultiSearch/MultiSearchTemplate/MultiSearchTemplateRequest.cs
src/Nest/Search/SearchTemplate/SearchTemplateRequest.cs
src/Nest/_Generated/_Descriptors.generated.cs
src/Nest/_Generated/_LowLevelDispatch.generated.cs
src/Nest/_Generated/_Requests.generated.cs
src/Tests/Search/MultiSearch/MultiSearchTemplate/MultiSearchTemplateApiTests.cs
src/Tests/Search/MultiSearch/MultiSearchTemplate/MultiSearchTemplateUrlTests.cs
src/Tests/Tests.csproj

https://www.elastic.co/guide/en/elasticsearch/reference/master/multi-search-template.html

Support for multi search template

---

src/Nest/CommonAbstractions/Extensions/JsonExtensions.cs
src/Nest/CommonAbstractions/Extensions/TypeExtensions.cs
src/Nest/CommonAbstractions/Fields/FieldValues.cs
src/Nest/CommonAbstractions/Infer/Field/Field.cs
src/Nest/CommonAbstractions/Infer/Id/IdJsonConverter.cs
src/Nest/CommonAbstractions/Infer/IndexName/IndexName.cs
src/Nest/CommonAbstractions/Infer/IndexName/IndexNameResolver.cs
src/Nest/CommonAbstractions/Infer/Indices/Indices.cs
src/Nest/CommonAbstractions/Infer/Inferrer.cs
src/Nest/CommonAbstractions/Infer/TypeName/TypeName.cs
src/Nest/CommonAbstractions/Infer/Types/Types.cs
src/Nest/CommonAbstractions/SerializationBehavior/ElasticContractResolver.cs
src/Nest/Document/Multiple/MultiGet/ElasticClient-MultiGet.cs
src/Nest/Document/Multiple/MultiGet/Response/MultiGetHitJsonConverter.cs
src/Nest/Search/MultiSearch/MultiSearchResponseJsonConverter.cs

- Cache JsonContracts per ConnectionSettings
- Cache Delegates per ConnectionSettings for constructing items in a MultiGetResponse
- Cache Delegates per ConnectionSettings for constructing items in a MultiSearchResponse
- Reuse Inferrer on ConnectionSettings
- Reduce complexity in getting IUrlParameter.GetString() for IndexName and TypeName

Performance Improvements

---

src/Nest/DSL/Query/IQueryContainer.cs
src/Nest/DSL/Query/QueryContainer.cs
src/Nest/DSL/Query/SpanFieldMaskingQueryDescriptor.cs
src/Nest/DSL/Query/SpanQueryDescriptor.cs
src/Nest/DSL/Visitor/DslPrettyPrintVisitor.cs
src/Nest/DSL/Visitor/QueryVisitor.cs
src/Nest/Nest.csproj
src/Tests/Nest.Tests.Unit/QueryParsers/Visitor/DslPrettyPrintVisitor.cs

Hi guys!
This commit extends query DSL with new very important query. More details could be found [here](https://lucene.apache.org/core/2_9_4/api/core/org/apache/lucene/search/spans/FieldMaskingSpanQuery.html) and [here](https://github.com/elastic/elasticsearch/issues/471). 
This query is very important for us and I believe for many other people who use multifields or several fields to analyze text differently. We use   2 fields to analyze text - one with stemming and one as-is. This allows us to build very sophisticated queries for our scenarios.
It would be great if you accept it and push 1.9.1 soon. 
Thanks in advance!

Extend query DSL with SpanFieldMaskingQuery

---

src/Nest/Mapping/AttributeBased/ElasticsearchCorePropertyAttributeBase.cs
src/Nest/Mapping/Types/CorePropertyBase.cs
src/Nest/Mapping/Types/CorePropertyDescriptorBase.cs
src/Tests/ClientConcepts/HighLevel/Mapping/AutoMap.doc.cs
src/Tests/Mapping/Types/Core/Binary/BinaryMappingTests.cs
src/Tests/Mapping/Types/Core/Boolean/BooleanMappingTests.cs
src/Tests/Mapping/Types/Core/Date/DateMappingTests.cs
src/Tests/Mapping/Types/Core/Number/NumberMappingTests.cs
src/Tests/Mapping/Types/Core/String/StringMappingTests.cs
src/Tests/Mapping/Types/Core/Text/TextMappingTests.cs
src/Tests/tests.yaml

Forward port of #2249 minus the hacky bits

fix #2119 in master, make similarity on per field mapping a string

---

src/Nest/CommonOptions/DateMath/DateMath.cs
src/Nest/CommonOptions/TimeUnit/Time.cs
src/Tests/CommonOptions/DateMath/DateMathExpressions.doc.cs

e.g `new Time(TimeSpan.FromHours(25))`  might serialize as 1.04h on its own but in datemath it should serialize to the lowest non fractional time unit we can represent it in `25h`

fix #2170, DateMath should not serialize time as fractional

---

src/Nest/CommonAbstractions/SerializationBehavior/ElasticContractResolver.cs
src/Tests/Reproduce/DateSerialization.cs
src/Tests/Tests.csproj

`IsoDateTimeConverter` deserializes a `DateTimeOffset` represented according ISO8601 into a `DateTimeOffset` with a local offset. For example `"1999-01-01T01:01:01.001+05:00"` deserializes to a `DateTimeOffset` with a value of `01/01/1999 07:01:01 +11:00`. The +11 offset is my local offset (Australia). The default deserialization for a `DateTimeOffset` not using `IsoDateTimeConverter` deserializes into a `DateTimeOffset` with an offset that reflects the one in the ISO8601 string representation. 
This seems more appropriate behaviour.
Use `CultureInfo.InvariantCulture` in `IsoDateTimeConverter` when deserializing `DateTime`

Do not use IsoDateTimeConverter to handle DateTimeOffset

---

src/Nest/Indices/AliasManagement/GetAlias/ElasticClient-GetAlias.cs
src/Nest/Indices/AliasManagement/GetAliases/ElasticClient-GetAliases.cs
src/Nest/Indices/AliasManagement/GetAliases/GetAliasesResponse.cs
src/Tests/Indices/AliasManagement/GetAlias/GetAliasApiTests.cs

- Move the deserialization into a custom converter
This is a tidying up of the deserialization, moving it from a method on `ElasticClient` into a json converter.
- Add a valid alias to the integration tests
All aliases used in the integration test do not exist, so Elasticsearch returns `{}`. Add an alias known to exist as a better test of deserialization logic.

Custom IGetAliasesResponse converter

---

src/Nest/Mapping/AttributeBased/ElasticsearchPropertyAttributeBase.cs
src/Nest/Mapping/Types/PropertyBase.cs
src/Nest/Mapping/Types/PropertyDescriptorBase.cs
src/Tests/Mapping/Types/Core/Binary/BinaryMappingTests.cs
src/Tests/Mapping/Types/Core/Boolean/BooleanMappingTests.cs
src/Tests/Mapping/Types/Core/Date/DateMappingTests.cs
src/Tests/Mapping/Types/Core/Number/NumberMappingTests.cs

Remove obsolete IndexName from mapping properties

---

src/Elasticsearch.Net/Connection/HttpConnection.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
src/Tests/ClientConcepts/ConnectionPooling/BuildingBlocks/RequestPipelines.doc.cs
src/Tests/ClientConcepts/ConnectionPooling/Dispose/ResponseBuilderDisposeTests.cs
src/Tests/Framework/TestClient.cs
src/Tests/Framework/VirtualClustering/VirtualCluster.cs
src/Tests/Framework/VirtualClustering/VirtualClusterConnection.cs
src/Tests/Tests.csproj
src/Tests/tests.yaml

Confirmed we do not handle the case where `response.GetResponseStream()` returns null in our `WebException` handling. 
As per: http://msdn.microsoft.com/en-us/library/system.net.httpwebresponse.getresponsestream.aspx
> You must call either the Stream.Close or the HttpWebResponse.Close method to close the stream and release the connection for reuse. It is not necessary to call both Stream.Close and HttpWebResponse.Close, but doing so does not cause an error. Failure to close the stream will cause your application to run out of connections.
We rely on disposing the `stream` only but in this case we need to forcefully call dispose on `response` instead.

fix #2311 null GetResponseStream() on HttpWebException

---

src/Nest/CommonAbstractions/Infer/Field/Field.cs
src/Nest/CommonAbstractions/Infer/Field/FieldExpressionVisitor.cs
src/Nest/CommonAbstractions/Infer/PropertyName/PropertyName.cs
src/Tests/ClientConcepts/HighLevel/Caching/FieldResolverCacheTests.cs

We only cache Field expressions that do not contain variables.  For
instance:
```csharp
Field<Project>(p => p.Name)
Field<Project>(p => p.Name.Suffix("foo"))
Field<Project>(p => p.Metadata["foo"])
```
are all cachable since they only contain constant expressions.
whereas
```csharp
Field<Project>(p => p.Name.Suffix(myVariable))
Field<Project>(p => p.Metadata[myVariable])
```
are not cachable since we can't evaluate the value of `myVariable` to be
used as a cache key.
However, there was a bug which this commit fixes where we would cache a
variable expression that ended with a constant.  For instance:
```csharp
Field<Project>(p => p.Metadata[myVariable].Suffix("foo"))
```
This expression was incorrectly cached because HasConstantExpressionVisitor
only concerned itself with the last method …

Fix #2319 caching of constant Field expressions

---

src/Nest/Mapping/AttributeBased/ElasticsearchPropertyAttributeBase.cs
src/Nest/Mapping/TypeMapping.cs
src/Nest/Mapping/Types/PropertyBase.cs
src/Nest/Mapping/Types/PropertyDescriptorBase.cs
src/Nest/Mapping/Visitor/IMappingVisitor.cs
src/Nest/Mapping/Visitor/MappingWalker.cs
src/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
src/Tests/Mapping/Metafields/LocalMetadataTests.cs
src/Tests/Tests.csproj

Initial pull request for adding support for local metadata to properties. I had to change the IMappingVisitor to use the property interfaces since it was taking the concrete classes and the mapping descriptors would not work with this. That doesn't seem to break anything and seems to just make the visitor support more scenarios, but I also realize that it's a breaking change that you might not want to take on and we could easily create our own visitor.

Adding support for local metadata on properties.

---

src/Elasticsearch.Net/Responses/ElasticsearchResponse.cs
src/Nest/CommonOptions/Failures/ShardFailure.cs
src/Nest/Document/Multiple/BulkIndexByScrollFailure.cs
src/Nest/Document/Multiple/ReindexOnServer/ElasticClient-ReindexOnServer.cs
src/Nest/Document/Multiple/ReindexOnServer/ReindexOnServerResponse.cs
src/Tests/Reproduce/GithubIssue2309.cs
src/Tests/Tests.csproj

When a `ReindexOnServerResponse` comes back as 400 status code, deserialize the response so that `Failures` is populated with more details for why things failed. 
Use the -1 special case in `AllowedStatusCodes` in the dispatch call, similar to `UpdateByQuery` and `DeleteByQuery`; `IsValid` will still be false as it checks `Failures` which will be deserialized and not be empty. `Success` on `ApiCallDetails` will be true however.
Closes #2309

Correctly handle 400 status code response

---

src/Nest/Mapping/Types/Core/String/StringAttribute.cs
src/Nest/Mapping/Visitor/PropertyWalker.cs
src/Tests/ClientConcepts/HighLevel/Mapping/AutoMap.doc.cs
src/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
src/Tests/Mapping/Types/Complex/Nested/NestedAttributeTests.cs
src/Tests/Mapping/Types/Complex/Object/ObjectAttributeTests.cs
src/Tests/Mapping/Types/Core/String/StringAttributeTests.cs
src/Tests/Mapping/Types/Core/Text/TextAttributeTests.cs
src/Tests/tests.yaml

This aligns with the default inferred mapping for a string in Elasticsearch 5.0
Closes #2329

Include ignore_above in string keyword mapping inference

---

src/Elasticsearch.Net/Extensions/Extensions.cs
src/Nest/CommonAbstractions/SerializationBehavior/GenericJsonConverters/EnumMemberValueCasingJsonConverter.cs
src/Nest/CommonOptions/TimeUnit/TimeUnit.cs
src/Nest/Ingest/PipelineJsonConverter.cs
src/Nest/Ingest/Processors/AttachmentProcessor.cs
src/Nest/Ingest/Processors/DateIndexNameProcessor.cs
src/Nest/Ingest/Processors/DotExpanderProcessor.cs
src/Nest/Ingest/Processors/GeoIpProcessor.cs
src/Nest/Ingest/Processors/ScriptProcessor.cs
src/Nest/Ingest/ProcessorsDescriptor.cs
src/Nest/Nest.csproj
src/Tests/Ingest/PipelineCrudTests.cs
src/Tests/Ingest/ProcessorSerializationTests.cs
src/Tests/Tests.csproj

- Add serialization test to ensure that all processors can be serialized and deserialized with the correct processor names
- Json.Net cannot handle an enum that is serialized to string where the values come from EnumMemberAttribute values and differ only in casing. Opened an issue at https://github.com/JamesNK/Newtonsoft.Json/issues/1067. We have two enums, TimeUnit and DateRounding that both use M and m for Month and Minute, respectively. Implemented a generic json converter that is able to handle this case.
Closes #2334

Add Script and DotExpander Processors

---

src/CodeGeneration/ApiGenerator/Overrides/Allow404/ApiEndpointsThatAllow404.cs
src/CodeGeneration/ApiGenerator/RestSpecification/Core/root.html
src/Elasticsearch.Net/ElasticLowLevelClient.Generated.cs
src/Tests/Document/Single/DocumentCrudTests.cs
src/Tests/Reproduce/GithubIssue1863.cs
src/Tests/Reproduce/GithubIssue2306.cs
src/Tests/Tests.csproj

Update Rest Api Specs to v5.0.0
Closes #2306

Allow 404s for Get and Delete requests

---

src/CodeGeneration/ApiGenerator/Domain/CsharpMethod.cs
src/Nest/Search/Search/ElasticClient-Search.cs
src/Nest/Search/Search/SearchRequest.cs
src/Nest/Search/Suggesters/Suggest/ElasticClient-Suggest.cs
src/Nest/Search/Suggesters/Suggest/SuggestRequest.cs
src/Nest/_Generated/_Descriptors.generated.cs
src/Nest/_Generated/_Requests.generated.cs
src/Tests/Search/Suggesters/SuggestApiTests.cs
src/Tests/Search/Suggesters/SuggestUrlTests.cs
src/Tests/Tests.csproj

In NEST 1.x, the index is inferred from T but this behaviour changed in 2.x such that the index was not inferred from T and always had to be explicitly specified. This commit reverts the behaviour to that of 1.x such that index is inferred from T again, and introduces a SuggestRequest<T> with a parameterless ctor that also infers the index from T.
Closes #2335

Infer index from generic type parameter T in Suggest<T>

---

src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdate.cs
src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdateBody.cs
src/Tests/Document/Multiple/Bulk/BulkApiTests.cs

Parameters related to an update script should be serialized as properties of an object assigned to a script property.
Closes #2357

Fix script representation for bulk updates

---

src/Elasticsearch.Net/Responses/IBodyWithApiCallDetails.cs
src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
src/Nest/CommonAbstractions/Response/ResponseBase.cs
src/Nest/ElasticClient.cs
src/Nest/Search/MultiSearch/MultiSearchResponse.cs
src/Nest/Search/Percolator/MultiPercolate/MultiPercolateResponse.cs
src/Profiling/Async/IndexAsyncOperation.cs
src/Profiling/Async/SearchAsyncOperation.cs
src/Tests/ClientConcepts/Exceptions/ExceptionTests.cs
src/Tests/Framework/EndpointTests/ApiIntegrationTestBase.cs
src/Tests/Framework/EndpointTests/ApiTestBase.cs
src/Tests/Framework/EndpointTests/UrlTests.cs
src/Tests/Modules/SnapshotAndRestore/Restore/RestoreApiTests.cs

If you get a hold of an `IResponse` you see both `ApiCall` and `CallDetails` which are in fact the same property this is confusing.
In `Elasticsearch.Net` response object can implement `IBodyWithApiCallDetails` which is a special interface the low level client knows how to handle and set the diagnostics `IApiCallDetails` on a `CallDetails` property.  
In the high level client we did not want to expose a setter on this so we hid the `CallDetails` from `IBodyWithApiCallDetails` and introduced `ApiCall`. 
We now more explicitly hide `IBodyWithApiCallDetails` and normalize the properties to the same name.
Also introduced xmldocs on these which were long overdue.

fix #2286 normalize ApiCall and CallDetails and add better xmldocs to IResponse

---

src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
src/Nest/Mapping/Types/Properties-Scalar.cs
src/Nest/Mapping/Types/Properties.cs
src/Nest/Nest.csproj
src/Tests/IndexModules/UsageTestBase.cs
src/Tests/Mapping/Scalar/ScalarUsageTests.cs
src/Tests/Tests.csproj
src/Tests/tests.yaml

... to map inside the fluent properties descriptor
```csharp
.Properties(ps => ps
.Scalar(p => p.Int, m => m)
.Scalar(p => p.IntNullable, m => m)
.Scalar(p => p.Float, m => m)
.Scalar(p => p.FloatNullable, m => m)
.Scalar(p => p.Char, m => m)
.Scalar(p => p.CharNullable, m => m)
.Scalar(p => p.Guid, m => m)
///snip 	
.Scalar(p => p.String, m => m)
);
```

fix #2368 by fixing the underlying problem that scalars should be easier

---

src/Elasticsearch.Net/Responses/ServerError.cs
src/Elasticsearch.Net/Serialization/SimpleJson.cs
src/Nest/Cluster/ClusterReroute/ClusterRerouteState.cs
src/Nest/Cluster/ClusterState/IndexRoutingTable.cs
src/Nest/Cluster/ClusterState/MetadataState.cs
src/Nest/Cluster/ClusterState/RoutingNodesState.cs
src/Nest/Cluster/ClusterState/RoutingTableState.cs
src/Nest/Cluster/ClusterStats/ClusterNodesStats.cs
src/Nest/CommonOptions/Stats/IndexingStats.cs
src/Nest/Modules/SnapshotAndRestore/Snapshot/Snapshot.cs
src/Nest/XPack/License/PostLicense/LicenseAcknowledgement.cs
src/Nest/XPack/Security/Authenticate/AuthenticateResponse.cs
src/Nest/XPack/Watcher/AcknowledgeWatch/AcknowledgeWatchResponse.cs
src/Nest/XPack/Watcher/ActivateWatch/ActivateWatchResponse.cs
src/Nest/XPack/Watcher/ExecuteWatch/ExecuteWatchResponse.cs
src/Nest/XPack/Watcher/Watch.cs
src/Nest/XPack/Watcher/WatcherStats/WatcherStatsResponse.cs
src/Tests/Cluster/ClusterState/ClusterStatsApiTests.cs
src/Tests/Cluster/TaskManagement/TasksCancel/TasksCancelApiTests.cs
src/Tests/CodeStandards/Responses.doc.cs
src/Tests/Document/Multiple/MultiTermVectors/MultiTermVectorsApiTests.cs
src/Tests/Framework/Extensions/ReadOnlyDictionaryAssertions.cs
src/Tests/Indices/IndexManagement/CreateIndex/CreateIndexApiTests.cs
src/Tests/Indices/Monitoring/IndicesShardStores/IndicesShardStoresApiTests.cs
src/Tests/Reproduce/GithubIssue2323.cs
src/Tests/Tests.csproj

- Reflection unit test traverses IResponse properties to check their types.
- Add Fluent Assertions for IReadOnlyDictionary<TKey, TValue>. See dennisdoomen/FluentAssertions#357
- Update Watcher APIs to use readonly collections
- Enable readonly collection deserialization in SimpleJson
(cherry-pick from commit 73a77a2e369a9d3bb9c70ad1aa9d661c1071d22a)

Assert all collections on Response types are read only

---

src/Nest/Document/Multiple/Bulk/ElasticClient-Bulk.cs
src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
src/Nest/Document/Multiple/BulkAll/BulkAllObserver.cs
src/Nest/Document/Multiple/BulkAll/BulkAllRequest.cs
src/Nest/Document/Multiple/BulkAll/BulkAllResponse.cs
src/Nest/Document/Multiple/BulkAll/ElasticClient-BulkAll.cs
src/Nest/Document/Multiple/Reindex/ReindexResponse.cs
src/Nest/Nest.csproj
src/Tests/Document/Multiple/BulkAll/BulkAllApiTests.cs
src/Tests/Tests.csproj

This backport includes:
https://github.com/elastic/elasticsearch-net/pull/2402
and @russcam's fixes:  
https://github.com/elastic/elasticsearch-net/commit/cf5b298e86368032f713fbe7d575de948e1e46ec
https://github.com/elastic/elasticsearch-net/commit/f1eabf4343c7e32aaa2995840dde8a1d1366ace7

Backport of the superuseful BulkAll to 2.x

---

src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
src/Nest/Document/Multiple/BulkAll/BulkAllRequest.cs
src/Tests/Document/Multiple/BulkAll/BulkAllApiTests.cs

how the buffer of `IList<T>` buffer is tranlated into a single bulk request, rather then always simply calling `IndexMany` on it.
This allows you to do use e.g the `IndexMany(buffer, perDocumentOpSelector)` overload or manually looping over the buffer and doing a `Create/Update/Index`

fix #2220 allow more control in BulkAll 

---

src/Nest/CommonAbstractions/SerializationBehavior/ElasticContractResolver.cs
src/Nest/CommonAbstractions/SerializationBehavior/GenericJsonConverters/VerbatimDictionaryKeysConverter.cs
src/Nest/CrossPlatform/TypeExtensions.cs
src/Tests/Framework/SerializationTests/DictionarySerializationTests.cs
src/Tests/Tests.csproj

Change in b062c5ec2b4ce49b1ecd5ba633199161e42e02d5 did not handle a number of dictionary cases including
- types that implement `IReadOnlyDictionary<TKey,TValue>`
e.g. `public class MyReadOnlyDictionary<TKey,TValue> : IReadOnlyDictionary<TKey,TValue>`
- types that implement `IDictionary<TKey, TValue>`
e.g. `public class MyDictionary<TKey,TValue> : IDictionary<TKey,TValue>`
- non-generic types that inherit a closed generic dictionary type
e.g. `public class MyDictionary : Dictionary<string,object>`
- types that implement `IDictionary` that are not generic
e.g. `public class MyNonGenericDictionary : IDictionary`
Include serialization tests for all the above cases and additionally, serialize `null` when the cast value in the json converter is null.
Fixes #2411

Fix dictionary serialization

---

src/Elasticsearch.Net/Configuration/Security/BasicAuthenticationCredentials.cs
src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs

RequestData's GetHashCode implementation uses instances of types that will return different values per instance (Headers, BasicAuthenticationCredentials). GetHashCode and Equals only need to reference properties that are unchanging per HttpClient instance, which are:
RequestTimeout
HttpCompression
ProxyAddress
ProxyUsername
ProxyPassword
DisableAutomaticProxyDetection
All other properties are set per request.
Fixes #2417

Fix RequestData hashcode and equality for .NET core HttpConnection

---

src/Nest/CommonAbstractions/Response/ResponseBase.cs
src/Nest/Document/Multiple/MultiTermVectors/ElasticClient-MultiTermVectors.cs
src/Nest/Document/Multiple/MultiTermVectors/MultiTermVectorsResponse.cs
src/Tests/Document/Multiple/MultiTermVectors/MultiTermVectorsApiTests.cs

Add a specific deserialization override to set ApiCallDetails on each TermVectorResponse in MultiTermVectorsResponse.Documents.
Closes #2142

Set ApiCall details on TermVectorResponses on MultiTermVectorsResponse

---

src/Nest/Nest.csproj
src/Nest/Search/Scroll/Scroll/ScrollRequest.cs
src/Nest/Search/Scroll/Scroll/SlicedScroll.cs
src/Nest/Search/Search/SearchRequest.cs
src/Tests/Search/Request/SlicedScrollSearchUsageTests.cs
src/Tests/Search/Scroll/Scroll/SlicedScrollApiTests.cs
src/Tests/Tests.csproj
src/Tests/tests.yaml

https://www.elastic.co/guide/en/elasticsearch/reference/5.x/search-request-scroll.html#sliced-scroll

sliced scroll support

---

src/Nest/CommonAbstractions/SerializationBehavior/GenericJsonConverters/ReadOnlyCollectionJsonConverter.cs
src/Nest/Document/Multiple/MultiTermVectors/MultiTermVectorsResponse.cs
src/Nest/Document/Single/TermVectors/TermVectors.cs
src/Nest/Nest.csproj
src/Tests/Document/Single/TermVectors/TermVectorsApiTests.cs

In NEST 2.x, MultiTermVectorsResponse reuses TermVectorsResponse as the type in the collection, but this exposes other properties inherited from IResponse. Introduce a specific type for this that does not inherit from IResponse.

Add specific TermVectors type for MultiTermVectors

---

src/Elasticsearch.Net/Connection/HttpConnection.cs

Everything old is new again, some lessons have to be learned over and over 😢 
In NEST `0.x` and `1.x` the[ HttpConnection async bits is implemented using a marvalous APM callback soup implementation](https://github.com/elastic/elasticsearch-net/blob/1.x/src/Elasticsearch.Net/Connection/HttpConnection.cs#L332) which was hard to read but battle hardened. 
With `2.x` we finally took the plunge to a TAP and async/await based implementation which is a joy to read. However in doing so we did not port all the timeouts registered with the threadpool to make the unabortable bits such as `GetRequestStreamAsync` and `GetResponseAsync`.
This PR brings back some APM wrapped to a Task with `Task.Factory.FromAsync` and `ThreadPool.RegisterWaitForSingleObject` is back in action to guard these calls. 
To …

fix #2438 make sure each async part of HttpConnection is abortable

---

src/Elasticsearch.Net/Serialization/ElasticsearchDefaultSerializer.cs
src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
src/Elasticsearch.Net/Transport/PostData.cs
src/Nest/CommonAbstractions/SerializationBehavior/JsonNetSerializer.cs
src/Nest/Document/Multiple/Bulk/BulkRequestJsonConverter.cs
src/Nest/Document/Multiple/Bulk/BulkResponseItem/BulkResponseItemJsonConverter.cs

Use the default buffer size when copying from one stream to another
Switch between default serializer and indented serializer with conditional ternary rather than allocating a dictionary
Introduce BufferSize property with a default size of 1024 to use when writing json to the request stream. Performance tests as part of #1899 indicate this to be a good compromise buffer size for performance throughput and bytes allocated.

Small Performance Improvements

---

src/Nest/CommonOptions/TimeUnit/Time.cs
src/Nest/CommonOptions/TimeUnit/TimeUnit.cs

Milliseconds do not apply when the Time is Month or Year.
Use constants for the milliseconds in each interval

Make milliseconds nullable on Time

---

src/Elasticsearch.Net/Extensions/Extensions.cs
src/Nest/CommonAbstractions/Extensions/Extensions.cs
src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
src/Nest/Document/Multiple/Reindex/ReindexResponse.cs
src/Nest/Document/Multiple/ScrollAll/ElasticClient-ScrollAll.cs
src/Nest/Document/Multiple/ScrollAll/ScrollAllObservable.cs
src/Nest/Document/Multiple/ScrollAll/ScrollAllObserver.cs
src/Nest/Document/Multiple/ScrollAll/ScrollAllRequest.cs
src/Nest/Document/Multiple/ScrollAll/ScrollAllResponse.cs
src/Nest/Nest.csproj
src/Nest/Search/Scroll/Scroll/SlicedScroll.cs
src/Tests/Document/Multiple/BulkAll/BulkAllApiTests.cs
src/Tests/Framework/Configuration/YamlConfiguration.cs
src/Tests/Search/Scroll/Scroll/SlicedScrollSearchApiTests.cs
src/Tests/Tests.csproj
src/Tests/tests.yaml

Exposes a sliced scroll behind an observable with an optional max degree
of parallelism
```csharp
var scrollObservable = this._client.ScrollAll<SmallObject>("1m", slices, s => s
.MaxDegreeOfParallelism(slices/ 2)
.Search(search => search
.Index(index)
.AllTypes()
.MatchAll()
)
);
```

ScrollAll()

---

build.bat
build/scripts/Building.fsx
build/scripts/Targets.fsx
build/scripts/Testing.fsx
src/Tests/Framework/Configuration/EnvironmentConfiguration.cs
src/Tests/Framework/Configuration/ITestConfiguration.cs
src/Tests/Framework/Configuration/NodeConfiguration.cs
src/Tests/Framework/Configuration/TestConfigurationBase.cs
src/Tests/Framework/Configuration/YamlConfiguration.cs
src/Tests/Framework/XUnitPlumbing/IntegrationTestDiscoverer.cs
src/Tests/Framework/XUnitPlumbing/NestTestDiscoverer.cs
src/Tests/Framework/XUnitPlumbing/UnitTestDiscoverer.cs
src/Tests/Framework/Xunit/TestAssemblyRunner.cs
src/Tests/Framework/Xunit/TestFramework.cs
src/Tests/tests.yaml

> build integrate 5.0.0 readonly getindexapi
Also fixes SkipMethod being too greedy ReadOnly cluster was only
yielding 14 tests.

Adds test collections filtering

---

src/Elasticsearch.Net/Transport/Sniff/SniffResponse.cs
src/Tests/ClientConcepts/ConnectionPooling/BuildingBlocks/RequestPipelines.doc.cs
src/Tests/ClientConcepts/ConnectionPooling/Sniffing/AddressParsing.doc.cs
src/Tests/ClientConcepts/ConnectionPooling/Sniffing/OnConnectionFailure.doc.cs
src/Tests/Framework/VirtualClustering/MockResponses/SniffingResponse.cs
src/Tests/Framework/VirtualClustering/VirtualCluster.cs
src/Tests/Framework/VirtualClustering/VirtualClusterConnection.cs
src/Tests/Framework/VirtualClustering/WaitingInMemoryConnection.cs

Now that 5.x no longer returns http_address we need to give precedence
to `publish_address` over `bound_address`

fix #2448 favor publish_address in 5.x

---

src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Dsl.cs
src/Nest/QueryDsl/Abstractions/Query/BoolQueryAndExtensions.cs
src/Nest/QueryDsl/Abstractions/Query/BoolQueryOrExtensions.cs
src/Nest/QueryDsl/Abstractions/Query/QueryBase.cs
src/Nest/QueryDsl/Abstractions/Query/QueryDescriptorBase.cs
src/Nest/QueryDsl/Compound/Bool/BoolQuery.cs
src/Tests/QueryDsl/BoolDsl/BoolDsl.doc.cs
src/Tests/tests.yaml

The performance and allocations fixes in #2235 also introduced virality
on the QueryContainer when using &= assignment. The composed result was
correct but the QueryContainer composed of `&=` would be left marked as
`CreatedByTheBoolDsl` which meant it was marked for reuse.
If you then later combined it with && (e.g `andAssignedQuery` && `newQuery`) the resulting
query would be correct but if you rely on `andAssignedQuery` not being
mutated you'd be in for a nasty suprise.
A QueryContainer composed with `&&` did not expose the same virality
problems.
This was due to a difference in how the `&` operator overload on `QueryContainer` and `QueryBase` behaved.
Removed the notion of trying to reuse all together since the big
performance gain from #2235 is that we can flatten many boolean should …

fix #2461 `&=` in the bool DSL is viral.

---

src/Nest/CommonAbstractions/Reactive/CoordinatedRequestObserverBase.cs
src/Nest/Document/Multiple/BulkIndexByScrollFailure.cs
src/Nest/Document/Multiple/Reindex/ElasticClient-Reindex.cs
src/Nest/Document/Multiple/Reindex/ReindexObservable.cs
src/Nest/Document/Multiple/Reindex/ReindexObserver.cs
src/Nest/Document/Multiple/Reindex/ReindexRequest.cs
src/Nest/Search/Search/Hits/Hit.cs
src/Tests/CodeStandards/ElasticClient.doc.cs
src/Tests/Document/Multiple/Reindex/ReindexApiTests.cs

User has to supply an explicit map between TSource and TTarget, the old
overloads where TSource == TTarget still exists.
The simplified helpers for reindex contained a bug, out integration
tests only reindexed 2 documents but if you had more the backpressure
sanity checks would kick in complaining, these now run with sane defaults.

Reindex now allows the target type to be different

---

src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
src/Elasticsearch.Net/Connection/HttpConnection.cs
src/Tests/Reproduce/ConnectionReuseAndBalancing.cs

Remove the async action in the Parallel.For
Add ConnectionLimit to ConnectionConfiguration
Add comments to all options with clear descriptions.
Part of #2476 
(cherry-picked from commit fbdaaee239892ffa6c0f4e1ba729831dc5ac935c)

Limit the number of TCP connections on .NET core

---

src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Dsl.cs
src/Nest/QueryDsl/Abstractions/Query/BoolQueryAndExtensions.cs
src/Nest/QueryDsl/Abstractions/Query/BoolQueryOrExtensions.cs
src/Nest/QueryDsl/Abstractions/Query/QueryBase.cs
src/Nest/QueryDsl/Abstractions/Query/QueryDescriptorBase.cs
src/Nest/QueryDsl/Compound/Bool/BoolQuery.cs
src/Tests/QueryDsl/BoolDsl/BoolDsl.doc.cs
src/Tests/tests.yaml

The performance and allocations fixes in #2235 also introduced virality
on the QueryContainer when using &= assignment. The composed result was
correct but the QueryContainer composed of `&=` would be left marked as
`CreatedByTheBoolDsl` which meant it was marked for reuse.
If you then later combined it with && (andAssignedQuery && newQuery) the resulting
query would be correct but if you rely on `andAssignedQuery` not being
mutated you'd be in for a nasty suprise.
A QueryContainer composed with `&&` did not expose the same virality
problems.
Removed the notion of trying to reuse all together since the big
performance gain from #2235 is that we can flatten many boolean should
queries using `&=` or `&&` or visa versa many boolean must queries with
`|=` or `||`.
Part of #2476 …

fix #2461 &= in the bool DSL is viral.

---

docs/aggregations/writing-aggregations.asciidoc
docs/client-concepts/high-level/mapping/auto-map.asciidoc
docs/high-level.asciidoc
docs/low-level.asciidoc
paket.lock
src/CodeGeneration/DocGenerator/AsciiDoc/GeneratedAsciidocVisitor.cs
src/CodeGeneration/DocGenerator/Documentation/Files/CSharpDocumentationFile.cs
src/CodeGeneration/DocGenerator/Documentation/Files/DocumentationFile.cs
src/CodeGeneration/DocGenerator/Documentation/Files/ImageDocumentationFile.cs
src/Tests/ClientConcepts/HighLevel/Mapping/AutoMap.doc.cs

Bump AsciiDoctNet to support additional asciidoc syntax
Closes #2463

Add important admonition about using System.Decimal POCO property types

---

src/Nest/Aggregations/Bucket/Terms/TermsIncludeExcludeJsonConverter.cs
src/Tests/Framework/Roundtrip.cs
src/Tests/Reproduce/GithubIssue2503.cs
src/Tests/Tests.csproj

Add deserialization method for TermsIncludeExclude

---

src/Nest/Aggregations/Bucket/DateHistogram/DateHistogramBucket.cs

1. DateTime.SpecifyKind will return a new DateTime instance.
2. Creating new DateTime instance for Epoch,
3. Adding Milliseconds creates a new DateTime Instance
Now only one instance is created (apart from the one time static hit)

Prevent multiple date time allocations

---

src/Nest/CommonOptions/Failures/BulkError.cs
src/Nest/CommonOptions/Failures/ShardFailure.cs

Nest.CausedBy didn't have a ToString override, and hence had the default "[Nest.CausedBy]" string representation.
This also caused non-informative string representations of BulkError: 
Type: "type" Reason: "reason" CausedBy: "[Nest.CausedBy]".
Now, string representation of Nest.CausedBy will contain the full cause chain (i.e., including the inner causes, in a way similar to a stack trace).
Should also be ported to 2.x & 5.x.

Added ToString to Nest.CausedBy for proper string representation.

---

src/Nest/Analysis/Languages/SnowballLanguage.cs

SnowballLanguage.German generates `ferman` due to typo

---

src/Elasticsearch.Net/Connection/RequestHandlers/RequestHandlerBase.cs
src/Tests/Nest.Tests.Integration/Index/IndexJObjectTests.cs
src/Tests/Nest.Tests.Integration/Nest.Tests.Integration.csproj

Elasticsearch.Net does not have a dependency on Json.NET, so use the fully qualified type name to check the type is not `JObject`.

Index JObject and collection of JObjects

---

src/Nest/CommonAbstractions/Infer/IndexName/IndexNameResolver.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
src/Nest/QueryDsl/Query.cs
src/Tests/ClientConcepts/HighLevel/Inference/IndexNameInference.doc.cs

Deprecate Template query. Can't deprecate the query types as they are used in the phrase suggester.

Fix broken test related to index name casing

---

docs/query-dsl-usage.asciidoc
docs/query-dsl.asciidoc
docs/query-dsl/geo/shape/geometry-collection/geo-geometry-collection-usage.asciidoc
docs/query-dsl/geo/shape/multi-polygon/geo-multi-polygon-usage.asciidoc
src/Nest/Indices/MappingManagement/PutMapping/PutMappingRequest.cs
src/Nest/Nest.csproj
src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
src/Nest/QueryDsl/Geo/GeoCoordinateJsonConverter.cs
src/Nest/QueryDsl/Geo/Shape/Circle/GeoShapeCircleQuery.cs
src/Nest/QueryDsl/Geo/Shape/GeoShapeQueryJsonConverter.cs
src/Nest/QueryDsl/Geo/Shape/GeometryCollection/GeoShapeGeometryCollectionQuery.cs
src/Nest/QueryDsl/Geo/Shape/GeometryCollection/GeometryCollection.cs
src/Nest/QueryDsl/MatchAllQuery.cs
src/Nest/QueryDsl/Query.cs
src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
src/Nest/QueryDsl/Visitor/QueryVisitor.cs
src/Nest/QueryDsl/Visitor/QueryWalker.cs
src/Tests/QueryDsl/Geo/Shape/GeometryCollection/GeoGeometryCollectionUsageTests.cs
src/Tests/QueryDsl/Geo/Shape/MultiPolygon/GeoMultiPolygonUsageTests.cs
src/Tests/QueryDsl/QueryDslUsageTestsBase.cs
src/Tests/Tests.csproj

Tidy up xml comments on queries
Fix warnings
Closes #2387

Support GeometryCollection geo_shape types and queries

---

src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
src/Elasticsearch.Net/Configuration/Security/BasicAuthenticationCredentials.cs
src/Elasticsearch.Net/Domain/RequestParameters/IRequestParameters.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
src/Elasticsearch.Net/Transport/PostData.cs
src/Nest/CommonAbstractions/Request/RequestBase.cs
src/Tests/ClientConcepts/LowLevel/DirectStreaming.cs

Backported from 5.x
(cherry picked from commit 44c5c8499dcc5cc81edc3d4bbc990afa07c62383)

Enable DisableDirectStreaming on a per request basis

---

src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
src/Tests/ClientConcepts/LowLevel/DirectStreaming.cs

This commit adds the ability to set .EnableDebugMode() on
ConnectionSettings which turns direct streaming and pretty JSON on and
writes DebugInformation to the output window.
It also accepts an optional Action<IApiCallDetails> to perform when the
request is completed, but preserves the original OnRequestCompleted action
that might be set on ConnectionSettings.
Closes #2535

Add debugging mode to connection settings

---

src/Nest/CommonOptions/DateFormat/DateFormat.cs
src/Nest/Nest.csproj

added DateFormat constants with xmldocs

---

src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
src/Elasticsearch.Net/Connection/HttpConnection.cs

Make the call to HttpClientHandler.MaxConnectionsPerServer optional if our ConnectionLimit setting is greater than zero, we also try catch and throw a nice exception message so folks know how to fix it may they run into this
fix #2581

fix #2561  HttpClientHandler.MaxConnectionsPerServer not always available

---

src/Elasticsearch.Net/Responses/ServerError.cs
src/Tests/Indices/AliasManagement/AliasExists/AliasExistsApiTests.cs
src/Tests/Indices/AliasManagement/GetAlias/GetAliasApiTests.cs
src/Tests/tests.yaml

Relates to: https://github.com/elastic/elasticsearch-net/issues/2582
Could not quite reproduce but the point in the code @niemyjski pointed out could use a null reference check so added it. 
This also makes sure 
```
{ 
"error" : "some error"
"status" : 404
}
Is properly deserialized into a `ServerError`, we were incorrectly assuming this is always an object.

More resilient error parsing 

---

src/Nest/Cluster/ClusterAllocationExplain/ClusterAllocationExplainResponse.cs
src/Nest/Cluster/ClusterAllocationExplain/ClusterAllocationExplainResponseJsonConverter.cs
src/Nest/Nest.csproj
src/Tests/ClientConcepts/LowLevel/PostData.doc.cs
src/Tests/Cluster/ClusterAllocationExplain/ClusterAllocationExplainApiTests.cs
src/Tests/Framework/EndpointTests/Bootstrappers/Seeder.cs
src/Tests/Framework/EndpointTests/Clusters/UnbalancedCluster.cs
src/Tests/Tests.csproj

Adds the new properties introduced in ES 5.2 and marks the old ones obsolete.
Test old against new:
`build integrate 5.1.2 unbalanced ClusterAllocationExplainResponseApiTests`
Test old against old:
`build integrate 5.1.2 unbalanced ClusterAllocationExplainResponseOldApiTests`
Test new against new:
`build integrate 5.2.0 unbalanced ClusterAllocationExplainResponseNewApiTests`

Fix #2573 bwc support for new cluster allocation explain response

---

src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/AggregationsHelper.cs
src/Nest/Aggregations/Bucket/AdjacencyMatrix/AdjacencyMatrixAggregation.cs
src/Nest/Nest.csproj
src/Tests/Aggregations/Bucket/AdjacencyMatrix/AdjacencyMatrixUsageTests.cs
src/Tests/Tests.csproj

Add support for the adjacency matrix aggregation

---

src/Elasticsearch.Net/Auditing/AuditEvent.cs
src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
src/Elasticsearch.Net/ConnectionPool/IConnectionPool.cs
src/Elasticsearch.Net/ConnectionPool/Node.cs
src/Elasticsearch.Net/ConnectionPool/SingleNodeConnectionPool.cs
src/Elasticsearch.Net/ConnectionPool/SniffingConnectionPool.cs
src/Elasticsearch.Net/ConnectionPool/StaticConnectionPool.cs
src/Elasticsearch.Net/Exceptions/ElasticsearchClientException.cs
src/Elasticsearch.Net/Responses/ElasticsearchResponse.cs
src/Elasticsearch.Net/Transport/Pipeline/IRequestPipeline.cs
src/Elasticsearch.Net/Transport/Pipeline/PipelineFailure.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
src/Elasticsearch.Net/Transport/Sniff/SniffResponse.cs
src/Elasticsearch.Net/Transport/Transport.cs
src/Tests/ClientConcepts/ConnectionPooling/Sniffing/RoleDetection.doc.cs
src/Tests/Framework/VirtualClustering/Audit/Auditor.cs
src/Tests/Framework/VirtualClustering/Cluster.cs
src/Tests/Framework/VirtualClustering/MockResponses/SniffingResponse.cs
src/Tests/Framework/VirtualClustering/VirtualCluster.cs

You can now set `NodePredicate(Func<Node, bool> filter)` on `ConnectionSettings`. 
This allows you to control which nodes are considered targets in the `RequestPipeline` for *normal* Elasticsearch API calls. Sniffing in the `RequestPipeline` does not take this predicate into account allowing you to seed your `SniffingConnectionPool` with master nodes and have it sniff on startup afterwhich none of the API calls will touch the master nodes.
The default predicate for any `IConnectionPool` that supports reseeding of nodes (`SniffingConnectionPool`) is to filter out `master only` nodes. 
For those that don't `SingleNode-, Static-, StickyConnectionPool et all) the default `NodePredicate` returns true for all nodes, assuming the list of nodes you pass are correct from the get go.
Our `Node` …

NodePredicate support on ConnectionSettings

---

src/Nest/Nest.csproj
src/Nest/Search/Search/Profile/AggregationBreakdown.cs
src/Nest/Search/Search/Profile/AggregationProfile.cs
src/Nest/Search/Search/Profile/Collector.cs
src/Nest/Search/Search/Profile/ShardProfile.cs
src/Tests/Search/Search/SearchProfileApiTests.cs
src/Tests/Tests.csproj
src/Tests/tests.yaml

- Added time_in_nanos to response (closes #2607)
- Respose was missing the aggregations portion
- Added full API and serialization tests which we were missing

Multiple fixes for the query profiler API

---

build.bat
src/Tests/Framework/Xunit/TestAssemblyRunner.cs

This PR makes it possible to filter by multiple clusters when running
integration tests and also exclude specific clusters, where previously
cluster filtering was inclusive only.
Examples:
Run readonly tests only (unchanged):
```build integrate 5.2.1 readonly```
Run readonly and writable tests only:
```buld integrate 5.2.1 "readonly,writable"```
Note the quotation marks.  These are required when passing multiple
cluster names due to how bat arguments are processed (commas are treated
like spaces).
Run all tests except xpack:
```build integrate 5.2.1 -xpack```
Run all tests except xpack and intrusiveoperation:
```build integrate 5.2.1 "-xpack,-intrusiveoperation"```
NOTE: both including and excluding clusters is redundant, but we do not throw
an exception.  For instance:
```build integrate …
```

Tests: Multiple cluster and exclusive filtering support

---

src/Nest/CommonAbstractions/SerializationBehavior/StatefulDeserialization/ConcreteTypeConverter.cs
src/Tests/Reproduce/CovariantSearchDateParsing.cs
src/Tests/Tests.csproj

This commit fixes an issue where indexing dates as strings and pulling
them back out using covariant search would result in the format being
different due to the default DateParseHandling serialization settings.
ConcereteTypeConverter now temporarily sets DateParseHandling to None
when deserializing covariant results.
/cc @gmoskovicz

Fix for covariant search date parsing

---

src/Nest/CommonAbstractions/Extensions/Extensions.cs
src/Nest/CommonAbstractions/Reactive/BlockingSubscribeExtensions.cs
src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
src/Nest/Document/Multiple/ScrollAll/ScrollAllObservable.cs
src/Nest/Document/Multiple/ScrollAll/ScrollAllObserver.cs
src/Nest/Nest.csproj
src/Tests/Document/Multiple/BulkAll/BulkAllApiTests.cs
src/Tests/Document/Multiple/Reindex/ReindexApiTests.cs
src/Tests/Framework/Xunit/TestAssemblyRunner.cs
src/Tests/Framework/Xunit/TestFrameworkExecutor.cs
src/Tests/tests.default.yaml

@sergii-sakharov rightfully pointed out in #2648 the Task.WhenAll is not the most
resource friendly solution and replaced it with bounded list we await
WhenAny is released and then continue.
That change had impact though on the way we relied on Task.WhenAll to be
blocking and being able to catch exceptions in Subscribe. This is now no
longer possible because we return early from calling an async method.
This is fine in our case because the returned Observable allows you to
track and dispose that async process.
This also introduces Wait(TimeSpan, Action onNext) extension methods for
period and have the exceptions propagated out of the subscribe as
expected. Fixes https://github.com/elastic/elasticsearch-net/issues/2634

Continuation of #2648 

---

src/Nest/CommonAbstractions/Extensions/Extensions.cs
src/Nest/CommonAbstractions/Reactive/BlockingSubscribeExtensions.cs
src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
src/Nest/Document/Multiple/ScrollAll/ScrollAllObservable.cs
src/Nest/Document/Multiple/ScrollAll/ScrollAllObserver.cs
src/Nest/Nest.csproj
src/Tests/Document/Multiple/BulkAll/BulkAllApiTests.cs
src/Tests/Document/Multiple/Reindex/ReindexApiTests.cs
src/Tests/Framework/Xunit/TestAssemblyRunner.cs
src/Tests/Framework/Xunit/TestFrameworkExecutor.cs
src/Tests/tests.default.yaml

Even though `MaxDegreeOfParallelism` is set to 1 there are multiple (3 or 4) items GC rooted in heap at all times for various reasons. E.g. as variables in enumerators in `PartitionHelper<>`, in response object, in tasks list in `ForEachAsync<,>()`. Seems acceptable but can cause higher than expected/necessary memory usage.

Added test for bulkall memory usage

---

src/Nest/Nest.csproj
src/Nest/Search/FieldStats/FieldMinMaxValueJsonConverter.cs
src/Nest/Search/FieldStats/FieldStatsResponse.cs
src/Tests/tests.default.yaml

`geo_point` and `geo_shape` field types now return a `min_value` and
`max_value` as per Elasticsearch 5.3 but do so as an object. This is
breaking for us in 5.x so for now we keep on ignoring them.
Included support for `min/max_value_as_string` which will never be
null.`

fix #2673 field stats on geo fields in elasticsearch 5.3

---

src/Nest/CommonAbstractions/Extensions/TypeExtensions.cs
src/Nest/Mapping/Types/PropertyBase.cs
src/Tests/ClientConcepts/HighLevel/Mapping/AutoMap.doc.cs

Previously, `AutoMap()` would not take into account properties that
have been overridden in derived classes:
```csharp
public class A
{
public int Foo { get; set; }
}
public class B : A
{
public new string Foo { get; set; }
}
```
So in this instance, mapping class `B` would result in `Foo` being mapped
as an `int`, even though it has been overridden as a `string` using the `new`
keyword.
With this commit, `AutoMap()` is now aware of overridden properties and
in this example, will map `Foo` as a `string`.
Closes #2566

AutoMap() is now aware of overridden properties in derived types

---

docs/aggregations/bucket/significant-terms/significant-terms-aggregation-usage.asciidoc
docs/aggregations/bucket/terms/terms-aggregation-usage.asciidoc
src/Nest/Aggregations/Bucket/SignificantTerms/SignificantTermsAggregation.cs
src/Nest/Aggregations/Bucket/SignificantTerms/SignificantTermsIncludeExclude.cs
src/Nest/Aggregations/Bucket/Terms/TermsAggregation.cs
src/Nest/Aggregations/Bucket/Terms/TermsIncludeExclude.cs
src/Nest/Aggregations/Bucket/Terms/TermsIncludeExcludeJsonConverter.cs
src/Nest/Nest.csproj
src/Tests/Aggregations/Bucket/SignificantTerms/SignificantTermsAggregationUsageTests.cs
src/Tests/Aggregations/Bucket/Terms/TermsAggregationUsageTests.cs
src/Tests/Framework/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
src/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
src/Tests/Reproduce/GithubIssue2503.cs

for Terms aggregation
- the flags property is no longer supported and a regular expression pattern is sent as a string value against the "include" key
- exact values are sent as an array of strings
for Significant Terms aggregation
- a dictionary was incorrectly used to filter terms. Introduce a `SignificantTermsIncludeExclude` type to represent the available options. Don't reuse the `TermsIncludeExclude` type because it includes properties that are not applicable for filtering on Significant Terms aggregation.
Add unit and integration tests for include and exclude filtering
Fixes #2682
Fixes #2676

Correctly handle terms include/exclude

---

src/Nest/DSL/Query/FuzzyDateQueryDescriptor.cs
src/Nest/DSL/Query/FuzzyNumericQueryDescriptor.cs
src/Nest/DSL/Query/FuzzyQueryDescriptor.cs
src/Nest/DSL/Query/IdsQueryDescriptor.cs
src/Nest/DSL/Query/MatchQueryDescriptor.cs
src/Nest/DSL/Query/MultiMatchQueryDescriptor.cs
src/Nest/DSL/Query/PrefixQueryDescriptor.cs
src/Nest/DSL/Query/QueryDescriptor.cs
src/Nest/DSL/Query/QueryStringDescriptor.cs
src/Nest/DSL/Query/WildcardQueryDescriptor.cs
src/Nest/Domain/DSL/Query.cs
src/Nest/Enums/RewriteMultiTerm.cs
src/Nest/Extensions/Extensions.cs
src/Nest/Resolvers/Converters/Queries/FuzzyQueryJsonConverter.cs
src/Nest/Resolvers/Converters/Queries/MatchQueryJsonConverter.cs
src/Tests/Nest.Tests.Integration/Search/QueryDSLTests.cs
src/Tests/Nest.Tests.Unit/ObjectInitializer/Count/CountRequestTests.cs
src/Tests/Nest.Tests.Unit/ObjectInitializer/DeleteByQuery/DeleteByQueryRequestTests.cs
src/Tests/Nest.Tests.Unit/ObjectInitializer/MoreLikeThis/MoreLikeThisRequestTests.cs
src/Tests/Nest.Tests.Unit/ObjectInitializer/Search/SearchRequestTests.cs
src/Tests/Nest.Tests.Unit/ObjectInitializer/Search/SearchRequestUntypedTests.cs
src/Tests/Nest.Tests.Unit/QueryParsers/Queries/MatchQueryTests.cs
src/Tests/Nest.Tests.Unit/QueryParsers/Queries/MultiMatchQueryTests.cs
src/Tests/Nest.Tests.Unit/QueryParsers/Queries/PrefixQueryTests.cs
src/Tests/Nest.Tests.Unit/QueryParsers/Queries/QueryStringQueryTests.cs
src/Tests/Nest.Tests.Unit/QueryParsers/Queries/WildCardQueryTests.cs
src/Tests/Nest.Tests.Unit/Search/InitializerSyntax/InitializerExample.cs
src/Tests/Nest.Tests.Unit/Search/Query/Singles/MatchQueryJson.cs
src/Tests/Nest.Tests.Unit/Search/Query/Singles/PrefixQueryJson.cs
src/Tests/Nest.Tests.Unit/Search/Query/Singles/QueryStringQueryJson.cs

TopTermsN and TopTermsBoostN require the ability to pass a value for N.
Deprecate the direct usage of RewriteMultiTerm enum in favour of MultiTermQueryRewrite type.
Fixes #2688
(cherry picked from commit 5784bdbf2f78cac40f7695c736df40b17e249fca)

Introduce MultiTermQueryRewrite type

---

src/Nest/Mapping/Types/Core/String/StringAttribute.cs
src/Nest/Mapping/Types/Core/String/StringProperty.cs
src/Nest/Modules/Indices/Fielddata/String/StringFielddata.cs
src/Tests/Mapping/Types/Core/String/StringAttributeTests.cs

fielddata is upgraded to a boolean flag and the filter and loading properties are used to set the fielddata_frequency_filter and eager_global_ordinals properties : https://github.com/elastic/elasticsearch/blob/9946abf479bfaa791e0b87904e088823430e47b4/core/src/main/java/org/elasticsearch/index/mapper/StringFieldMapper.java#L241-L259
Deprecate `Fielddata` property on `StringProperty` type and add `FielddataUpgrade`, `EagerGlobalOrdinals ` and `FielddataFrequencyFilter` properties
Closes #2721

Fix fielddata for upgraded string field types

---

build/Clients.Common.targets
src/Elasticsearch.Net/Responses/ElasticsearchResponse.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
src/Nest/Document/Multiple/ReindexOnServer/ReindexOnServerResponse.cs
src/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerApiTests.cs
src/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerInvalidApiTests.cs
src/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerRemoteApiTests.cs

Fixes #2725 and #2719
Do a double read for error for response that are always valid since they return valid object shapes on non 200-300 such as reindex and deletebyquery.
Relates too https://github.com/elastic/elasticsearch/issues/17548
In normal cases we shortcircuit reading `error` in the low level client on invalid http status codes. Some API's still return a response on bad status codes as well (such as Reindex, DeleteByQuery). If these API's **actually** return an `error` we  failed to pick up on these causing `.IsValid` to always be true here.

Fix #2725 and #2719

---

contributing.md

For those new to compiling with .NET Core, a gotcha is the limitation of `global.json` having to specify an exact SDK version. See: https://docs.microsoft.com/en-us/dotnet/articles/core/tools/global-json
This PR adds a section to _Troubleshooting_, reminding anyone building from source, that they must have the exact SDK version installed. I have also cleaned up some markdown heading tags which were not displaying properly.  
(Elasticsearch CLA signed)

Added troubleshooting section, corrected heading markdown tags

---

src/Elasticsearch.Net/Connection/HttpConnection.cs

When the passed cancellation token is shared for a longer time then a single request, e.g bulkall/scrollall/reindex all spawn multiple requests over a single cancellationtoken it will leak Register() handles and memory will keep on growing because it will keep `requests` around indefinitely.

Make sure we dispose CancellationTokenRegistration

---

build.sh
build/Clients.Common.targets
build/scripts/Building.fsx
build/scripts/Commandline.fsx
build/scripts/Testing.fsx
build/scripts/Tooling.fsx
src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
src/Elasticsearch.Net/Connection/HttpConnection.cs
src/Elasticsearch.Net/CrossPlatform/TypeExtensions.cs
src/Elasticsearch.Net/Elasticsearch.Net.csproj
src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
src/Tests/ClientConcepts/Troubleshooting/AuditTrail.doc.cs
src/Tests/Framework/ManagedElasticsearch/Nodes/ElasticsearchNode.cs
src/Tests/Framework/ManagedElasticsearch/Nodes/NodeFileSystem.cs
src/Tests/Framework/ManagedElasticsearch/Process/ElasticsearchConsoleOut.cs
src/Tests/Framework/ManagedElasticsearch/Tasks/InstallationTasks/EnsureSecurityUsersInDefaultRealmAreAdded.cs
src/Tests/Framework/ManagedElasticsearch/Tasks/InstallationTasks/InstallationTaskBase.cs
src/Tests/Framework/TestClient.cs
src/Tests/Reproduce/ConnectionReuseAndBalancing.cs

This PR fixes several issues:
While on Desktop CLR we still use WebRequest where the following holds true as per: http://msdn.microsoft.com/en-us/library/system.net.httpwebresponse.getresponsestream.aspx
> You must call either the Stream.Close or the HttpWebResponse.Close method to close the stream and release the connection for reuse. It is not necessary to call both Stream.Close and HttpWebResponse.Close, but doing so does not cause an error. Failure to close the stream will cause your application to run out of connections.
The same is not necessarily true for all `HttpMessageHandler` implementations on CoreFX as @icanhasjonas reported on #2784.
While fixing that and running our connection reuse integration test I noticed that even with the fix in place this test always failed. Some TCP …

Several fixes related to HttpClient + .NET Core + linux

---

src/Tests/Program.cs
src/Tests/Tests.csproj

Visual Studio 2017 RTM and Resharper unit test runner are currently broken: https://youtrack.jetbrains.com/issue/RSRP-464233
This fix allows xunit tests to be runnable within Visual Studio by adding references to the following packages:
```
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
```
A consequence of doing this is that Microsoft.NET.Test.Sdk defines a Main entry point which means that Tests project cannot define one. Main renamed to TestMain until this is resolved.

Runnable xunit tests with Resharper

---

src/Tests/ClientConcepts/ConnectionPooling/Sniffing/RoleDetection.doc.cs
src/Tests/Document/Multiple/BulkAll/BulkAllApiTests.cs
src/Tests/Framework/Configuration/EnvironmentConfiguration.cs
src/Tests/Framework/Configuration/Versions/ElasticsearchVersion.cs
src/Tests/Framework/Configuration/YamlConfiguration.cs
src/Tests/Framework/ManagedElasticsearch/Nodes/ElasticsearchNode.cs
src/Tests/Framework/ManagedElasticsearch/Nodes/NodeConfiguration.cs
src/Tests/Framework/ManagedElasticsearch/Plugins/ElasticsearchPluginCollection.cs
src/Tests/Framework/ManagedElasticsearch/Tasks/ValidationTasks/ValidateRunningVersion.cs
src/Tests/Framework/TestClient.cs
src/Tests/XPack/Watcher/ExecuteWatch/ExecuteWatchApiTests.cs

- Share `ElasticsearchVersion` instances created.
- Allow more time for flaky integration tests
These were failing consistently locally for me so I've increased the doc count and wait time to allow some indexing to take place.
Needs porting to `master`

`ElasticsearchNode` should use `DesiredPort` from `NodeConfiguration`

---

src/Nest/CommonAbstractions/LazyDocument/LazyDocument.cs
src/Nest/CommonAbstractions/LazyDocument/LazyDocumentJsonConverter.cs
src/Nest/Search/Search/Hits/InnerHitsResult.cs
src/Tests/Reproduce/GithubIssue2788.cs

When converting a LazyDocument to type T, use the JsonNetSerializer configured, along with all registered contract resolvers.
Fixes #2788

Use serializer when deserializing LazyDocument to T

---

src/Nest/QueryDsl/FullText/Match/MatchQuery.cs
src/Nest/QueryDsl/FullText/MultiMatch/MultiMatchQuery.cs
src/Nest/QueryDsl/FullText/QueryString/QueryStringQuery.cs
src/Nest/QueryDsl/FullText/SimpleQueryString/SimpleQueryStringQuery.cs
src/Nest/QueryDsl/TermLevel/Fuzzy/FuzzyQueryBase.cs
src/Nest/QueryDsl/TermLevel/Prefix/PrefixQuery.cs
src/Nest/QueryDsl/TermLevel/Wildcard/WildcardQuery.cs
src/Tests/QueryDsl/FullText/QueryString/QueryStringUsageTests.cs
src/Tests/QueryDsl/FullText/SimpleQueryString/SimpleQueryStringUsageTests.cs

Add missing fields on simple query string query
Add `quote_field_suffix` to simple_query_string query
Deprecate `lowercase_expanded_terms` and `locale`: elastic/elasticsearch#20208
Add "all field" execution mode to query_string and simple_query_string query: elastic/elasticsearch#20925
Fixes #2792
Requires porting to `master` (check if `lowercase_expanded_terms` and `locale` should be removed)

Add missing fields on simple query string query

---

docs/intro.asciidoc

This updates "stackoverflow" to "Stack Overflow" and moves to `https://`.

Fixes to Stack Overflow links in NEST

---

build/scripts/Benchmarking.fsx
build/scripts/Commandline.fsx

Add branchname and setup Team City command line version.

Add branch name to benchmarking results, add command line parameter

---

src/Nest/Aggregations/Bucket/Histogram/HistogramAggregation.cs
src/Tests/Aggregations/Bucket/Histogram/HistogramAggregationUsageTests.cs

Reintroduced removed members for backwards compatibility
rebased and squashed version of #2820 by @jeroenkoknl

deprecate PreOffset and PostOffset and introduced Offset

---

src/Nest/Aggregations/AggregationsHelper.cs
src/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageHoltLinearAggregationUsageTests.cs
src/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageHoltWintersAggregationUsageTests.cs
src/Tests/Aggregations/Pipeline/SerialDifferencing/SerialDifferencingAggregationUsageTests.cs

Use lag in the usage test that return values.
https://discuss.elastic.co/t/using-serial-differencing-aggregation-in-net/96402/3

Add AggregationsHelper for SerialDifferencing

---

src/Nest/Aggregations/Bucket/DateHistogram/DateHistogramAggregation.cs
src/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs

Make the ExtendedBounds property of the DateHistogramAggregation to use DateMath instead of DateTime.
See Issue #2828

ExtendedBounds property of the DateHistogramAggregation to use DateMath

---

build/scripts/Paths.fsx
build/scripts/Releasing.fsx

Supercedes #2862 
Resolve the version of JSON.Net from the version referenced in Nest.csproj and calculate the next major version from this.
Closes #2831

Resolve JSON.Net version and next major version from Nest.csproj

---

src/Nest/Aggregations/Bucket/DateHistogram/DateHistogramAggregation.cs
src/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs

Set Format when Missing is specified

---

src/Nest/Analysis/TokenFilters/CommonGramsTokenFilter.cs

Add ReadSingleOrEnumerableJsonConverter attribute to allow single common_words values to be deserialized
Fix for #2886

Add ReadSingleOrEnumerableJsonConverter attribute

---

src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
src/Elasticsearch.Net/Connection/HttpConnection.cs

- Disable `AllowWriteStreamBuffering` on HttpWebRequest as requests do not require retrying with buffered content.
- Remove superfluous Keep-Alive header on .NET Core HttpConnection

Disable AllowWriteStreamBuffering 

---

src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs

Issue: If a node is down due to some maintenance work. Then sometimes the ES queries take more than 20s to complete. Instead of timing out after 2s (PingTimeout) and retrying on the other client node in the cluster.
Fix: Change the request time out for ping requests to ping timeout.

For Ping(node) method, setting request time out equal to ping timeout

---

src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
src/Tests/ClientConcepts/Connection/HttpConnectionTests.cs

With HttpClientHandler.Proxy = null HttClient still tries to detect and use system proxy.
I've fixed this by using HttpClientHandler.UseProxy flag, which prevents HttpClient from using proxy at all.
"Else if" is used to avoid preventing usage of proxy, if client setted ProxyAddress.

Set HttpClientHandler.UseProxy=false to disable automatic proxy detection

---

src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/Bucket/BucketAggregation.cs
src/Nest/Search/Percolator/Percolate/PercolateRequest.cs
src/Nest/Search/Percolator/PercolateCount/PercolateCountRequest.cs
src/Nest/Search/Search/SearchRequest.cs
src/Tests/Aggregations/WritingAggregations.doc.cs

Firstly this PR allows you to use the ois syntax directly on the fluent
descriptors.
Second, when abstracting to methods e.g .Aggs(s=> Compose()) could lead
to unexpected results if `Compose` returns `AggregationContainer` by
using OIS to compose multiple `AggregationBase`'s. The implicit
conversion from `AggregationBase` to `AggregationContainer` failed if
that `AggregationBase` was off type `AggregationCombinator` in which
case none of the combinator aggregations were lifted. This is a tad
unconvential and undocumented way of generating aggregations but its not
that far fetched + it compiles so should generate the expected output.
Third, you are now allowed to call unary `&&` operator on the same
`AggregationDescriptor` allowing you to write `aggs.Terms() &&
agg.Max()` and abstract to …

Improve composing aggregations

---

src/Nest/CommonAbstractions/Extensions/Extensions.cs
src/Nest/Document/Multiple/ScrollAll/ScrollAllObservable.cs

Relates elastic/support-dev-help#2934
The sychronization context is captured in some of the asychronous calls made within the paths of the *All observable methods. Whilst this does not exhibit problems with the synchronization context within a console application, it causes problems with the synchronization context within ASP.NET 4.5 MVC, resulting in the response to an MVC controller to be returned before the last response is returned from Elasticsearch:
Whilst there are integration tests for *All observable methods, this was not picked up because async methods within tests run with the same synchronization context as a console application.
With this PR, the behaviour is now correct within ASP.NET 4.5. MVC:
Other changes:
- Continue only when the count of tasks is less than degrees of …

Do not capture synchronization context on async calls

---

src/Nest/Search/Search/Sort/SortBase.cs
src/Nest/Search/Search/Sort/SortGeoDistance.cs
src/Tests/Search/Request/SortUsageTests.cs

This PR allows non string values to be passed for the value of the "missing" field by using `object` as the property type.
Rename `PinTo()` to `Points()` to align the fluent method for setting Points to the object initializer name.
Requires backporting to 2.x and 5.x in a non-binary breaking way
Closes #2857

Allow non-string values for Sort "missing" field

---

src/Nest/Search/Search/Sort/SortBase.cs
src/Tests/Search/Request/SortUsageTests.cs

Non-binary breaking backport
Closes #2857
(cherry picked from commit f5959d66c15574a23595cdee2777f6987319775b)

Support non string values for sort missing

---

src/Nest/Modules/Scripting/IStoredScript.cs
src/Nest/Modules/Scripting/PutScript/PutScriptRequest.cs
src/Nest/Modules/Scripting/ScriptLang.cs
src/Tests/Modules/Scripting/PutScript/PutScriptApiTests.cs

PR may contradict breaking change information here: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_scripting_changes.html#_stored_search_template_apis_removed
---
- Groovy, JavaScript, and Python languages removed
The Groovy, JavaScript, and Python scripting languages were deprecated in elasticsearch 5.0 and have now been removed. Use painless instead.
- lang can no longer be specified when using a stored script as part of a request
The lang variable can no longer be specified as part of a request that uses a stored script otherwise an error will occur. Note that a request using a stored script is different from a request that puts a stored script. The language of the script has already been stored as part of the cluster state and an id is sufficient to access …

6.0 Script changes

---

src/Elasticsearch.Net/ConnectionPool/Node.cs
src/Elasticsearch.Net/Responses/Sniff/SniffResponse.cs
src/Tests/ClientConcepts/ConnectionPooling/BuildingBlocks/ConnectionPooling.doc.cs
src/Tests/ClientConcepts/ConnectionPooling/Sniffing/RoleDetection.doc.cs
src/Tests/ClientConcepts/ConnectionPooling/Sticky/StickySniffingConnectionPool.doc.cs
src/Tests/Framework/VirtualClustering/VirtualCluster.cs

Relates https://github.com/elastic/elasticsearch/issues/27805
Elasticsearch 6.1.0 returns path.data as an array of values. Cater for this by making settings a `Dictionary<string,object>` as opposed to `Dictionary<string,string>`

Change Node settings to Dictionary<string,object>

---

docs/aggregations/bucket/date-histogram/date-histogram-aggregation-usage.asciidoc
src/Nest/Aggregations/Bucket/DateHistogram/DateHistogramAggregation.cs
src/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs

Non-binary breaking backport of #2829
Closes #2828

Support DateMath for DateHistogram ExtendedBounds

---

src/Nest/Aggregations/Bucket/SignificantTerms/SignificantTermsAggregation.cs

Change MinimumDocumentCount to long? to align with Elasticsearch implementation
Closes #2847 
Backport to 5.x and 2.x _without_ the binary breaking change to `MinimumDocumentCount `

Add shard_min_doc_count to Significant Terms Aggregation

---

docs/search/request/highlighting-usage.asciidoc
src/Nest/Search/Search/Highlighting/Highlight.cs
src/Nest/Search/Search/Highlighting/HighlightField.cs
src/Nest/Search/Search/Highlighting/HighlighterEncoder.cs
src/Nest/Search/Search/Highlighting/HighlighterOrder.cs
src/Nest/Search/Search/Highlighting/HighlighterTagsSchema.cs
src/Tests/Search/Request/HighlightingUsageTests.cs

- Change order from string to HighlighterOrder?
- Change TagsSchema from string to HighlighterTagsSchema?
- Remove BoundaryMaxSize
- Change Encoder to HighlighterEncoder?
- Remove encoder from highlight fields as it is only valid on the top level highlighter
- Add Encoder and PhraseLimit to integration test
Requires backporting to 5.x and 2.x in a non-binary breaking way.
Closes #2851

Add phrase_limit to highlighting

---

src/Nest/Indices/IndexSettings/IndexTemplates/GetIndexTemplate/TemplateMapping.cs
src/Nest/Indices/IndexSettings/IndexTemplates/PutIndexTemplate/PutIndexTemplateRequest.cs
src/Tests/Indices/IndexSettings/IndexTemplates/GetIndexTemplate/GetIndexTemplateApiTests.cs
src/Tests/Indices/IndexSettings/IndexTemplates/PutIndexTemplate/PutIndexTemplateApiTests.cs

Add version to PutTemplateRequest

---

docs/aggregations/metric/top-hits/top-hits-aggregation-usage.asciidoc
src/Nest/Aggregations/Metric/TopHits/TopHitsAggregation.cs
src/Tests/Aggregations/Metric/TopHits/TopHitsAggregationUsageTests.cs

Top Hits Aggregation fluent lambda syntax constrains sort options to field sorting, even though ITopHitsAggregation can accept any implementation of ISort. This commit deprecates the current fluent Sort implementation in favour of an implementation that allow multiple sort options besides field sorting, and assigns the resulting collection of sort options to IList<ISort>.
Update TopHitsAggregation usage test to call the new Sort method.
Fixes #2913

 Add additional sort options to Top Hits Aggregation

---

src/Nest/Indices/IndexManagement/RolloverIndex/RolloverIndexRequest.cs
src/Tests/Indices/IndexManagement/RolloverIndex/RolloverIndexApiTests.cs

Add Settings, Aliases and Mappings to RollOverIndexRequest

---

docs/search/request/suggest-usage.asciidoc
src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
src/Nest/QueryDsl/Specialized/Template/TemplateQuery.cs
src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
src/Nest/QueryDsl/Visitor/QueryVisitor.cs
src/Nest/Search/Suggesters/PhraseSuggester/PhraseSuggestCollate.cs
src/Nest/Search/Suggesters/PhraseSuggester/PhraseSuggestCollateQuery.cs
src/Tests/QueryDsl/Specialized/Template/TemplateQueryUsageTests.cs
src/Tests/Search/Request/SuggestUsageTests.cs

Relates #2965 
This commit adds a Parameters dictionary to IPhraseSuggestCollate so that parameters are serialized to the correct query form and introduces a PhraseSuggestCollateQuery to specify the query.
Add XML documentation to indicate the usage of each property.
Closes #2849
(cherry-picked from commit f905270)

 Add Params to PhraseSuggestCollate (forward port to master)

---

src/Nest/CommonAbstractions/Extensions/Extensions.cs
src/Nest/CommonAbstractions/Response/ResolvableDictionaryProxy.cs
src/Nest/Indices/MappingManagement/GetMapping/GetMappingResponse.cs
src/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs

We used to have a Mapping property which returns the first index's first type's mapping. Since folks typically call get mapping to only return a single mapping. We removed this because its a leaky abstraction but it might be hard for folks to figure out the best way now. Introduced GetMappingFor helpers and reintroduced the Mapping property with an obsolete to guide folks during upgrade.
cc @niemyjski

GetMapping helpers to get the TypeMapping for a type.

---

src/Nest/Indices/AliasManagement/Alias/BulkAliasRequest.cs
src/Tests/Indices/AliasManagement/Alias/AliasApiRemoveIndexTests.cs

RemoveIndex on BulkAliasDescriptor was not fluent, returning instead the interface IBulkAliasRequest.

Fix fluent for BulkAliasDescriptor.RemoveIndex()

---

docs/common-options/date-math/date-math-expressions.asciidoc
docs/common-options/time-unit/time-units.asciidoc
docs/query-dsl/term-level/range/date-range-query-usage.asciidoc
src/Nest/CommonAbstractions/Extensions/Extensions.cs
src/Nest/CommonAbstractions/SerializationBehavior/GenericJsonConverters/JsonConverterBase.cs
src/Nest/CommonOptions/DateMath/DateMath.cs
src/Nest/CommonOptions/DateMath/DateMathExpression.cs
src/Nest/CommonOptions/DateMath/DateMathOperation.cs
src/Nest/CommonOptions/DateMath/DateMathTime.cs
src/Nest/CommonOptions/DateMath/DateMathTimeUnit.cs
src/Nest/CommonOptions/TimeUnit/Time.cs
src/Nest/CommonOptions/TimeUnit/TimeUnit.cs
src/Tests/Aggregations/Bucket/DateRange/DateRangeAggregationUsageTests.cs
src/Tests/ClientConcepts/ConnectionPooling/RequestOverrides/RequestTimeoutsOverrides.doc.cs
src/Tests/CommonOptions/DateMath/DateMathExpressions.doc.cs
src/Tests/CommonOptions/TimeUnit/TimeUnits.doc.cs
src/Tests/QueryDsl/TermLevel/Range/DateRangeQueryUsageTests.cs

The Time type has historically been used to represent both Elasticsearch's TimeValue and time within Date Math expressions. This is slightly misleading because
1. TimeValue accepts units from nanos -> seconds
2. Date Math expressions with time accept units from seconds -> years
In both cases, Elasticsearch accepts only whole numbers in addition to a unit of measure.
This commit introduces a new DateMathTime type to represent times within DateMath expressions, with a DateMathTimeUnit enum to represent the valid units for this type. There are implicit conversions from string, TimeSpan and double such that implicit conversion usage in users upgrading from 5.x -> 6.x will not be affected by the change. The constructors that accept string, TimeSpan and double accept fractional numbers to make …

Split out Time into separate types for Time values and DateMath times

---

docs/aggregations/bucket/significant-terms/significant-terms-aggregation-usage.asciidoc
docs/aggregations/metric/top-hits/top-hits-aggregation-usage.asciidoc
src/Tests/Indices/IndexManagement/CreateIndex/CreateIndexApiTests.cs

Fixes test with a SkipAttribute.
Update docs.

DFI similarity type only exists on 2.3.0+ versions.

---

src/Nest/CommonAbstractions/Extensions/TypeExtensions.cs
src/Nest/CommonAbstractions/SerializationBehavior/InternalSerializer.cs

Cache compiled expressions for resolving default(T) from a Type
Remove virtual from methods of InternalSerializer. Users cannot derive from this internal type any more.

DeserializeAsync behaviour consistent with its generic counterpart

---

src/Nest/Aggregations/AggregateJsonConverter.cs
src/Tests/Aggregations/AggregationMetaUsageTests.cs

This commit uses the JsonSerializer to deserialize the aggregation metadata to a Dictionary<string,object> from the JsonReader.
Add integration test to assert behaviour.
Closes #3072

Deserialize aggregation metadata to Dictionary<string,object>

---

docs/client-concepts/certificates/working-with-certificates.asciidoc
docs/client-concepts/high-level/mapping/attribute-mapping.asciidoc
docs/client-concepts/high-level/mapping/auto-map.asciidoc
docs/client-concepts/high-level/mapping/fluent-mapping.asciidoc
docs/client-concepts/high-level/mapping/ignoring-properties.asciidoc
docs/client-concepts/high-level/mapping/multi-fields.asciidoc
docs/client-concepts/high-level/mapping/visitor-pattern-mapping.asciidoc
src/Nest/CrossPlatform/TypeExtensions.cs
src/Nest/Mapping/TypeMapping.cs
src/Nest/Mapping/Types/Properties.cs
src/Tests/ClientConcepts/HighLevel/Mapping/AttributeMapping.doc.cs
src/Tests/ClientConcepts/HighLevel/Mapping/AutoMap.doc.cs
src/Tests/ClientConcepts/HighLevel/Mapping/FluentMapping.doc.cs
src/Tests/ClientConcepts/HighLevel/Mapping/IgnoringProperties.doc.cs
src/Tests/ClientConcepts/HighLevel/Mapping/MultiFields.doc.cs
src/Tests/ClientConcepts/HighLevel/Mapping/VisitorPatternMapping.doc.cs

- This commit adds a non-generic overload for automapping.
Closes #2907
- Use client calls in automapping documentation, and test the non-generic automapping overload
Closes #2960

Non generic automap

---

src/CodeGeneration/DocGenerator/AsciiDoc/GeneratedAsciidocVisitor.cs
src/CodeGeneration/DocGenerator/AsciiDoc/RawAsciidocVisitor.cs
src/CodeGeneration/DocGenerator/DocGenerator.csproj

Backport of #3088 to 6.x. 
Should this be backported to `5.x` and `2.x` as well?

update to alpha6 on the 6.x branch

---

src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
src/Tests/Reproduce/BytesResponseTests.cs

This commit fixes a bug that was introduced when moving to typed
ElasticsearchResponse<T> responses from the low level client,
whereby the response.Body was not being set in the case of BytesResponse.

Set Body on low level response for BytesResponse

---

build/NEST.JsonNetSerializer.nuspec
src/CodeGeneration/DocGenerator/DocGenerator.csproj
src/Nest/Nest.csproj
src/Serializers/Nest.JsonNetSerializer/Nest.JsonNetSerializer.csproj

This also removes the +1 major exclusive restriction on the dependency range.
I am OK with folks upgrading at their own risk given that we internalize our own `JSON.NET` now.

Fix #3115 bump json.net to version 11

---

src/CodeGeneration/ApiGenerator/ApiGenerator.csproj
src/CodeGeneration/DocGenerator/DocGenerator.csproj
src/Nest/Nest.csproj
src/Tests/Tests.csproj

Fix #3115 bump json.net to version 11
This keeps the strict nuget dependency version range because anything over `11.x` might introduce breaking changes in NEST's serialization.

Fix #3115 bump json.net to version 11.x [5.x clients]

---

src/CodeGeneration/ApiGenerator/ApiGenerator.csproj
src/CodeGeneration/DocGenerator/DocGenerator.csproj
src/Nest/Nest.csproj
src/Tests/Tests.csproj

Keeps the strict dependency range because a major upgrade of JSON.NET might break NEST's own types serialization.

Fix #3115 bump json.net to version 11.x [2.x clients]

---

src/Nest/Search/Search/InnerHits/InnerHits.cs
src/Tests/Search/Request/InnerHitsUsageTests.cs

Add ignore_unmapped to inner_hits

---

src/Nest/Search/Suggesters/BaseSuggest.cs
src/Nest/Search/Suggesters/CompletionSuggester/CompletionSuggester.cs
src/Tests/Search/Request/SuggestUsageTests.cs

Add skip_duplicates to completion suggester

---

.paket/Paket.Restore.targets
src/Nest/Mapping/AttributeBased/ElasticsearchCorePropertyAttributeBase.cs
src/Nest/Mapping/DynamicMapping.cs
src/Nest/Mapping/Types/Complex/Object/ObjectProperty.cs
src/Nest/Mapping/Types/CorePropertyBase.cs
src/Nest/Mapping/Types/PropertyBase.cs
src/Tests/ClientConcepts/HighLevel/Mapping/AttributeMapping.doc.cs
src/Tests/ClientConcepts/HighLevel/Mapping/FluentMapping.doc.cs
src/Tests/ClientConcepts/HighLevel/Mapping/VisitorPatternMapping.doc.cs

Remove multiple types per index from documentation

---

docs/client-concepts/high-level/serialization/custom-serialization.asciidoc
src/Serializers/Nest.JsonNetSerializer/ConnectionSettingsAwareSerializerBase.Serializer.cs
src/Tests/ClientConcepts/HighLevel/Serialization/CustomSerialization.doc.cs
src/Tests/Reproduce/JsonNetSerializerConverters.cs

This commit honours the addition of JsonConverters to the JsonSerializerSettings
constructed from the Func<JsonSerializerSettings> passed to JsonNetSerializer.
JsonSerializerSettings is always instantiated with an instance of List<JsonConverter>
for its Converters property.
Closes #3161

Honour JsonConverters added in JsonSerializerSettings

---

src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs

When making a HEAD requests the response does not contain a ContentType. The Async version of `Request` already has this check, however the synchronous call fails with a NullReferenceException.

Fix synchronous HEAD request

---

src/Nest/QueryDsl/FullText/MultiMatch/MultiMatchQuery.cs
src/Tests/QueryDsl/FullText/MultiMatch/MultiMatchUsageTests.cs

This commit adds the ability to send multi_match query without providing any fields.
When no fields are provided the multi_match query will use the fields
defined in the index setting index.query.default_field
(which in turns defaults to *).
Closes #3159

Change Fields to be optional on MultiMatchQuery

---

src/Nest/Indices/Monitoring/IndicesSegments/Segment.cs
src/Tests/Indices/Monitoring/IndicesSegments/SegmentsApiTests.cs

This commit adds attributes to the Segments API.
Add memory_in_bytes, version and compound.
Deprecate size.
Closes #3160

Add segment attributes to the _segments API

---

src/Nest/Mapping/Types/Geo/GeoShape/GeoShapeAttribute.cs
src/Nest/Mapping/Types/Geo/GeoShape/GeoShapeProperty.cs

This commit adds ignore_malformed to GeoShapeProperty mappings i.e. geo_shape fields.
Add XML documentation to explain properties.
Closes #3155

Add ignore_malformed to GeoShapeProperty

---

src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
src/Elasticsearch.Net/Responses/ElasticsearchResponse.cs
src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs

This commit is a backport of #3188 that adds the response mime type to ElasticsearchResponse.

Add response mime type to response

---

src/Nest/Modules/SnapshotAndRestore/Repositories/S3Repository.cs
src/Tests/Modules/SnapshotAndRestore/Repositories/CreateRepository/CreateRepositoryApiTests.cs

This commit updates the settings available for the s3 repository
plugin.
Add client,buffer_size,canned_acl,storage_class,server_side_encryption
Remove access_key,secret_key. Now specified in elasticsearch keystore.
Remove concurrent_streams.
Closes #3141

Update settings available for s3 repository plugin

---

src/Nest/Aggregations/AggregateDictionary.cs
src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/Bucket/SignificantTerms/IncludeExclude.cs
src/Nest/Aggregations/Bucket/SignificantTerms/SignificantTermsAggregation.cs
src/Nest/Aggregations/Bucket/SignificantText/SignificantTextAggregation.cs
src/Nest/Aggregations/Visitor/AggregationVisitor.cs
src/Nest/Aggregations/Visitor/AggregationWalker.cs
src/Tests/Aggregations/Bucket/SignificantTerms/SignificantTermsAggregationUsageTests.cs
src/Tests/Aggregations/Bucket/SignificantText/SignificantTextAggregationUsageTests.cs

This commit adds SignificantText aggregation. Reuse types from
SignificantTerms aggregation where possible.
Rename SignificantTermsIncludeExclude to simply IncludeExclude
Closes #3181

Add Significant Text Aggregation

---

src/Nest/Aggregations/AggregateDictionary.cs
src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/Bucket/SignificantTerms/SignificantTermsIncludeExclude.cs
src/Nest/Aggregations/Bucket/SignificantText/SignificantTextAggregation.cs
src/Nest/Aggregations/Visitor/AggregationVisitor.cs
src/Nest/Aggregations/Visitor/AggregationWalker.cs
src/Tests/Aggregations/Bucket/SignificantText/SignificantTextAggregationUsageTests.cs

Backport of #3200
Preserves type name of `SignificantTermsIncludeExclude` instead of newly named `IncludeExclude`

Add significant terms aggregations to 6.x

---

src/Nest/QueryDsl/Geo/Shape/Circle/GeoShapeCircleQuery.cs
src/Nest/QueryDsl/Geo/Shape/Envelope/GeoShapeEnvelopeQuery.cs
src/Nest/QueryDsl/Geo/Shape/GeoShapeBase.cs
src/Nest/QueryDsl/Geo/Shape/GeoShapeQueryJsonConverter.cs
src/Nest/QueryDsl/Geo/Shape/GeometryCollection/GeometryCollection.cs
src/Nest/QueryDsl/Geo/Shape/IGeoShapeQuery.cs
src/Nest/QueryDsl/Geo/Shape/LineString/GeoShapeLineStringQuery.cs
src/Nest/QueryDsl/Geo/Shape/MultiLineString/GeoShapeMultiLineStringQuery.cs
src/Nest/QueryDsl/Geo/Shape/MultiPoint/GeoShapeMultiPointQuery.cs
src/Nest/QueryDsl/Geo/Shape/MultiPolygon/GeoShapeMultiPolygonQuery.cs
src/Nest/QueryDsl/Geo/Shape/Point/GeoShapePointQuery.cs
src/Nest/QueryDsl/Geo/Shape/Polygon/GeoShapePolygonQuery.cs
src/Tests/QueryDsl/Geo/GeoShapeQueryUsageTests.cs
src/Tests/QueryDsl/Geo/Shape/GeoShapeQueryUsageTestsBase.cs
src/Tests/QueryDsl/Geo/Shape/Polygon/GeoShapePolygonQueryUsageTests.cs

This commit deprecates IgnoreUnmapped on IGeoShape by applying Obsolete attribute.
IgnoreUnmapped exists at the same level as _name and boost on a geo_shape query.
Map IgnoreUnmapped from IGeoShape.IgnoreUnmapped to IGeoShapeQuery.IgnoreUnmapped if
assigned.

Obsolete IgnoreUnmapped on IGeoShape

---

src/Nest/Mapping/Visitor/IMappingVisitor.cs
src/Nest/Mapping/Visitor/IPropertyVisitor.cs
src/Nest/Mapping/Visitor/MappingWalker.cs
src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
src/Nest/Mapping/Visitor/PropertyWalker.cs
src/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs

This commit adds mapping and property visitor methods for
the range data types.
Map a QueryContainer property as a percolator data type by default.

Add Visit methods for *_range properties

---

src/Nest/CommonAbstractions/Infer/Id/Id.cs
src/Nest/Document/Single/Index/IndexRequest.cs
src/Tests/Document/Single/Index/IndexUrlTests.cs

This commit fixes the selection of HTTP method for an index request based
on the presence of an explicilty set Id, or an Id value that can be inferred from
the document.
In the previous implementation, the IUrlParameter.GetString() method on the Id type
evaluated the Document to infer an Id from it, setting the internal Value of the Id to this
inferred value. As part of refactoring, this assignment was removed, which changes the
behaviour of the client when determining the HTTP method for an index request; in this
scenario, it is not enough to look to see if the Id type has a value, or that the Document is
not null, we need to know at this point that an Id can be inferred from the Document, and can
thereby send a PUT request.
An Id is inferred from the Document before the HTTP method is …

Fix HTTP method choice for index requests

---

src/CodeGeneration/ApiGenerator/Domain/ApiQueryParameters.cs
src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
src/Elasticsearch.Net/Serialization/ElasticsearchUrlFormatter.cs
src/Nest/CommonOptions/TimeUnit/Time.cs
src/Nest/_Generated/_Requests.generated.cs
src/Tests/Reproduce/GithubIssue3220.cs

This commit implements IUrlParameter on Time so that the conversion to a
string value happens when building the url.
Add condition to ElasticsearchUrlFormatter to convert TimeSpan to Time unit
string value when building the url.
Remove special case handling for Time and TimeSpan and re-run API generation
Fixes #3220

Implement IUrlParameter on Time

---

src/Tests/Framework/Configuration/Versions/ElasticsearchVersion.cs
src/Tests/Framework/ManagedElasticsearch/Tasks/InstallationTasks/EnsureElasticsearchBatWorksAcrossDrives.cs
src/Tests/Framework/ManagedElasticsearch/Tasks/NodeTaskRunner.cs

This commit patches the elasticsearch.bat file for 6.2 versions to include the
fix in PR https://github.com/elastic/elasticsearch/pull/29086

Patch elasticsearch.bat for 6.2 versions

---

src/Tests/ClientConcepts/Certificates/WorkingWithCertificates.doc.cs

This PR fixes https://www.elastic.co/guide/en/elasticsearch/client/net-api/master/working-with-certificates.html such that it uses the command name "elasticsearch-certutil" instead of just "certutil".

[DOCS] Fixes certutil command name

---

src/Nest/Search/Suggesters/TermSuggester/StringDistance.cs

Unsure if we should rename the enumeration value at this stage as it would break binary compatibility.
Potentially consider implementing another enumeration value with the correct spelling? @russcam - thoughts?

Closes #3251. Rename levenstein to levenshtein.

---

src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs

ReadErrorAsync() was missing a ConfigureAwait when called

---

src/Nest/CommonAbstractions/SerializationBehavior/SourceConverter.cs
src/Tests/Reproduce/GithubIssue3164.cs

This commit fixes an issue where the default Json.NET implementation when
creating a JToken from a reader, will convert DateTimeOffset to local time with
local offset. See https://github.com/JamesNK/Newtonsoft.Json/issues/862. This
is unwanted when passing off to the SourceSerializer.
Closes #3164

Respect JSON Dates from Elasticsearch when passing to SourceSerializer

---

docs/aggregations.asciidoc
docs/aggregations/bucket/composite/composite-aggregation-usage.asciidoc
docs/aggregations/bucket/date-histogram/date-histogram-aggregation-usage.asciidoc
src/Nest/Aggregations/AggregateDictionary.cs
src/Nest/Aggregations/AggregateDictionaryConverter.cs
src/Nest/Aggregations/AggregateJsonConverter.cs
src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/Bucket/Composite/CompositeAggregation.cs
src/Nest/Aggregations/Bucket/Composite/CompositeAggregationSource.cs
src/Nest/Aggregations/Bucket/Composite/CompositeBucket.cs
src/Nest/Aggregations/Bucket/Composite/DateHistogramCompositeAggregationSource.cs
src/Nest/Aggregations/Bucket/Composite/HistogramCompositeAggregationSource.cs
src/Nest/Aggregations/Bucket/Composite/TermsCompositeAggregationSource.cs
src/Nest/Aggregations/Visitor/AggregationVisitor.cs
src/Nest/Aggregations/Visitor/AggregationWalker.cs
src/Nest/CommonAbstractions/LazyDocument/LazyDocument.cs
src/Nest/CommonAbstractions/LazyDocument/LazyDocumentJsonConverter.cs
src/Tests/Aggregations/Bucket/Composite/CompositeAggregationUsageTests.cs
src/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs

This commit adds Composite Aggregation support.
The bucket keys in the response to a Composite Aggregation are
`ILazyDocument`, allowing a user to convert to a type of their choosing.
Closes #2902

Add CompositeAggregation

---

src/Nest/CommonAbstractions/SerializationBehavior/InternalSerializer.cs

This commit checks that the response stream is seekable
before checking the length; Streams that are not seekable
will throw.

Check stream is seekable when checking length

---

src/Nest/Modules/SnapshotAndRestore/Snapshot/SnapshotStatus/SnapshotStatusResponse.cs

Needs porting to `6.x` and part of `6.2` release.
Relates to: https://github.com/elastic/elasticsearch/pull/26853
Example reference: https://github.com/liketic/elasticsearch/blob/ab0b127efd47b06aefea0eda27b99fd9d92abbe5/core/src/test/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatusTests.java

Include include_global_state in Snapshot status API. Closes #3258.

---

src/CodeGeneration/ApiGenerator/RestSpecification/Core/reindex.patch.json
src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
src/Nest/_Generated/_Descriptors.generated.cs
src/Nest/_Generated/_Requests.generated.cs

Sorry for all of the white space noise in the pull request, looks like it was added from the re-gen.
Added a patch file to the local json spec, awaiting fix in `elasticsearch` repo: https://github.com/elastic/elasticsearch/pull/31316

Add scroll parameter to reindex. Closes #3253

---

src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
src/Nest/Cluster/TaskManagement/GetTask/TaskInfo.cs
src/Nest/Cluster/TaskManagement/ListTasks/ListTasksResponse.cs
src/Tests/Search/Search/SearchApiTests.cs

Associate an external id with a task, so that it can be cancelled later.

---

src/Nest/Aggregations/Bucket/BucketAggregate.cs
src/Tests/Reproduce/GithubIssue3286.cs
src/Tests/tests.default.yaml

This commit fixes a bug with SingleBucketAggregate having an Aggregations
property; the property should not be there. Mark as obsolete and assign the
instance itself to the property, to at least mitigate null reference exception.
Remove `Aggregations` when porting to master
Closes #3286

Assign instance to Aggregations property

---

src/Nest/Document/Multiple/ReindexOnServer/ReindexSource.cs
src/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerSourceApiTests.cs

This commit adds the ability to specify the fields from source to reindex
when using the Reindex API (ReindexOnServer in NEST).
Closes #3288

Add ability to specify fields from _source to reindex

---

docs/client-concepts/high-level/inference/field-inference.asciidoc
docs/client-concepts/high-level/inference/types-and-relations-inference.asciidoc
docs/high-level.asciidoc
src/Nest/CommonAbstractions/Infer/Field/FieldExpressionVisitor.cs
src/Nest/CommonAbstractions/Infer/TypeName/TypeNameResolver.cs
src/Nest/CommonAbstractions/SerializationBehavior/PropertyMapping.cs
src/Tests/ClientConcepts/HighLevel/Inference/FieldInference.doc.cs
src/Tests/ClientConcepts/HighLevel/Inference/TypesAndRelationsInference.doc.cs
src/Tests/Framework/TestClient.cs
src/Tests/Reproduce/GithubIssue3107.cs
src/Tests/high-level.asciidoc

This commit updates the behaviour of TypeNameResolver and
PropertyMapping to respect the usage of DataMember and
DataContract attributes for all requests.
Prior behaviour to this commit was that indexing would honour
DataMember attributes on a document due to the internal implementation of
JSON.Net honouring them. With other requests such as Search however,
where a Field type is used, the the resolution of the Field string name did
not honour the attributes.
Closes #3107

Honour DataMember and DataContract attributes

---

build/scripts/Building.fsx
build/scripts/Commandline.fsx
build/scripts/Targets.fsx
src/Tests/BenchmarkProgram.cs
src/Tests/ClusterLaunchProgram.cs
src/Tests/Framework/Configuration/EnvironmentConfiguration.cs
src/Tests/Framework/Configuration/ITestConfiguration.cs
src/Tests/Framework/Configuration/TestConfigurationBase.cs
src/Tests/Framework/Configuration/YamlConfiguration.cs
src/Tests/Framework/ManagedElasticsearch/Clusters/ClientTestClusterBase.cs
src/Tests/Framework/ManagedElasticsearch/Clusters/INestTestCluster.cs
src/Tests/Framework/ManagedElasticsearch/Clusters/XPackCluster.cs
src/Tests/Framework/ManagedElasticsearch/XunitSetup.cs
src/Tests/ProfileProgram.cs
src/Tests/Program.cs
src/Tests/Tests.csproj

Can now start a test cluster from the root of the project by calling
`build cluster <clustername> <version>`
This will build and run the specified cluster from a temporary location.
Allowing us to develop and build under src/Test while it's running.
When running tests `Elastic.Xunit` now supports allowing it to assume a
cluster is already started. With a cluster already running, running the
integration tests from the IDE will be more responsive as we do not have
to wait for the whole cluster setup and teardown.
This brings back the final missing piece of functionality we had before
breaking `Elastic.Xunit` into its own project

build cluster command

---

src/Nest/Cat/ElasticClient-Cat.cs
src/Tests/Cat/CatIndices/CatIndicesApiTests.cs
src/Tests/Framework/EndpointTests/ApiIntegrationTestBase.cs

Right now we always attempt to deserialize to list of records but when a
server side error is returned we have can't deserialize the array as as
an object so we need to special case this in the converter callback

Fix #3303 Cat Response error should bubble out

---

src/Serializers/Nest.JsonNetSerializer/Converters/HandleNestTypesOnSourceJsonConverter.cs
src/Tests/Tests.Core/Client/TestClient.cs
src/Tests/Tests.Core/Serialization/SerializationTester.cs
src/Tests/Tests.Reproduce/GithubIssue3356.cs

When the join field is a string and using JsonNetSerializer, the string
conversion should not emit the surrounding double quotes
Closes #3356

Correctly deserialize JoinField

---

src/Nest/Mapping/DynamicTemplate/DynamicTemplate.cs
src/Tests/Tests/Mapping/Types/SingleMappingPropertyTestsBase.cs
src/Tests/Tests/Tests.csproj

Add MatchPattern to dynamic templates

---

src/CodeGeneration/ApiGenerator/Domain/ApiQueryParameters.cs
src/CodeGeneration/ApiGenerator/RestSpecification/Core/_common.json
src/CodeGeneration/ApiGenerator/Views/_Descriptors.Generated.cshtml
src/Nest/CommonAbstractions/Request/RequestBase.cs
src/Nest/_Generated/_Descriptors.generated.cs
src/Nest/_Generated/_Requests.generated.cs

This commit adds a note to the filter_path XML comments to warn about
response filtering potentially affecting deserialization to the respective response type.
Include XML comments on common options for Descriptor types
Closes #3331

Add note about filter_path and deserialization

---

src/Nest/Modules/SnapshotAndRestore/Restore/RestoreRequest.cs

Add include_aliases and partial to Snapshot Restore request

---

src/Nest/Document/Multiple/MultiTermVectors/ElasticClient-MultiTermVectors.cs
src/Nest/Document/Multiple/MultiTermVectors/MultiTermVectorOperation.cs
src/Nest/Document/Multiple/MultiTermVectors/MultiTermVectorsRequest.cs
src/Tests/Tests/Document/Multiple/MultiTermVectors/MultiTermVectorsApiTests.cs

This commit adds support for providing a set of Ids to MultiTermVectors API to be used in
conjunction with index and type provided in the URI.
Index() and Type() methods added to MultiTermVectorOperation to allow the default typeof(T)
values to be overidden.
Closes #3219

Support Ids in MultiTermVectors API

---

src/Nest/XPack/MachineLearning/Job/Detectors/Detector.cs
src/Nest/XPack/MachineLearning/Job/Detectors/GeographicDetector.cs

Include LatLongDetector on DetectorsDescriptor<T>

---

src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
src/Nest/QueryDsl/Query.cs
src/Nest/QueryDsl/TermLevel/Range/LongRangeQuery.cs
src/Nest/QueryDsl/TermLevel/Range/NumericRangeQuery.cs
src/Nest/QueryDsl/TermLevel/Range/RangeQueryJsonConverter.cs
src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
src/Nest/QueryDsl/Visitor/QueryVisitor.cs
src/Nest/QueryDsl/Visitor/QueryWalker.cs
src/Tests/QueryDsl/TermLevel/Range/LongRangeQueryUsageTests.cs

Hello, everybody,
I want to make range queries that correctly work with long type. So, I have added support of long range query. 
Small test to demonstrate trouble that I want to solve .
We want to work with timestamps that are long type:
```
q.Range(c => c
.Name("named_query")
.Boost(1.1)
.Field(p => p.Description)
.GreaterThan(636634079999999999)
.GreaterThanOrEquals(636634080000000000)
.LessThan(636634080000000000)
.LessThanOrEquals(636634079999999999)
.Relation(RangeRelation.Within))
```
converts numbers to double type:
```
query = new {
range = new {
description = new {
_name = "named_query",
boost = 1.1,
gt = 6.3663408E+17,
gte = 6.3663408E+17,
lt = 6.3663408E+17,
lte = 6.3663408E+17,
relation = "within"
}
}
}
```
and loses precision.
Elasticsearch himself is able to make such …

Long range query support

---

src/Tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
src/Tests/Tests.Profiling/Framework/ProfilingCluster.cs
src/Tests/Tests/Document/Multiple/Reindex/ReindexApiTests.cs

Before:
After:
Speeds up launching an integration cluster (`ReadOnlyCluster` and others who use `DefaultSeeder`).

SeedNode() on DefaultSeeder parallelizes where possible

---

src/Tests/Tests/Framework/EndpointTests/ApiIntegrationTestBase.cs
src/Tests/Tests/Search/Request/FieldsUsageTests.cs

When we do our response testing in the API integration tests only.
This changes the way assertions are executed though, reporting on all ALL the failures. 
Since we do quite a few assertions in a single method this would become noisy so we hack the message to only include the first failure as before

Use AssertionScope to always include response.DebugInformation

---

src/Tests/Tests/Aggregations/AggregationUsageTestBase.cs
src/Tests/Tests/Framework/EndpointTests/ApiIntegrationAgainstNewIndexTestBase.cs
src/Tests/Tests/Framework/EndpointTests/ApiIntegrationTestBase.cs
src/Tests/Tests/Framework/EndpointTests/ApiTestBase.cs
src/Tests/Tests/Framework/EndpointTests/CanConnectTestBase.cs
src/Tests/Tests/Framework/EndpointTests/ConnectionErrorTestBase.cs
src/Tests/Tests/Search/SearchUsageTestBase.cs
src/Tests/Tests/XPack/MachineLearning/MachineLearningIntegrationTestBase.cs

This PR duplicates inherited tests in the tests base class hierarchy, this fixes a bug in the jetBrains Rider/Resharper test runner that removes tests inherited from a (great++) grandparent when you open the test file https://youtrack.jetbrains.com/issue/RIDER-19912

Workaround RIDER-19912 

---

src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/Pipeline/MovingFunction/MovingFunctionAggregation.cs
src/Nest/Aggregations/Pipeline/PipelineAggregationBase.cs
src/Tests/Tests/Aggregations/Pipeline/MovingFunction/MovingAverageSimpleAggregationUsageTests.cs

https://github.com/elastic/elasticsearch/pull/29594

Add support for moving function aggregation

---

src/Nest/Aggregations/AggregateDictionary.cs
src/Nest/Aggregations/Aggregation.cs
src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/Metric/MetricAggregation.cs
src/Nest/Aggregations/Metric/WeightedAverage/WeightedAverageAggregation.cs
src/Nest/Aggregations/Metric/WeightedAverage/WeightedAverageValue.cs
src/Tests/Tests/Aggregations/Metric/WeightedAverage/WeightedAverageAggregationUsageTests.cs

https://www.elastic.co/guide/en/elasticsearch/reference/6.x/search-aggregations-metrics-weight-avg-aggregation.html

Add support for weighted average aggregation

---

src/Nest/Mapping/Types/Core/Keyword/KeywordAttribute.cs
src/Nest/Mapping/Types/Core/Keyword/KeywordProperty.cs
src/Tests/Tests.Configuration/tests.default.yaml
src/Tests/Tests/Mapping/Types/Core/Keyword/KeywordPropertyTests.cs

https://github.com/elastic/elasticsearch/pull/30691

add split_queries_on_whitespace to keyword property mappings

---

src/Nest/Mapping/Types/FieldType.cs
src/Nest/Mapping/Types/Properties.cs
src/Nest/Mapping/Types/PropertyDescriptorBase.cs
src/Nest/Mapping/Types/PropertyJsonConverter.cs
src/Nest/Mapping/Types/Specialized/FieldAlias/FieldAliasProperty.cs
src/Tests/Tests.Configuration/tests.default.yaml
src/Tests/Tests/Mapping/Types/Specialized/FieldAlias/AliasPropertyTests.cs

https://github.com/elastic/elasticsearch/pull/32172
This property mapping is not exposed as an attribute since this feature is about creating `"virtual"` fields I think it makes very little sense to map concrete POCO properties as aliases.

Add support for alias property mapping

---

src/Nest/Search/Search/Collapsing/FieldCollapse.cs
src/Nest/Search/Search/InnerHits/InnerHits.cs
src/Nest/Search/Search/SearchRequest.cs
src/Tests/Tests.Configuration/tests.default.yaml
src/Tests/Tests/Search/Search/Collapsing/FieldCollapseUsageTests.cs

as per https://github.com/elastic/elasticsearch/pull/31808

Support 2nd level field collapsing

---

src/Nest/Indices/Monitoring/IndicesStats/IndicesStats.cs

https://github.com/elastic/elasticsearch/pull/31871

Add uuid to indices stats

---

src/Nest/IndexModules/IndexSettings/Settings/DynamicIndexSettings.cs
src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsConverter.cs
src/Tests/Tests/Document/Multiple/Bulk/BulkApiTests.cs
src/Tests/Tests/Indices/IndexSettings/UpdateIndicesSettings/UpdateIndexSettingsApiTests.cs

This commit allows a null value to be passed for refresh_interval, which
allows a user to remove a transient value to fallback to the configured
persistent value.
A couple of different approaches were considered
1. Introducing an internal field on concrete implementations of IDynamicIndexSettings
that could be checked in IndexSettingsConverter to determine whether to serialize
the refresh_interval value, allowing a user to pass null. This has the downside of
needing to cast to concrete implementations in IndexSettingsConverter, rendering the
interface less useful.
2. Introducing a Time 'null' value with a Null Object pattern implementation, and
setting a Time.Null value in the event that null is passed to the property setter.
This would mean that IndexSettingsConverter would not need to …

Allow null refresh_interval to be passed

---

src/CodeGeneration/ApiGenerator/ApiGenerator.csproj
src/CodeGeneration/DocGenerator/DocGenerator.csproj
src/Nest/Nest.csproj
src/Tests/Tests.Domain/Tests.Domain.csproj
src/Tests/Tests/Framework/EndpointTests/ApiIntegrationTestBase.cs
src/Tests/Tests/Search/Suggesters/SuggestApiTests.cs

Upgrade to latest `Newtonsoft.Json` and silence flakey suggest tests. 
Also backports `AssertResponse` handling of `6.x` and `master` which does not eat the full stack trace

Fix #3501 bump Json.NET dependency on 5.x

---

src/Nest/CommonAbstractions/Infer/Field/Field.cs
src/Nest/CommonAbstractions/Infer/Field/FieldJsonConverter.cs
src/Nest/CommonAbstractions/Infer/Fields/Fields.cs
src/Nest/CommonAbstractions/Infer/Fields/FieldsDescriptor.cs
src/Nest/CommonAbstractions/Infer/Fields/FieldsJsonConverter.cs
src/Nest/CommonAbstractions/Static/Infer.cs
src/Tests/Tests/Search/Search/SearchApiTests.cs

This commit adds a format property on the Field type
to use with Doc Values fields, and updates serialization
components to handle the presence of a Format property value.
Closes #3490

Include Format property on Field for Doc Values fields

---

src/CodeGeneration/ApiGenerator/ApiGenerator.csproj
src/CodeGeneration/DocGenerator/DocGenerator.csproj
src/Nest/Nest.csproj
src/Serializers/Nest.JsonNetSerializer/Nest.JsonNetSerializer.csproj
src/Tests/Tests.Domain/Tests.Domain.csproj

On `6.x` `Nest.JsonNetSerializer.csproj` is the only one that publishes `Json.Net` as dependency on nuget but we still use it as an internalized dependency in `Nest`. 
We are working on moving away from that internalized `Json.Net` on `6.x` but in the interim lets stay up to date and upgrade.

Bump Newtonsoft.Json to 12 on 6.x

---

src/CodeGeneration/ApiGenerator/ApiGenerator.csproj
src/CodeGeneration/DocGenerator/DocGenerator.csproj
src/Nest/Nest.csproj
src/Serializers/Nest.JsonNetSerializer/Nest.JsonNetSerializer.csproj
src/Tests/Tests.Domain/Tests.Domain.csproj

Similar to #3509, we are in the process of moving away from `Json.Net` internally but while that work is on going make sure we stay up to date with the latest greatest.

Bump Newtonsoft.Json to 12 on master

---

src/Nest/CommonAbstractions/Infer/Field/Field.cs
src/Nest/CommonAbstractions/Static/Infer.cs
src/Tests/Tests/ClientConcepts/HighLevel/Inference/FieldInference.doc.cs
src/Tests/Tests/Search/Search/SearchApiTests.cs

removing thm was a bwc breaking change.
cc @codebrain @russcam

Return overloads that do not take format on Field in 6.x, 

---

src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
src/Elasticsearch.Net/Configuration/RequestConfiguration.cs

Updated Xmldocs to clarify that exceptions are not thrown for bulk actions.

Updated Xmldocs

---

src/Nest/CommonAbstractions/Infer/Field/Field.cs
src/Nest/CommonAbstractions/Infer/Fields/Fields.cs
src/Nest/CommonAbstractions/Infer/Fields/FieldsDescriptor.cs
src/Tests/Tests/Search/Search/SearchApiTests.cs

This PRadds backwards binary compatibility with 6.4.0
for method overloads on Field related types that can accept
a format parameter.

Add backwards compatible overloads for Field format

---

src/Nest/Aggregations/AggregateDictionary.cs
src/Nest/Aggregations/AggregateJsonConverter.cs
src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramAggregation.cs
src/Nest/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramBucket.cs
src/Nest/Aggregations/Bucket/BucketAggregate.cs
src/Nest/Aggregations/Bucket/DateHistogram/DateHistogramAggregation.cs
src/Tests/Tests/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramAggregationUsageTests.cs

Add support for the auto_date_histogram aggregations

---

src/Nest/Cluster/NodesStats/Statistics/IngestStats.cs
src/Tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
src/Tests/Tests/Cluster/NodesStats/NodesStatsApiTests.cs

Relates to: https://github.com/elastic/elasticsearch/pull/34724

Add processor stats to node ingest stats

---

src/Nest/Ingest/Processors/Plugins/GeoIpProcessor.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/AzureRepository.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/CreateRepository/CreateRepositoryRequest.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/FileSystemRepository.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/HdfsRepository.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/ISnapshotRepository.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/ReadOnlyUrlRepository.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/S3Repository.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/SourceOnlyRepository .cs
src/Tests/Tests/Modules/SnapshotAndRestore/Repositories/CreateRepository/CreateRepositoryApiTests.cs

elastic/elasticsearch#32844
This one was tricky to implement since `delegate_type` indicates which settings one can send. Came up with   a way to reuse existing typed classes for the other repository settings in the end although its not the cleanest.

Add support for source only snapshot repository

---

src/Tests/Tests.Core/ManagedElasticsearch/Clusters/XPackCluster.cs
src/Tests/Tests/XPack/MachineLearning/MachineLearningCluster.cs

This commit updates the DownloadMachineLearningSampleDataDistribution
compose task to move all files from files directory in the unzip
target directory into the top level target directory.

Move files from machine learning zip

---

src/Nest/CommonAbstractions/Infer/Field/Field.cs
src/Nest/CommonAbstractions/Static/Infer.cs
src/Nest/CommonOptions/DateMath/DateMath.cs
src/Nest/QueryDsl/TermLevel/Range/DateRangeQuery .cs
src/Tests/Tests.Reproduce/GithubIssue3538.cs
src/Tests/Tests/ClientConcepts/HighLevel/Inference/FieldInference.doc.cs
src/Tests/Tests/CommonOptions/DateMath/DateMathTests.cs
src/Tests/Tests/QueryDsl/TermLevel/Range/DateRangeQueryUsageTests.cs
src/Tests/Tests/Search/Search/SearchApiTests.cs

Pending the merge of `6.5` branch and all related PR's to that target branch.

fix #3505 daterange default DateTime should not serialize

---

docs/aggregations/bucket/auto-date-histogram/auto-date-histogram-aggregation-usage.asciidoc

Related to https://github.com/elastic/elasticsearch-net/commit/2234d5be612a77f94832bf0917b2bf164e500317
In particular, the documentation build was failing with these broken links:
09:33:56 Bad cross-document links:
09:33:56   html/en/elasticsearch/client/net-api/6.x/auto-date-histogram-aggregation-usage.html:
09:33:56    - en/elasticsearch/reference/6.4/search-aggregations-bucket-autodatehistogram-aggregation.html
09:33:56   html/en/elasticsearch/client/net-api/current/auto-date-histogram-aggregation-usage.html:
09:33:56    - en/elasticsearch/reference/6.4/search-aggregations-bucket-autodatehistogram-aggregation.html

[DOCS] Changed URL from 6.4 to 6.5

---

src/Nest/Document/Multiple/Bulk/BulkRequestJsonConverter.cs

I noticed this OOM exception and saw string concat in the call stack.
No need to do concat when we are putting the result into a JsonWriter anyway.
I can see that you have improved the serialization in other branches, but I guess that is not coming in the near future.
> Inner exception System.OutOfMemoryException handled at Elasticsearch.Net.Transport`1+<RequestAsync>d__15`1.MoveNext:
>    at System.String.Concat (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Nest.BulkRequestJsonConverter.WriteJson (Nest, Version=6.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d)

Avoid doing string concat when not needed

---

src/Nest/Analysis/TokenFilters/KeywordMarkerTokenFilter.cs
src/Tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs

Add keywords_pattern to Keyword Marker Token Filter. A regular expression pattern to match against words in the text.
Addresses: https://github.com/elastic/elasticsearch-net/issues/3551
Port to `master` on merge.
Will be released in `6.6.0`

Add keywords_pattern to Keyword Marker Token Filter.

---

src/CodeGeneration/DocGenerator/Program.cs

This pull request addresses an issue whereby the documentation can be generated for a release with the incorrect version number. The version number is now calculated from the `global.json` file, thereby limiting the chances of the incorrect version number being used on a release.
Regular expressions and basic character manipulation has been used to avoid the need for JSON parsing and Semver libraries.
Backport to `6.x` on merge.

Use the version number present in the global.json file when generating documentation

---

src/Nest/Analysis/TokenFilters/ElisionTokenFilter.cs
src/Tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs

Add articles_case to elision token filter

---

src/Elasticsearch.Net/Responses/Sniff/SniffResponse.cs
src/Elasticsearch.Net/Serialization/SimpleJson.cs
src/Nest/Aggregations/Metric/PercentileRanks/PercentileRanksAggregationJsonConverter.cs
src/Nest/Aggregations/Metric/Percentiles/PercentilesAggregationJsonConverter.cs
src/Nest/Aggregations/Pipeline/MovingAverage/MovingAverageAggregationJsonConverter.cs
src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs
src/Nest/CommonOptions/Scripting/ScriptJsonConverter.cs
src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsConverter.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/GetRepository/GetRepositoryResponse.cs
src/Nest/XPack/Watcher/Condition/ScriptConditionBase.cs
src/Nest/XPack/Watcher/Input/ChainInput.cs
src/Nest/XPack/Watcher/Transform/ScriptTransformBase.cs

Dictionary lookup involves get key hash, find bucket for hash and iterate bucket for key, so look the value up once, instead of checking if the key exists and then using the indexer to look up the value.
It also reduces the amount of duplicate hardcoded keys in the code.
Could not find any documentation for running the benchmark, so I haven't checked if it actually makes any difference. Haven't analyzed how often the code is executed.
Some places ContainsKey is used before Remove. That is not needed for Dictionary<>, as it will just return false for key not found, but I am uncertain of the specification for IDictionary<> void Remove, so I left it in place.

Avoid doing multiple dictionary lookups

---

src/Elasticsearch.Net/Serialization/SimpleJson.cs
src/Tests/Tests/ClientConcepts/LowLevel/SniffOnLowLevelClient.cs

#3483 introduced SIMPLE_JSON_TYPEDEF pragma to be defined which caused netstandard and netfx exceptions when deserializing sniff responses, but would light up in different places as well.
This affects the low level client starting from 6.4.1 and 5.6.5 on the 5.x releases. 
The high level client or using the high level client through client.LowLevel are not affected.

fix #3582 low level client sniffing

---

src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs

`ApiCallDetails` will be set and overridden by multiple requests.

fix #3585 VoidResponse should not be shared

---

src/Nest/CommonOptions/Fuzziness/Fuzziness.cs
src/Nest/CommonOptions/Fuzziness/FuzzinessJsonConverter.cs
src/Nest/CommonOptions/Fuzziness/IFuzziness.cs
src/Tests/Tests/QueryDsl/FullText/Match/MatchUsageTests.cs

As of now fuzziness AUTO parameter does not support custom length behaviour added in https://github.com/elastic/elasticsearch/issues/25528 and described on https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#fuzziness
This PR contains simple implementation for that to NEST. It could be easily ported to the new JSON serialization implementation: https://github.com/elastic/elasticsearch-net/pull/3583

Add fuzzy auto length support for NEST

---

src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs
src/Nest/XPack/MachineLearning/Job/Config/JobStats.cs

Return statistics about forecasts as part of the job stats and usage API.
ES Change: https://github.com/elastic/elasticsearch/pull/31647
Associated Meta ticket: https://github.com/elastic/elasticsearch-net/issues/3552

Return statistics about forecasts as part of the job stats and usage API

---

src/Nest/Aggregations/Bucket/Composite/CompositeBucket.cs
src/Tests/Tests/Framework/SerializationTests/CompositeKeySerializationTests.cs

Serialize null values in composite aggregation key

---

src/Nest/Aggregations/Bucket/Composite/CompositeAggregationSource.cs
src/Tests/Tests/Aggregations/Bucket/Composite/CompositeAggregationUsageTests.cs

Include missing in CompositeAggregationSource

---

src/Nest/Mapping/Types/Specialized/Attachment/Attachment.cs
src/Tests/Tests/Document/Single/Index/IndexIngestAttachmentApiTests.cs

This commit updates the Attachment Json converter to use the
ingest-geoip attachment field names when serializing an attachment.
The current serialization implementation is based on mapper-attachments plugin which
was deprecated in 5.x and removed in 6.x.
Fixes #3502

Reindex attachment honours ingest-attachment field names

---

docs/client-concepts/high-level/serialization/custom-serialization.asciidoc
src/CodeGeneration/DocGenerator/SyntaxNodeExtensions.cs
src/Serializers/Nest.JsonNetSerializer/ConnectionSettingsAwareSerializerBase.Serializer.cs
src/Tests/Tests/ClientConcepts/HighLevel/Serialization/CustomSerialization.doc.cs

This commit allows derived implementations of ConnectionSettingsAwareContractResolver
to be specified when creating a derived ConnectionSettingsAwareSerializerBase. This can
be useful when wishing to include Type information in the serialized JSON.
Add documentation to demonstrate how to use.
Closes #3494

Allow derived implementations of ConnectionSettingsAwareContractResolver

---

src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
src/Nest/Document/Multiple/BulkAll/BulkAllResponse.cs
src/Tests/Tests/Document/Multiple/BulkAll/BulkAndScrollApiTests.cs

This commit exposes the bulk response items on the BulkAllResponse.
Closes #3487

Expose BulkResponseItems on BulkAllResponse

---

src/CodeGeneration/ApiGenerator/ApiGenerator.cs
src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
src/Elasticsearch.Net/ElasticLowLevelClient.Generated.cs
src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
src/Nest/Cluster/TaskManagement/ListTasks/ListTasksResponse.cs
src/Nest/Document/Multiple/UpdateByQueryRethrottle/ElasticClient-UpdateByQueryRethrottle.cs
src/Nest/Document/Multiple/UpdateByQueryRethrottle/UpdateByQueryRethrottleRequest.cs
src/Nest/_Generated/_Descriptors.generated.cs
src/Nest/_Generated/_LowLevelDispatch.generated.cs
src/Nest/_Generated/_Requests.generated.cs
src/Tests/Tests/CodeStandards/NamingConventions.doc.cs
src/Tests/Tests/Document/Multiple/UpdateByQueryRethrottle/UpdateByQueryRethrottleApiTests.cs
src/Tests/Tests/Document/Multiple/UpdateByQueryRethrottle/UpdateByQueryRethrottleUrlTests.cs

Update by query rethrottle API

---

src/Nest/XPack/RollUp/RollupConfiguration/DateHistogramRollupGrouping.cs

Add support for date histogram `format` parameter.
https://github.com/elastic/elasticsearch/pull/34537

Add support for date histogram format.

---

src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs

Relates to: https://github.com/elastic/elasticsearch/pull/33863

Add node count to ML usage response

---

src/Nest/CommonAbstractions/Infer/ActionIds/ActionIds.cs
src/Tests/Tests/CommonOptions/ActionIdsTests.cs

- Ensure GetHashcode() returns same value for out of order lists.
- Prefer empty lists over nulls for internal _actionIds collection.

Fix ActionIds type

---

src/Nest/Document/Multiple/MultiGet/Response/MultiGetHitJsonConverter.cs
src/Tests/Tests.Reproduce/GithubIssue3554.cs

Use DateParseHandling.None when loading JObject for MultiGetHit<T>

---

src/Nest/CommonAbstractions/Infer/Field/FieldJsonConverter.cs
src/Nest/CommonAbstractions/Infer/Fields/FieldsJsonConverter.cs

This commit replaces the ReferenceLoopHandling property manipulation
in FieldsJsonConverter that is used to circumvent Json.NET's reference
loop detection when Fields contains only a single Field, with a direct
call to the serialization method on FieldJsonConverter for each Field.
Fixes #3617

Replace ReferenceLoopHandling with direct method call

---

docs/elasticsearch-net/building-requests.asciidoc

Fixes the delimiter on a code block that Asciidoctor is not a fan of.
This should let us convert all of these docs from the unmaintained
AsciiDoc project to the actively maintained Asciidoctor project.

Docs: Fix the delimiter on a code block

---

src/Elasticsearch.Net/Connection/HttpConnection.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
src/Tests/Tests/ClientConcepts/Connection/HttpConnectionTests.cs

- return `HttpMessageHandler` when creating a handler for a `HttpClient` in `HttpConnection`
Fixes #3415
- Use `MemoryStreamFactory`  to create a Memory Stream when the response is an Elasticsearch.Net response type.
- replace the use of `string.Join` and the capturing delegate to instead use
a `StringBuilder` and for loop. It also uses a simple heuristic to intialize the `StringBuilder` capacity.
- avoid allocating a `NameValueCollection` for `Headers` if there are no headers to send

Use HttpMessageHandler on HttpConnection

---

src/Nest/CommonOptions/Sorting/SortFormatter.cs
src/Nest/Document/Multiple/ScrollAll/ScrollAllObservable.cs
src/Nest/Search/Search/Sort/FieldSort.cs
src/Nest/Search/Search/Sort/GeoDistanceSort.cs
src/Nest/Search/Search/Sort/ScriptSort.cs
src/Nest/Search/Search/Sort/SortBase.cs
src/Nest/Search/Search/Sort/SortDescriptor.cs
src/Tests/Tests/Aggregations/Metric/TopHits/TopHitsAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/BucketSort/BucketSortAggregationUsageTests.cs
src/Tests/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerApiTests.cs
src/Tests/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerSliceApiTests.cs
src/Tests/Tests/Search/Request/SearchAfterUsageTests.cs
src/Tests/Tests/Search/Request/SortUsageTests.cs

This PR updates sort type names for consistency
- Rename SortGeoDistance to GeoDistanceSort
- Rename SortField to FieldSort
- Rename SortScript to ScriptSort
- Rename property GeoUnit to Unit on GeoDistanceSort
Also remove deprecated `NestedPath` and `NestedFilter`
Fixes #3454

Consistent Sort type names

---

src/Nest/Aggregations/AggregateDictionary.cs
src/Nest/Aggregations/AggregateFormatter.cs
src/Nest/Aggregations/Bucket/IpRange/IpRangeBucket.cs
src/Tests/Tests/Aggregations/Bucket/IpRange/IpRangeAggregationUsageTests.cs

This commit adds an IpRangeBucket for the IpRangeAggregation, allowing the To and From string fields to be deserialized and set on each bucket instance.
Fixes #3550

Add IpRangeBucket for IpRangeAggregation

---

src/Nest/Aggregations/Bucket/Composite/DateHistogramCompositeAggregationSource.cs
src/Nest/Ingest/Processors/DateProcessor.cs
src/Nest/QueryDsl/FullText/QueryString/QueryStringQuery.cs
src/Tests/Tests/Ingest/ProcessorAssertions.cs

This commit updates usage of Timezone to TimeZone, for consistency.
Fixes #3622

Consistent use of TimeZone

---

docs/client-concepts/low-level/getting-started.asciidoc

the old "Searching" syntax for ES 6.* is wrong, so I commit the right one

update "Searching" DSL

---

src/Elasticsearch.Net/Serialization/ElasticsearchNetFormatterResolver.cs
src/Elasticsearch.Net/Serialization/Formatters/ExceptionFormatter.cs
src/Elasticsearch.Net/Utf8Json/Resolvers/DynamicObjectResolver.cs
src/Tests/Tests/Framework/SerializationTests/ExceptionSerializationTests.cs

This commit introduces an ExceptionFormatters that serializes exceptions to the same structure as that used in 6.x
Fixes #3656

Low level client exception structure should match SimpleJson strategy

---

docs/index.asciidoc

When we use Asciidoctor to build the docs for the elasticsearch-net repo
it sees the `:` in the title of the book as a delimiter for a subtitle.
This is probably a nice feature, but we actually intend the title of the
book to have a `:` in it. The simple work around is to use a different
character for the delimiter. This change does that.

Docs: Drop subtitle in Asciidoctor

---

src/Elasticsearch.Net/Utf8Json/JsonReader.cs

This commit fixes the logic for determining whether a double quote character is escaped when reading inside of a JSON string. the current implementation checks that the previous character is `\`, and that the character before this is not `\`, but does not take into account whether that last character itself is part is escaped. The fix is to backtrack from the double quote and count the number of sequential backslash characters; an even number implies that the double quote is not escaped and therefore the end of the JSON string.

Fix utf8json escape characters

---

src/Nest/Aggregations/AggregateFormatter.cs
src/Tests/Tests.Reproduce/GithubIssue3673.cs
src/Tests/Tests/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs

Deserialize DateHistogram bucket with no sub aggregations

---

src/CodeGeneration/ApiGenerator/Views/_Requests.Generated.cshtml
src/Nest/_Generated/_Requests.generated.cs
src/Tests/Tests/CodeStandards/Requests.doc.cs

This commit updates the API generator to trim the leading forward slashes from all API paths. When the base URI with which the API path will be combined also contains a relative path, the relative path should be respected in the combined URI output.
Fixes #3691

Generate API paths without leading forward slash

---

src/Nest/Mapping/AttributeBased/ElasticsearchTypeAttribute.cs

This commit reintroduces the Name property on ElasticsearchTypeAttribute, which gets/sets the RelationName property. The reintroduction is marked as Obsolete as it will be removed in 8.x
Closes #3681

Support deprecate Name property on ElasticsearchTypeAttribute

---

src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
src/Nest/QueryDsl/FullText/Intervals/IntervalsAllOf.cs
src/Nest/QueryDsl/FullText/Intervals/IntervalsAnyOf.cs
src/Nest/QueryDsl/FullText/Intervals/IntervalsFilter.cs
src/Nest/QueryDsl/FullText/Intervals/IntervalsMatch.cs
src/Nest/QueryDsl/FullText/Intervals/IntervalsQuery.cs
src/Nest/QueryDsl/Query.cs
src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
src/Nest/QueryDsl/Visitor/QueryVisitor.cs
src/Nest/QueryDsl/Visitor/QueryWalker.cs
src/Tests/Tests.Configuration/tests.default.yaml
src/Tests/Tests/CodeStandards/Descriptors.doc.cs
src/Tests/Tests/QueryDsl/FullText/Intervals/IntervalsUsageTests.cs

Implement Intervals query

---

src/Nest/Cluster/ClusterHealth/ClusterHealthResponse.cs
src/Tests/Tests/Cluster/ClusterHealth/ClusterHealthApiTests.cs

Updated ClusterHealthResponse.cs to align with ClusterHealthResponse.java (https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/admin/cluster/health/ClusterHealthResponse.java). Previously missing fields included "ActiveShardsPerecentAsNumber", "DelayedUnassignedShards", "NumberOfInFlightFetch", and "TaskMaxWaitTimeInQueueInMillis".

Fix 3698: Update ClusterHealthResponse.cs to align with ClusterHealthResponse.java

---

src/Nest/Indices/AliasManagement/Alias.cs
src/Nest/Indices/AliasManagement/PutAlias/PutAliasRequest.cs
src/Tests/Tests/Indices/IndexManagement/CreateIndex/CreateIndexApiTests.cs

This commit adds the ability to add an alias with is_write_index when creating an index using the Create Index API.
Closes #3686

Add is_write_index to aliases on create index API

---

src/CodeGeneration/ApiGenerator/Overrides/GlobalOverrides.cs
src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
src/Nest/Document/Multiple/Bulk/BulkOperation/BulkDelete.cs
src/Nest/Document/Multiple/Bulk/BulkOperation/BulkIndex.cs
src/Nest/Document/Multiple/MultiGet/Response/MultiGetHit.cs
src/Nest/Document/Single/Get/GetResponse.cs
src/Nest/Search/Search/Hits/Hit.cs
src/Nest/_Generated/_Descriptors.generated.cs
src/Nest/_Generated/_Requests.generated.cs
src/Tests/Tests/Aggregations/Metric/TopHits/TopHitsAggregationUsageTests.cs
src/Tests/Tests/Document/Multiple/Bulk/BulkInvalidVersionApiTests.cs
src/Tests/Tests/Document/Multiple/MultiGet/MultiGetApiTests.cs
src/Tests/Tests/Document/Single/Get/GetApiTests.cs
src/Tests/Tests/Search/Request/InnerHitsUsageTests.cs
src/Tests/Tests/Search/Search/SearchApiTests.cs

This commit adds the SequenceNumber and PrimaryTerm properties to the Hit<T>, MultiGetHit<T> and GetResponse.
Closes #3708

Add SequenceNumber and PrimaryTerm to Hits, Get and MulitGetHit

---

src/Nest/Mapping/Types/Geo/GeoShape/GeoShapeAttribute.cs
src/Nest/Mapping/Types/Geo/GeoShape/GeoShapeProperty.cs
src/Tests/Tests/Mapping/Types/Geo/GeoShape/GeoShapeAttributeTests.cs
src/Tests/Tests/Mapping/Types/Geo/GeoShape/GeoShapePropertyTests.cs

Relates to https://github.com/elastic/elasticsearch/issues/35059

Allow geo_shape types to be coerced into valid shapes.

---

src/CodeGeneration/ApiGenerator/Overrides/GlobalOverrides.cs
src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
src/Nest/_Generated/_Descriptors.generated.cs
src/Nest/_Generated/_Requests.generated.cs

Remove _source_include and _source_exclude from generated

---

src/Nest/Aggregations/AggregateFormatter.cs
src/Nest/Aggregations/Metric/Percentiles/PercentilesMetricAggregate.cs
src/Tests/Tests.Reproduce/GithubIssue3715.cs

This commit correctly deserializes percentiles aggegations by closing
the object or array in which values are returned. In addition, percentile item values can be
nullable, so read as null or double and update PercentileItem to have nullable value.
Closes #3715

Correctly deserialize Percentiles aggregate

---

src/Nest/XPack/Security/User/PutUser/ElasticClient-PutUser.cs
src/Nest/XPack/Security/User/PutUser/PutUserRequest.cs

Relates to: https://github.com/elastic/elasticsearch/pull/35242

Add password_hash parameter to PutUser

---

src/Nest/XPack/CrossClusterReplication/Stats/CcrStatsResponse.cs

Relates to: https://github.com/elastic/elasticsearch/pull/36542

Add time since last auto follow fetch to auto follow stats

---

src/Nest/XPack/Security/Authenticate/AuthenticateResponse.cs
src/Tests/Tests/XPack/Security/Authenticate/AuthenticateApiTests.cs

Relates to: https://github.com/elastic/elasticsearch/pull/35648

Add realm information for Authenticate API

---

src/Tests/Tests.Core/ManagedElasticsearch/Clusters/IntrusiveOperationSeededCluster.cs
src/Tests/Tests/Cluster/ClusterReroute/ClusterRerouteApiTests.cs
src/Tests/Tests/XPack/CrossClusterReplication/CrossClusterReplicationFollowTests.cs

- WaitForActiveShards is a new feature in 6.7.0, which defaults to false, this is opposite behaviour of 6.6.0 (which implicitly waits for active shards)
- Unfollowing a closed index in 6.7.0 now throws an exception

Fix CCR Tests.

---

src/Nest/XPack/Ilm/LifecycleActions.cs
src/Nest/XPack/Ilm/MoveToStep/MoveToStepRequest.cs
src/Nest/XPack/Ilm/Phases.cs
src/Nest/XPack/Ilm/Policy.cs
src/Nest/XPack/Security/ApiKey/CreateApiKey/ApiKeyPrivileges.cs
src/Nest/XPack/Security/ApiKey/CreateApiKey/ApiKeyRole.cs
src/Nest/XPack/Security/ApiKey/CreateApiKey/CreateApiKeyRequest.cs
src/Nest/XPack/Security/ApiKey/GetApiKey/GetApiKeyResponse.cs

Some small fixes to ILM and ApiKey APIs that were discovered whilst forward porting to 7.x

Fix ILM and ApiKey APIs

---

src/Tests/Tests/high-level.asciidoc

Fixes a few links broken with https://github.com/elastic/elasticsearch-net/commit/69a60a6cb9b8c00a0ba3c2e2383f28038bf1c37b.

[DOCS] Fix broken cross-ref links

---

src/Tests/Tests/high-level.asciidoc

Fixes a few links broken with 69a60a6.

[DOCS] Fix broken cross-ref links (6.x backport of #3740)

---

src/Elasticsearch.Net/Extensions/CharUtils.cs
src/Elasticsearch.Net/Extensions/X509CertificateExtensions.cs
src/Elasticsearch.Net/Utf8Json/JsonWriter.cs
src/Tests/Tests.Reproduce/GithubIssue3743.cs

This commit corrects serialization of Unicode special characters.
All characters before U+0020 (' ' space character) must be encoded
in bytes as Unicode escape sequences
Fixes #3743

Correctly serialize Unicode special characters

---

src/Nest/Cluster/ClusterState/MetadataState.cs
src/Nest/Cluster/ClusterState/StoredScriptMapping.cs
src/Tests/Tests/Cluster/ClusterState/ClusterStateApiTests.cs

Fixes #3746.
Backport to `7.x` and `master` after approval and merge.

Include stored_scripts response in cluster metadata response.

---

src/Nest/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramAggregation.cs
src/Tests/Tests/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramAggregationUsageTests.cs

Fixes #3754.
Sets test values to 10 (which is the default).

Add buckets to AutoDateHistogramAggregation.

---

src/Nest/XPack/RollUp/GetRollupJob/RollupJobStats.cs

Additional stats added in: https://github.com/elastic/elasticsearch/pull/35471

Additional Rollup Stats

---

src/Nest/XPack/Info/XPackInfo/XPackInfoResponse.cs
src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs
src/Tests/Tests/XPack/Info/XPackInfoApiTests.cs
src/Tests/Tests/XPack/Info/XPackInfoUrlTests.cs

Add integration tests for XPack info and usage endpoints.
Additional properties on request objects.

 XPack info and usage improvements.

---

src/Nest/Search/Suggesters/SuggestBucket.cs
src/Tests/Tests.Reproduce/Discuss179634.cs

This commit adds JsonProperty attributes to SuggestBucket to ensure
that properties are correctly serialized when a DefaultFieldNameInferrer delegate is passed.
These are required because the concrete SuggestBucket is not passed and serialized as the
ISuggestBucket interface in the VerbatimDictionaryKeysJsonConverter WriteJson method.
Fixes issue found by https://discuss.elastic.co/t/nest-suggester-errors/179634/5

Attribute SuggestBucket for serialization

---

src/Nest/Cluster/ClusterStats/ClusterNodesStats.cs
src/Nest/Cluster/ClusterStats/ClusterStatsResponse.cs
src/Nest/Cluster/NodesInfo/NodeInfo.cs
src/Nest/CommonOptions/Stats/PluginStats.cs
src/Nest/CommonOptions/Stats/SegmentsStats.cs
src/Tests/Tests/Cluster/ClusterStats/ClusterStatsApiTests.cs

Do not port to `master` or `7.x` as responses need to be cleaned up in those branches as per: https://github.com/elastic/elasticsearch-net/issues/3765

Add pretty names (and other properties) to the cluster stats response.

---

src/Nest/Mapping/Types/Geo/GeoShape/GeoShapeProperty.cs

Addresses: https://github.com/elastic/elasticsearch/pull/35320

Set obsolete warning on GeoShape properties.

---

src/Nest/Document/Multiple/MultiGet/Response/MultiGetHit.cs
src/Nest/Document/Single/Get/GetResponse.cs
src/Tests/Tests/Document/Multiple/MultiGet/MultiGetApiTests.cs
src/Tests/Tests/Document/Single/DocumentCrudTests.cs
src/Tests/Tests/Document/Single/Get/GetApiTests.cs

Addresses: https://github.com/elastic/elasticsearch/pull/36680
Backport to `master` and `7.x` requires care due to naming conventions,

Add doc’s sequence number + primary term to get responses

---

src/Nest/XPack/Ilm/Actions/RolloverAction.cs
src/Tests/Tests/XPack/Ilm/BytesValueConverterTests.cs
src/Tests/Tests/XPack/Ilm/IlmApiTests.cs

Convert rollover lifecycle action to accept max size as a `string` instead of `long?`
Breaking change from `6.7` to `6.8`
Fixes #3768

Convert rollover lifecycle action to accept max size as a string and not long?

---

src/Nest/Mapping/Types/Geo/GeoShape/GeoOrientation.cs
src/Tests/Tests/Mapping/Types/Geo/GeoShape/GeoShapeClusterMetadataApiTests.cs

The documentation (https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html) states that there are multiple values possible; 1. Right-hand rule: `right`, `ccw`, `counterclockwise`, 2. Left-hand rule: `left`, `cw`, `clockwise`.
It looks like NEST only supported `cw` and `ccw`.
Cluster metadata exposed `cw` as `LEFT` in the responses.

Use a custom convertor for GeoOrientation to tolerate alternative options in Elasticsearch

---

src/Nest/Aggregations/AggregateFormatter.cs
src/Nest/Aggregations/Bucket/BucketAggregate.cs
src/Nest/Aggregations/Bucket/Composite/CompositeAggregation.cs
src/Nest/Aggregations/Bucket/Composite/CompositeBucket.cs

This commit sets AfterKey as a CompositeKey on BucketAggregate, such that null values are respected
when passing into subsequent composite aggregation calls.
Fixes #3694

Use CompositeKey on BucketAggregate

---

src/Nest/Aggregations/AggregateDictionary.cs
src/Nest/Aggregations/AggregateJsonConverter.cs
src/Nest/Aggregations/Bucket/BucketAggregate.cs

Discourage the use of AfterKey on BucketAggregate by marking it as obsolete. Passing it directly into After will not honour null values for keys returned - it must be passed as a CompositeKey.
Fixes #3694

Set CompositeKey on BucketAggregate

---

src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/NestFormatterResolver.cs
src/Nest/Mapping/Types/Geo/GeoShape/GeoOrientation.cs
src/Tests/Tests/Mapping/Types/Geo/GeoShape/GeoShapeClusterMetadataApiTests.cs

Opening to start a conversation on how to implement a `JsonFormatter` for an `enum`.
OOTB it looks like UTF8JSON doesnt support placing the attribute on enum values.
Any idea where to go with this? @russcam

Use a custom convertor for GeoOrientation to tolerate alternative options in Elasticsearch #3776

---

src/Nest/CommonOptions/DateMath/DateMath.cs
src/Tests/Tests.Reproduce/GitHubIssue3719.cs

This commit ensures that DateMath containing DateTime are always serialized with a minimum of 3 decimal places.
https://github.com/elastic/elasticsearch/pull/41871 introduced a bug in Elasticsearch 7.x < 7.1.0 whereby date strings
with less than 3 decimal places throw a parser exception.
Fixes #3719

Serialize DateMath with minimum 3 decimal places

---

src/CodeGeneration/DocGenerator/StringExtensions.cs
src/Nest/Mapping/Visitor/PropertyWalker.cs
src/Nest/QueryDsl/Geo/Shape/GeoShapeBase.cs
src/Nest/QueryDsl/Specialized/MoreLikeThis/Like/LikeDocument.cs
src/Tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
src/Tests/Tests.Domain/Project.cs
src/Tests/Tests/Aggregations/Bucket/GeoDistance/GeoDistanceAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Bucket/GeoHashGrid/GeoHashGridAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Metric/GeoBounds/GeoBoundsAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Metric/GeoCentroid/GeoCentroidAggregationUsageTests.cs
src/Tests/Tests/ClientConcepts/HighLevel/Inference/Equality/FieldsEqualityTests.cs
src/Tests/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
src/Tests/Tests/Mapping/Types/Geo/GeoPoint/GeoPointPropertyTests.cs
src/Tests/Tests/Mapping/Types/Geo/GeoShape/GeoShapePropertyTests.cs
src/Tests/Tests/QueryDsl/Compound/FunctionScore/FunctionScoreQueryUsageTests.cs
src/Tests/Tests/QueryDsl/Geo/BoundingBox/GeoBoundingBoxQueryUsageTests.cs
src/Tests/Tests/QueryDsl/Geo/Distance/GeoDistanceQueryUsageTests.cs
src/Tests/Tests/QueryDsl/Geo/Polygon/GeoPolygonQueryUsageTests.cs
src/Tests/Tests/QueryDsl/Geo/Shape/GeoShapeQueryUsageTests.cs
src/Tests/Tests/QueryDsl/QueryDslUsageTestsBase.cs
src/Tests/Tests/QueryDsl/Specialized/MoreLikeThis/MoreLikeThisFullDocumentQueryUsageTests.cs
src/Tests/Tests/Search/Request/SortUsageTests.cs

This PR removes the lenient assertion within QueryDslUsagesTestsBase that allowed parsing exceptions in Elasticsearch to pass. This was a temporary solution whilst upgrading the client to work with Elasticsearch 7.x that must be removed before releasing to GA.
The remaining commits fix the remaining query usage tests that exhibited parsing tests. These were 
1. geo shape query tests, which are now run against a new `geo_shape` field mapping on `Project`. Automapping will now also map an `IGeoShape` property on a POCO as a `GeoShapeProperty` automatically.
2. more like this queries where the `_id` field was also being set when a document is provided for the `like` input.

Fix Query DSL usage tests

---

src/Nest/Cluster/ClusterStats/ClusterNodesStats.cs
src/Nest/Cluster/ClusterStats/ClusterStatsResponse.cs
src/Nest/Cluster/NodesInfo/NodeInfo.cs
src/Nest/CommonOptions/Stats/CompletionStats.cs
src/Nest/CommonOptions/Stats/FieldDataStats.cs
src/Nest/CommonOptions/Stats/PluginStats.cs
src/Nest/CommonOptions/Stats/QueryCacheStats.cs
src/Nest/CommonOptions/Stats/SegmentsStats.cs
src/Tests/Tests/Cluster/ClusterStats/ClusterStatsApiTests.cs

Removes some of the redundant properties.

Add pretty names (and other properties) to the cluster stats response. #3766

---

src/Nest/QueryDsl/Specialized/MoreLikeThis/Like/LikeDocument.cs
src/Tests/Tests/QueryDsl/Specialized/MoreLikeThis/MoreLikeThisFullDocumentQueryUsageTests.cs

This commit updates the unit test for more like this query to ensure that routing
is set when an artificial document is specified.

Routing must be specified when doc used

---

src/Nest/CommonAbstractions/ConnectionSettings/ClrTypeDefaults.cs
src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs
src/Tests/Tests.Domain/Extensions/ConnectionSettingsExtensions.cs
src/Tests/Tests/ClientConcepts/Connection/ConfigurationOptions.doc.cs
src/Tests/Tests/ClientConcepts/HighLevel/Inference/TypesAndRelationsInference.doc.cs
src/Tests/Tests/ClientConcepts/HighLevel/Mapping/AutoMap.doc.cs
src/Tests/Tests/ClientConcepts/HighLevel/Mapping/ParentChildRelationships.doc.cs

This commit removes the defaultTypeNames mappings on ConnectionSettings as they
are no longer used.
The TypeName on IClrTypeMapping is also removed as it too is no longer used.

Remove default TypeNames and TypeName from IClrTypeMapping

---

src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
src/Elasticsearch.Net/Configuration/Security/BasicAuthenticationCredentials.cs
src/Elasticsearch.Net/Connection/HttpConnection.cs
src/Elasticsearch.Net/Connection/SecureStrings.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
src/Tests/Tests/Cat/CatIndices/CatIndicesApiTests.cs
src/Tests/Tests/ClientConcepts/Connection/HttpConnectionTests.cs
src/Tests/Tests/XPack/Security/ApiKey/SecurityApiKeyTests.cs
src/Tests/Tests/XPack/Security/Authenticate/AuthenticateApiTests.cs
src/Tests/Tests/XPack/Security/Privileges/ApplicationPrivilegesApiTests.cs

This commit changes the BasicAuthenticationCredentials and ProxyPassword types
to use SecureString for holding the passwords in memory, as opposed to as a plain text string.
A plain text string is retrieved from SecureString only at the point at which it is required.
This prevents plain text passwords from being automatically emitted in cases where properties
may be enumerated and captured e.g. logging frameworks.
Closes #2505

User SecureString for Basic and Proxy passwords

---

src/Elasticsearch.Net/Serialization/ElasticsearchSerializerExtensions.cs

This commit adds method overloads of SerializeToString and SerializeToBytes
that accept an IMemoryStreamFactory as a non-optional parameter, and reinstates
methods that do not take an IMemoryStreamFactory. This will make upgrading from
6.x to 7.x easier for those that make use of SerializeToString.
Closes #3771

Add overloads of SerializeToString and SerializeToBytes

---

src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
src/Elasticsearch.Net/Domain/NativeMethods.cs
src/Elasticsearch.Net/Domain/RuntimeInformation.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs
src/Nest/CrossPlatform/NativeMethods.cs
src/Nest/CrossPlatform/RuntimeInformation.cs

This commit adds a User-Agent to all API calls to Elasticsearch, that includes the client name and version, along with OS, Framework and assembly.
Where System.Runtime.InteropServices.RuntimeInformation is available, use the properties of this type. For .NET 4.6.1 which does not support this type, use native Windows functions to determine the version of Windows, and Environment.OSVersion.VersionString for other platforms. The latter is not used for Windows because it can report incorrect version information depending on runtime version and service packs installed, and the context in which calls are executed i.e. it is not reliable.

Add User-Agent string to API calls to Elasticsearch

---

src/Nest/QueryDsl/Geo/WKT/GeoWKTWriter.cs
src/Tests/Tests.Reproduce/GitHubIssue3819.cs
src/Tests/Tests.Reproduce/UseCultureAttribute.cs

Write WKT coordinates with invariant culture

---

docs/aggregations/metric/scripted-metric/scripted-metric-aggregation-usage.asciidoc
docs/client-concepts/connection/configuration-options.asciidoc
docs/query-dsl/compound/bool/bool-dsl-complex-query-usage.asciidoc
src/CodeGeneration/DocGenerator/StringExtensions.cs
src/CodeGeneration/DocGenerator/XmlDocs/XmlDocsVisitor.cs
src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs
src/Nest/CommonAbstractions/ConnectionSettings/IConnectionSettingsValues.cs
src/Nest/IndexModules/IndexSettings/Settings/AutoExpandReplicas.cs
src/Tests/Tests/ClientConcepts/Connection/ConfigurationOptions.doc.cs
src/Tests/Tests/QueryDsl/Compound/Bool/BoolDslComplexQueryUsageTests.cs

This PR fixes 7.x documentation in preparation for GA. Once this is merged, https://github.com/elastic/docs/pull/876 can be merged to bring 7.x documentation onto elastic.co site.

Fix 7.x documentation

---

src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
src/Elasticsearch.Net/Configuration/Security/BasicAuthenticationCredentials.cs
src/Elasticsearch.Net/Connection/SecureStrings.cs
src/Tests/Tests/ClientConcepts/Connection/SecureStringsTests.cs

Relates: https://github.com/elastic/elasticsearch-net/pull/3806#issuecomment-502700127
This commit updates the SecureStrings implementation to use the cross platform
Marshal methods that deal with unmanaged unicode strings.
Implement IDisposable on BasicAuthenticationCredentials and dispose of SecureString
instances when ConnectionConfiguration is disposed.

Use Marshal.SecureStringToGlobalAllocUnicode

---

src/Nest/Cat/CatThreadPool/CatThreadPoolRecord.cs
src/Tests/Tests/Cat/CatThreadPool/CatThreadpoolApiTests.cs

Relates: https://github.com/elastic/elasticsearch/pull/29195

Align Cat Threadpool properties

---

src/Nest/Search/MultiSearch/MultiSearchResponse.cs
src/Nest/Search/MultiSearch/MultiSearchResponseFormatter.cs
src/Tests/Tests/Search/MultiSearch/MultiSearchApiTests.cs

Implements: https://github.com/elastic/elasticsearch/pull/23767

Adding took time to _msearch

---

src/Nest/IndexModules/IndexSettings/Settings/IndexSettings.cs

Relates: https://github.com/elastic/elasticsearch/pull/30539

Update documentation for default number of shards

---

src/Nest/Analysis/TokenFilters/TokenFilterFormatter.cs

Relates: https://github.com/elastic/elasticsearch/pull/27705
This commit adds support for the deprecated delimited_payload_filter
name when deserializing token filters in a 6.x index within a 7.x cluster.
When serializing, the new name delimited_payload will be used.

Support deprecated delimited_payload_filter name in deserialization

---

src/Nest/Aggregations/AggregateFormatter.cs
src/Nest/Aggregations/Metric/ExtendedStats/ExtendedStatsAggregate.cs
src/Nest/Aggregations/Metric/Stats/StatsAggregate.cs
src/Tests/Tests/Aggregations/Metric/ExtendedStats/ExtendedStatsAggregationUsageTests.cs

Relates: https://github.com/elastic/elasticsearch/pull/27193
This commit updates Sum property on StatsAggregate to be modelled as non-nullable and to derive ExtendedStatsAggregate from StatsAggregate. Adds integration test to assert deserialization behaviour.

Sum on stats aggregation always returns a value

---

src/Nest/Aggregations/Aggregate.cs
src/Nest/Aggregations/AggregateDictionary.cs
src/Nest/Aggregations/AggregateFormatter.cs
src/Nest/Aggregations/Bucket/BucketAggregate.cs
src/Nest/Aggregations/Bucket/SignificantTerms/SignificantTermsAggregate.cs
src/Nest/Aggregations/Matrix/MatrixAggregate.cs
src/Nest/Aggregations/Matrix/MatrixStats/MatrixStatsAggregate.cs
src/Nest/Aggregations/Metric/TopHits/TopHitsAggregate.cs

This commit removes the Meta property setter on IAggregate, setting the meta dictionary on concrete IAggregate implementations inside AggregateFormatter

Remove IAggregate Meta property setter

---

src/Nest/Indices/IndexManagement/CreateIndex/CreateIndexResponse.cs
src/Tests/Tests/Indices/IndexManagement/CreateIndex/CreateIndexApiTests.cs

Fixes #3823
Port to `7.x` requires attention to new serialiser attributes.

Add index name to ICreateIndexResponse

---

src/Nest/Aggregations/Bucket/Terms/TermsExcludeFormatter.cs
src/Nest/Aggregations/Bucket/Terms/TermsIncludeFormatter.cs
src/Nest/Aggregations/Metric/PercentileRanks/PercentileRanksAggregationFormatter.cs
src/Nest/Aggregations/Metric/Percentiles/PercentilesAggregationFormatter.cs
src/Nest/Aggregations/Pipeline/MovingAverage/MovingAverageAggregationFormatter.cs
src/Nest/CommonAbstractions/Fields/FieldValuesFormatter.cs
src/Nest/CommonAbstractions/Infer/IndexName/IndexNameFormatter.cs
src/Nest/CommonAbstractions/Infer/Indices/IndicesFormatter.cs
src/Nest/CommonAbstractions/Infer/PropertyName/PropertyNameFormatter.cs
src/Nest/CommonAbstractions/Infer/RelationName/RelationNameFormatter.cs
src/Nest/CommonAbstractions/LazyDocument/LazyDocumentFormatter.cs
src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/DateTimeOffsetEpochMillisecondsFormatter.cs
src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/IndicesBoostFormatter.cs
src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/NullableDateTimeOffsetEpochSecondsFormatter.cs
src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/SortOrderFormatter.cs
src/Nest/CommonOptions/Fuzziness/FuzzinessFormatter.cs
src/Nest/CommonOptions/Geo/DistanceFormatter.cs
src/Nest/CommonOptions/Scripting/ScriptFormatter.cs
src/Nest/QueryDsl/MultiTermQueryRewrite/MultiTermQueryRewriteFormatter.cs
src/Nest/QueryDsl/TermLevel/Fuzzy/FuzzyQueryFormatter.cs
src/Nest/QueryDsl/TermLevel/Terms/TermsQueryFormatter.cs
src/Nest/Search/Suggesters/ContextSuggester/SuggestContextFormatter.cs

This commit advances the JSON reader when a JSON token is one that is unexpected e.g. when the JSON token is null.

Advance reader when not expected JSON token

---

src/Nest/Cat/CatThreadPool/CatThreadPoolRecord.cs
src/Nest/Cluster/NodesInfo/NodeInfo.cs
src/Tests/Tests/Cluster/NodesInfo/NodesInfoApiTests.cs

Relates: https://github.com/elastic/elasticsearch/pull/29123

Align thread pool info to thread pool configuration

---

src/Elasticsearch.Net/Providers/RecyclableMemoryStreamFactory.cs
src/Elasticsearch.Net/Providers/RecyclableMemoryStreamManager.cs
src/Nest/Aggregations/AggregateFormatter.cs
src/Nest/CommonAbstractions/LazyDocument/LazyDocument.cs

This normalizes `LazyDocument` a bit and makes it flow through the source serializer rather than sidestepping it through a formatter (a path source serializer will also take). 
Also added `async` overloads to `ILazyDocument`, since its currently backed a `byte[]` not immediately needed but good to have as part of the interface in`7.x` going forward.
This also updates `RecyclableStreamFactory` to simply return ` MemoryStream(bytes)` rather then going through the hoops in `RecyclableStream(bytes)` which ends up doing a copy which seems unnecessary.

Lazy document now uses source serializer and has async overloads

---

src/Elasticsearch.Net/Serialization/Formatters/ExceptionFormatter.cs
src/Elasticsearch.Net/Utf8Json/Formatters/DictionaryFormatter.cs
src/Nest/Aggregations/VerbatimDictionaryKeysFormatter.cs
src/Tests/Tests/Framework/SerializationTests/DictionarySerializationTests.cs

This PR adds additional dictionary serialization tests, aligning serialization behaviour in 7.x to that of 6.x

Dictionary serialization tests

---

build/scripts/Tooling.fs
build/scripts/scripts.fsproj
src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
src/Nest/Cluster/NodesHotThreads/NodesHotThreadsRequest.cs
src/Nest/CommonAbstractions/Request/RequestBase.cs
src/Nest/ElasticClient.cs
src/Tests/Tests.Benchmarking/Tests.Benchmarking.csproj
src/Tests/Tests.Core/Tests.Core.csproj
src/Tests/Tests.Domain/Tests.Domain.csproj
src/Tests/Tests/ClientConcepts/Troubleshooting/DiagnosticSource.doc.cs
src/Tests/Tests/Framework/EndpointTests/CoordinatedIntegrationTestBase.cs
src/Tests/Tests/Indices/IndexManagement/RolloverIndex/RolloverIndexApiTests.cs
src/Tests/Tests/XPack/Security/User/PutUser/PutUserApiTests.cs

Fixes cathelp and nodehotthreads now being unsuccesful in the low level client due to mimetype mismatch.
Also improves SSL generation which was failing on my windows partition due to warnings emitted about forbidden API usage.

Fix CatHelp NodeHotThreads integ tests due to mimetype mismatch 

---

src/Tests/Tests/Search/Search/SearchApiTests.cs

Relates: https://github.com/elastic/elasticsearch/pull/30831

Remove use_field_mapping from integration test

---

src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs

as mimetype includes encoding when using HttpWebRequest

ResponseBuilder mimeType check is too strict on net461 

---

src/Nest/Aggregations/AggregateDictionary.cs
src/Nest/Aggregations/AggregateFormatter.cs
src/Nest/Aggregations/Bucket/SignificantTerms/SignificantTermsAggregate.cs
src/Nest/Aggregations/Bucket/SignificantTerms/SignificantTermsBucket.cs
src/Tests/Tests.Domain/Project.cs
src/Tests/Tests/Aggregations/Bucket/SignificantTerms/SignificantTermsAggregationUsageTests.cs

Supersedes: #3795
Key of SignificantTermsBucket is generic to allow for returning both string and numeric key values.

make SignificantTermsBucket generic on key type

---

build/scripts/scripts.fsproj
src/Tests/Tests.Benchmarking/Tests.Benchmarking.csproj
src/Tests/Tests.Core/Tests.Core.csproj
src/Tests/Tests.Domain/Tests.Domain.csproj

Relates: https://github.com/elastic/elasticsearch-net-abstractions/commit/f75189735cb6d23dd685a2ad0003dea68bafc6dd
The ephemeral cluster generates a cached folder name based on the options including the chosen plugins which can be a very long list and cause max file path issues down the line.

Ephemeral Cluster for tests now uses a SHA has for its cached folder

---

src/Nest/QueryDsl/Compound/FunctionScore/Functions/ScoreFunctionJsonFormatter.cs
src/Tests/Tests/QueryDsl/Compound/FunctionScore/FunctionScoreQueryUsageTests.cs

This commit updates the ScoreFunctionJsonFormatter to serialize only the
script inside of the script_score JSON object.
Fixes #3904

Serialize only script in script_score function

---

docs/common-options/date-math/date-math-expressions.asciidoc
src/CodeGeneration/DocGenerator/StringExtensions.cs
src/CodeGeneration/DocGenerator/SyntaxNodeExtensions.cs
src/Elasticsearch.Net/Extensions/StringBuilderCache.cs
src/Nest/CommonOptions/DateMath/DateMath.cs
src/Tests/Tests/CommonOptions/DateMath/DateMathExpressions.doc.cs

This commit adds the time zone information for a DateTime within a DateMath type, when the DateTimeKind is Local or Utc. This behaviour aligns 7.x with 6.x.
Introduce StringBuilderCache for caching a StringBuilder per thread. Use of this can be extended in a later commit.
Fixes #3899

Include time zone information for Local and Utc DateTimeKind

---

src/Elasticsearch.Net/Connection/Content/RequestDataContent.cs
src/Elasticsearch.Net/Connection/HttpConnection.cs
src/Tests/Tests.Reproduce/GithubIssue3907.cs

This commit changes the HttpConnection to not set Content on HttpRequestMessage when there is no PostData. The check is performed inside of Request and RequestAsync to avoid creating any content instance and allocations.
Change length to default in TryComputeLength to match HttpContent implementation.
Pass RequestData through to _onStreamAvailable delegates so that HttpCompression, ConnectionSettings and PostData can be accessed on the passed instance.
Fixes #3907

Do not set HttpRequestMessage content when no PostData

---

src/Nest/QueryDsl/Geo/WKT/GeoWKTReader.cs
src/Tests/Tests/QueryDsl/Geo/Shape/GeoWKTTests.cs

This commit provides support for numbers with an exponent when reading WKT.
Fixes #3920

Support numbers with exponent in WKT

---

src/CodeGeneration/ApiGenerator/Configuration/Overrides/GlobalOverrides.cs
src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.NoNamespace.cs
src/Nest/Descriptors.NoNamespace.cs
src/Nest/Requests.NoNamespace.cs
src/Nest/Search/MultiSearch/MultiSearchFormatter.cs
src/Nest/Search/MultiSearch/MultiSearchRequest.cs
src/Nest/Search/Search/SearchRequest.cs
src/Tests/Tests/Search/MultiSearch/MultiSearchApiTests.cs

This commit removes track_total_hits as a query string parameter on a search request and instead defines it in the body, allowing track_total_hits to work with individual search requests in multi search API.
Closes #3906

Add track_total_hits to search request body

---

src/Nest/Indices/MappingManagement/GetFieldMapping/FieldMappingFormatter.cs
src/Nest/Indices/MappingManagement/PutMapping/PutMappingRequest.cs
src/Nest/Mapping/Mappings.cs
src/Nest/Mapping/MetaFields/All/AllField.cs
src/Nest/Mapping/MetaFields/Index/IndexField.cs
src/Nest/Mapping/TypeMapping.cs

This commit obsoletes the AllField and IndexField. Both should have been removed in 7.x but were missed.
Remove the DataMemberAttribute and add IgnoreDataMemberAttribute so that any value is not
sent in a request.
Fixes #3905

Obsolete AllField and IndexField

---

src/Nest/Cat/CatResponse.cs
src/Nest/Cat/CatResponseBuilder.cs
src/Tests/Tests/Cat/CatCount/CatCountApiTests.cs

This commit adds handling for 404 responses for cat APIs. When a 404 is returned, NEST's HttpStatusCodeClassifier deems it to be successful, which the CatResponseBuilder tries to then deserialize the response to a collection of TCatRecord. When a 404 is returned however, the response is a JSON object with an error and status. The CatResponse<TRecord> should be deserialized from this when a 404 is returned.
Fixes #3936

Handle cat API 404 responses

---

src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs
src/Tests/Tests.Reproduce/GitHubIssue3926.cs

This commit fixes a bug introduced with Diagnostics Source support. DiagnosticsSerializerProxy does not implement IPropertyMappingProvider, so if it wraps and delegates to a serializer that does implement IPropertyMappingProvider, such as JsonNetSerialzer, this is not honoured when assigning to _propertyMappingProvider. This commit uses the sourceSerializer when determining _propertyMappingProvider, and not the DiagnosticsSerializerProxy.
Fixes #3926

Honour IPropertyMappingProvider on custom IElastisearchSerializer

---

src/Nest/Modules/SnapshotAndRestore/Snapshot/SnapshotStatus/SnapshotStatusResponse.cs
src/Nest/XPack/Security/User/InvalidateUserAccessToken/InvalidateUserAccessTokenRequest.cs
src/Nest/XPack/Security/User/InvalidateUserAccessToken/InvalidateUserAccessTokenResponse.cs

Enhance Invalidate Token API
https://github.com/elastic/elasticsearch/issues/35388

Additions to Invalidate Token API

---

src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
src/Elasticsearch.Net/Configuration/Security/ApiKeyAuthenticationCredentials.cs
src/Elasticsearch.Net/Connection/HttpConnection.cs
src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
src/Tests/Tests.Core/Extensions/EphemeralClusterExtensions.cs
src/Tests/Tests/ClientConcepts/Troubleshooting/DebugInformation.doc.cs
src/Tests/Tests/XPack/Security/ApiKey/SecurityApiKeyUsageTests.cs

It is possible to set both the `Basic` auth and `ApiKey` auth together.
Clearly this doesn't make sense to do, and to me this feels like an exception.
Should we throw an exception in the client? (which would only surface at runtime), or do we apply some kind of precedence in which auth to apply if both are set?
I also left in the `string` override as I think this might be a little easier for someone to use, if they are unable to find our `.CreateSecureString()` extension method.

Implement Api Key authorisation on requests

---

build/Elasticsearch.Net.nuspec
src/Elasticsearch.Net/Elasticsearch.Net.csproj

Add System.Diagnostics.DiagnosticSource reference for NetStandard 2.0

---

docs/common-options/date-math/date-math-expressions.asciidoc
src/CodeGeneration/DocGenerator/StringExtensions.cs
src/CodeGeneration/DocGenerator/SyntaxNodeExtensions.cs
src/Elasticsearch.Net/Connection/Content/RequestDataContent.cs
src/Elasticsearch.Net/Connection/HttpConnection.cs
src/Elasticsearch.Net/Extensions/StringBuilderCache.cs
src/Nest/Aggregations/Metric/WeightedAverage/WeightedAverageValue.cs
src/Nest/CommonOptions/DateMath/DateMath.cs
src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
src/Nest/Mapping/Types/Core/DateNanos/DateNanosAttribute.cs
src/Nest/Mapping/Types/Core/DateNanos/DateNanosProperty.cs
src/Nest/Mapping/Types/FieldType.cs
src/Nest/Mapping/Types/Properties-Scalar.cs
src/Nest/Mapping/Types/Properties.cs
src/Nest/Mapping/Types/PropertyFormatter.cs
src/Nest/Mapping/Visitor/IMappingVisitor.cs
src/Nest/Mapping/Visitor/IPropertyVisitor.cs
src/Nest/Mapping/Visitor/MappingWalker.cs
src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
src/Nest/QueryDsl/Compound/FunctionScore/Functions/ScoreFunctionJsonFormatter.cs
src/Nest/QueryDsl/Geo/WKT/GeoWKTReader.cs
src/Nest/Search/FieldCapabilities/FieldCapabilitiesResponse.cs
src/Tests/Tests.Reproduce/GithubIssue3907.cs
src/Tests/Tests/CommonOptions/DateMath/DateMathExpressions.doc.cs
src/Tests/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
src/Tests/Tests/Mapping/Scalar/ScalarUsageTests.cs
src/Tests/Tests/Mapping/Types/Core/DateNanos/DateNanosAttributeTests.cs
src/Tests/Tests/Mapping/Types/Core/DateNanos/DateNanosPropertyTests.cs
src/Tests/Tests/QueryDsl/Compound/FunctionScore/FunctionScoreQueryUsageTests.cs
src/Tests/Tests/QueryDsl/Geo/Shape/GeoWKTTests.cs

Add nanosecond field mapper
https://github.com/elastic/elasticsearch/issues/37755

Date Nanos implementation

---

src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
src/Elasticsearch.Net/Connection/HttpConnection.cs
src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
src/Tests/Tests/ClientConcepts/Connection/HttpConnectionTests.cs
src/Tests/Tests/ClientConcepts/Connection/HttpWebRequestConnectionTests.cs

This PR reverts the behaviour of the client to not use chunked tranfer encoding by default, and exposes chunked transfer encoding as a configuration value on IConnectionConfigurationValues and RequestConfiguration.
With the introduction of the pull based streaming model in RequestDataContent, a ContentLength value cannot be computed for what will be written to the request stream; a ContentLength value is attempted to be determined, and TryComputeLength() executed, _before_ PostData is serialized to the request stream, making it not possible to provide a ContentLength value in the implementation, and falling into the HttpClient behaviour of using chunked transfer encoding.
A potential fix could have been applied in RequestDataContent, to serialize PostData ahead of time and store in a byte …

Fix default chunked transfer encoding and expose as configurable

---

src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
src/Nest/Mapping/Types/Properties-Scalar.cs
src/Tests/Tests/Mapping/Scalar/ScalarUsageTests.cs

Remove Scalar Nanos implementation.
Will look at removing `Scalar()` methods in `8.0`.

Remove Scalar Nanos implementation

---

src/Tests/Tests/QueryDsl/Specialized/MoreLikeThis/MoreLikeThisFullDocumentQueryUsageTests.cs

This commit fixes the MoreLikeThisFullDocumentQueryUsageTests. The free text needs fields to target.

Fix MoreLikeThisFullDocumentQueryUsageTests

---

src/Elasticsearch.Net/Connection/HttpConnection.cs

This commit fixes a bug whereby written bytes captured when disable direct streaming is enabled are captured before they are compressed, so should not be used for the content of the request when http compression is enabled.

Don't use written bytes when http compression is enabled

---

docs/client-concepts/high-level/inference/index-name-inference.asciidoc
src/Tests/Tests/ClientConcepts/HighLevel/Inference/IndexNameInference.doc.cs

This commit improves the readability of the index name inference documentation,
and updates paragraphs in line with client changes.
Closes #3914

Improve Index name inference docs

---

src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs

Check if mimeType is empty string, or null, as this is different in .NET Core vs FULL .NET.

Fix for #3971, change check for mimeType to include empty string

---

src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
src/Tests/Tests/ClientConcepts/ConnectionPooling/Pinging/PingTests.cs
src/Tests/Tests/Framework/VirtualClustering/VirtualClusterConnection.cs

This commit updates the RequestPipeline ping operation to use an empty string for the ping relative path. Using a relative
path that starts with "/" will overwrite any base path when combined with the node URI.
Fixes #3970

Connection pool ping honours relative path

---

src/Tests/Tests/ClientConcepts/Troubleshooting/AuditTrail.doc.cs

Audit trail test assumed timespan is never TimeSpan.Zero but of course can be.
Needs to be cherry-picked to `7.2` as well

AuditTrail integration assertion fix

---

src/Nest/Search/Search/Sort/NumericType.cs
src/Nest/Search/Search/Sort/SortBase.cs
src/Tests/Tests/Search/Request/SortUsageTests.cs

For numeric fields it is also possible to cast the values from one type to another using this option. This can be useful for cross-index search if the sort field is mapped differently on some indices.

Add numeric_type sorting option.

---

src/Nest/Cluster/ClusterStats/ClusterNodesStats.cs

This commit adds a packaging_types field to the cluster stats response that outlines the build flavors and types present in a cluster.

Add packaging to cluster stats response.

---

src/Nest/Ingest/Processors/DateIndexNameProcessor.cs

Just some minor annoyance, when editors think they should convert characters for better looks.
Saw these while investigating a date index name processor issue.

Fixed formatting typos (’ --> ')

---

src/Nest/Aggregations/Bucket/DateHistogram/DateHistogramAggregation.cs
src/Tests/Tests.Reproduce/GithubIssue3673.cs
src/Tests/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/AverageBucket/AverageBucketAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/BucketScript/BucketScriptAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/BucketSelector/BucketSelectorAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/BucketSort/BucketSortAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/CumulativeSum/CumulativeSumAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/Derivative/DerivativeAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/ExtendedStatsBucket/ExtendedStatsBucketAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/MaxBucket/MaxBucketAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/MinBucket/MinBucketAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageEwmaAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageHoltLinearAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageHoltWintersAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageLinearAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageSimpleAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/MovingFunction/MovingFunctionAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/PercentilesBucket/PercentilesBucketAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/SerialDifferencing/SerialDifferencingAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/StatsBucket/StatsBucketAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/SumBucket/SumBucketAggregationUsageTests.cs
src/Tests/Tests/CodeStandards/Descriptors.doc.cs

Implements https://github.com/elastic/elasticsearch/pull/33727

Force selection of calendar or fixed intervals in date histo aggregations

---

src/Nest/XPack/Sql/QuerySql/QuerySqlRequest.cs
src/Nest/XPack/Sql/QuerySql/QuerySqlResponse.cs

Implements https://github.com/elastic/elasticsearch/pull/39287

Introduce the columnar option for SQL REST requests.

---

src/Serializers/Nest.JsonNetSerializer/Converters/HandleNestTypesOnSourceJsonConverter.cs
src/Tests/Tests.Reproduce/GitHubIssue3981.cs

This commit adds GeoLocation to types handled by the internal serializer so that
a property on a document POCO of type GeoLocation is serialized by the internal serializer.
It's not possible with the current test configuration to test this scenario, because
IL rewriting happens after unit tests are run, so the Json.NET constructs used on Nest types
are recognised by the JsonNetSerializer. Have added test that _would_ test behaviour, should
tests be run after IL-merging in the future.
Fixes #3981

Serialize GeoLocation with internal serializer

---

src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
src/Elasticsearch.Net/Configuration/Security/ApiKeyAuthenticationCredentials.cs
src/Elasticsearch.Net/Configuration/Security/BasicAuthenticationCredentials.cs
src/Elasticsearch.Net/ConnectionPool/CloudConnectionPool.cs
src/Elasticsearch.Net/ConnectionPool/SingleNodeConnectionPool.cs
src/Elasticsearch.Net/ElasticLowLevelClient.cs
src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs
src/Nest/ElasticClient.cs
src/Tests/Tests.Configuration/tests.default.yaml
src/Tests/Tests/ClientConcepts/ConnectionPooling/BuildingBlocks/ConnectionPooling.doc.cs

This PR allows Elastic Cloud users to use their Cloud Id to configure the client much like they would Logstash / Beats see: https://www.elastic.co/guide/en/cloud/current/ec-cloud-id.html
This also allows us to set some specific `ConnectionSettings` defaults.

Add a CloudConnectionPool

---

src/Nest/CommonAbstractions/Extensions/Extensions.cs
src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
src/Nest/Document/Multiple/BulkAll/BulkAllRequest.cs
src/Tests/Tests/Document/Multiple/BulkAll/BulkAllExceptionApiTests.cs
src/Tests/Tests/Framework/VirtualClustering/VirtualizedCluster.cs

This PR fixes a bug and improves the run time behaviour of `BulkAll()`
* If the `_bulk` operation itself keeps returning an invalid status code the `BulkAll()` could potentially hang, As reported on #3954 This is rare since `_bulk` tends to return 200 even if all items fail but a problem nonetheless.
* `ForEachAsync()` should bail out after receiving a faulted task. This was preventing exceptions thrown from halting the `BulkAll()` in a controlled fashion.
* Added a callback for every `BulkResponse` received. `OnNext()` is for being notified when a batch succeeded but that might constitute multiple `Bulk()` calls.

BulkAll() improvements

---

src/Nest/Document/Multiple/BulkAll/BulkAllRequest.cs
src/Nest/Document/Multiple/BulkAll/ElasticClient-BulkAll.cs

This commit adds additional XML docs to indicate that Index on `BulkAllRequest<T>` will be inferred from `T`. When a default index has not been mapped for
`T` on `ConnectionSettings`, using `DefaultMappingFor<T>(m => m.IndexName("some_index"))`, an exception will be thrown.
Closes #3951

Add XML docs for index inference on BulkAll

---

src/Nest/Cluster/NodesResponseBase.cs
src/Tests/Tests/Cluster/NodesUsage/NodesUsageUnitTests.cs

Map node failures.

---

src/CodeGeneration/DocGenerator/LitUp.cs

This commit updates the doc generation process to delete existing documentation,
except for the breaking changes directories, when generating new  documentation.
This is to prevent stale doc pages from carrying over.
Closes #3976

Delete existing docs when generating new docs

---

src/Nest/QueryDsl/Geo/GeoLocationFormatter.cs

The ReindexApiTests were failing on a serialisation roundtrip when dealing with properties that used the GeoLocation type. This manifested due to the inclusion of GeoLocation types in the _source serialisation on commit https://github.com/elastic/elasticsearch-net/commit/5492599e7d5964bbc0c9f7975f81ad5db276ea4e
The `GeoLocationFormatter` was found to be returning a `GeoCoordinate` type and not a `GeoLocation` type.

Ensure GeoLocationFormatter returns GeoLocation type

---

src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
src/Elasticsearch.Net/Transport/Transport.cs
src/Nest/CommonAbstractions/Reactive/CoordinatedRequestObserverBase.cs
src/Tests/Tests/Document/Multiple/BulkAll/BulkAllCancellationTokenApiTests.cs
src/Tests/Tests/Document/Multiple/BulkAll/BulkAllDisposeApiTests.cs

Coordinated request observables when aborted could bubble out an `UnexpectedElasticsearchClientException` or an `OperationCancelledException`.
This normalizes what gets passed to `OnError` namely (`OperationCancelledException`)
This is a bug was never released and something that the early termination in `ForEach` that #4014 fixed highlighted.

Normalize exception from cancelling an observable coordinated operation

---

appveyor.yml
azure-pipelines.yml
build/scripts/Commandline.fs
build/scripts/Targets.fs

To generate documentation include the "gendocs" argument in the build command line, e.g.
`build.bat gendocs`
Fixes #3674

Invert document generation so it is not run by default.

---

src/Elasticsearch.Net/Utf8Json/Formatters/EnumFormatter.cs

This is the propsed fix from the original repo of the code: https://github.com/neuecc/Utf8Json/pull/129
Resolves #4029 
I've tested this locally in a .NET Framework project and it works, compared to previously where it'd throw with an exception as mentioned in #4029.
I'm not sure if this should target 7.x or the master branch.

fix #4029: Use enum item.Name instead of Enum.GetName to get enum value

---

src/Elasticsearch.Net/Utf8Json/IJsonProperty.cs
src/Elasticsearch.Net/Utf8Json/Internal/Emit/MetaMember.cs
src/Elasticsearch.Net/Utf8Json/Internal/Emit/MetaType.cs
src/Elasticsearch.Net/Utf8Json/Resolvers/DynamicObjectResolver.cs
src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/NestFormatterResolver.cs
src/Tests/Tests/CodeStandards/Serialization/Enums.cs

This commit supports attributing a an enum property on a type with StringEnumAttribute to serialize it as a string.
Closes #4035

Support StringEnumAttribute on properties

---

src/Elasticsearch.Net/Utf8Json/Internal/ByteArrayStringHashTable.cs

I think the exception message sounds better without the extra "was" in there 😊

fix: Remove redundant word from exception message.

---

src/Tests/Tests.Reproduce/DateSerialization.cs

The PR *only* changes the unit tests.
Do not merge this PR unless the change in serialization is acceptable. I would not be able to say if this is a breaking change or not. This PR is primarily intended to show the change in date formatting that was introduced with the switch of serializers.
See issue #4037

Issue #4037: Added unit test showing differences between serializers

---

src/Tests/Tests/XPack/MachineLearning/GetFilters/GetFiltersApiTests.cs
src/Tests/Tests/XPack/MachineLearning/MachineLearningIntegrationTestBase.cs
src/Tests/Tests/XPack/MachineLearning/PutFilter/PutFilterApiTests.cs
src/Tests/Tests/XPack/MachineLearning/UpdateFilter/UpdateFilterApiTests.cs

This commit updates ML filter integration tests to ensure that filters created as part of a test are deleted.

Ensure filters created are deleted

---

src/Nest/Cluster/NodesInfo/NodeRole.cs

This commit adds a MachineLearning role to the NodeRole enum. "ml" is now returned as
a node role value in node APIs in 8.0
Fixes #4040

Add ml to NodeRole enum

---

src/Elasticsearch.Net/Utf8Json/Internal/DoubleConversion/StringToDoubleConverter.cs
src/Tests/Tests.Reproduce/GithubIssue4057.cs

Fallback parsing for `double` numbers affected by rounding precision issues used culture dependent `double.Parse` method.
Closes #4057

Fix for #4057 - fallback parsing for `double` thread culture dependent.

---

src/Nest/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramAggregation.cs
src/Nest/Aggregations/Bucket/AutoDateHistogram/MinimumInterval.cs
src/Tests/Tests/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramAggregationUsageTests.cs

Relates: #4001
This commit adds the minimum_interval property to auto date histogram aggregation. A new enum needs to be introduced for this as DateInterval contains values that are invalid for the minimum_interval.

Add minimum_interval to AutoDateHistogram aggregation

---

src/Nest/Aggregations/AggregateDictionary.cs
src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/Bucket/RareTerms/RareTermsAggregation.cs
src/Nest/Aggregations/Bucket/RareTerms/RareTermsBucket.cs
src/Nest/Aggregations/Visitor/AggregationVisitor.cs
src/Nest/Aggregations/Visitor/AggregationWalker.cs
src/Tests/Tests/Aggregations/Bucket/RareTerms/RareTermsAggregationUsageTests.cs

Relates: #4001
This commit implements the Rare terms aggregations. Rare term buckets only expose key and doc_count, so a new RareTermsBucket<TKey> type is used.

Implement Rare Terms aggregation

---

src/Nest/Mapping/Types/Complex/Flattened/FlattenedAttribute.cs
src/Nest/Mapping/Types/Complex/Flattened/FlattenedProperty.cs
src/Nest/Mapping/Types/FieldType.cs
src/Nest/Mapping/Types/Properties.cs
src/Nest/Mapping/Types/PropertyFormatter.cs
src/Nest/Mapping/Visitor/IMappingVisitor.cs
src/Nest/Mapping/Visitor/IPropertyVisitor.cs
src/Nest/Mapping/Visitor/MappingWalker.cs
src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
src/Tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
src/Tests/Tests.Domain/Extensions/DateTimeExtensions.cs
src/Tests/Tests.Domain/Project.cs
src/Tests/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
src/Tests/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
src/Tests/Tests/Mapping/Types/Complex/Flattened/FlattenedAttributeTests.cs
src/Tests/Tests/Mapping/Types/Complex/Flattened/FlattenedPropertyTests.cs

Relates #4001
This commit adds support for the flattened data type introduced in 7.3.0 and basic.

Add support for flattened datatype

---

src/CodeGeneration/DocGenerator/StringExtensions.cs
src/Nest/QueryDsl/FullText/Intervals/IntervalsPrefix.cs
src/Nest/QueryDsl/FullText/Intervals/IntervalsQuery.cs
src/Nest/QueryDsl/FullText/Intervals/IntervalsWildcard.cs
src/Tests/Tests/QueryDsl/FullText/Intervals/IntervalsUsageTests.cs

Relates: #4001
This commit adds wildcard and prefix rules support to the Intervals query.
Neither wildcard or prefix rules support filters, so a new IIntervalsNoFilter interface
is introduced for these rules. Added TODO to consolidate rules in 8.0

Add wildcard and prefix interval rules

---

src/Nest/Cluster/ClusterStats/ClusterNodesStats.cs
src/Nest/Cluster/NodesInfo/NodeRole.cs
src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs
src/Tests/Tests/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Bucket/RareTerms/RareTermsAggregationUsageTests.cs
src/Tests/Tests/XPack/Info/XPackInfoApiTests.cs

Relates: #4001
This commit adds voting_only to ClusterNodeStats and XPackUsageResponse.
VotingOnly is supported only in the default distribution

Add voting_only to ClusterNodeStats and XPackInfo

---

src/Nest/XPack/MachineLearning/Job/Config/JobStats.cs
src/Tests/Tests/XPack/MachineLearning/GetJobStats/GetJobStatsApiTests.cs

Relates: #4001
This commit adds timing stats to Machine Learning job stats

Add timing stats to machine learning job stats

---

src/Nest/Document/Multiple/DeleteByQuery/DeleteByQueryRequest.cs
src/Nest/Document/Multiple/ReindexOnServer/ReindexOnServerRequest.cs
src/Nest/Document/Multiple/ReindexOnServer/ReindexSource.cs
src/Nest/Document/Multiple/UpdateByQuery/UpdateByQueryRequest.cs

- Add `MaximumDocuments` to ReindexOnServer API and deprecate `Size`
- Add `MaximumDocuments` and support for SlicedScroll to UpdateByQuery and DeleteByQuery

Add max_docs to ReindexOnServer API

---

src/Nest/Indices/IndexManagement/OpenCloseIndex/CloseIndex/CloseIndexResponse.cs
src/Tests/Tests/Indices/IndexManagement/OpenCloseIndex/CloseIndex/CloseIndexApiTests.cs

Relates: #4001
Relates: elastic/elasticsearch#39687
This commit adds shards_acknowledged and indices resuls to CloseIndexResponse.

Add shards_acknowledged and indices results to CloseIndexResponse

---

src/Elasticsearch.Net/Utf8Json/JsonReader.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/AzureRepository.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/CreateRepository/CreateRepositoryRequest.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/FileSystemRepository.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/GetRepository/GetRepositoryResponseFormatter.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/HdfsRepository.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/ISnapshotRepository.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/ReadOnlyUrlRepository.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/S3Repository.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/SourceOnlyRepository.cs
src/Tests/Tests/Modules/SnapshotAndRestore/Repositories/CreateRepository/CreateRepositoryApiTests.cs
src/Tests/Tests/Modules/SnapshotAndRestore/Repositories/GetRepository/GetRepositoryApiTests.cs

This commit adds support for SourceOnly repository.
Introduce a ResetOffset() method on JsonReader to reset the offset back to the initial offset
Tidy up XML docs on repositories

Add support for SourceOnly snapshot repository

---

src/CodeGeneration/ApiGenerator/Configuration/Overrides/Endpoints/SearchOverrides.cs
src/CodeGeneration/ApiGenerator/Configuration/Overrides/Endpoints/UpdateOverrides.cs
src/CodeGeneration/ApiGenerator/Configuration/Overrides/GlobalOverrides.cs
src/CodeGeneration/ApiGenerator/Domain/Specification/QueryParameters.cs

Remove "_source_include" and "_source_exclude" from overrides.
Relates to:  Remove deprecated _source_exclude and _source_include from get API spec http://github.com/elastic/elasticsearch/pull/42188
And #4001

Remove "_source_include" and "_source_exclude" from overrides.

---

src/Nest/XPack/Watcher/Action/ActionBase.cs
src/Nest/XPack/Watcher/Action/ActionsDescriptorBase.cs
src/Tests/Tests/XPack/Watcher/PutWatch/PutWatchApiTests.cs

Relates: #4001
This commit introduces Foreach on Watcher actions, to allow execution of the Watcher
action on each element in an array specified by the path assigned to foreach.
Add condition to Watcher actions and ensure condition and transform are serialized.
Add integration test for Action foreach, transform and condition.

Allow execution of each Watcher action in array

---

src/CodeGeneration/ApiGenerator/Configuration/Overrides/Endpoints/DeleteByQueryOverrides.cs
src/CodeGeneration/ApiGenerator/Configuration/Overrides/Endpoints/ReindexOnServerOverrides.cs
src/CodeGeneration/ApiGenerator/Configuration/Overrides/Endpoints/UpdateByQueryOverrides.cs
src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.NoNamespace.cs
src/Nest/Descriptors.NoNamespace.cs
src/Nest/Requests.NoNamespace.cs
src/Tests/Tests/Document/Multiple/DeleteByQuery/DeleteByQueryApiTests.cs

This commit skips max_docs as query string params on DeleteByQuery,UpdateByQuery and ReindexOnServer.
The parameter can also be defined in the request body, so prefer this.

Skip max_docs query string params

---

src/Elasticsearch.Net/Exceptions/ElasticsearchClientException.cs
src/Elasticsearch.Net/Responses/ResponseStatics.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs

This commit changes how DebugInformation is built in ElasticsearchClientException to use either Request
or ApiCallDetails to retrieve the Uri and method of the request. There are some usages of ElasticsearchClientException
where the Request property is not set, such as Throw() method in BulkAllObservable.
Fixes #3687

Build DebugInformation uri and method from Request or ApiCallDetails

---

src/Nest/Analysis/TokenFilters/PatternReplaceTokenFilter.cs
src/Tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs

f845aab05b7f528810b46189cfd70292aaf3f52d  adds Flags property to PatternReplaceCharFilter. This commit adds Flags to PatternReplaceTokenFilter

Add PatternReplaceTokenFilter Flags property

---

src/Nest/Search/Suggesters/ContextSuggester/GeoSuggestContext.cs

This should only be one value, and not an array.
This is based on documentation from v6+ and v7+.
#4089

Precision on GeoSuggestContext Is A Single Value

---

src/Nest/Aggregations/AggregateJsonConverter.cs
src/Tests/Tests.Reproduce/GitHubIssue4103.cs

Supersedes: #4103 
Adds a unit test to assert that the change to `AggregateJsonConverter` for ExtendedStats aggregation
can deserialize the provided response.

Fix Extended stats deserialization

---

src/Nest/CommonAbstractions/SerializationBehavior/PropertyMapping.cs
src/Tests/Tests/ClientConcepts/HighLevel/Mapping/IgnoringProperties.doc.cs

Honour PropertyNameAttribute Ignore property in mappings

---

src/Nest/Ingest/Processor.cs

This fix the `Processor` `IgnoreFailure` property name mapping. A typo prevented the use of that property in the current NEST version.
```
processor [xxx] doesn't support one or more provided configuration parameters [ignore_failue]
```

Fix Processor IgnoreFailure property name mapping

---

src/Elasticsearch.Net/ConnectionPool/StaticConnectionPool.cs
src/Tests/Tests/ClientConcepts/ConnectionPooling/BuildingBlocks/ConnectionPooling.doc.cs

This commit fixes the initial randomization of nodes in a StaticConnectionPool. Instead of calling the protected ctor,
the initialization logic has been pulled out into a separate method that is now called from the ctor that accepts a
randomize parameter.
Fixes #4055

Fix initial randomization of nodes

---

src/Elasticsearch.Net/ConnectionPool/SniffingConnectionPool.cs
src/Elasticsearch.Net/ConnectionPool/StaticConnectionPool.cs
src/Tests/Tests/ClientConcepts/ConnectionPooling/BuildingBlocks/ConnectionPooling.doc.cs

This commit fixes the initial randomization of nodes in a StaticConnectionPool. The protected ctor also now takes a `randomize` parameter

Fix initial randomization of nodes (#4112)

---

src/Tests/Tests/Aggregations/Bucket/Histogram/HistogramAggregationUsageTests.cs

This commit updates the histogram aggregation usage test to only return buckets with a min_doc_count of 1.
Closes #4104

Fix flaky histogram aggregation

---

src/Nest/Aggregations/AggregateJsonConverter.cs
src/Tests/Tests.Reproduce/GitHubIssue4103.cs

Relates: #4109
This commit fixes an issue with extended stats aggregation parsing whereby the closing brace of std_deviation_bounds_as_string
is not read when skipping over the object, leading to the reader exiting at this point, resulting in any subsequent aggregations
from not being read from the JSON response and added to SearchResponse.Aggregations.

Read closing brace of extended stats aggregation

---

src/Nest/Mapping/DynamicMapping.cs
src/Nest/Mapping/TypeMapping.cs
src/Nest/Mapping/Types/Complex/Object/ObjectProperty.cs
src/Tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs

This commit introduces a custom formatter for Union<bool,DynamicMapping>. A boolean value may be returned as a "true" or "false" string, which should be handled correctly.
Closes #4124

Deserialize boolean strings to dynamic mapping

---

build/scripts/scripts.fsproj
src/CodeGeneration/ApiGenerator/Configuration/CodeConfiguration.cs
src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Indices.cs
src/Elasticsearch.Net/ElasticLowLevelClient.Indices.cs
src/Nest/Descriptors.Indices.cs
src/Nest/ElasticClient.Indices.cs
src/Nest/Indices/IndexManagement/CloneIndex/CloneIndexRequest.cs
src/Nest/Indices/IndexManagement/CloneIndex/CloneIndexResponse.cs
src/Nest/Requests.Indices.cs
src/Nest/_Generated/ApiUrlsLookup.generated.cs
src/Tests/Tests.Benchmarking/Tests.Benchmarking.csproj
src/Tests/Tests.Core/Tests.Core.csproj
src/Tests/Tests.Domain/Tests.Domain.csproj
src/Tests/Tests/Indices/IndexManagement/CloneIndex/CloneIndexApiTests.cs
src/Tests/Tests/Indices/IndexManagement/CloneIndex/CloneIndexUrlTests.cs

This commit adds support for the clone index API, introduced in Elasticsearch 7.4.0

Add support for clone index API

---

src/Nest/CommonOptions/Sorting/SortFormatter.cs

This commit writes null when ISort or ISort.SortKey is null. Simply returning without writing a value can result in incorrectly formatted JSON.
Closes #4128

Write null when ISort or SortKey is null

---

src/Elasticsearch.Net/ConnectionPool/StaticConnectionPool.cs
src/Tests/Tests/ClientConcepts/ConnectionPooling/BuildingBlocks/ConnectionPooling.doc.cs

The test was using a local method that yielded a single pool while later
.Take(50) was requested on this sequence. This always yields an
enumeration with 1 element which increases the chances for the assertion
to turn false.
Rather than relying on Thread.Sleep to create different seeded randoms
the StaticConnectionPool now defines a protected constructor that allows
one to pass in a seed value.
Continuation of #4112

Fix test for random initialized node

---

src/Nest/Modules/SnapshotAndRestore/Repositories/S3Repository.cs

Add support for elastic/elasticsearch#41966

S3 repo settings: path style access

---

src/Nest/Aggregations/Pipeline/MovingFunction/MovingFunctionAggregation.cs
src/Tests/Tests/Aggregations/Pipeline/MovingFunction/MovingFunctionAggregationUsageTests.cs

Addresses elastic/elasticsearch#44360

Add shift option to moving_avg aggregation

---

src/Nest/XPack/Ilm/ExplainLifecycle/ExplainLifecycleResponse.cs
src/Tests/Tests/XPack/Ilm/IlmApiTests.cs

addresses elastic/elasticsearch#44457

Expose index age in ILM explain output

---

src/Nest/XPack/Slm/SnapshotLifecyclePolicyMetadata.cs
src/Tests/Tests/XPack/Slm/SlmApiTests.cs

addresses elastic/elasticsearch#45245
Note this only maps `start_time_millis` directly as `DateTimeOffset` in quite some places we map both `XContent.timeField` representations. Would be nice to clean this up in 8.0. Thoughts?

Include in-progress snapshot for a policy with get SLM policy API

---

src/Nest/Modules/SnapshotAndRestore/Repositories/S3Repository.cs

Relates to: https://github.com/elastic/elasticsearch/pull/44052

Implement disable_chucked_encoding s3 repository setting.

---

src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs
src/Tests/Tests/XPack/Info/XPackInfoApiTests.cs

Relates to: https://github.com/elastic/elasticsearch/pull/44512

Implement vector usage

---

docs/query-dsl/geo/geo-shape/geo-shape-query-usage.asciidoc
docs/query-dsl/specialized/shape/shape-query-usage.asciidoc
src/Nest/CommonOptions/Shape/ShapeRelation.cs
src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
src/Nest/QueryDsl/Query.cs
src/Nest/QueryDsl/Specialized/Shape/IShapeQuery.cs
src/Nest/QueryDsl/Specialized/Shape/ShapeQueryFormatter.cs
src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
src/Nest/QueryDsl/Visitor/QueryVisitor.cs
src/Nest/QueryDsl/Visitor/QueryWalker.cs
src/Tests/Tests/QueryDsl/Geo/GeoShape/GeoShapeQueryUsageTests.cs
src/Tests/Tests/QueryDsl/Geo/GeoShape/GeoShapeSerializationTests.cs
src/Tests/Tests/QueryDsl/Geo/GeoShape/GeoWKTTests.cs
src/Tests/Tests/QueryDsl/Specialized/Shape/ShapeQueryUsageTests.cs
src/Tests/Tests/QueryDsl/Specialized/Shape/ShapeSerializationTests.cs

Depends on PR: https://github.com/elastic/elasticsearch-net/pull/4154
Implements: https://github.com/elastic/elasticsearch/pull/45108

Implement shape queries.

---

src/Nest/XPack/MachineLearning/UpdateDataFeed/UpdateDatafeedRequest.cs
src/Tests/Tests/XPack/MachineLearning/UpdateDatafeed/UpdateDatafeedApiTests.cs

adresses elastic/elasticsearch#44691

Deprecate the ability to update datafeed's job_id

---

src/Nest/Ingest/ProcessorFormatter.cs
src/Nest/Ingest/Processors/CircleProcessor.cs
src/Nest/Ingest/Processors/DissectProcessor.cs
src/Nest/Ingest/ProcessorsDescriptor.cs
src/Tests/Tests/Ingest/ProcessorAssertions.cs

Relates to: https://github.com/elastic/elasticsearch/pull/43851

Add Circle processor

---

src/Elasticsearch.Net/ConnectionPool/SniffingConnectionPool.cs
src/Elasticsearch.Net/ConnectionPool/StaticConnectionPool.cs
src/Tests/Tests/ClientConcepts/ConnectionPooling/BuildingBlocks/ConnectionPooling.doc.cs

The test was using a local method that yielded a single pool while later .Take(50)
was requested on this sequence. This always yields an enumeration with 1 element
which increases the chances for the assertion to turn false.
Rather than relying on Thread.Sleep to create different seeded randoms the StaticConnectionPool
now defines a protected constructor that allows one to pass in a seed value.
(cherry picked from commit 9734f04a161e6cbbe8b632b2993e61cb7f553a6a)

Fix test for random initialized node (#4134)

---

src/Nest/XPack/Slm/SnapshotLifecyclePolicyMetadata.cs

Relates to: https://github.com/elastic/elasticsearch/pull/45245
https://github.com/elastic/elasticsearch/blob/7.4/client/rest-high-level/src/main/java/org/elasticsearch/client/slm/SnapshotLifecyclePolicyMetadata.java

Implement snapshot records for last_success and last_failure on SnapshotLifecyclePolicyMetadata.

---

src/Tests/Tests/Aggregations/Pipeline/BucketScript/BucketScriptAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/Derivative/DerivativeAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageEwmaAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageHoltLinearAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageHoltWintersAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/MovingAverage/MovingAverageSimpleAggregationUsageTests.cs
src/Tests/Tests/Aggregations/Pipeline/SerialDifferencing/SerialDifferencingAggregationUsageTests.cs

This commit fixes integration tests for aggregations that use a date_histogram aggregation,
where a bucker may have no documents with a specific seed value. For example,
```
build.bat seed:41075 integrate 7.4.0 "readonly"
```

Fix aggs integration tests where buckets can be empty

---

src/Auxiliary/Elasticsearch.Net.VirtualizedCluster/Audit/Auditor.cs
src/CodeGeneration/ApiGenerator/Domain/Code/HighLevel/Requests/Constructor.cs
src/CodeGeneration/ApiGenerator/Generator/CodeGenerator.cs
src/CodeGeneration/ApiGenerator/Views/HighLevel/Descriptors/XmlDocs.cshtml
src/CodeGeneration/ApiGenerator/Views/LowLevel/Enums.Generated.cshtml
src/CodeGeneration/DocGenerator/AsciiDoc/GeneratedAsciidocVisitor.cs
src/CodeGeneration/DocGenerator/AsciiDoc/RawAsciidocVisitor.cs
src/CodeGeneration/DocGenerator/XmlDocs/XmlDocsVisitor.cs
src/Elasticsearch.Net/Responses/ResponseStatics.cs
src/Tests/Tests.Core/Extensions/DiffExtensions.cs
src/Tests/Tests.Core/ManagedElasticsearch/Tasks/WriteAnalysisFiles.cs
src/Tests/Tests/Framework/Extensions/UriExtensions.cs

This is in preperation of adding `dotnet-format` to our build.
Currently the doc and code gen end up generating mixed line ending files.

remove hardcoded \r\n from code generator strings

---

src/Nest/Aggregations/AggregateDictionary.cs

Given a document
```json
{
"color": "1"
}
```
and an enum definition
```c#
enum Color {
Red = 1
}
```
an invalid cast exception would be throw when attempting
```c#
aggs.Terms<Color>(agg.Name).Buckets
```

Added support for enums as keys for KeyedBucket.

---

src/Nest/XPack/Slm/SnapshotLifecyclePolicyMetadata.cs
src/Tests/Tests/XPack/Slm/SlmApiTests.cs

This commit updates the SLM API responses to convert date properties that are returned long values representing milliseconds since epoch
to DateTimeOffset. This is consistent with other API responses where longs are returned. What is slightly different with
this API is that Human=true can be specified on the request to also return the properties as string values. With this change, the client
now effectively ignores these values as they serve little purpose, since both would end up being converted to DateTimeOffset when deserialized.

Convert SLM API dates returned as long to DateTimeOffset

---

src/Nest/CommonOptions/Sorting/SortFormatter.cs

Fixes issue where unintended value separator is added. Example:
"sort":[{"_geo_distance":{,"some.coordinate":[{"lat":1.0,"lon":1.0}]
The "," is incorrectly added causing deserialization issues on the server.

Fix GeoDistance serialization

---

src/Tests/Tests.Domain/Extensions/ConnectionSettingsExtensions.cs
src/Tests/Tests.Domain/GeoShape.cs
src/Tests/Tests/QueryDsl/Geo/GeoShape/GeoShapeSerializationTests.cs
src/Tests/Tests/QueryDsl/Specialized/Shape/ShapeSerializationTests.cs

- Remove circle from Shape tests
- Change integration test setup to use Shape() instead of GeoShape()
- Change default index for Shape types to be `shapes`

Fix shape serialisation tests

---

src/Elasticsearch.Net/Responses/Dynamic/DynamicValue.cs
src/Tests/Tests/ClientConcepts/LowLevel/LowLevelResponseTypes.doc.cs
src/Tests/Tests/Search/MultiSearch/MultiSearchLowLevelPostDataTests.cs

Cherry-pick improvements made as part of the backport of #4123 yaml test runner to 7.x: #4179

Forward port of backport improvements #4123

---

src/Elasticsearch.Net/Utf8Json/Resolvers/CompositeResolver.cs
src/Elasticsearch.Net/Utf8Json/Resolvers/DynamicObjectResolver.cs

We generate namespaced versions of the clients, UTF8 should generate types in that namespace

Utf8Json dynamic type namespaces

---

src/Nest/Document/Multiple/ReindexOnServer/ReindexDestination.cs
src/Tests/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerPipelineApiTests.cs

(cherry picked from commit 593d871c028d3edeb27336ac1197bea17cd09128)
backport to 7.x

Added pipeline to ReindexDestination (#4183) (#4187)

---

src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs

less strict mime type checking, can contain charset information (old httpconnection)

Fix DynamicResponse not parsing when mimetype contains charset 

---

nuget.config
src/Elasticsearch.Net/Providers/MemoryStreamFactory.cs
src/Tests/Tests.Benchmarking/BenchmarkProgram.cs
src/Tests/Tests.Benchmarking/BulkBenchmarkTests.cs
src/Tests/Tests.Benchmarking/Tests.Benchmarking.csproj
src/Tests/Tests.Core/Client/Settings/AlwaysInMemoryConnectionSettings.cs
src/Tests/Tests.Core/Client/Settings/TestConnectionSettings.cs
src/Tests/Tests.Core/Client/TestClient.cs
src/Tests/Tests.Core/Extensions/TestConfigurationExtensions.cs
src/Tests/Tests.Domain/Project.cs
src/Tests/Tests.ScratchPad/Program.cs
src/Tests/Tests.ScratchPad/Tests.ScratchPad.csproj
src/Tests/Tests/ClientConcepts/Connection/HttpConnectionTests.cs

Allows the benchmarking project to reference Nest.v7 and so makes it easier for us to benchmark proposed changes.

Adds versioned benchmarking

---

src/CodeGeneration/ApiGenerator/RestSpecDownloader.cs

RestSpecDownloader uses windows path separator

---

src/Auxiliary/Elasticsearch.Net.VirtualizedCluster/MockResponses/SniffResponseBytes.cs
src/Auxiliary/Elasticsearch.Net.VirtualizedCluster/Rules/RuleBase.cs
src/Auxiliary/Elasticsearch.Net.VirtualizedCluster/VirtualClusterConnection.cs
src/Elasticsearch.Net/Utf8Json/Internal/Emit/ILViewer.cs

Found a few places, that still new'ed MemoryStream directly (outside of client mainly)

Use MemoryStreamFactory everywhere
