src/Nest/IElasticClient.cs

Cat Api's were missing from IElasticClient.

cat api's interface fix #1212

---

src/Nest/DSL/Filter/HasChildFilterDescriptor.cs
src/Tests/Nest.Tests.Unit/QueryParsers/Filter/HasChildFilterTests.cs
src/Tests/Nest.Tests.Unit/Search/Filter/ConditionLess/ConditionLessTests.cs
src/Tests/Nest.Tests.Unit/Search/Filter/Singles/HasChildFilterJson.cs

Hey, folks!
I want to use HasChild filter in my project and to filter childs instead of querying them, but miss this functionality in NEST, so I've added a few lines of code.
Do not judge strictly, I'm a newcomer in elasticsearch community:)

Added filter support for HasChild filter.

---

src/Nest/Domain/Analysis/TokenFilter/StopTokenFilter.cs
src/Tests/Nest.Tests.Unit/Core/Indices/Analysis/TokenFilters/TestStopTokenFilterWithArray.json
src/Tests/Nest.Tests.Unit/Core/Indices/Analysis/TokenFilters/TestStopTokenFilterWithPredefinedLanguageList.json
src/Tests/Nest.Tests.Unit/Core/Indices/Analysis/TokenFilters/TokenFilterTests.cs
src/Tests/Nest.Tests.Unit/Nest.Tests.Unit.csproj

Add support for predefined language specific stopwords

---

src/Nest/Domain/Mapping/Descriptors/BooleanMappingDescriptor.cs
src/Nest/Domain/Mapping/Descriptors/DateMappingDescriptor.cs
src/Nest/Domain/Mapping/Descriptors/NumberMappingDescriptor.cs
src/Nest/Domain/Mapping/SpecialFields/TypeFieldMapping.cs
src/Nest/Enums/NumericIndexOption.cs
src/Nest/Resolvers/Writers/WritePropertiesFromAttributeVisitor.cs
src/Tests/Nest.Tests.Unit/Core/Map/FluentMappingFullExampleTests.cs
src/Tests/Nest.Tests.Unit/Core/Map/GetMappingSerializationTests.cs
src/Tests/Nest.Tests.Unit/Core/Map/Properties/BooleanProperty.json
src/Tests/Nest.Tests.Unit/Core/Map/Properties/DateProperty.json
src/Tests/Nest.Tests.Unit/Core/Map/Properties/NumberProperty.json
src/Tests/Nest.Tests.Unit/Core/Map/TypeField/TypeFieldSerializesYes.json

removed analyzed and not analyzed from the nonstringindexoption enum 

---

src/Nest/ConvenienceExtensions/ExistsExtensions.cs
src/Tests/Nest.Tests.Integration/Indices/IndicesTemplateTests.cs

Convenience extensions for template exists

---

src/Nest/DSL/Filter/IndicesFilterDescriptor.cs
src/Tests/Nest.Tests.Unit/Reproduce/Reproduce1187Tests.cs

index property was missing for Indices filter. It is now added.
Refactored the test case

Included index property for Indices Filter

---

src/Nest/Domain/Cat/CatIndicesRecord.cs

Add status and total memory to cat indices response

---

src/CodeGeneration/CodeGeneration.LowLevelClient/ApiEndpoints/root.html
src/Nest/DSL/CatSegmentsDescriptor.cs
src/Nest/DSL/_Descriptors.generated.cs
src/Nest/DSL/_Requests.generated.cs
src/Nest/Domain/Cat/CatSegmentsRecord.cs
src/Nest/ElasticClient-Cat.cs
src/Nest/IElasticClient.cs
src/Nest/Nest.csproj
src/Tests/Nest.Tests.Integration/Core/Cat/CatTests.cs

Add support for cat segments

---

src/Nest/DSL/Query/SimpleQueryStringQueryDescriptor.cs
src/Tests/Nest.Tests.Unit/QueryParsers/Queries/SimpleQueryStringQueryTests.cs

PR for https://github.com/elastic/elasticsearch-net/issues/1356

Support for minimum_should_match option on query_string_query #1356

---

src/Nest/Domain/Cat/CatHealthRecord.cs
src/Nest/Domain/Responses/HealthResponse.cs

Add pending tasks to cluster health and cat health

---

src/Nest/DSL/Query/FunctionScoreQueryDescriptor.cs

New feature as per request #1418.
Please review @gmarz.
__Just adding the Filter choice for Function Score Query__

Added Filter to FunctionScoreQuery

---

src/Nest/DSL/Facets/FacetContainer.cs
src/Nest/DSL/Filter/HasChildFilterDescriptor.cs
src/Nest/DSL/MultiPercolate/IPercolateOperation.cs
src/Nest/DSL/PutAliasDescriptor.cs
src/Nest/DSL/Query/FilterScoreQueryDescriptor.cs
src/Nest/DSL/Query/Functions/IFunctionScoreFunction.cs
src/Nest/DSL/Suggest/PhraseSuggestCollateDescriptor.cs
src/Nest/Domain/Alias/AliasAddOperation.cs
src/Nest/Domain/Alias/AliasDefinition.cs
src/Nest/Domain/Alias/CreateAliasDescriptor.cs
src/Nest/Domain/Analysis/Analyzers/CustomAnalyzer.cs
src/Tests/Nest.Tests.Unit/Nest.Tests.Unit.csproj
src/Tests/Nest.Tests.Unit/ObjectInitializer/Aliases/AliasFilterBody.json
src/Tests/Nest.Tests.Unit/ObjectInitializer/Aliases/AliasFilterRequestTests.cs

__This pull request fixes an existing bug #1409__
Please review :ghost: 
Happy to make any change from comments

Added JsonCoverter for IFilterContainer

---

src/Nest/Resolvers/Writers/TypeMappingWriter.cs
src/Tests/Nest.Tests.Integration/Mapping/MapFromAttributeTests.cs

fix #1381  mapfromattributes now maps Guid to strings automatically

---

src/Nest/DSL/Filter/HasChildFilterDescriptor.cs

.. correspondingly as it was implemented in HasChildQueryDescriptor.cs. This fixes #1505

Added Min/MaxChildren to HasChildFilterDescriptor

---

src/Nest/Nest.csproj

Couldn't build solution after checkout from 2.0 branch, hope it helps :+1:

2.0 solution build fix

---

src/CodeGeneration/CodeGeneration.LowLevelClient/ApiEndpoints/update.json
src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
src/Nest/DSL/UpdateDescriptor.cs
src/Nest/DSL/_Descriptors.generated.cs
src/Nest/DSL/_Requests.generated.cs
src/Tests/Nest.Tests.Integration/Core/UpdateTests.cs
src/Tests/Nest.Tests.Unit/Core/Update/UpdateDetectNoop.json
src/Tests/Nest.Tests.Unit/Core/Update/UpdateTests.cs
src/Tests/Nest.Tests.Unit/Nest.Tests.Unit.csproj

Hi Guys,
This is fix for https://github.com/elastic/elasticsearch-net/issues/1587.
Also I've created PR to address this in api spec https://github.com/elastic/elasticsearch/pull/14004.

Support detect_noop in NEST #1587

---

src/Tests/QueryDsl/Exact/Term/TermQueryUsageTests.cs
src/Tests/Tests.csproj

Usage test for [TermQuery](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-term-query.html)

Usage test for TermQuery

---

src/Nest/CommonAbstractions/SerializationBehavior/NestSerializer.cs

Fixes #1631 by not creating a new Newtosoft serializer for each Serialize/Deserialize method call.
I didn't see any need except formatting.
I think also about removing `SerializationFormatting` parameter from Serialize method and add it as a property to `IElastisearchSerializer` interface or even completely remove it. Who changes indenting per request?
This option should be saved at constructor time. 
What do you think?

- fixes #1631 NestSerializer performance problems

---

src/Nest/QueryDsl/Compound/Bool/BoolQuery.cs
src/Tests/QueryDsl/Specialized/BoolQueryUsageTests.cs
src/Tests/Tests.csproj

See https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-bool-query.html

Added filters to bool query

---

src/Nest/DSL/ScrollDescriptor.cs
src/Nest/ElasticClient-Scroll.cs

Replaces #1685 which was on a branch that DNE anymore.

Introduced ability to set up scroll's type selector

---

src/Nest/QueryDsl/Abstractions/Query/BoolQueryExtensions.cs

Right container wasn't checked properly.

Fixed potentially incorrect combining

---

src/Tests/Nest.Tests.Integration/Core/UpdateTests.cs

For #1666 Looks like my VS might have fiddled with the indentation.

Move DetectNoop() to DocAsUpsert Test #1666

---

paket.lock
src/CodeGeneration/CodeGeneration.LowLevelClient/Domain/ApiQueryParameters.cs
src/CodeGeneration/CodeGeneration.LowLevelClient/Views/_Descriptors.Generated.cshtml
src/CodeGeneration/CodeGeneration.LowLevelClient/Views/_Requests.Generated.cshtml
src/Nest/CommonAbstractions/Request/RequestBase.cs
src/Nest/CommonOptions/TimeUnit/Time.cs
src/Nest/CommonOptions/TimeUnit/TimeJsonConverter.cs
src/Nest/Document/Multiple/Reindex/ReindexObservable.cs
src/Nest/_Generated/_Descriptors.generated.cs
src/Nest/_Generated/_Requests.generated.cs
src/Performance/Profiling/Profiling.csproj
src/Tests/CommonOptions/TimeUnit/TimeUnits.doc.cs
src/Tests/Search/Search/SearchUrlTests.cs
src/Tests/Tests.csproj
src/Tests/tests.yaml

High level methods now take Time instead of TimeSpan

---

src/Nest/Aggregations/Bucket/DateRange/DateRangeExpression.cs
src/Nest/Mapping/TypeMapping.cs
src/Nest/Search/MultiSearch/MultiSearchJsonConverter.cs

Hi,
Here is my changes of library, that my code is working.
DateRangeExpression fix typo
TypeMapping missing SourceField
MultiSearchRequest operation index, type should override request index, type if exists

Fixes for 2.0

---

src/Elasticsearch.Net/Connection/RequestHandlers/RequestHandlerBase.cs

This is to handle serializing `JObject` using the Json.NET contract for it and not treating it as an `IEnumerable<object>`
See https://github.com/elastic/elasticsearch-net/issues/1609
/cc @gmarz @Mpdreamz

Align serialization with NEST 2.0 implementation

---

build/scripts/Paths.fsx

Use Path.Combine to escape spaces in UserProfile

---

docs/2.0-breaking-changes/nest-breaking-changes.md

Hello guys,
Looks like folks are confused how to change default serialization settings in NEST 2.x.
I've added little help, hope you are gonna like it :)

Update breaking changes note with info about custom serialization settings.

---

src/Nest/CommonOptions/Sorting/SortJsonConverter.cs
src/Nest/Search/Search/Sort/SortGeoDistance.cs
src/Tests/Search/Request/SortUsageTests.cs

See https://github.com/elastic/elasticsearch-net/issues/1836

Include unit and distance_type when set

---

src/Nest/Document/Multiple/MultiTermVectors/MultiTermVectorsResponse.cs
src/Nest/Document/Single/TermVectors/TermVectorsResponse.cs
src/Tests/Document/Multiple/MultiTermVectors/MultiTermVectorsApiTests.cs
src/Tests/tests.yaml

Fixes https://github.com/elastic/elasticsearch-net/issues/1866

Include Index, Type, Id and Took on TermVectorsResponse

---

src/Elasticsearch.Net/Responses/ServerError.cs
src/Elasticsearch.Net/Serialization/ElasticsearchNetJsonStrategy.cs
src/Tests/ClientConcepts/ServerError/ServerErrorTests.cs
src/Tests/tests.yaml

Fixes https://github.com/elastic/elasticsearch-net/issues/1845

Deserialize caused_by as part of ServerError

---

src/Nest/CommonAbstractions/Infer/Types/Types.cs
src/Nest/Mapping/DynamicTemplate/DynamicTemplatesJsonConverter.cs
src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
src/Nest/Mapping/Types/Specialized/Generic/GenericProperty.cs
src/Nest/Nest.csproj
src/Tests/Indices/IndexSettings/IndexTemplates/PutIndexTemplate/PutIndexTemplateApiTests.cs

Closes https://github.com/elastic/elasticsearch-net/issues/2066

Generic mapping for dynamic templates

---

src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs

Make .NET core HttpConnection implementation more extensible

---

docs/aggregations-usage.asciidoc
docs/aggregations.asciidoc
docs/aggregations/metric/geo-centroid/geo-centroid-aggregation-usage.asciidoc
src/CodeGeneration/CodeGeneration.LowLevelClient/CodeGeneration.LowLevelClient.project.lock.json
src/CodeGeneration/Nest.Litterateur/Nest.Litterateur.project.lock.json
src/Elasticsearch.Net/Elasticsearch.Net.project.lock.json
src/Nest/Aggregations/AggregateJsonConverter.cs
src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/AggregationsHelper.cs
src/Nest/Aggregations/Metric/GeoCentroid/GeoCentroidAggregate.cs
src/Nest/Aggregations/Metric/GeoCentroid/GeoCentroidAggregation.cs
src/Nest/Aggregations/Metric/PercentileRanks/PercentileRanksAggregationJsonConverter.cs
src/Nest/Aggregations/Visitor/AggregationVisitor.cs
src/Nest/Aggregations/Visitor/AggregationWalker.cs
src/Nest/Nest.csproj
src/Tests/Aggregations/Metric/GeoCentroid/GeoCentroidAggregationUsageTests.cs
src/Tests/Tests.csproj

[Aggregations are missing `geo_centroid` aggregation](http://stackoverflow.com/questions/37672582/elasticsearch-geo-centroid-aggregation-with-c-sharp-nest)
This PR addresses this and provides usage examples, including as a sub aggregation.
Foward port to 5.x PR in #2120

Add geo_centroid aggregation

---

src/Nest/QueryDsl/FullText/QueryString/QueryStringQuery.cs
src/Tests/QueryDsl/FullText/QueryString/QueryStringUsageTests.cs

See https://github.com/elastic/elasticsearch-net/pull/2114

Fix Fuzziness on QueryStringQuery

---

src/Nest/Document/Multiple/ReindexOnServer/ReindexSource.cs
src/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerApiTests.cs

Fix #2145 Missing Batch Size property in ReindexSource while performing Reindexing by ReindexOnServer

Fix #2145 Missing Batch Size property in ReindexSource while performing Reindexing by ReindexOnServer

---

src/Elasticsearch.Net/Responses/ServerError.cs
src/Nest/CommonOptions/Failures/BulkError.cs
src/Nest/CommonOptions/Failures/ShardFailure.cs
src/Tests/QueryDsl/Joining/HasChild/HasChildQueryUsageTests.cs
src/Tests/Reproduce/GithubIssue2152.cs
src/Tests/Tests.csproj

Closes #2152
Requires forward porting to `master`

Deserialize recursive error details

---

src/Nest/Document/Multiple/UpdateByQuery/UpdateByQueryResponse.cs
src/Tests/Reproduce/GithubIssue2173.cs
src/Tests/Tests.csproj
src/Tests/tests.yaml

Fix IsValid logic error in UpdateByQuery response

---

src/Nest/CommonAbstractions/LowLevelDispatch/LowLevelDispatch.cs
src/Nest/ElasticClient.cs
src/Nest/Indices/MappingManagement/GetMapping/ElasticClient-GetMapping.cs
src/Nest/Indices/MappingManagement/GetMapping/GetMappingResponse.cs
src/Nest/Mapping/Visitor/MappingWalker.cs
src/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs

Closes https://github.com/elastic/elasticsearch-net/issues/2072

Map type names along with mappings

---

src/Nest/Indices/AliasManagement/GetAlias/ElasticClient-GetAlias.cs
src/Nest/Indices/AliasManagement/GetAlias/GetAliasRequest.cs
src/Nest/Indices/AliasManagement/GetAliases/ElasticClient-GetIndicesPointingToAlias.cs
src/Nest/Indices/AliasManagement/GetAliases/GetAliasesRequest.cs
src/Nest/_Generated/_Descriptors.generated.cs
src/Tests/Indices/AliasManagement/GetAliasesPointingToIndex/GetAliasesPointingToIndexTests.cs
src/Tests/Indices/AliasManagement/GetIndicesPointingToAlias/GetIndicesPointingToAliasTests.cs
src/Tests/Tests.csproj
src/Tests/tests.yaml

Closes https://github.com/elastic/elasticsearch-net/issues/2194

Deprecate Alias on GetAlias and GetAliases

---

src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs

typo in exception message on MaxTimeoutReached

---

src/CodeGeneration/ApiGenerator/ApiGenerator.csproj
src/CodeGeneration/ApiGenerator/Overrides/Descriptors/AnalyzeDescriptorOverrides.cs
src/CodeGeneration/ApiGenerator/Views/RequestParameters.Generated.cshtml
src/Elasticsearch.Net/Domain/RequestParameters/AnalyzeRequestParameters.cs
src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
src/Elasticsearch.Net/Elasticsearch.Net.csproj
src/Nest/Indices/Analyze/AnalyzeRequest.cs
src/Nest/Indices/Analyze/ElasticClient-Analyze.cs
src/Nest/_Generated/_Descriptors.generated.cs
src/Nest/_Generated/_RequestParametersExtensions.Generated.cs
src/Nest/_Generated/_Requests.generated.cs
src/Tests/Indices/Analyze/AnalyzeApiTests.cs

Move Analyze parameters to json body

---

src/Nest/Document/Multiple/MultiGet/Response/MultiGetHit.cs
src/Nest/Document/Multiple/MultiGet/Response/MultiGetResponse.cs
src/Nest/Document/Single/Get/GetResponse.cs
src/Tests/Document/Multiple/MultiGet/MultiGetApiTests.cs
src/Tests/Document/Multiple/Reindex/ReindexApiTests.cs
src/Tests/Document/Single/Get/GetApiTests.cs
src/Tests/Document/Single/Index/IndexApiTests.cs
src/Tests/Framework/Integration/Bootstrappers/Seeder.cs
src/Tests/Framework/MockData/CommitActivity.cs

Add missing metadata to IGetResponse<T> and IMultiHit<T>

---

src/Nest/Document/Single/TermVectors/TermVectorFilter.cs
src/Nest/Document/Single/TermVectors/TermVectorsRequest.cs
src/Tests/Document/Single/TermVectors/TermVectorsApiTests.cs

Add missing Term Vector Filters

---

src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs

In using ES, I found that the following scenario could throw an error, and it seems to be down to the way the semaphores are handled. This is the scenario:
1) Thread A blocks the semaphore, sniffs, and releases it.
2) Thread B waits for the semaphore, A releases, B blocks, and then, not needing to sniff, simply returns.
3) Thread C waits for the semaphore, A releases, B blocks, and then C times out because B never released it.
My solution is two-fold:
1) Thread B will release the semaphore, so that C can enter.
2) In case Thread C times out before B can release, it checks if sniffing is needed before throwing the exception, and, if it isn't, it simply returns (as opposed to throwing the exception).

Fix for sniffing throwing error for multiple threads.

---

src/CodeGeneration/ApiGenerator/Domain/ApiUrlPart.cs
src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
src/Elasticsearch.Net/ElasticLowLevelClient.Generated.cs
src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
src/Nest/Indices/IndexManagement/ShrinkIndex/ElasticClient-ShrinkIndex.cs
src/Nest/Indices/IndexManagement/ShrinkIndex/ShrinkIndexRequest.cs
src/Nest/Indices/IndexManagement/ShrinkIndex/ShrinkIndexResponse.cs
src/Nest/Nest.csproj
src/Nest/_Generated/_Descriptors.generated.cs
src/Nest/_Generated/_LowLevelDispatch.generated.cs
src/Nest/_Generated/_Requests.generated.cs
src/Tests/Indices/IndexManagement/ShrinkIndex/ShrinkIndexApiTests.cs
src/Tests/Indices/IndexManagement/ShrinkIndex/ShrinkIndexUrlTests.cs
src/Tests/Tests.csproj
src/Tests/tests.yaml

https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-shrink-index.html

Support for shrink index API

---

src/Elasticsearch.Net/Domain/RequestParameters/RequestParameters.Generated.cs
src/Elasticsearch.Net/ElasticLowLevelClient.Generated.cs
src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
src/Nest/Indices/IndexManagement/RolloverIndex/ElasticClient-RolloverIndex.cs
src/Nest/Indices/IndexManagement/RolloverIndex/RolloverConditions.cs
src/Nest/Indices/IndexManagement/RolloverIndex/RolloverIndexRequest.cs
src/Nest/Indices/IndexManagement/RolloverIndex/RolloverIndexResponse.cs
src/Nest/Nest.csproj
src/Nest/_Generated/_Descriptors.generated.cs
src/Nest/_Generated/_LowLevelDispatch.generated.cs
src/Nest/_Generated/_Requests.generated.cs
src/Tests/Indices/IndexManagement/RolloverIndex/RolloverIndexApiTests.cs
src/Tests/Indices/IndexManagement/RolloverIndex/RolloverIndexUrlTests.cs
src/Tests/Tests.csproj
src/Tests/tests.yaml

https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-rollover-index.html

Support for rollover index API

---

docs/query-dsl-usage.asciidoc
docs/query-dsl.asciidoc
docs/query-dsl/span/field-masking/span-field-masking-usage.asciidoc
src/Nest/Nest.csproj
src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
src/Nest/QueryDsl/Query.cs
src/Nest/QueryDsl/Span/FieldMasking/SpanFieldMaskingQuery.cs
src/Nest/QueryDsl/Span/SpanQuery.cs
src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
src/Nest/QueryDsl/Visitor/QueryVisitor.cs
src/Nest/QueryDsl/Visitor/QueryWalker.cs
src/Tests/QueryDsl/Span/FieldMasking/SpanFieldMaskingUsageTests.cs
src/Tests/Tests.csproj

Add field_masking_span query

---

src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs

Add missing `ConfigureAwait(false)` calls to async methods

ConfigureAwait(false) all async calls on BulkAllObservable

---

docs/2.0-breaking-changes/nest-breaking-changes.asciidoc

Add changes for NumericRangeQueryDescriptor`1

---

src/Nest/QueryDsl/Abstractions/FieldLookup/FieldLookup.cs
src/Nest/QueryDsl/TermLevel/Terms/TermsQueryJsonConverter.cs
src/Tests/QueryDsl/TermLevel/Terms/TermsLookupQueryUsageTests.cs

Fix #2261 add missing Routing option to FieldsLookup

---

src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
src/Nest/QueryDsl/TermLevel/Missing/MissingQuery.cs

Deprecate missing query

---

src/Nest/Mapping/AttributeBased/ElasticsearchPropertyAttributeBase.cs
src/Nest/Mapping/Types/PropertyBase.cs
src/Nest/Mapping/Types/PropertyDescriptorBase.cs
src/Tests/Mapping/Types/Core/Binary/BinaryMappingTests.cs
src/Tests/Mapping/Types/Core/Boolean/BooleanMappingTests.cs
src/Tests/Mapping/Types/Core/Date/DateMappingTests.cs
src/Tests/Mapping/Types/Core/Number/NumberMappingTests.cs

Remove obsolete IndexName from mapping properties

---

src/Nest/Mapping/Types/PropertyBase.cs

Deprecate IndexName mapping property

---

src/Benchmarking/PartitionExtension.cs
src/Benchmarking/Results.cs
src/Benchmarking/Tester.cs
src/Nest/Document/Multiple/Bulk/BulkResponse.cs
src/Nest/Document/Single/TermVectors/TermVectorsResponse.cs
src/Nest/Search/Percolator/Percolate/PercolateResponse.cs
src/Nest/Search/Search/SearchResponse.cs

As discussed on #2317, this is the first PR that modifies the type of the "Took" field in the remaining responses that are ints.

Change type of took field in responses

---

src/Nest/CommonAbstractions/Extensions/ExpressionExtensions.cs
src/Tests/ClientConcepts/HighLevel/Inference/FieldInference.doc.cs

AppendSuffix should work with any expression instead of just member access expressions
Closes #2331

Fix AppendSuffix to work with different expressions and updated test

---

src/Nest/Search/Search/SearchRequest.cs
src/Tests/Framework/TestClient.cs
src/Tests/Search/Request/SearchAfterUsageTests.cs
src/Tests/Tests.csproj

Add support for search after

---

docs/aggregations/matrix/matrix-stats/matrix-stats-aggregation-usage.asciidoc
src/CodeGeneration/DocGenerator/StringExtensions.cs
src/Nest/Aggregations/AggregateJsonConverter.cs
src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/AggregationsHelper.cs
src/Nest/Aggregations/Matrix/MatrixAggregate.cs
src/Nest/Aggregations/Matrix/MatrixAggregation.cs
src/Nest/Aggregations/Matrix/MatrixStats/MatrixStatsAggregate.cs
src/Nest/Aggregations/Matrix/MatrixStats/MatrixStatsAggregation.cs
src/Nest/Aggregations/Matrix/MatrixStats/MatrixStatsMode.cs
src/Nest/Aggregations/Metric/Stats/StatsAggregation.cs
src/Nest/Aggregations/Visitor/AggregationVisitor.cs
src/Nest/Nest.csproj
src/Tests/Aggregations/Matrix/MatrixStats/MatrixStatsAggregationUsageTests.cs
src/Tests/Framework/MockData/Project.cs
src/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
src/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
src/Tests/Search/Search/InvalidSearchApiTests.cs
src/Tests/Tests.csproj

Support for matrix stats aggregation

---

src/Nest/CommonAbstractions/LazyDocument/LazyDocument.cs
src/Nest/CommonAbstractions/LazyDocument/LazyDocumentJsonConverter.cs
src/Nest/CommonAbstractions/SerializationBehavior/StatefulDeserialization/ConcreteTypeConverter.cs
src/Nest/Nest.csproj
src/Nest/Search/Search/Hits/Hit.cs
src/Nest/Search/Search/Hits/NestedIdentity.cs
src/Tests/Reproduce/GithubIssue2323.cs
src/Tests/Search/Hits/HitsSerializationTests.cs
src/Tests/Tests.csproj

See https://www.elastic.co/guide/en/elasticsearch/reference/2.0/search-aggregations-metrics-top-hits-aggregation.html#_top_hits_support_in_a_nested_or_reverse_nested_aggregator
Closes #2323

Included the nested identity for inner hits on a nested type

---

src/Nest/Search/Search/Highlighting/HighlightField.cs
src/Tests/Search/Request/HighlightingUsageTests.cs

Remove max_boundary_size
Rename OnAll fluent method to AllField
Add xml comments
Closes #2362

Add max_boundary_scan to highlighting

---

src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
src/Elasticsearch.Net/Configuration/Security/BasicAuthenticationCredentials.cs
src/Elasticsearch.Net/Domain/RequestParameters/IRequestParameters.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
src/Elasticsearch.Net/Transport/PostData.cs
src/Nest/CommonAbstractions/Request/RequestBase.cs
src/Tests/ClientConcepts/LowLevel/DirectStreaming.cs

Enable DisableDirectStreaming on a per request basis

---

docs/client-concepts/connection-pooling/building-blocks/request-pipelines.asciidoc
docs/client-concepts/connection-pooling/sniffing/address-parsing.asciidoc
docs/client-concepts/high-level/inference/field-inference.asciidoc
docs/code-standards/descriptors.asciidoc
docs/code-standards/responses.asciidoc
docs/mapping/scalar/scalar-usage.asciidoc
docs/query-dsl/compound/bool/bool-query-usage.asciidoc
docs/search/request/highlighting-usage.asciidoc
src/Nest/CommonAbstractions/Infer/Field/Field.cs
src/Nest/CommonAbstractions/Infer/Fields/Fields.cs
src/Nest/CommonAbstractions/Static/Static.cs
src/Tests/ClientConcepts/HighLevel/Inference/FieldInference.doc.cs
src/Tests/QueryDsl/Compound/Bool/BoolQueryUsageTests.cs
src/Tests/QueryDsl/Compound/Dismax/DismaxQueryUsageTests.cs

Add additional methods for combining Field values and building Fields

---

src/Nest/Indices/MappingManagement/PutMapping/PutMappingRequest.cs
src/Nest/Mapping/TypeMapping.cs
src/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs

Add include_in_all to TypeMapping

---

src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs

Query methods on `QueryContainerDescriptor<T>` wrap the `IQuery` in a new instantiated `QueryContainerDescriptor<T>` each time. The `QueryContainerDescriptor<T>` instance on which the method is called can be used when it does not already contain a query.
Align `.Raw()` query method call with the rest of the query methods.
Found this when looking at #2234

Do not instantiate QueryContainerDescriptor<T> unneccessarily

---

src/Nest/XPack/Security/Role/GetRole/Role.cs
src/Nest/XPack/Security/Role/PutRole/PutRoleRequest.cs
src/Tests/XPack/Security/Role/PutRole/PutRoleApiTests.cs

Added Metadata for Roles 

---

src/Nest/Aggregations/Bucket/Terms/TermsIncludeExcludeJsonConverter.cs
src/Nest/Analysis/Analyzers/AnalyzerJsonConverter.cs
src/Nest/Analysis/CharFilters/CharFilterJsonConverter.cs
src/Nest/Analysis/TokenFilters/TokenFilterJsonConverter.cs
src/Nest/Analysis/Tokenizers/TokenizerJsonConverter.cs
src/Nest/CommonAbstractions/Fields/FieldValuesJsonConverter.cs
src/Nest/CommonAbstractions/SerializationBehavior/GenericJsonConverters/JsonConverterBase.cs
src/Nest/Document/Multiple/MultiGet/Request/MultiGetRequestJsonConverter.cs
src/Nest/IndexModules/Similarity/SimilarityJsonConverter.cs
src/Nest/Indices/Monitoring/IndicesShardStores/ShardStoreJsonConverter.cs
src/Nest/Indices/StatusManagement/Upgrade/UpgradeStatus/UpgradeStatusResponseJsonConverter.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/CreateRepository/CreateRepositoryJsonConverter.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainerJsonConverter.cs
src/Nest/Search/MultiSearch/MultiSearchTemplate/MultiSearchTemplateJsonConverter.cs

Semantically correct in these cases and means they do not get flagged as TODOs

Convert NotImplementedException to NotSupportedException

---

src/Nest/Document/Multiple/MultiTermVectors/MultiTermVectorsRequest.cs
src/Nest/Indices/IndexManagement/CreateIndex/CreateIndexRequest.cs
src/Nest/Mapping/Types/Specialized/Attachment/AttachmentAttribute.cs
src/Nest/Search/MultiSearch/MultiSearchJsonConverter.cs
src/Nest/Search/MultiSearch/MultiSearchTemplate/MultiSearchTemplateJsonConverter.cs
src/Tests/ClientConcepts/ConnectionPooling/Sniffing/RoleDetection.doc.cs
src/Tests/CodeStandards/NamingConventions.doc.cs
src/Tests/Framework/XUnitPlumbing/IntegrationTestDiscoverer.cs

Clean up TODOs

---

src/Nest/CommonOptions/TimeUnit/TimeUnit.cs
src/Nest/Indices/Monitoring/IndicesShardStores/IndicesShardStoresResponse.cs
src/Nest/Modules/Indices/Fielddata/GeoPoint/GeoPointFielddataFormat.cs
src/Nest/Modules/Indices/Fielddata/Numeric/NumericFielddataFormat.cs
src/Nest/Modules/Indices/Fielddata/String/StringFielddataFormat.cs
src/Tests/CodeStandards/Serialization/Enums.cs
src/Tests/Tests.csproj

Add unit test to assert this for all enums in Nest
Closes #2464

Ensure all enums serialize to string

---

build/scripts/Targets.fsx
src/Elasticsearch.Net/Transport/Transport.cs
src/Nest/Aggregations/Bucket/Filters/NamedFiltersContainer.cs
src/Nest/Cluster/ClusterReroute/ClusterRerouteResponse.cs
src/Nest/CommonAbstractions/Infer/Inferrer.cs
src/Nest/CommonAbstractions/SerializationBehavior/GenericJsonConverters/KeyValueJsonConverter.cs
src/Nest/CommonAbstractions/SerializationBehavior/JsonNetSerializer.cs
src/Nest/Document/Single/Delete/ElasticClient-Delete.cs
src/Nest/Document/Single/Update/UpdateRequest.cs
src/Nest/Indices/MappingManagement/GetFieldMapping/GetFieldMappingRequest.cs
src/Nest/Indices/MappingManagement/GetFieldMapping/GetFieldMappingResponse.cs
src/Nest/Indices/MappingManagement/GetMapping/GetMappingRequest.cs
src/Nest/Modules/SnapshotAndRestore/Restore/SnapshotRestore.cs
src/Tests/Cluster/TaskManagement/TasksCancel/TasksCancelApiTests.cs
src/Tests/Document/Multiple/MultiTermVectors/MultiTermVectorsApiTests.cs
src/Tests/Framework/ManagedElasticsearch/Process/ElasticsearchNode.cs
src/Tests/Framework/VirtualClustering/VirtualClusterConnection.cs
src/Tests/tests.yaml

verify
also its sweep yeah i know 😢

Quick sweap over all the TODO's that were quick to

---

src/Nest/Indices/IndexManagement/GetIndex/ElasticClient-GetIndex.cs
src/Nest/Indices/IndexManagement/GetIndex/GetIndexResponse.cs
src/Nest/Indices/IndexSettings/GetIndexSettings/GetIndexSettingsResponse.cs
src/Tests/Indices/IndexManagement/GetIndex/GetIndexApiTests.cs

Also changed GetIndexSettingsResponse to from IIndexState to IndexState.

Fix GetIndexResponse so it inherits from DictionaryResponseBase

---

src/Elasticsearch.sln
src/Nest/Cat/CatTemplates/CatTemplatesRecord.cs
src/Nest/Cat/CatTemplates/CatTemplatesRequest.cs
src/Nest/Cat/CatTemplates/ElasticClient-CatTemplates.cs
src/Nest/Nest.csproj
src/Nest/_Generated/_Descriptors.generated.cs
src/Nest/_Generated/_Requests.generated.cs
src/Tests/Cat/CatTemplates/CatTemplatesApiTests.cs
src/Tests/Cat/CatTemplates/CatTemplatesUrlTests.cs
src/Tests/Tests.csproj

Ended up implementing this since 5.x had already generated code for it but we should not pull this until ES 5.1 hits the streets.

add support for cat templates which is forthcomming in 5.1

---

docs/aggregations/metric/min/min-aggregation-usage.asciidoc
docs/client-concepts/connection-pooling/sniffing/address-parsing.asciidoc
src/Nest/Aggregations/AggregateJsonConverter.cs
src/Nest/Aggregations/Metric/TopHits/TopHitsAggregate.cs
src/Nest/Aggregations/Metric/ValueAggregate.cs
src/Nest/Nest.csproj
src/Tests/Aggregations/Metric/Min/MinAggregationUsageTests.cs
src/Tests/Aggregations/Pipeline/MinBucket/MinBucketAggregationUsageTests.cs

Include value_as_string for ValueAggregate

---

src/Nest/Search/Search/SourceFiltering/SourceFilterJsonConverter.cs
src/Tests/Search/Request/SourceFilteringUsageTests.cs

Allow SourceFiltering Disable to be set to false

---

src/Nest/DSL/Aggregations/MetricAggregationBaseDescriptor.cs
src/Tests/Nest.Tests.Integration/Aggregations/MetricAggregationTests.cs

Add ScriptFile and ScriptId to metrics aggregations

---

src/Nest/Aggregations/AggregateJsonConverter.cs

Already added this in `2.x` as part of the backport of #2551

add meta as reserved aggregation key name

---

src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
src/Elasticsearch.Net/Connection/HttpConnection.cs
src/Elasticsearch.Net/Responses/ElasticsearchResponse.cs
src/Elasticsearch.Net/Responses/IApiCallDetails.cs
src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
src/Nest/CommonAbstractions/Response/ApiCallDetailsOverride.cs
src/Tests/ClientConcepts/DeprecationLogging.doc.cs
src/Tests/Tests.csproj
src/Tests/tests.yaml

still pending elastic/elasticsearch#22986

Return Warning HTTP headers as deprecations on response

---

src/Nest/Analysis/TokenFilters/Synonym/SynonymGraphTokenFilter.cs
src/Nest/Analysis/TokenFilters/TokenFilterJsonConverter.cs
src/Nest/Analysis/TokenFilters/TokenFilters.cs
src/Nest/Nest.csproj
src/Tests/Analysis/TokenFilters/TokenFilterUsageTests.cs

https://www.elastic.co/guide/en/elasticsearch/reference/master/analysis-synonym-graph-tokenfilter.html

Add support for the synonym_graph token filter

---

src/Nest/Indices/Analyze/AnalyzeToken.cs

Yeah, 👑 typo at it again in the branch name :)

fix #2604 add position_length on analyze api response

---

src/Tests/Framework/Configuration/Versions/ElasticsearchVersion.cs
src/Tests/Framework/DocumentationTests/IntegrationDocumentationTestBase.cs
src/Tests/Framework/Extensions/TypeExtensions.cs
src/Tests/Framework/ManagedElasticsearch/Nodes/ElasticsearchNode.cs
src/Tests/Framework/ManagedElasticsearch/Nodes/NodeConfiguration.cs
src/Tests/Framework/ManagedElasticsearch/Plugins/ElasticsearchPlugin.cs
src/Tests/Framework/ManagedElasticsearch/Plugins/ElasticsearchPluginCollection.cs
src/Tests/Framework/ManagedElasticsearch/Plugins/ElasticsearchPluginConfiguration.cs
src/Tests/Framework/ManagedElasticsearch/Plugins/MonikerAttribute.cs
src/Tests/Framework/ManagedElasticsearch/Process/ElasticsearchConsoleOut.cs
src/Tests/Framework/ManagedElasticsearch/Tasks/InstallationTasks/EnsureSecurityRolesFileExists.cs
src/Tests/Framework/ManagedElasticsearch/Tasks/InstallationTasks/EnsureSecurityUsersInDefaultRealmAreAdded.cs
src/Tests/Framework/ManagedElasticsearch/Tasks/InstallationTasks/EnsureWatcherActionConfigurationInElasticsearchYaml.cs
src/Tests/Framework/ManagedElasticsearch/Tasks/InstallationTasks/InstallPlugins.cs
src/Tests/Framework/ManagedElasticsearch/Tasks/NodeTaskRunner.cs
src/Tests/Framework/TestClient.cs
src/Tests/Framework/XUnitPlumbing/IntegrationTestDiscoverer.cs
src/Tests/Tests.csproj
src/Tests/tests.default.yaml

#2629
- task runner log growing unboundedly
- make sure validation tasks always run
- split plugin code over multiple files

forward port of test runner bugs noticed in the backport

---

src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs

2.x moved away from Task.WhenAll in the bulk all implementation

---

src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsConverter.cs
src/Tests/Reproduce/GithubIssue2690.cs
src/Tests/Tests.csproj

Fix #2690: NRE in IndexSettingsConverter when merge policy isn't set

---

src/Nest/Indices/Analyze/AnalyzeToken.cs

Intorduce EndOffset to Analyze token

---

src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs

Small fix for keyword attribute parser in NoopPropertyVisitor

Fixed NoopPropertyVisitor

---

src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs

when setting MaxConnectionsPerServer
Closes #2758

catch PlatformNotSupportedException

---

src/Elasticsearch.Net/ConnectionPool/SniffingConnectionPool.cs

move monitor enter readlock outside of try

---

src/Nest/CommonAbstractions/SerializationBehavior/GenericJsonConverters/VerbatimDictionaryKeysConverter.cs
src/Nest/CommonOptions/Scripting/ScriptBase.cs
src/Tests/Document/Single/Update/UpdateWithScriptApiTests.cs
src/Tests/Framework/SerializationTests/SerializationTestBase.cs

fix https://github.com/elastic/elasticsearch-net/issues/2763

allow null to be passed as value on params to scripts

---

src/Tests/ClientConcepts/Serializer/IsoDateTimeConverterTests.cs

IsoDateTimeConverterTests

---

src/Nest/Search/MultiSearch/IMultiSearchResponse.cs
src/Nest/Search/MultiSearch/MultiSearchResponse.cs

to allow easier mocking when writing unit tests

interface for mutli search responses

---

src/Nest/Document/Multiple/MultiGet/Response/MultiGetHit.cs
src/Nest/Document/Multiple/MultiGet/Response/MultiGetResponse.cs
src/Tests/Reproduce/GithubIssue2871.cs

Deserialize error property on MultiGetHit

---

src/Nest/Document/Multiple/Bulk/BulkResponse.cs
src/Nest/Document/Multiple/Bulk/BulkResponseItem/BulkResponseItemBase.cs
src/Nest/Document/Multiple/Bulk/BulkResponseItem/BulkResponseItemJsonConverter.cs

Easier to mock bulk responses
Closes #2867

Introduce IBulkResponseItem interface

---

src/Nest/Aggregations/Bucket/Terms/TermsAggregation.cs
src/Nest/Aggregations/Bucket/Terms/TermsOrder.cs
src/Nest/Aggregations/Bucket/Terms/TermsOrderDescriptor.cs
src/Tests/Aggregations/Bucket/Terms/TermsAggregationUsageTests.cs

Deprecate Terms order _terms with Obsolete attributes
Closes #2840

Make Terms order assignative

---

src/Nest/CommonAbstractions/Extensions/JsonExtensions.cs
src/Nest/Search/MultiSearch/MultiSearchResponseJsonConverter.cs
src/Nest/Search/Search/SearchResponse.cs

replaces https://github.com/elastic/elasticsearch-net/pull/2932

MultiSearchServerError on SearchResponse is no longer needed

---

src/Nest/CommonAbstractions/Response/DictionaryResponseBase.cs
src/Nest/Indices/AliasManagement/GetAlias/GetAliasResponse.cs

… as aliases, earlier in the 5.x series this was always a string

Fix #2884 get alias error object

---

src/Nest/QueryDsl/Joining/HasParent/HasParentQuery.cs
src/Tests/QueryDsl/Joining/HasParent/HasParentQueryUsageTests.cs

type on has_parent query should be parent_type'

---

src/Nest/Document/Multiple/DeleteByQuery/DeleteByQueryRequest.cs
src/Nest/Document/Multiple/DeleteByQuery/DeleteByQueryResponse.cs
src/Tests/Document/Multiple/DeleteByQuery/DeleteByQueryApiTests.cs

Support slice in delete by query

---

src/Nest/Search/Search/InnerHits/InnerHits.cs
src/Nest/Search/Search/SearchRequest.cs
src/Tests/Search/Request/InnerHitsUsageTests.cs

fix #3017 add docvalues_fields to innerhits

---

src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsConverter.cs
src/Tests/Indices/IndexSettings/UpdateIndicesSettings/UpdateIndexSettingsApiTests.cs

fix #3019, converter should not nullify known keys in the base dictionary

---

src/Nest/Aggregations/AggregateJsonConverter.cs

fixed loop so the deserialisation doesn't crash when reciving en empty aggregation bucket.

fix on empty buckets

---

src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/Pipeline/BucketSort/BucketSortAggregation.cs
src/Nest/Aggregations/Visitor/AggregationVisitor.cs
src/Nest/Aggregations/Visitor/AggregationWalker.cs
src/Tests/Aggregations/Pipeline/BucketSort/BucketSortAggregationUsageTests.cs

Add bucket_sort aggregation

---

src/Nest/Ingest/PipelineJsonConverter.cs
src/Nest/Ingest/Processors/UrlDecodeProcessor.cs
src/Nest/Ingest/ProcessorsDescriptor.cs
src/Tests/Ingest/PutPipeline/PutPipelineApiTests.cs

Add urldecode ingest processor

---

src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Dsl.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainerJsonConverter.cs
src/Nest/QueryDsl/Query.cs
src/Nest/QueryDsl/TermLevel/TermsSet/TermsSetQuery.cs
src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
src/Nest/QueryDsl/Visitor/QueryVisitor.cs
src/Nest/QueryDsl/Visitor/QueryWalker.cs
src/Tests/Framework/MockData/Project.cs
src/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
src/Tests/QueryDsl/TermLevel/TermsSet/TermsSetQueryUsageTests.cs

Add terms_set query

---

src/Nest/Analysis/Tokenizers/WhitespaceTokenizer.cs

Add Max Token Length to Whitespace Tokenizer

---

src/Nest/QueryDsl/Specialized/Percolate/PercolateQuery.cs
src/Tests/QueryDsl/Specialized/Percolate/PercolateQueryUsageTests.cs

Add multiple documents to percolate query

---

src/Nest/Indices/IndexManagement/RolloverIndex/RolloverConditions.cs

Add MaxSize to Rollover index API

---

src/Nest/Document/Multiple/ReindexOnServer/ElasticClient-ReindexOnServer.cs
src/Nest/Document/Multiple/ReindexOnServer/ReindexDestination.cs
src/Nest/Document/Multiple/ReindexOnServer/ReindexOnServerRequest.cs
src/Nest/Document/Multiple/ReindexOnServer/ReindexOnServerResponse.cs
src/Nest/Document/Multiple/ReindexOnServer/ReindexSource.cs
src/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerSliceApiTests.cs
src/Tests/Framework/EndpointTests/ApiTestBase.cs
src/Tests/Framework/EndpointTests/RequestResponseApiTestBase.cs
src/Tests/Framework/EndpointTests/TestState/EndpointUsage.cs

This commit adds support for manual slicing to the Reindex API
Add integration test to verify slice_id is returned on response
Slight tidy of integration test framework components
Closes #3158

Add support for manual slicing on ReindexOnServer

---

src/Nest/Indices/Monitoring/IndicesStats/IndicesStats.cs
src/Nest/Indices/Monitoring/IndicesStats/IndicesStatsResponse.cs
src/Nest/Indices/Monitoring/IndicesStats/ShardCommit.cs
src/Nest/Indices/Monitoring/IndicesStats/ShardPath.cs
src/Nest/Indices/Monitoring/IndicesStats/ShardRouting.cs
src/Nest/Indices/Monitoring/IndicesStats/ShardRoutingState.cs
src/Nest/Indices/Monitoring/IndicesStats/ShardStats.cs
src/Nest/Indices/Monitoring/IndicesStats/ShardStatsStore.cs
src/Tests/Indices/Monitoring/IndicesStats/IndicesStatsWithShardsInformationApiTests.cs

Indices ShardsStats in 5.x

---

src/Nest/Modules/SnapshotAndRestore/Repositories/S3Repository.cs
src/Tests/Modules/SnapshotAndRestore/Repositories/CreateRepository/CreateRepositoryApiTests.cs

S3 repo settings for 5.x clients

---

src/Elasticsearch.Net/ElasticLowLevelClient.cs
src/Tests/Reproduce/GithubIssue3231.cs

Ported change related to #3231 to 6.x

---

.paket/Paket.Restore.targets
src/Nest/XPack/Watcher/Action/ActionBase.cs
src/Nest/XPack/Watcher/Action/Email/EmailAttachments.cs
src/Nest/XPack/Watcher/Action/Email/HttpAttachment.cs
src/Nest/XPack/Watcher/Action/PagerDuty/PagerDutyAction.cs
src/Nest/XPack/Watcher/Action/PagerDuty/PagerDutyEvent.cs
src/Nest/XPack/Watcher/Action/Webhook/WebhookAction.cs
src/Nest/XPack/Watcher/Execution/HttpInputRequestResult.cs
src/Nest/XPack/Watcher/Input/ChainInput.cs
src/Nest/XPack/Watcher/Input/HttpInputAuthentication.cs
src/Nest/XPack/Watcher/Input/HttpInputRequest.cs
src/Nest/XPack/Watcher/Input/SearchInput.cs
src/Nest/XPack/Watcher/PutWatch/ElasticClient-PutWatch.cs
src/Nest/XPack/Watcher/PutWatch/PutWatchRequest.cs
src/Tests/XPack/Watcher/GetWatch/GetWatchApiTests.cs
src/Tests/XPack/Watcher/PutWatch/PutWatchApiTests.cs

Fix alerting deserialization

---

src/Tests/Search/Request/InnerHitsUsageTests.cs

Integration test to verify version support for inner hits in field collapsing

---

docs/aggregations/metric/top-hits/top-hits-aggregation-usage.asciidoc
src/CodeGeneration/DocGenerator/StringExtensions.cs
src/Nest/Aggregations/Metric/TopHits/TopHitsAggregation.cs
src/Tests/Aggregations/Metric/TopHits/TopHitsAggregationUsageTests.cs

Add DocValueFields to TopHits Aggregation

---

src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdate.cs

Add _ScriptedUpsert to BulkUpdateOperation

---

src/Nest/Analysis/Analyzers/CustomAnalyzer.cs
src/Nest/Analysis/Normalizers/CustomNormalizer.cs
src/Nest/CommonAbstractions/SerializationBehavior/GenericJsonConverters/ReadSingleOrEnumerableJsonConverter.cs
src/Tests/Reproduce/GithubIssue3262.cs

Support single or array of char filters and token filters

---

docs/aggregations/metric/scripted-metric/scripted-metric-aggregation-usage.asciidoc
docs/aggregations/pipeline/moving-average/moving-average-holt-winters-aggregation-usage.asciidoc
docs/aggregations/writing-aggregations.asciidoc
docs/analysis/token-filters/token-filter-usage.asciidoc
docs/client-concepts/connection-pooling/exceptions/unexpected-exceptions.asciidoc
docs/client-concepts/connection-pooling/exceptions/unrecoverable-exceptions.asciidoc
docs/client-concepts/connection-pooling/request-overrides/disable-sniff-ping-per-request.asciidoc
docs/client-concepts/connection-pooling/round-robin/skip-dead-nodes.asciidoc
docs/client-concepts/connection-pooling/sniffing/role-detection.asciidoc
docs/client-concepts/high-level/analysis/writing-analyzers.asciidoc
docs/client-concepts/high-level/getting-started.asciidoc
docs/client-concepts/high-level/inference/field-inference.asciidoc
docs/client-concepts/high-level/inference/indices-paths.asciidoc
docs/client-concepts/high-level/inference/types-and-relations-inference.asciidoc
docs/client-concepts/high-level/mapping/fluent-mapping.asciidoc
docs/client-concepts/high-level/mapping/ignoring-properties.asciidoc
docs/client-concepts/high-level/mapping/multi-fields.asciidoc
docs/client-concepts/high-level/mapping/parent-child-relationships.asciidoc
docs/client-concepts/high-level/mapping/visitor-pattern-mapping.asciidoc
docs/client-concepts/low-level/getting-started.asciidoc
docs/client-concepts/low-level/lifetimes.asciidoc
docs/client-concepts/troubleshooting/logging-with-on-request-completed.asciidoc
docs/code-standards/naming-conventions.asciidoc
docs/high-level.asciidoc
docs/search/request/inner-hits-usage.asciidoc
docs/search/returned-fields.asciidoc
docs/search/writing-queries.asciidoc
src/Tests/ClientConcepts/HighLevel/Inference/TypesAndRelationsInference.doc.cs
src/Tests/high-level.asciidoc

Regenerate documentation and fix spelling in Types and Relations documentation

Update types and relations documentation

---

src/Nest/Cluster/NodesStats/AdaptiveSelectionStats.cs
src/Nest/Cluster/NodesStats/NodeStats.cs
src/Nest/Cluster/NodesStats/Statistics/IngestStats.cs
src/Nest/Cluster/NodesStats/Statistics/NodeIngestStats.cs
src/Tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
src/Tests/Tests/Cluster/NodesStats/NodesStatsApiTests.cs

Add `ingest` and `adaptive_selection` node statistics.

Feature/node stats 6.3

---

docs/client-concepts/connection/configuration-options.asciidoc

Remove duplicate

---

src/Tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
src/Tests/Tests.Core/Xunit/SkipOnTeamCityAttribute.cs
src/Tests/Tests.Domain/CommitActivity.cs
src/Tests/Tests.Domain/Project.cs
src/Tests/Tests/Cat/CatFielddata/CatFielddataApiTests.cs
src/Tests/Tests/Document/Single/Create/CreateApiTests.cs
src/Tests/Tests/Document/Single/Index/IndexApiTests.cs
src/Tests/Tests/Document/Single/Index/IndexIngestApiTests.cs
src/Tests/Tests/Document/Single/Index/IndexIngestGeoIpApiTests.cs
src/Tests/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
src/Tests/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
src/Tests/Tests/Search/Request/FieldsUsageTests.cs
src/Tests/Tests/Search/Request/SourceFilteringUsageTests.cs
src/Tests/Tests/Search/Request/SuggestUsageTests.cs
src/Tests/Tests/Search/SearchUsageTestBase.cs

`6.x` received some integration test fixes to fix some of our flaky tests.

Forward port of 6.x test fixes

---

src/Nest/XPack/Watcher/ExecuteWatch/ExecuteWatchResponse.cs

as per https://github.com/elastic/elasticsearch/pull/31873

return user on watch record

---

src/Nest/Cluster/ClusterAllocationExplain/ClusterAllocationExplainResponse.cs

Add missing enum values for UnassignedInformationReason

---

src/Nest/XPack/Security/Role/PutRole/IApplicationPrivileges.cs
src/Nest/XPack/Security/Role/PutRole/IndicesPrivileges.cs
src/Nest/XPack/Security/Role/PutRole/PutRoleRequest.cs
src/Tests/Tests/XPack/Security/Role/PutRole/PutRoleApiTests.cs

Add application privileges to Put Role API

---

docs/aggregations/bucket/auto-date-histogram/auto-date-histogram-aggregation-usage.asciidoc

This PR is an alternative to https://github.com/elastic/elasticsearch-net/pull/3555
It just comments out the broken link.

[DOCS] Comments out broken link

---

src/Nest/Document/Single/TermVectors/TermVectorTerm.cs
src/Tests/Tests/Document/Multiple/MultiTermVectors/MultiTermVectorsApiTests.cs
src/Tests/Tests/Document/Single/TermVectors/TermVectorsApiTests.cs

Add score to TermVectorTerm

---

src/Nest/QueryDsl/Abstractions/Query/QueryBase.cs

Relates to elastic/elasticsearch#28390 and elastic/elasticsearch#34112

 Throw a parsing exception when boost is set in span_or query,

---

docs/aggregations.asciidoc
docs/aggregations/bucket/parent/parent-aggregation-usage.asciidoc
src/Nest/Aggregations/AggregateDictionary.cs
src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/Bucket/Parent/ParentAggregation.cs
src/Nest/Aggregations/Visitor/AggregationVisitor.cs
src/Nest/Aggregations/Visitor/AggregationWalker.cs
src/Tests/Tests/Aggregations/Bucket/Parent/ParentAggregationUsageTests.cs

Relates: elastic/elasticsearch#34210
This commit adds Parent Aggregation to the high level client.

Add Parent Aggregation

---

src/Elasticsearch.Net/Transport/Transport.cs

Fix the comment: WebExeption -> WebException

Fix the comment: WebExeption -> WebException

---

docs/aggregations.asciidoc
docs/aggregations/metric/median-absolute-deviation/median-absolute-deviation-aggregation-usage.asciidoc
src/Nest/Aggregations/AggregateDictionary.cs
src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/Metric/MedianAbsoluteDeviation/MedianAbsoluteDeviationAggregation.cs
src/Nest/Aggregations/Visitor/AggregationVisitor.cs
src/Nest/Aggregations/Visitor/AggregationWalker.cs
src/Tests/Tests/Aggregations/Metric/MedianAbsoluteDeviation/MedianAbsoluteDeviationAggregationUsageTests.cs

Add Median Absolute Deviation Aggregation

---

src/Nest/Analysis/Tokenizers/NoriTokenizer.cs
src/Tests/Tests/Analysis/Tokenizers/TokenizerTests.cs

Relates #3615, elastic/elasticsearch#3620

Add User Dictionary Rules to NoriTokenizer

---

src/Nest/QueryDsl/Specialized/MoreLikeThis/MoreLikeThisQuery.cs
src/Tests/Tests/QueryDsl/QueryDslUsageTestsBase.cs
src/Tests/Tests/QueryDsl/Specialized/MoreLikeThis/MoreLikeThisFullDocumentQueryUsageTests.cs
src/Tests/Tests/QueryDsl/Specialized/MoreLikeThis/MoreLikeThisQueryUsageTests.cs

Fix MoreLikeThisQuery conditionless behaviour

---

src/Nest/Aggregations/AggregateFormatter.cs
src/Tests/Tests.Reproduce/GithubIssue3717.cs

Handle empty aggregation

---

src/Elasticsearch.Net/Extensions/Extensions.cs
src/Elasticsearch.Net/Serialization/IElasticsearchSerializer.cs

Forward port of b75271d9bd4f3e5be1420d8ec4c23d1084d7e1c1

Use Stream buffer

---

docs/high-level.asciidoc

Fixes a few links and includes broken with 69a60a6.

[DOCS] Fix includes and broken links

---

src/Nest/Aggregations/AggregateFormatter.cs
src/Tests/Tests.Reproduce/GithubIssue3745.cs
src/Tests/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs

Fix composite aggregation deserialization

---

src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs

This commit updates DefaultMappingFor methods to assign default mapping values
using indexers into dictionaries as opposed to using the Add method.
Fixes #3706

Use indexers to set default mapping values

---

src/Nest/IndexModules/IndexSettings/Settings/UpdatableIndexSettings.cs

Relates: https://github.com/elastic/elasticsearch/pull/27529

Add index.analyze.max_token_count to updateable index settings

---

src/Nest/IndexModules/IndexSettings/Settings/FixedIndexSettings.cs

Relates: https://github.com/elastic/elasticsearch/pull/28060

Add index.percolator.map_unmapped_fields_as_text index setting

---

src/CodeGeneration/ApiGenerator/Configuration/Overrides/GlobalOverrides.cs

Relates: https://github.com/elastic/elasticsearch/pull/29224

Remove parent param from obsoletes

---

src/Nest/QueryDsl/Compound/Bool/BoolQuery.cs

Relates: #3855
This PR makes the implementation of ShouldSerialize methods explicit on the `BoolQuery` implementations

Make Should implementation explicit

---

src/Nest/Modules/SnapshotAndRestore/Snapshot/SnapshotStatus/SnapshotStatusResponse.cs

Relates: https://github.com/elastic/elasticsearch/pull/30890

Remove Snapshot stats fields

---

src/Nest/Document/Single/Get/GetRequest.cs
src/Nest/Document/Single/Source/SourceRequest.cs
src/Nest/Search/Search/SearchRequest.cs

Relates: https://github.com/elastic/elasticsearch/pull/26791

Remove _primary and _replica execution preferences

---

src/Tests/Tests/Search/SearchUsageTestBase.cs

Probably a dev change leftover on `master`.

Search usage tests used wrong http code assertion

---

docs/query-dsl.asciidoc
docs/query-dsl/compound/function-score/function-score-query-usage.asciidoc
docs/query-dsl/specialized/script-score/script-score-query-usage.asciidoc
src/CodeGeneration/DocGenerator/StringExtensions.cs
src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
src/Nest/QueryDsl/Query.cs
src/Nest/QueryDsl/Specialized/ScriptScore/ScriptScoreQuery.cs
src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
src/Nest/QueryDsl/Visitor/QueryVisitor.cs
src/Nest/QueryDsl/Visitor/QueryWalker.cs
src/Tests/Tests/QueryDsl/Specialized/ScriptScore/ScriptScoreQueryUsageTests.cs

This commit adds script_score query support to the high level client
Closes #3843

Add script_score query support

---

build/scripts/scripts.fsproj

Contains a minor fix: https://github.com/adamralph/bullseye/pull/254

update Bullseye from 2.4.0-beta.1 to 2.4.0-rc.2

---

contributing.md
readme.md

Issue #3931 raised some questions around compatibility between the client and server versions. This new section addresses those questions raised and also aims to quell similar future questions.
Requires porting.
Thanks to @lcawl for reviewing.

Update homepage to give further information on compatibility questions

---

src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs

Addresses: https://github.com/elastic/elasticsearch/pull/40518

 Add created_by info to usage stats.

---

src/Nest/CommonOptions/Stats/RefreshStats.cs

Expose external refreshes through the stats API

Expose external refreshes through the stats API

---

examples/Mapping/Dynamic/TemplatesPage/0b91c082258ce623cc716b679aace653.asciidoc
examples/Mapping/Dynamic/TemplatesPage/4f54b88e05c7a62901062e9e0ed13e5a.asciidoc
examples/Mapping/Dynamic/TemplatesPage/bb33e638fdeded7d721d9bbac2305fda.asciidoc
examples/Mapping/Dynamic/TemplatesPage/be51ed37c8425d281a8153abe56b04cb.asciidoc
examples/QueryDsl/QueryStringQueryPage/28aad2c5942bfb221c2bf1bbdc01658e.asciidoc
examples/QueryDsl/QueryStringQueryPage/58b5003c0a53a39bf509aa3797aad471.asciidoc
examples/QueryDsl/QueryStringQueryPage/60ee33f3acfdd0fe6f288ac77312c780.asciidoc
examples/QueryDsl/QueryStringQueryPage/6f21a878fee3b43c5332b81aaddbeac7.asciidoc
examples/QueryDsl/QueryStringQueryPage/81f09836772b03f6e7e8e7986409d67e.asciidoc
examples/QueryDsl/QueryStringQueryPage/a2a25aad1fea9a541b52ac613c78fb64.asciidoc
examples/QueryDsl/QueryStringQueryPage/be1bd47393646ac6bbee177d1cdb7738.asciidoc
examples/QueryDsl/QueryStringQueryPage/db6cba451ba562abe953d09ad80cc15c.asciidoc
examples/QueryDsl/QueryStringQueryPage/e17e8852ec3f31781e1364f4dffeb6d0.asciidoc
examples/QueryDsl/QueryStringQueryPage/f2d68493abd3ca430bd03a7f7f8d18f9.asciidoc
examples/QueryDsl/QueryStringQueryPage/f32f0c19b42de3b87dd764fe4ca17e7c.asciidoc
examples/QueryDsl/QueryStringQueryPage/fdd38f0d248385a444c777e7acd97846.asciidoc
examples/QueryDsl/QueryStringQueryPage/fe1dd67108b04e07d0832b539d4e0d99.asciidoc
examples/Root/AnalysisPage/7ffee3c2a5581994fc0ea59dd106d39f.asciidoc
examples/Root/MappingPage/b311b42b7dcc69821df1f77bfaf2d50d.asciidoc
examples/Root/SearchPage/014b788c879e4aaa1020672e45e25473.asciidoc
examples/Root/SearchPage/189a921df2f5b1fe580937210ce9c1c2.asciidoc
examples/Root/SearchPage/8acc1d67b152e7027e0f0e1a8b4b2431.asciidoc
src/Examples/Examples/Mapping/Dynamic/FieldMappingPage.cs
src/Examples/Examples/Mapping/Dynamic/TemplatesPage.cs
src/Examples/Examples/QueryDsl/QueryStringQueryPage.cs
src/Examples/Examples/ResponseExtensions.cs
src/Examples/Examples/Root/AnalysisPage.cs
src/Examples/Examples/Root/GettingStartedPage.cs
src/Examples/Examples/Root/MappingPage.cs
src/Examples/Examples/Root/SearchPage.cs

This PR adds more docs examples.
It also fixes the way that example diffs are calculated, to take into account that both expected and actual are a list of `JObject`.

more docs examples

---

src/Nest/Document/Multiple/Bulk/BulkOperation/BulkIndex.cs
src/Nest/Document/Multiple/Bulk/BulkOperation/BulkOperationBase.cs
src/Nest/Document/Multiple/Bulk/BulkOperation/BulkOperationsCollection.cs
src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdate.cs
src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdateBody.cs
src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs

Fixes #3943
Requires porting to `master` and `6.x`

Add if_seq_no and if_primary_term to bulk updates.

---

src/Nest/Aggregations/Bucket/DateRange/DateRangeAggregation.cs

Missing method was missing in DateRange Aggregation

feat(date-range-agg): Add Missing method

---

src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
src/Nest/QueryDsl/FullText/CommonTerms/CommonTermsQuery.cs
src/Nest/QueryDsl/FullText/Match/MatchQuery.cs
src/Nest/QueryDsl/Query.cs
src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
src/Nest/QueryDsl/Visitor/QueryVisitor.cs
src/Tests/Tests/QueryDsl/FullText/CommonTerms/CommonTermsUsageTests.cs
src/Tests/Tests/QueryDsl/FullText/Match/MatchUsageTests.cs

Deprecate CommonTerms query and CutoffFrequency of MatchQuery

---

src/Nest/XPack/CrossClusterReplication/Follow/FollowIndexStats/FollowIndexShardStats.cs

Add FollowerAliasesVersion to follow index shard stats

---

src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/DateTimeEpochMillisecondsFormatter.cs
src/Nest/Indices/Monitoring/IndicesRecovery/RecoveryBytes.cs
src/Nest/Indices/Monitoring/IndicesRecovery/RecoveryIndexStatus.cs
src/Nest/Indices/Monitoring/IndicesRecovery/RecoveryVerifyIndex.cs
src/Nest/Indices/Monitoring/IndicesRecovery/ShardRecovery.cs

Addresses the following in #4001 
- Make Recovery API support detailed params http://github.com/elastic/elasticsearch/pull/29076 (issue: http://github.com/elastic/elasticsearch/issues/28910)

Map additional Recovery API response properties.

---

src/Nest/Document/Multiple/Bulk/BulkOperation/BulkIndex.cs
src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdate.cs
src/Tests/Tests.Reproduce/GithubIssue4078.cs
src/Tests/Tests/Document/Multiple/Bulk/BulkInvalidVersionApiTests.cs

Fixes fluent serialization of if_primary_term for BulkIndexDescriptor and BulkUpdateDescriptor

Fix fluent serialization of if_primary_term (#4078)

---

src/Nest/Analysis/CharFilters/PatternReplaceCharFilter.cs
src/Tests/Tests/Analysis/CharFilters/CharFilterTests.cs

Add Flags property, use in tests

---

build/scripts/scripts.fsproj

Thanks very much for testing the RC.

update Bullseye to 3.0.0

---

src/Nest/Analysis/Plugins/Kuromoji/KuromojiTokenizer.cs
src/Tests/Tests/Analysis/Tokenizers/TokenizerTests.cs

Addresses elastic/elasticsearch#45489

Add support for inlined user dictionary in the Kuromoji plugin

---

src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
src/Nest/QueryDsl/Query.cs
src/Nest/QueryDsl/Specialized/Pinned/PinnedQuery.cs
src/Nest/QueryDsl/TermLevel/Ids/IdsQuery.cs
src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
src/Nest/QueryDsl/Visitor/QueryVisitor.cs
src/Nest/QueryDsl/Visitor/QueryWalker.cs
src/Tests/Tests/QueryDsl/Specialized/Pinned/PinnedQueryUsageTests.cs

Addresses elastic/elasticsearch#44345

Search enhancement: pinned queries

---

src/Nest/Search/Suggesters/SuggestOption.cs

Added fields block (docvalue_fields) to SuggestOption #4148

---

src/Tests/Tests/XPack/MachineLearning/GetDatafeedStats/GetDatafeedStatsApiTests.cs

TimingStats was introduced in 7.4.0

Ignore TimingStats object if version < 7.4.0

---

readme.md

Fix typo in readme.md - Candidate for smallest pull request

Fix typo in readme.md - Candidate for smallest pull request

---

build/scripts/Releasing.fs
build/scripts/Testing.fs
build/scripts/scripts.fsproj
contributing.md
readme.md
src/CodeGeneration/ApiGenerator/Domain/RestApiSpec.cs
src/CodeGeneration/ApiGenerator/Domain/Specification/UrlInformation.cs
src/Elasticsearch.Net/ConnectionPool/StaticConnectionPool.cs
src/Elasticsearch.Net/Serialization/LowLevelRequestResponseSerializer.cs
src/Nest/Aggregations/AggregateFormatter.cs
src/Nest/CommonAbstractions/Extensions/Extensions.cs
src/Nest/CommonAbstractions/SerializationBehavior/DefaultHighLevelSerializer.cs
src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/SingleOrEnumerableFormatter.cs
src/Nest/CommonAbstractions/Union/UnionFormatter.cs
src/Nest/CommonOptions/DateMath/DateMath.cs
src/Nest/CommonOptions/TimeUnit/Time.cs
src/Nest/Document/Single/Create/ElasticClient-Create.cs
src/Nest/Document/Single/TermVectors/TermVectorsResponse.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/GetRepository/GetRepositoryResponse.cs
src/Nest/Nest.csproj
src/Nest/Search/Search/Hits/Hit.cs
src/Nest/XPack/Watcher/Input/ChainInput.cs
src/Tests/Tests.Configuration/ConfigurationLoader.cs
src/Tests/Tests.Configuration/tests.default.yaml
src/Tests/Tests.Core/Tests.Core.csproj
src/Tests/Tests.Domain/Tests.Domain.csproj
src/Tests/Tests/ClientConcepts/Connection/ModifyingDefaultConnection.doc.cs

This PR syncs some of the changes that went into `master` that did not make it into `7.x`. These are mainly stylistic/whitespace changes.
Doing this so that if we do a folder diff mainly functional changes will light up.

Sync 7.x with master

---

src/Elasticsearch.Net/Serialization/Resolvers/ElasticsearchNetFormatterResolver.cs

Static property for formatter instance returned new instance everytime

---

src/Tests/Tests/XPack/Slm/SlmApiTests.cs

Integration test to ensure correct handling of: https://github.com/elastic/elasticsearch/pull/47679

Ensure missing SLM policy is handled by client correctly

---

.ci/run-elasticsearch.sh
.ci/run-repository.sh
.ci/run-tests

So that our repository specifics are in a separate file `run-repository.sh`.
Merging this in as I am by myself this week. @russcam I could use a PS Guru to reflect these changes in Powershell :)

updates the .ci scripts to latest greatest

---

docs/search/request/fields-usage.asciidoc
docs/search/request/highlighting-usage.asciidoc
docs/search/request/inner-hits-usage.asciidoc
docs/search/request/script-fields-usage.asciidoc
docs/search/request/source-filtering-usage.asciidoc
tests/Tests/Search/Request/FieldsUsageTests.cs
tests/Tests/Search/Request/HighlightingUsageTests.cs
tests/Tests/Search/Request/InnerHitsUsageTests.cs
tests/Tests/Search/Request/ScriptFieldsUsageTests.cs
tests/Tests/Search/Request/SourceFilteringUsageTests.cs

[DOCS] [7.x] Fix search request body links (#4296)

---

.ci/run-elasticsearch.ps1
.ci/run-repository.ps1
.ci/run-tests.ps1

Relates: #4301
This commit adds a PowerShell script equivalents to the CI bash scripts

Add run-repository powershell script

---

readme.md

without defining the default index it does not work.
I was struggling for some minutes to make it work.

Improve DefaultIndex documentation

---

docs/client-concepts/high-level/getting-started.asciidoc

ndexResponse should be indexResponse
Signed-off-by: oneoneonepig <peihuachu1112@gmail.com>

Fix possible typo in variable name

---

src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs

Pass base64 encoded API key on Connectionsettings

---

.ci/jobs/elastic+elasticsearch-net+pull-request.yml
.ci/run-elasticsearch.sh

Also introduce pull-requests yaml tests for our repository

Shared CI 1.0.1

---

src/Elasticsearch.Net/Utf8Json/Formatters/DictionaryFormatter.cs
tests/Tests.Core/Serialization/RoundtripperDsl.cs
tests/Tests/Framework/SerializationTests/DictionarySerializationTests.cs

Low level client should sent null for dictionary values.

---

src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
src/Elasticsearch.Net/Connection/HttpConnection.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs

Allow headers to be specified on a per request basis

---

tests/Tests/Search/SearchTemplate/SearchTemplateApiTests.cs

Update our tests to reflect this

[test] Unknown query now returns a different error

---

src/Nest/Analysis/CharFilters/CharFilterFormatter.cs
src/Nest/Analysis/TokenFilters/TokenFilterFormatter.cs
tests/Tests/Analysis/CharFilters/CharFilterTests.cs
tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs

This commit adds the ability to serialize custom ITokenFilter implementations.
Closes #4326

Serialize custom ITokenFilter and ICharFilter implementations

---

src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs
tests/Tests/XPack/Info/XPackInfoApiTests.cs

Relates: #4341, elastic/elasticsearch#48972

Add flattened usage field count

---

src/Nest/XPack/MachineLearning/MachineLearningInfo/MachineLearningInfoResponse.cs
tests/Tests/XPack/MachineLearning/MachineLearningInfo/MachineLearningInfoApiTests.cs

Relates: #4341, elastic/elasticsearch#49545

Add categorization analyzer to defaults on ml info response

---

src/Nest/Cluster/ClusterStats/ClusterNodesStats.cs
tests/Tests/Cluster/ClusterStats/ClusterStatsApiTests.cs

Relates: #4341, elastic/elasticsearch#48485

Add ingest info to Cluster Stats response

---

src/Nest/Aggregations/AggregateJsonConverter.cs
src/Nest/Aggregations/Metric/TopHits/TopHitsAggregate.cs
src/Nest/CommonAbstractions/Fields/FieldValuesJsonConverter.cs
src/Nest/CommonAbstractions/LazyDocument/LazyDocument.cs
src/Nest/CommonAbstractions/LazyDocument/LazyDocumentJsonConverter.cs
src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdate.cs
src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdateBody.cs
src/Nest/Document/Multiple/Bulk/BulkResponseItem/BulkResponseItemBase.cs
src/Nest/Document/Multiple/MultiGet/Response/MultiGetHitJsonConverter.cs
src/Nest/XPack/Sql/QuerySql/SqlValue.cs
src/Tests/Tests/Document/Multiple/Bulk/BulkSourceDeserialize.cs

Implement _source parameter on action and doc lines.
(cherry picked from commit e4c1d35)

Implement _source parameter on action and doc lines (#4339)

---

src/Elasticsearch.Net/Elasticsearch.Net.csproj

Remove 4.6.0-preview3.19128.7 and bump to GA release 4.6.0

Remove pre-release reference for Microsoft.CSharp

---

src/Nest/Modules/SnapshotAndRestore/Repositories/AzureRepository.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/HdfsRepository.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/ReadOnlyUrlRepository.cs
src/Nest/Modules/SnapshotAndRestore/Repositories/S3Repository.cs
tests/Tests.Reproduce/GithubIssue4467.cs

This commit updates the repository settings to deserialize
nullable bool and int values from strings.
Fixes #4467

Deserialize string bool and int repository setting values

---

src/ApiGenerator/Generator/Razor/DescriptorsGenerator.cs
src/ApiGenerator/Generator/Razor/HighLevelClientImplementationGenerator.cs
src/ApiGenerator/Generator/Razor/LowLevelClientImplementationGenerator.cs
src/ApiGenerator/Generator/Razor/RequestParametersGenerator.cs
src/ApiGenerator/Generator/Razor/RequestsGenerator.cs

Delete dependant fles generated by the ApiGenerator before generating them

---

readme.md
src/ApiGenerator/Views/LowLevel/Client/Methods/MethodDocs.cshtml

Add remarks around beta and experimental functionality in the low level client.
Suggest we wait for merge until `7.7.0`

Update readme.md for LLC compatibility

---

docs/query-dsl/specialized/distance-feature/distance-feature-query-usage.asciidoc
src/Nest/QueryDsl/Specialized/DistanceFeature/DistanceFeatureQuery.cs
tests/Tests.Reproduce/GitHubIssue4487.cs
tests/Tests/QueryDsl/Specialized/DistanceFeature/DistanceFeatureQueryUsageTests.cs

Fix distance_feature query serialization

---

src/Nest/XPack/Ilm/Actions/ForceMergeAction.cs

Updates documentation with new capability.

Allow forcemerge in the hot phase for ILM policies

---

src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
src/Elasticsearch.Net/Connection/HandlerTracking/ActiveHandlerTrackingEntry.cs
src/Elasticsearch.Net/Connection/HandlerTracking/ExpiredHandlerTrackingEntry.cs
src/Elasticsearch.Net/Connection/HandlerTracking/LifetimeTrackingHttpMessageHandler.cs
src/Elasticsearch.Net/Connection/HandlerTracking/RequestDataHttpClientFactory.cs
src/Elasticsearch.Net/Connection/HandlerTracking/ValueStopWatch.cs
src/Elasticsearch.Net/Connection/HttpConnection.cs
src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
src/Elasticsearch.Net/Utf8Json/Internal/Emit/ILViewer.cs
tests/Tests.Configuration/tests.default.yaml
tests/Tests.ScratchPad/Program.cs
tests/Tests/ClientConcepts/Connection/HttpConnectionTests.cs
tests/Tests/Framework/EndpointTests/ApiIntegrationTestBase.cs

Allow HttpClient instances to be refreshed periodically (#4673)

---

src/Nest/Analysis/TokenFilters/NgramTokenFilter.cs
tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs

Relates: #4718, elastic/elasticsearch#55432

Add PreserveOriginal to NGramTokenFilter

---

src/Nest/XPack/Transform/PreviewTransform/PreviewTransformRequest.cs
src/Nest/XPack/Transform/PutTransform/PutTransformRequest.cs
src/Nest/XPack/Transform/Transform.cs
src/Nest/XPack/Transform/TransformSettings.cs
src/Nest/XPack/Transform/UpdateTransform/UpdateTransformRequest.cs
tests/Tests/XPack/Transform/TransformApiWithSettingsTests.cs

Relates: #4718, elastic/elasticsearch#54862
Add transform settings to Transform APIs

Add Transform settings

---

docs/query-dsl/term-level/regexp/regexp-query-usage.asciidoc
src/Nest/QueryDsl/TermLevel/Regexp/RegexpQuery.cs
tests/Tests/QueryDsl/TermLevel/Regexp/RegexpQueryUsageTests.cs

Add rewrite to RegExp query

---

tests/Tests.Domain/Project.cs
tests/Tests/XPack/Transform/TransformApiTests.cs

Force stop transform and wait for completion

---

src/Nest/XPack/MachineLearning/OpenJob/OpenJobResponse.cs
src/Nest/XPack/MachineLearning/StartDatafeed/StartDatafeedResponse.cs
tests/Tests/XPack/MachineLearning/OpenJob/OpenJobApiTests.cs
tests/Tests/XPack/MachineLearning/StartDatafeed/StartDatafeedApiTests.cs

Relates: elastic/elasticsearch#55473, #4803

Add assigned node to OpenJob/StartDatafeed response

---

src/Nest/Indices/AliasManagement/Alias/Actions/AliasAdd.cs
src/Nest/Indices/AliasManagement/Alias/Actions/AliasAddOperation.cs
src/Nest/Indices/AliasManagement/Alias/Actions/AliasRemove.cs
src/Nest/Indices/AliasManagement/Alias/Actions/AliasRemoveOperation.cs
src/Nest/Indices/AliasManagement/Alias/Actions/IAliasAction.cs
src/Nest/Indices/AliasManagement/Alias/BulkAliasRequest.cs
tests/Tests/Indices/AliasManagement/Alias/AliasApiTests.cs

This commit adds the aliases and indices options to add and remove alias operations for the bulk alias API.
Closes #4721

Add Indices and Aliases in BulkAlias API

---

docs/client-concepts/high-level/indexing/indexing-documents.asciidoc
docs/high-level.asciidoc
docs/search/scrolling-documents.asciidoc
tests/Tests/ClientConcepts/HighLevel/Indexing/IndexingDocuments.doc.cs
tests/Tests/Search/ScrollingDocuments.doc.cs
tests/Tests/high-level.asciidoc

This PR adds documentation for ScrollAllObservable.
Closes #4694

Add ScrollAllObservable docs

---

src/Elasticsearch.Net/Connection/HandlerTracking/RequestDataHttpClientFactory.cs
src/Elasticsearch.Net/Connection/HttpConnection.cs

Specifically: https://github.com/elastic/elasticsearch-net/pull/4673/files#diff-6c7514b4a5a813d5985444b99a4f7a4fL167

client.Timeout was not being set after refactoring introduced in #4673

---

docs/search/request/highlighting-usage.asciidoc
src/Nest/Search/Search/Highlighting/Highlight.cs
tests/Tests/Search/Request/HighlightingUsageTests.cs

This commit adds a global highlight_query to
highlighter options.
Closes #4862

Add global highlight_query

---

src/Nest/Search/FieldCapabilities/FieldCapabilitiesRequest.cs
tests/Tests/Search/FieldCapabilities/FieldCapabilitiesApiTests.cs

Relates: elastic/elasticsearch#57276

Add index filter to field_caps API

---

src/Nest/Aggregations/AggregateFormatter.cs
src/Nest/Aggregations/Metric/ExtendedStats/ExtendedStatsAggregate.cs
tests/Tests/Aggregations/Metric/ExtendedStats/ExtendedStatsAggregationUsageTests.cs

Relates: elastic/elasticsearch#49782

Add standard deviation / variance sampling to extended stats

---

docs/aggregations.asciidoc
docs/aggregations/pipeline/moving-percentiles/moving-percentiles-aggregation-usage.asciidoc
src/Nest/Aggregations/AggregateDictionary.cs
src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/Pipeline/MovingPercentiles/MovingPercentilesAggregation.cs
src/Nest/Aggregations/Visitor/AggregationVisitor.cs
src/Nest/Aggregations/Visitor/AggregationWalker.cs
tests/Tests/Aggregations/Pipeline/MovingPercentiles/MovingPercentilesAggregationUsageTests.cs

Relates: elastic/elasticsearch#55441

Add moving_percentiles aggregation

---

src/Nest/Analysis/Plugins/Kuromoji/KuromojiTokenizer.cs
tests/Tests/Analysis/Tokenizers/TokenizerTests.cs

Relates: elastic/elasticsearch#57421

Add discard_compound_token to kuromoji tokenizer

---

src/Nest/Indices/AliasManagement/Alias/Actions/AliasRemoveOperation.cs

Relates: elastic/elasticsearch#58100

Add must_exist to alias remove

---

src/Nest/Ingest/Processors/SetProcessor.cs

Relates: elastic/elasticsearch#57030

Add ignore_empty_value to set processor

---

src/ApiGenerator/Configuration/CodeConfiguration.cs
src/Nest/Descriptors.Security.cs
src/Nest/ElasticClient.Security.cs
src/Nest/Requests.Security.cs
src/Nest/XPack/Security/ClearCachedPrivileges/ClearCachedPrivilegesRequest.cs
src/Nest/XPack/Security/ClearCachedPrivileges/ClearCachedPrivilegesResponse.cs
src/Nest/_Generated/ApiUrlsLookup.generated.cs
tests/Tests/XPack/Security/ClearCachedPrivileges/ClearCachedPrivilegesApiTests.cs
tests/Tests/XPack/Security/ClearCachedPrivileges/ClearCachedPrivilegesUrlTests.cs
tests/Tests/XPack/Security/ClearCachedRealms/ClearCachedRealmsApiTests.cs

Relates: elastic/elasticsearch#55836
Derive ClearCachedRealmsResponse from NodesResponseBase to
expose NodeStatistics.

Add security.clear_cached_privileges API

---

src/Nest/XPack/Transform/Pivot/GeoTileGridGroupSource.cs
src/Nest/XPack/Transform/Pivot/SingleGroupSource.cs
tests/Tests/XPack/Transform/TransformApiTests.cs

Relates: elastic/elasticsearch#56514

Add geotile_grid transform group by

---

src/Nest/XPack/MachineLearning/Job/Config/ModelPlotConfig.cs

Relates: elastic/elasticsearch#57539

Add annotations_enabled to model config

---

.editorconfig

Fixes #4998 by removing invalid severity values.

Fix formatting conventions.

---

docs/client-concepts/troubleshooting/deprecation-logging.asciidoc
src/Nest/XPack/Info/XPackInfo/XPackInfoResponse.cs
src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs
tests/Tests.Core/Extensions/ClientExtensions.cs
tests/Tests/Aggregations/Bucket/Filters/FiltersAggregationUsageTests.cs
tests/Tests/ClientConcepts/Troubleshooting/DeprecationLogging.doc.cs
tests/Tests/XPack/Info/XPackInfoApiTests.cs
tests/Tests/XPack/Sql/TranslateSql/TranslateSqlQueryApiTests.cs

This commit fixes some of the test assertions for 8.x snapshots.

Fix test assertions

---

src/ApiGenerator/Domain/Specification/UrlPart.cs
src/ApiGenerator/RestSpecification/_Patches/security.clear_api_key_cache.patch.json
src/Elasticsearch.Net/ElasticLowLevelClient.Security.cs
src/Nest/Descriptors.Security.cs
src/Nest/ElasticClient.Security.cs
src/Nest/Requests.Security.cs
src/Nest/XPack/Security/ApiKey/ClearApiKeyCache/ClearApiKeyCacheRequest.cs
src/Nest/XPack/Security/ApiKey/ClearApiKeyCache/ClearApiKeyCacheResponse.cs
src/Nest/_Generated/ApiUrlsLookup.generated.cs
tests/Tests/XPack/Security/ApiKey/SecurityApiKeyTests.cs
tests/Tests/XPack/Security/ApiKey/SecurityApiKeyUrlTests.cs

[Backport master] Support clear api key cache

---

.ci/jobs/elastic+elasticsearch-net+7.11.yml

* Deleted 7.9 YML file
* Added 7.11 YML file

Updated CI jobs

---

build/scripts/Versioning.fs

Backport 1e5b039e8032ce0408a4adc7474cfb9088207a1d from #5163

[Backport 7.11] Update with additional sdk version properties

---

src/DocGenerator/DocGenerator.csproj
src/DocGenerator/Documentation/Blocks/BlockCallOutHelper.cs
src/DocGenerator/Documentation/Blocks/CSharpBlock.cs
src/DocGenerator/Documentation/Blocks/JavaScriptBlock.cs
src/DocGenerator/Walkers/Constants.cs
src/DocGenerator/Walkers/JsonCallOutHelper.cs
src/DocGenerator/Walkers/UsageTestsWalker.cs

Backport 530f156698e896db18cdd038ddb1d5a6e4a37d41 from #5115

[Backport 7.11] Support call outs in JSON (JavaScript) blocks.

---

tests/Tests.YamlRunner/TestSuiteBootstrap.fs

Causing all the xpack tests to fail.

Fix broken yaml test bootstrap

---

src/Nest/Ingest/Processors/AppendProcessor.cs
tests/Tests/Ingest/ProcessorAssertions.cs

Backport 2b75c5ef1623197dc67a96d37696fcf9007438c8 from #5208

[Backport master] Support allow_duplicates on append processor

---

docs/client-concepts/high-level/mapping/fluent-mapping.asciidoc
docs/high-level.asciidoc
docs/search/searching-runtime-fields.asciidoc
src/Nest/Indices/MappingManagement/PutMapping/PutMappingRequest.cs
src/Nest/Mapping/RuntimeFields/RuntimeFields.cs
src/Nest/Mapping/TypeMapping.cs
src/Nest/Search/Search/SearchRequest.cs
tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
tests/Tests.Domain/Project.cs
tests/Tests/ClientConcepts/HighLevel/Mapping/FluentMapping.doc.cs
tests/Tests/Search/Search/SearchApiTests.cs
tests/Tests/Search/SearchingRuntimeFields.doc.cs

Backport caa6920c16ecb8a77b6c9d3a406ef829a3415e29 from #5259

[Backport master] Implement runtime fields on searches

---

src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.AsyncSearch.cs
src/Elasticsearch.Net/ElasticLowLevelClient.AsyncSearch.cs
src/Nest/Descriptors.AsyncSearch.cs
src/Nest/ElasticClient.AsyncSearch.cs
src/Nest/Requests.AsyncSearch.cs
src/Nest/XPack/AsyncSearch/AsyncSearch.cs
src/Nest/XPack/AsyncSearch/Delete/AsyncSearchDeleteRequest.cs
src/Nest/XPack/AsyncSearch/Delete/AsyncSearchDeleteResponse.cs
src/Nest/XPack/AsyncSearch/Get/AsyncSearchGetRequest.cs
src/Nest/XPack/AsyncSearch/Get/AsyncSearchGetResponse.cs
src/Nest/XPack/AsyncSearch/Status/AsyncSearchStatusRequest.cs
src/Nest/XPack/AsyncSearch/Status/AsyncSearchStatusResponse.cs
src/Nest/XPack/AsyncSearch/Submit/AsyncSearchSubmitRequest.cs
src/Nest/XPack/AsyncSearch/Submit/AsyncSearchSubmitResponse.cs
src/Nest/_Generated/ApiUrlsLookup.generated.cs
tests/Tests/XPack/AsyncSearch/AsyncSearchApiTests.cs
tests/Tests/XPack/AsyncSearch/Status/AsyncSearchStatusUrlTests.cs

Backport cebf2bd53cdfad124316ec0c53f4e6e0ff5ba786 from #5239

[Backport master] Implement AsyncSearch Status API

---

readme.md

I believe this would make navigating the readme much easier.

Add a table of contents to readme.md

---

readme.md

Backport 0c823cac6f70207cd7f7e4263ebc3442c7441503 from #5235

[Backport 7.11] Add a table of contents to readme.md

---

readme.md

Backport 0c823cac6f70207cd7f7e4263ebc3442c7441503 from #5235

[Backport 7.x] Add a table of contents to readme.md

---

.ci/DockerFile
tests/Tests.YamlRunner/Models.fs
tests/Tests.YamlRunner/OperationExecutor.fs
tests/Tests.YamlRunner/Program.fs
tests/Tests.YamlRunner/TestSuiteBootstrap.fs
tests/Tests.YamlRunner/TestsDownloader.fs
tests/Tests.YamlRunner/TestsRunner.fs

- Updated Dockerfile with Debian certificates issue workaround listed [here](https://github.com/NuGet/Announcements/issues/49#issuecomment-768766265)
- Updated YAML tests to use updated version naming
@Mpdreamz YAML tests seem to run correctly in local testing so hopefully these changes are good!

Update YAML tests and SDK Docker image

---

.ci/DockerFile
tests/Tests.YamlRunner/Models.fs
tests/Tests.YamlRunner/OperationExecutor.fs
tests/Tests.YamlRunner/Program.fs
tests/Tests.YamlRunner/TestSuiteBootstrap.fs
tests/Tests.YamlRunner/TestsDownloader.fs
tests/Tests.YamlRunner/TestsRunner.fs

Backport f78099bb4f4a1709271449a83dbf4e32216955a3 from #5296

[Backport master] Update YAML tests and SDK Docker image

---

.ci/make.sh
.ci/readme.md
.ci/run-repository.ps1
.ci/run-repository.sh
.ci/run-tests.ps1
.ci/test-matrix.yml
appveyor.yml
azure-pipelines.yml

May as well keep these updated since we updated the dockerfile for the YAML tests earlier this week.

Update SDK to latest patch

---

build/scripts/scripts.fsproj
tests/Tests.Configuration/Tests.Configuration.csproj
tests/Tests.Core/Tests.Core.csproj
tests/Tests.Domain/Tests.Domain.csproj

The new packages include a fix for running XPack cluster.

Update abstractions dependencies

---

src/Nest/Ingest/ProcessorFormatter.cs
src/Nest/Ingest/Processors/FingerprintProcessor.cs
src/Nest/Ingest/ProcessorsDescriptor.cs
tests/Tests/Ingest/ProcessorAssertions.cs

Add Fingerprint ingest processor

---

src/Nest/Cluster/ClusterStats/ClusterNodesStats.cs
tests/Tests/Cluster/ClusterStats/ClusterStatsApiTests.cs

Add architecture stats to cluster node stats

---

src/Nest/Ingest/ProcessorFormatter.cs
src/Nest/Ingest/Processors/NetworkDirectionProcessor.cs
src/Nest/Ingest/ProcessorsDescriptor.cs
tests/Tests/Ingest/ProcessorAssertions.cs

Add network direction ingest processor

---

src/Nest/Indices/IndexManagement/RolloverIndex/RolloverConditions.cs
tests/Tests/Indices/IndexManagement/RolloverIndex/RolloverIndexApiTests.cs

Backport 2dbaf16ade2d44c495c2f3d420d606498e63c3e4 from #5353

[Backport master] Add rollover API support for max_primary_shard_size

---

src/Nest/Search/Search/Highlighting/Highlight.cs

Contributes to #5337
Relates to https://github.com/elastic/elasticsearch/pull/67325

Add max_analyzed_offset to highlight

---

docs/aggregations.asciidoc
docs/aggregations/bucket/multi-terms/multi-terms-aggregation-usage.asciidoc
src/Nest/Aggregations/AggregateDictionary.cs
src/Nest/Aggregations/AggregateFormatter.cs
src/Nest/Aggregations/AggregationContainer.cs
src/Nest/Aggregations/Bucket/MultiTerms/MultiTermsAggregate.cs
src/Nest/Aggregations/Bucket/MultiTerms/MultiTermsAggregation.cs
src/Nest/Aggregations/Bucket/MultiTerms/MultiTermsBucket.cs
src/Nest/Aggregations/Bucket/MultiTerms/Term.cs
src/Nest/Aggregations/Bucket/Terms/TermsInclude.cs
src/Nest/Aggregations/Visitor/AggregationVisitor.cs
src/Nest/Aggregations/Visitor/AggregationWalker.cs
tests/Tests/Aggregations/Bucket/MultiTerms/MultiTermsAggregationUsageTests.cs

Add multi terms aggregation

---

docs/query-dsl/specialized/rank-feature/rank-feature-query-usage.asciidoc
src/Nest/QueryDsl/Specialized/RankFeature/RankFeatureQuery.cs
tests/Tests/QueryDsl/Specialized/RankFeature/RankFeatureQueryUsageTests.cs

Add linear function to rank_feature query

---

src/Nest/Aggregations/AggregateFormatter.cs
src/Nest/Aggregations/Metric/ExtendedStats/ExtendedStatsAggregate.cs

Handle "NaN" in sampling fields

---

.ci/make.sh
.github/workflows/unified-release.yml
build/scripts/Targets.fs
build/scripts/scripts.fsproj

- Updates make assemble to produce a zip file
- make sure the zip file is flattened

Fix make assemble to produce zip

---

src/Nest/XPack/Security/Role/GetRole/Role.cs

Add applications to get role response

---

tests/Tests/Search/Search/SearchApiTests.cs

Fixes #5446 by removing the potential for random failures.

Less flaky test assertions

---

.ci/make.sh
build/scripts/Commandline.fs
build/scripts/Targets.fs

Updating to combine with the other items in the client's team skeleton.

Update make.sh with skeleton from clients team

---

src/Nest/Ingest/Processors/ConvertProcessor.cs

Add IP type to convert processor

---

src/Nest/Ingest/Processors/NetworkDirectionProcessor.cs
tests/Tests/Ingest/ProcessorAssertions.cs

Adds support for using the internal_networks_field option.
Contributes to #5584

Support network direction processor additions

---

src/Nest/CommonOptions/Scripting/InlineScript.cs
src/Nest/Mapping/RuntimeFields/RuntimeField.cs
tests/Tests/ClientConcepts/HighLevel/Mapping/FluentMapping.doc.cs
tests/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
tests/Tests/Mapping/RuntimeFields/RuntimeFieldsTests.cs
tests/Tests/Search/Search/SearchApiTests.cs
tests/Tests/Search/SearchingRuntimeFields.doc.cs
tests/Tests/XPack/Transform/TransformApiWithSettingsTests.cs

Backports 8d040472e3479d73c372eddc95f8e876375ed93b from #5546

[Backport master] Update RuntimeField to use IInlineScript

---

tests/Tests.YamlRunner/SkipList.fs

Cherry picked e231721eb40ae0828464539984e57dcd34590a50 from #5615

[Backport 7.13] Skip service accounts YAML tests (#5615)

---

docs/query-dsl.asciidoc
docs/query-dsl/full-text/combined-fields/combined-fields-usage.asciidoc
docs/query-dsl/term-level/terms/terms-query-usage.asciidoc
tests/Tests/QueryDsl/TermLevel/Terms/TermsQueryUsageTests.cs

Fixed the source file for the typo identified in #5715. Includes docs regen.

Fix typo and regen documentation

---

src/Elasticsearch.Net.VirtualizedCluster/packages.lock.json
src/Elasticsearch.Net/Elasticsearch.Net.csproj
src/Elasticsearch.Net/Extensions/NameValueCollectionExtensions.cs
src/Elasticsearch.Net/packages.lock.json
src/Nest.JsonNetSerializer/packages.lock.json
src/Nest/packages.lock.json
tests/Tests.Core/packages.lock.json
tests/Tests.Domain/packages.lock.json
tests/Tests/Extensions/NameValueCollectionExtensionsTests.cs

Backport dff2c6a2d486978c70ad2952e037b6d2edbafa41 from #4952

[Backport 7.x] NameValueCollection.ToQueryString performance optimisation

---

src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
tests/Tests.Reproduce/GitHubIssue5730.cs

Backport e3e477af5e3579752bd1c215ce227eff1087b484 from #5735

[Backport master] Skip MIME type validation when no body

---

src/Nest/Modules/SnapshotAndRestore/Repositories/FileSystemRepository.cs
tests/Tests/Modules/SnapshotAndRestore/Repositories/RepositoryCrudTests.cs

Add readonly property to FS repository settings

---

.ci/run-elasticsearch.ps1
.ci/run-elasticsearch.sh

Backport ff98649afe7eec6b9f95e1ef9d41dc6de035775f from #5764

[Backport master] Disable GeoIP database

---

.editorconfig

Backport d5bb92eaf682fd98648e2a60affcad3ec8e9b570 from #5723

[Backport 7.x] Update editor config naming rules

---

src/Nest/Indices/MappingManagement/GetMapping/GetMappingResponse.cs
src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
src/Nest/Mapping/Types/Core/DenseVector/DenseVectorAttribute.cs
src/Nest/Mapping/Types/Core/DenseVector/DenseVectorProperty.cs
src/Nest/Mapping/Types/FieldType.cs
src/Nest/Mapping/Types/Properties.cs
src/Nest/Mapping/Types/PropertyFormatter.cs
src/Nest/Mapping/Visitor/IMappingVisitor.cs
src/Nest/Mapping/Visitor/IPropertyVisitor.cs
src/Nest/Mapping/Visitor/MappingWalker.cs
src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
src/Nest/Search/FieldCapabilities/FieldCapabilitiesResponse.cs
tests/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
tests/Tests/Mapping/Types/Core/DenseVector/DenseVectorAttributeTests.cs
tests/Tests/Mapping/Types/Core/DenseVector/DenseVectorPropertyTests.cs

Add support for dense vector fields

---

src/Nest/Analysis/Tokenizers/SimplePatternSplitTokenizer.cs
src/Nest/Analysis/Tokenizers/SimplePatternTokenizer.cs
src/Nest/Analysis/Tokenizers/Tokenizers.cs
src/Nest/Indices/Analyze/AnalyzeTokenizersDescriptor.cs
tests/Tests/Analysis/Tokenizers/TokenizerTests.cs

Support simple_pattern and simple_pattern_split tokenizers

---

src/Nest/XPack/MachineLearning/Datafeed/DatafeedStats.cs
src/Nest/XPack/MachineLearning/Datafeed/RunningState.cs

Add running state to data feed stats

---

src/Nest/Cluster/NodesStats/NodeStats.cs

Add IO stats to node stats model

---

src/Nest/Aggregations/Pipeline/GapPolicy.cs

Add keep_values gap policy

---

src/Nest/Analysis/Analyzers/AnalyzerBase.cs

Mark version property on Analyzer as obsolete

---

src/Nest/XPack/CrossClusterReplication/AutoFollow/CreateAutoFollowPattern/CreateAutoFollowPatternRequest.cs
src/Nest/XPack/CrossClusterReplication/AutoFollow/GetAutoFollowPattern/GetAutoFollowPatternResponse.cs

Support index pattern exclusion in CCR AutoFollow

---

src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Sql.cs
src/Elasticsearch.Net/ElasticLowLevelClient.Sql.cs
src/Nest/Descriptors.Sql.cs
src/Nest/ElasticClient.Sql.cs
src/Nest/Requests.Sql.cs
src/Nest/XPack/Sql/Status/SqlSearchStatusRequest.cs
src/Nest/XPack/Sql/Status/SqlSearchStatusResponse.cs
src/Nest/_Generated/ApiUrlsLookup.generated.cs
tests/Tests/XPack/Sql/Status/SqlSearchStatusUrlTests.cs

Manual backport (with clean code gen) of #5856

[master] Support get async SQL search status API

---

src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Sql.cs
src/Elasticsearch.Net/ElasticLowLevelClient.Sql.cs
src/Nest/Descriptors.Sql.cs
src/Nest/ElasticClient.Sql.cs
src/Nest/Requests.Sql.cs
src/Nest/XPack/Sql/Delete/SqlDeleteRequest.cs
src/Nest/XPack/Sql/Delete/SqlDeleteResponse.cs
src/Nest/XPack/Sql/Status/SqlSearchStatusRequest.cs
src/Nest/_Generated/ApiUrlsLookup.generated.cs
tests/Tests/XPack/Sql/Delete/SqlDeleteUrlTests.cs

Manual backport (with clean code-gen) of #5858

[master] Support delete async SQL search API

---

src/Nest/Search/Search/SearchResponse.cs
tests/Tests.Reproduce/GitHubIssue5892.cs

Fix null-ref exception when track total hits is disabled

---

src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
src/Elasticsearch.Net/Transport/Pipeline/UnsupportedProductException.cs
tests/Tests/ClientConcepts/ProductCheckTests.cs

Aligns with the other clients.

Rename InvalidProductException to UnsupportedProductException

---

src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs

https://github.com/elastic/elasticsearch-net/issues/5938

Fix bug with case-sensitive header comparisions

---

src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs

Backports 6727073437d64758ee42549ba5bc6430d488ef03 from #5940

[Backport 7.x] Fix bug with case-sensitive header comparisions

---

docs/client-concepts/connection/function-as-a-service-environments.asciidoc
docs/client-concepts/high-level/getting-started.asciidoc
docs/high-level.asciidoc
tests/Tests/ClientConcepts/Connection/FunctionAsAServiceEnvironments.doc.cs
tests/Tests/ClientConcepts/HighLevel/GettingStarted.doc.cs
tests/Tests/high-level.asciidoc

[Backport 7.x] Add guidance for using client in FaaS environments

---

src/DocGenerator/packages.lock.json
src/Nest.JsonNetSerializer/packages.lock.json
src/Nest/Aggregations/AggregateFormatter.cs
tests/Tests.Benchmarking/BulkBenchmarkTests.cs
tests/Tests.Benchmarking/BulkCreationBenchmarkTests.cs
tests/Tests.Benchmarking/Tests.Benchmarking.csproj
tests/Tests.Benchmarking/packages.lock.json
tests/Tests.ClusterLauncher/packages.lock.json
tests/Tests.Core/packages.lock.json
tests/Tests.Domain/packages.lock.json
tests/Tests.Reproduce/GitHubIssue5962.cs
tests/Tests.Reproduce/packages.lock.json
tests/Tests.ScratchPad/packages.lock.json
tests/Tests/packages.lock.json

Backport 469b0a3736f7a9404d98896431e66a3ef354f0b4 from #5963

[Backport master] Fix AggregateFormatter to read boolean values

---

src/Nest/XPack/AsyncSearch/AsyncSearch.cs

Add missing properties to AsyncSearch response.

---

docs/client-concepts/high-level/getting-started.asciidoc
tests/Tests/ClientConcepts/HighLevel/GettingStarted.doc.cs

- Update connection section of getting started
- Generate updated getting started doc
- Add release notes to index

Update index and add compatibility mode to connection section

---

docs/aggregations/pipeline/average-bucket/average-bucket-aggregation-usage.asciidoc
docs/aggregations/pipeline/bucket-script/bucket-script-aggregation-usage.asciidoc
docs/aggregations/pipeline/bucket-selector/bucket-selector-aggregation-usage.asciidoc
docs/aggregations/pipeline/bucket-sort/bucket-sort-aggregation-usage.asciidoc
docs/aggregations/pipeline/cumulative-sum/cumulative-sum-aggregation-usage.asciidoc
docs/aggregations/pipeline/derivative/derivative-aggregation-usage.asciidoc
docs/aggregations/pipeline/extended-stats-bucket/extended-stats-bucket-aggregation-usage.asciidoc
docs/aggregations/pipeline/max-bucket/max-bucket-aggregation-usage.asciidoc
docs/aggregations/pipeline/min-bucket/min-bucket-aggregation-usage.asciidoc
docs/aggregations/pipeline/moving-average/moving-average-ewma-aggregation-usage.asciidoc
docs/aggregations/pipeline/moving-average/moving-average-holt-linear-aggregation-usage.asciidoc
docs/aggregations/pipeline/moving-average/moving-average-holt-winters-aggregation-usage.asciidoc
docs/aggregations/pipeline/moving-average/moving-average-linear-aggregation-usage.asciidoc
docs/aggregations/pipeline/moving-average/moving-average-simple-aggregation-usage.asciidoc
docs/aggregations/pipeline/moving-function/moving-function-aggregation-usage.asciidoc
docs/aggregations/pipeline/percentiles-bucket/percentiles-bucket-aggregation-usage.asciidoc
docs/aggregations/pipeline/serial-differencing/serial-differencing-aggregation-usage.asciidoc
docs/aggregations/pipeline/stats-bucket/stats-bucket-aggregation-usage.asciidoc
docs/aggregations/pipeline/sum-bucket/sum-bucket-aggregation-usage.asciidoc
docs/client-concepts/high-level/getting-started.asciidoc
tests/Tests/ClientConcepts/HighLevel/GettingStarted.doc.cs

- Update connection section of getting started
- Generate updated docs

[master] Document compatibility mode

---

docs/release-notes/release-notes-7.16.0-generated.asciidoc
src/ApiGenerator/RestSpecification/Core/fleet.msearch.json
src/ApiGenerator/RestSpecification/Core/fleet.search.json
src/ApiGenerator/RestSpecification/Core/nodes.hot_threads.json
src/ApiGenerator/RestSpecification/Core/open_point_in_time.json
src/ApiGenerator/RestSpecification/_Patches/snapshot.cleanup_repository.patch.json
src/Elasticsearch.Net/Api/Enums.Generated.cs
src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Nodes.cs
src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Snapshot.cs
src/Elasticsearch.Net/ElasticLowLevelClient.Fleet.cs
src/Elasticsearch.Net/ElasticLowLevelClient.Snapshot.cs

Fix cleanup repository patch and regen LL code

---

src/Elasticsearch.Net/Connection/HandlerTracking/RequestDataHttpClientFactory.cs

See https://github.com/elastic/elasticsearch-net/issues/6062

Fix timeout for http client (6.x)

---

src/Nest/QueryDsl/Geo/BoundingBox/GeoBoundingBoxQuery.cs
src/Nest/QueryDsl/Geo/Distance/GeoDistanceQuery.cs
src/Nest/QueryDsl/Geo/Polygon/GeoPolygonQuery.cs
tests/Tests/QueryDsl/Geo/BoundingBox/GeoBoundingBoxQueryUsageTests.cs
tests/Tests/QueryDsl/Geo/Distance/GeoDistanceQueryUsageTests.cs
tests/Tests/QueryDsl/Geo/Polygon/GeoPolygonQueryUsageTests.cs

Add IgnoreUnmapped to GeoDistanceQuery, GeoBoundingBoxQuery and GeoPolygon

---

src/Nest/QueryDsl/Geo/BoundingBox/GeoBoundingBoxQuery.cs
src/Nest/QueryDsl/Geo/Distance/GeoDistanceQuery.cs
src/Nest/QueryDsl/Geo/Polygon/GeoPolygonQuery.cs
tests/Tests/QueryDsl/Geo/BoundingBox/GeoBoundingBoxQueryUsageTests.cs
tests/Tests/QueryDsl/Geo/Distance/GeoDistanceQueryUsageTests.cs
tests/Tests/QueryDsl/Geo/Polygon/GeoPolygonQueryUsageTests.cs

* Add IgnoreUnmapped to GeoDistanceQuery, GeoBoundingBoxQuery and GeoPolygonQuery
* Resolve merge conflicts
(cherry picked from commit 5c9eb4b27ae43dc4e2aee7cf72cfab3418fed766)

[Backport 7.17] Add IgnoreUnmapped to GeoDistanceQuery, GeoBoundingBoxQuery and GeoPolygon

---

src/Nest/Mapping/TermVectorOption.cs

Add missing TermVectorOption

---

src/Nest/Indices/Monitoring/IndicesStats/IndexStats.cs
src/Nest/Indices/Monitoring/IndicesStats/ShardTotalStats.cs

Add shard_stats to primary index stats

---

src/Nest/Cluster/NodesStats/AdaptiveSelectionStats.cs

Fix type for AverageResponseTime on node stats response

---

src/Nest/XPack/Security/RoleMapping/Rules/Field/FieldRuleBase.cs
src/Nest/XPack/Security/RoleMapping/Rules/Field/FieldRuleBaseFormatter.cs
src/Nest/XPack/Security/RoleMapping/Rules/Field/UsernameRule.cs
src/Nest/XPack/Security/RoleMapping/Rules/Role/RoleMappingRulesDescriptor.cs
tests/Tests.Reproduce/GitHubIssue5270.cs

Fix username rule when returned as array

---

Directory.Build.props
benchmarks/Benchmarks/packages.lock.json
benchmarks/Profiling/packages.lock.json
build/scripts/packages.lock.json
src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
src/Elastic.Clients.Elasticsearch/packages.lock.json
src/Playground/packages.lock.json
src/PlaygroundV7x/packages.lock.json
tests/Tests.ClusterLauncher/packages.lock.json
tests/Tests.Configuration/packages.lock.json
tests/Tests.Core/packages.lock.json
tests/Tests.Domain/packages.lock.json
tests/Tests/packages.lock.json

Re-enable locked package restores

---

.github/workflows/integration-jobs.yml
.github/workflows/test-jobs.yml

(cherry picked from commit 4175e96d2f0385eab05648cba6ab5af3ad3aecf1)

[Backport 8.0] Re-enable GitHub action cache steps

---

README.md

Hi!
I was checking your contributing guide and found a broken link to it in README.md.

Fix broken link to contributing.md

---

docs/high-level.asciidoc
docs/index.asciidoc
docs/install.asciidoc
docs/installation.asciidoc
docs/intro.asciidoc
docs/introduction.asciidoc
docs/low-level.asciidoc

Backports the following changes to 8.0:
[DOCS] Adds new Intro and Install chapters #6171

[8.0][DOCS] Adds new Intro and Install chapters (#6171)

---

docs/high-level.asciidoc
docs/index.asciidoc
docs/install.asciidoc
docs/installation.asciidoc
docs/intro.asciidoc
docs/introduction.asciidoc
docs/low-level.asciidoc

Backports the following changes to 8.1:
[DOCS] Adds new Intro and Install chapters #6171

[8.1][DOCS] Adds new Intro and Install chapters (#6171)

---

.github/workflows/integration-jobs.yml

(cherry picked from commit 7fe1b82f6c609cdd3108a9e93f514b72e774d0ef)

[Backport 8.0] Enable more CI integration test clusters

---

.github/workflows/integration-jobs.yml

(cherry picked from commit 7fe1b82f6c609cdd3108a9e93f514b72e774d0ef)

[Backport 8.1] Enable more CI integration test clusters

---

tests/Tests/AsyncSearch/AsyncSearchApiTests.cs

(cherry picked from commit 3af78aad2f2788591bc71bc802be2d64b84b5442)

[Backport 8.0] Re-enable async search test assertion

---

tests/Tests/AsyncSearch/AsyncSearchApiTests.cs

(cherry picked from commit 3af78aad2f2788591bc71bc802be2d64b84b5442)

[Backport 8.1] Re-enable async search test assertion

---

docs/connecting.asciidoc
docs/high-level.asciidoc
docs/index.asciidoc

This PR backports the following changes to the 8.1 branch: 
[DOCS] Adds Connecting section to docs #6183

[8.1][DOCS] Adds Connecting section to docs (#6183)

---

docs/client-concepts/high-level/mapping/parent-child-relationships.asciidoc
docs/connecting.asciidoc
docs/install.asciidoc

Update connecting guide to document pre-release packages

---

src/Nest/Ingest/Processors/SetProcessor.cs

Add CopyFrom to SetProcessor

---

.github/workflows/test-jobs.yml

Fix nuget cmd after SDK update

---

benchmarks/Benchmarks/Program.cs

Tweak benchmark setup

---

src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient-Manual.cs
src/Elastic.Clients.Elasticsearch/Common/Infer/JoinFieldConverter.cs
src/Elastic.Clients.Elasticsearch/Serialization/DefaultRequestResponseSerializer.cs
src/Elastic.Clients.Elasticsearch/Serialization/DefaultSourceSerializer.cs
src/Elastic.Clients.Elasticsearch/Types/Mapping/Properties.cs
src/PlaygroundV7x/Person.cs
src/PlaygroundV7x/Program.cs
tests/Tests.Configuration/tests.default.yaml
tests/Tests/ClientConcepts/HighLevel/Mapping/AutoMap.doc.cs
tests/Tests/ClientConcepts/HighLevel/Mapping/ParentChildRelationships.doc.cs
tests/Tests/Tests.csproj

Complete JoinFieldConverter

---

docs/configuration.asciidoc
docs/high-level.asciidoc
docs/index.asciidoc

This PR adds a `Configuration` section to the .NET docs with some configuration options.

[DOCS] Adds Configuration section to the client docs

---

src/Nest/Document/Multiple/ReindexOnServer/ReindexDestination.cs
tests/Tests/Indices/IndexTemplates/IndexTemplateApiTests.cs

Add missing data attribute to pipeline on ReindexDestiation

---

global.json

Fix global.json version

---

benchmarks/Profiling/Program.cs
src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient-BulkAll.cs
src/Elastic.Clients.Elasticsearch/Helpers/BlockingSubscribeExtensions.cs
src/Elastic.Clients.Elasticsearch/Helpers/BulkAllObservable.cs
src/Elastic.Clients.Elasticsearch/Helpers/BulkAllObserver.cs
src/Elastic.Clients.Elasticsearch/Helpers/BulkAllRequest.cs
src/Elastic.Clients.Elasticsearch/Helpers/BulkAllResponse.cs
src/Elastic.Clients.Elasticsearch/Helpers/CoordinatedRequestDefaults.cs
src/Elastic.Clients.Elasticsearch/Helpers/CoordinatedRequestObserverBase.cs
src/Elastic.Clients.Elasticsearch/Helpers/HelperIdentifiers.cs
src/Elastic.Clients.Elasticsearch/Helpers/IBulkAllRequest.cs
src/Elastic.Clients.Elasticsearch/Helpers/IHelperCallable.cs
src/Elastic.Clients.Elasticsearch/Helpers/PartitionHelper.cs
src/Elastic.Clients.Elasticsearch/Helpers/ProducerConsumerBackPressure.cs
src/Elastic.Clients.Elasticsearch/Helpers/RequestMetaDataExtensions.cs
src/Elastic.Clients.Elasticsearch/Helpers/RequestMetaDataFactory.cs
src/Elastic.Clients.Elasticsearch/Helpers/RequestParametersExtensions.cs
tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
tests/Tests.Core/ManagedElasticsearch/NodeSeeders/TimeSeriesSeeder.cs
tests/Tests/ClientConcepts/HighLevel/Indexing/IndexingDocuments.doc.cs
tests/Tests/Document/Multiple/BulkAll/BulkAllCancellationTokenApiTests.cs
tests/Tests/Document/Multiple/BulkAll/BulkAllDeallocationApiTests.cs
tests/Tests/Document/Multiple/BulkAll/BulkAllDisposeApiTests.cs
tests/Tests/Document/Multiple/BulkAll/BulkOnErrorApiTests.cs

Remove helpers namespace

---

build/scripts/packages.lock.json
build/scripts/scripts.fsproj
src/Elastic.Clients.Elasticsearch.JsonNetSerializer/Elastic.Clients.Elasticsearch.JsonNetSerializer.csproj
src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
src/Playground/packages.lock.json
tests/Tests.ClusterLauncher/packages.lock.json
tests/Tests.Core/packages.lock.json
tests/Tests.Domain/Tests.Domain.csproj
tests/Tests.Domain/packages.lock.json
tests/Tests/packages.lock.json

Respond to https://github.com/advisories/GHSA-5crp-9r3c-p9vr

Bump newtonsoft dependency to 13.0.1 to respond to vulnerability

---

tests/Tests.ClusterLauncher/packages.lock.json
tests/Tests.Configuration/Tests.Configuration.csproj
tests/Tests.Configuration/packages.lock.json
tests/Tests.Configuration/tests.default.yaml
tests/Tests.Core/Tests.Core.csproj
tests/Tests.Core/packages.lock.json
tests/Tests.Domain/Tests.Domain.csproj
tests/Tests.Domain/packages.lock.json
tests/Tests/Tests.csproj
tests/Tests/packages.lock.json

Bump abstractions package versions

---

.github/workflows/integration-jobs.yml

Update release matrix for integration tests

---

src/Elastic.Clients.Elasticsearch/Common/DateTime/DateMath/DateMath.cs
src/Elastic.Clients.Elasticsearch/Common/DateTime/DateMath/DateMathExpression.cs
src/Elastic.Clients.Elasticsearch/Common/DateTime/DateMath/DateMathOperation.cs
src/Elastic.Clients.Elasticsearch/Common/DateTime/DateMath/DateMathTime.cs
src/Elastic.Clients.Elasticsearch/Common/DateTime/DateMath/DateMathTimeUnit.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/FieldDateMath.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/MappingCharFilter.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/DateRangeQuery.g.cs
tests/Tests.Configuration/EnvironmentConfiguration.cs
tests/Tests.Configuration/TestConfigurationBase.cs
tests/Tests.Configuration/YamlConfiguration.cs
tests/Tests/Common/DateTime/DateMath/DateMathExpressions.doc.cs
tests/Tests/Common/DateTime/DateMath/DateMathTests.cs
tests/Tests/Tests.csproj

- Port DateMath and related types
- Updated code-gen to use DateMath alias
- Add tests and fix serialization

Port DateMath and update codegen

---

src/Elastic.Clients.Elasticsearch/Serialization/SingleOrManySerializationHelper.cs

Avoid double emuneration for SingleOrMany serialization

---

.github/ISSUE_TEMPLATE/bug-report-for-version-6-x-and-below.md
.github/ISSUE_TEMPLATE/bug-report-for-version-7-x.md
.github/ISSUE_TEMPLATE/bug-report-for-version-8-x.md
.github/workflows/integration-jobs.yml

- Update integration job test matrix
- Update GH issue templates

Update issue templates and test matrix

---

.ci/test-matrix.yml
.github/workflows/integration-jobs.yml

Update CI versions [8.3]

---

.ci/test-matrix.yml
.github/workflows/integration-jobs.yml

Update CI versions [8.2]

---

.ci/test-matrix.yml
.github/workflows/integration-jobs.yml

Update CI versions [8.1]

---

.ci/test-matrix.yml
.github/workflows/integration-jobs.yml

Update CI versions [8.0]

---

tests/Tests.ClusterLauncher/packages.lock.json
tests/Tests.Core/Tests.Core.csproj
tests/Tests.Core/packages.lock.json
tests/Tests/Tests.csproj
tests/Tests/packages.lock.json

Update test dependencies

---

docs/install.asciidoc

Backports #6558 from ebde26a32101cc2cc6cf8006f594bfcea06f3d21

[Backport main] Command line to add package is incorrect.

---

.gitignore
docs/client-concepts/connection-pooling/exceptions/unrecoverable-exceptions.asciidoc
docs/client-concepts/high-level/getting-started.asciidoc
docs/configuration.asciidoc
docs/high-level.asciidoc
docs/index.asciidoc
docs/redirects.asciidoc
docs/release-notes/breaking-change-policy.asciidoc
docs/release-notes/release-notes-8.0.0.asciidoc
docs/release-notes/release-notes.asciidoc

[8.0] Sync docs with main

---

src/Elastic.Clients.Elasticsearch/Serialization/DefaultRequestResponseSerializer.cs
src/Elastic.Clients.Elasticsearch/Serialization/DefaultSourceSerializer.cs
src/Elastic.Clients.Elasticsearch/Serialization/PropertyNameConverter.cs
src/Elastic.Clients.Elasticsearch/Serialization/SettingsJsonConverter.cs
src/Elastic.Clients.Elasticsearch/Types/Mapping/PropertyBase.cs
tests/Tests/Serialization/Mapping/PropertiesSerializationTests.cs
tests/Tests/Serialization/SerializerTestBase.cs
tests/Tests/_VerifySnapshots/PropertiesSerializationTests.CanSerialize_MultipleProperties_WithPropertyNameExpression.verified.txt
tests/Tests/_VerifySnapshots/PropertiesSerializationTests.CanSerialize_Properties_WithPropertyNameExpression.verified.txt

- Implement properties serialization
- Add properties serialization tests

Fix properties serialization

---

docs/connecting.asciidoc
docs/index.asciidoc
docs/redirects.asciidoc

This PR removes the outdated/not-relevant pages from the .NET documentation book. The content will be rewritten to align with the new .NET client API.

[DOCS] Removes outdated pages from docs

---

docs/redirects.asciidoc

This PR adds a redirect to the ID "indexing-documents".

[DOCS] Adds redirect to indexing-documents ID

---

docs/redirects.asciidoc

Backports https://github.com/elastic/elasticsearch-net/pull/6663.

[8.3][DOCS] Backports redirects

---

docs/redirects.asciidoc

Backports https://github.com/elastic/elasticsearch-net/pull/6663.

[8.1][DOCS] Backports redirects

---

docs/redirects.asciidoc

Backports https://github.com/elastic/elasticsearch-net/pull/6663.

[8.2][DOCS] Backports redirects

---

docs/redirects.asciidoc

Backports https://github.com/elastic/elasticsearch-net/pull/6663.

[8.0][DOCS] Backports redirects

---

docs/examples.asciidoc
docs/index.asciidoc

[DOCS] Adds Examples section to .NET docs

---

src/Elastic.Clients.Elasticsearch/Serialization/StringAliasConverter.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.NoNamespace.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Highlight.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/HighlightField.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/InlineScript.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/LanguageContext.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Security/RoleTemplateInlineScript.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/StoredScript.g.cs

Generates open enumerations as a struct wrapping a string.

Improvements for open enumeration types

---

src/Elastic.Clients.Elasticsearch/Common/UrlParameters/TaskId/TaskId.cs
src/Elastic.Clients.Elasticsearch/_Generated/Api/ClearScrollRequest.g.cs
tests/Tests.Configuration/tests.default.yaml
tests/Tests.Core/ManagedElasticsearch/Clusters/ReindexCluster.cs
tests/Tests/AsyncSearch/AsyncSearchApiTests.cs
tests/Tests/Document/Multiple/DeleteByQuery/DeleteByQueryApiTests.cs
tests/Tests/Document/Multiple/DeleteByQuery/DeleteByQueryUrlTests.cs
tests/Tests/Document/Multiple/DeleteByQueryRethrottle/DeleteByQueryRethrottleApiTests.cs
tests/Tests/Document/Multiple/DeleteByQueryRethrottle/DeleteByQueryRethrottleUrlTests.cs
tests/Tests/Search/Scroll/ClearScroll/ClearScrollApiTests.cs
tests/Tests/Search/Scroll/ClearScroll/ClearScrollUrlTests.cs
tests/Tests/Search/Scroll/Scroll/ScrollApiTests.cs
tests/Tests/Search/Scroll/Scroll/ScrollUrlTests.cs
tests/Tests/Search/Scroll/Scroll/SlicedScrollSearchApiTests.cs

Port some missing unit and integration tests.

Add more integration and unit tests

---

.github/workflows/backport.yml

Updating as per the deprecation warning and recommendations in https://github.com/actions/runner-images/issues/6002

Update ubuntu version for backport action

---

.editorconfig
src/Elastic.Clients.Elasticsearch/Helpers/BulkAllObservable.cs
tests/Tests/Document/Multiple/BulkAll/BulkAllForEachAsyncApiTests.cs
tests/Tests/Document/Multiple/BulkAll/BulkAllRetryTests.cs

Fixes #6647
Will manually port this to `7.17` once this is merged.

Fix dropped doc callback for retried docs

---

src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/CombinedFieldsQuery.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/LikeDocument.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/MoreLikeThisQuery.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/QueryStringQuery.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/SimpleQueryStringQuery.g.cs

Prefer Fields type over IEnumerable<Field>

---

src/Elastic.Clients.Elasticsearch/Client/IndicesNamespace.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.AsyncSearch.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Cluster.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Eql.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Indices.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Sql.g.cs
tests/Tests/Document/Multiple/DeleteByQuery/DeleteByQueryApiTests.cs
tests/Tests/Document/Multiple/DeleteByQueryRethrottle/DeleteByQueryRethrottleApiTests.cs

This simplifies a common user scenario.

Add shortcut client methods for indices refresh

---

docs/index.asciidoc

[DOCS] Remove NEST breaking changes from index

---

benchmarks/Benchmarks/packages.lock.json
benchmarks/Profiling/packages.lock.json
src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
src/Elastic.Clients.Elasticsearch/Api/SearchRequest.cs
src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient.cs
src/Elastic.Clients.Elasticsearch/Core/Request/ApiUrls.cs
src/Elastic.Clients.Elasticsearch/Core/Request/Request.cs
src/Elastic.Clients.Elasticsearch/Core/Request/UrlLookup.cs
src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
src/Elastic.Clients.Elasticsearch/Helpers/BulkAllObservable.cs
src/Elastic.Clients.Elasticsearch/packages.lock.json
src/Playground/packages.lock.json
tests/Tests.ClusterLauncher/packages.lock.json
tests/Tests.Core/Client/TestClient.cs
tests/Tests.Core/ManagedElasticsearch/Clusters/OpenTelemtryCluster.cs
tests/Tests.Core/packages.lock.json
tests/Tests.Domain/packages.lock.json
tests/Tests/ClientConcepts/OpenTelemetry/ActivityTest.cs
tests/Tests/ClientConcepts/OpenTelemetry/OpenTelemetryActivityTest.cs
tests/Tests/Tests.csproj
tests/Tests/packages.lock.json

Respond to Transport changes and support OpenTelemetry

Respond to Transport changes and support OpenTelemetry

---

docs/release-notes/release-notes-8.0.0.asciidoc
docs/release-notes/release-notes.asciidoc
docs/troubleshooting.asciidoc

Add 8.0 release notes

---

docs/release-notes/release-notes-8.0.1.asciidoc
src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/Buckets.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/FieldDateMath.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/Percentiles.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/CharFilter.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/TokenFilter.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/Tokenizer.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/ByteSize.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/MultiGetResponseItem.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/MultiSearchResponseItem.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/SourceConfig.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/SourceConfigParam.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/TrackHits.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Fuzziness.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/GeoHashPrecision.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/Like.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/TermsQueryField.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Script.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Slices.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Tasks/TaskInfos.g.cs

Seal union types for consistency

---

README.md
docs/install.asciidoc
docs/release-notes/release-notes-8.0.0.asciidoc
src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj

Update readme and docs

---

docs/release-notes/release-notes-8.0.1.asciidoc

Fix typos in 8.0.1 release notes

---

docs/install.asciidoc
docs/release-notes/release-notes-8.0.3.asciidoc
docs/release-notes/release-notes.asciidoc

Add release notes for 8.0.3

---

docs/release-notes/breaking-change-policy.asciidoc
docs/release-notes/release-notes-8.0.4.asciidoc
docs/release-notes/release-notes.asciidoc

Add release notes for 8.0.4

---

src/Elastic.Clients.Elasticsearch/Core/UrlParameters/Name/Name.cs
src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/SimulateIndexTemplateRequest.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndexTemplate.g.cs
tests/Tests/IndexManagement/TemplateManagement/GetTemplateResponseSerializationTests.cs

Fix code-gen for IndexTemplate

---

benchmarks/Benchmarks/packages.lock.json
benchmarks/Profiling/packages.lock.json
src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
src/Elastic.Clients.Elasticsearch/packages.lock.json
src/Playground/packages.lock.json
tests/Tests.ClusterLauncher/packages.lock.json
tests/Tests.Core/packages.lock.json
tests/Tests.Domain/packages.lock.json
tests/Tests/packages.lock.json

Bump Elastic.Transport to 0.4.6

---

docs/release-notes/release-notes-8.0.5.asciidoc
docs/release-notes/release-notes.asciidoc

Add release notes for 8.0.5

---

benchmarks/Benchmarks/packages.lock.json
benchmarks/Profiling/packages.lock.json
src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
src/Elastic.Clients.Elasticsearch/packages.lock.json
src/Playground/packages.lock.json
tests/Tests.ClusterLauncher/packages.lock.json
tests/Tests.Core/packages.lock.json
tests/Tests.Domain/packages.lock.json
tests/Tests/packages.lock.json

Update to Elastic.Transport 0.4.7.

---

docs/release-notes/release-notes-8.0.7.asciidoc
docs/release-notes/release-notes.asciidoc

Add release notes for 8.0.7.

---

src/Elastic.Clients.Elasticsearch/Types/QueryDsl/Query.cs
src/Elastic.Clients.Elasticsearch/Types/QueryDsl/QueryDescriptor.cs
src/Elastic.Clients.Elasticsearch/Types/QueryDsl/RangeQuery.cs
src/Elastic.Clients.Elasticsearch/Types/QueryDsl/RawJsonQuery.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/Query.g.cs
tests/Tests/QueryDsl/RawJsonQueryUsageTests.cs
tests/Tests/_VerifySnapshots/RawJsonQueryUsageTests.VerifyDescriptorJson.verified.txt
tests/Tests/_VerifySnapshots/RawJsonQueryUsageTests.VerifyInitializerJson.verified.txt

Add support for raw JSON query.

---

.github/workflows/auto-label.yml
.github/workflows/integration-jobs.yml
.github/workflows/license.yml
.github/workflows/make-bump.yml
.github/workflows/make-codegen.yml
.github/workflows/make-release-notes.yml
.github/workflows/stale-jobs.yml
.github/workflows/test-jobs.yml
.github/workflows/unified-release.yml

Update GitHub action versions in workflows.

---

.github/workflows/auto-label.yml
.github/workflows/integration-jobs.yml
.github/workflows/license.yml
.github/workflows/make-bump.yml
.github/workflows/make-codegen.yml
.github/workflows/make-release-notes.yml
.github/workflows/stale-jobs.yml
.github/workflows/test-jobs.yml
.github/workflows/unified-release.yml

Backport 1aa68e7c4d407d70a903bbde63471e7d02800238 from #7412

[Backport 8.0] Update GitHub action versions in workflows.

---

.github/workflows/auto-label.yml
.github/workflows/integration-jobs.yml
.github/workflows/license.yml
.github/workflows/make-bump.yml
.github/workflows/make-codegen.yml
.github/workflows/make-release-notes.yml
.github/workflows/stale-jobs.yml
.github/workflows/test-jobs.yml
.github/workflows/unified-release.yml

Backport 1aa68e7c4d407d70a903bbde63471e7d02800238 from #7412

[Backport 8.1] Update GitHub action versions in workflows.

---

src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryCacheStats.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/SegmentsStats.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/StoreStats.g.cs

Fix byte properties in index stats types.

---

docs/release-notes/release-notes-8.0.8.asciidoc
docs/release-notes/release-notes.asciidoc

Add release notes for 8.0.8.

---

docs/release-notes/release-notes-8.0.8.asciidoc

Fix release notes for 8.0.8.

---

docs/index-custom-title-page.html

This PR backports the following commits to the `8.0` branch:
* [DOCS] Creates custom landing page for the .NET client book #7503
* [DOCS] Changes hero image to contain .NET logo #7507

[8.0][DOCS] Creates custom landing page for the .NET client book

---

docs/index-custom-title-page.html

This PR backports the following commits to the `8.1` branch:
* [DOCS] Creates custom landing page for the .NET client book #7503
* [DOCS] Changes hero image to contain .NET logo #7507

[8.1][DOCS] Creates custom landing page for the .NET client book

---

docs/index-custom-title-page.html

This PR backports the following commits to the `8.2` branch:
* [DOCS] Creates custom landing page for the .NET client book #7503
* [DOCS] Changes hero image to contain .NET logo #7507

[8.2][DOCS] Creates custom landing page for the .NET client book

---

docs/release-notes/release-notes-8.0.9.asciidoc
docs/release-notes/release-notes.asciidoc

Add release notes for 8.0.9.

---

benchmarks/Benchmarks/packages.lock.json
benchmarks/Profiling/packages.lock.json
src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient.cs
src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
src/Elastic.Clients.Elasticsearch/packages.lock.json
src/Playground/packages.lock.json
tests/Tests.ClusterLauncher/packages.lock.json
tests/Tests.Core/packages.lock.json
tests/Tests.Domain/packages.lock.json
tests/Tests/packages.lock.json

Update to latest transport to ensure ActivitySource is static.

---

docs/release-notes/release-notes-8.0.10.asciidoc
docs/release-notes/release-notes.asciidoc

Add release notes for 8.0.10.

---

.editorconfig
exclusion.dic
src/Elastic.Clients.Elasticsearch/Types/QueryDsl/BoolQueryAndExtensions.cs
src/Elastic.Clients.Elasticsearch/Types/QueryDsl/SearchQuery.cs
tests/Tests/QueryDsl/BoolDsl/AndOperatorUsageTests.cs

 Avoid side effects when combining with And operator

---

src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient.cs

OpenTelemetry tweaks

---

docs/index.asciidoc
docs/install.asciidoc
docs/intro.asciidoc

Documentation improvements for introduction

---

docs/introduction.asciidoc
tests/Tests/Documentation/DocumentationTestBase.cs
tests/Tests/introduction.asciidoc

Update introduction documentation for v7

---

src/Elastic.Clients.Elasticsearch/Api/Sql/QueryResponse.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.AsyncSearch.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Cluster.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.DanglingIndices.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Enrich.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Eql.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Graph.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Indices.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Ingest.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Sql.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Tasks.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs

Backports the latest changes into the main branch, which were missing during the original backporting.

Missing backports for 8.8

---

docs/release-notes/release-notes-8.1.1.asciidoc
docs/release-notes/release-notes.asciidoc

Add release notes for 8.1.1.

---

README.md
docs/getting-started.asciidoc

Backports the following changes to 8.7: [DOCS] Restructures repo README #7843

[8.7][DOCS] Restructures repo README

---

benchmarks/Benchmarks/packages.lock.json
benchmarks/Profiling/packages.lock.json
build/scripts/packages.lock.json
build/scripts/scripts.fsproj
src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
src/Elastic.Clients.Elasticsearch/packages.lock.json
src/Playground/packages.lock.json
tests/Tests.ClusterLauncher/packages.lock.json
tests/Tests.Configuration/Tests.Configuration.csproj
tests/Tests.Configuration/packages.lock.json
tests/Tests.Core/ManagedElasticsearch/Clusters/ClientTestClusterBase.cs
tests/Tests.Core/Tests.Core.csproj
tests/Tests.Core/packages.lock.json
tests/Tests.Domain/Tests.Domain.csproj
tests/Tests.Domain/packages.lock.json
tests/Tests/Tests.csproj
tests/Tests/packages.lock.json

Update `Elastic.*` dependencies

---

src/Elastic.Clients.Elasticsearch/Types/Core/Bulk/BulkUpdateOperation.cs

Fix typing of `BulkUpdateOperation.RetryOnConflict`

---

src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/AsciiFoldingTokenFilter.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/EdgeNGramTokenFilter.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/MultiplexerTokenFilter.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/NGramTokenFilter.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/PatternCaptureTokenFilter.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/WordDelimiterGraphTokenFilter.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/WordDelimiterTokenFilter.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Aggregations.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Analysis.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Cluster.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Core.Search.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Enrich.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Eql.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.IndexManagement.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Ingest.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Mapping.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Ml.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.NoNamespace.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.QueryDsl.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Tasks.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Watcher.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndexSettingsLifecycle.g.cs

Use `Stringified<boolean>` for `preserve_original` and `indexing_complete`

---

src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Aggregations.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Analysis.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Cluster.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Core.Search.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Enrich.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Eql.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.IndexManagement.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Ingest.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Mapping.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Ml.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.NoNamespace.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.QueryDsl.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Tasks.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Watcher.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/SimpleQueryStringQuery.g.cs

Add support for `SimpleQueryStringQuery.flags` property

---

benchmarks/Benchmarks/packages.lock.json
benchmarks/Profiling/packages.lock.json
src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
src/Elastic.Clients.Elasticsearch/packages.lock.json
src/Playground/packages.lock.json
tests/Tests.ClusterLauncher/packages.lock.json
tests/Tests.Core/packages.lock.json
tests/Tests.Domain/packages.lock.json
tests/Tests/Tests.csproj
tests/Tests/packages.lock.json

Contained bug-fixes and improvements:
- https://github.com/elastic/elastic-transport-net/pull/91
- https://github.com/elastic/elastic-transport-net/pull/94

Update `Elastic.Transport` dependency

---

src/Elastic.Clients.Elasticsearch/_Generated/Types/KnnQuery.g.cs

Add `Similarity` to `KnnQuery`

---

src/Elastic.Clients.Elasticsearch.Shared/Types/Ranges.cs

Use JsonPropertyName in Ranges

---

src/Elastic.Clients.Elasticsearch.Shared/Core/RawJsonString.cs
tests/Tests/_VerifySnapshots/ScriptParamsSerializationTests.SerializesRawJson.verified.txt

fixes https://github.com/elastic/elasticsearch-net/issues/8037

Fix RawJsonString serialization

---

src/Elastic.Clients.Elasticsearch.Shared/Api/ScrollResponse.cs
src/Elastic.Clients.Elasticsearch.Shared/Api/SearchResponse.cs
src/Elastic.Clients.Elasticsearch.Shared/Core/Infer/Fields/FieldsConverter.cs
src/Elastic.Clients.Elasticsearch.Shared/Types/AsyncSearch/AsyncSearch.cs
src/Elastic.Clients.Elasticsearch.Shared/Types/MultiSearchItem.cs

Fix incorrect `Total` value for search responses

---

src/Elastic.Clients.Elasticsearch.Shared/Api/ExistsResponse.cs
src/Elastic.Clients.Elasticsearch.Shared/Api/ExistsSourceResponse.cs
src/Elastic.Clients.Elasticsearch.Shared/Api/IndexManagement/ExistsAliasResponse.cs
src/Elastic.Clients.Elasticsearch.Shared/Api/IndexManagement/ExistsIndexTemplateResponse.cs
src/Elastic.Clients.Elasticsearch.Shared/Api/IndexManagement/ExistsResponse.cs
src/Elastic.Clients.Elasticsearch.Shared/Api/IndexManagement/ExistsTemplateResponse.cs

Re-implement `Exists` property

---

src/Elastic.Clients.Elasticsearch.Shared/Types/OpType.cs

Fix serialization of `OpType`

---

src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/Core/MSearch/MultisearchBody.g.cs
src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/Core/MSearch/MultisearchHeader.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/MSearch/MultisearchBody.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/MSearch/MultisearchHeader.g.cs

Fix serialization of `MultisearchBody`/`MultisearchHeader`

---

src/Elastic.Clients.Elasticsearch.Shared/Serialization/UnionConverter.cs

Fix union serialization

---

benchmarks/Benchmarks/packages.lock.json
benchmarks/Profiling/packages.lock.json
src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
src/Elastic.Clients.Elasticsearch.Serverless/Elastic.Clients.Elasticsearch.Serverless.csproj
src/Elastic.Clients.Elasticsearch.Serverless/packages.lock.json
src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
src/Elastic.Clients.Elasticsearch/packages.lock.json
src/Playground/Playground.csproj
src/Playground/packages.lock.json
tests/Tests.ClusterLauncher/packages.lock.json
tests/Tests.Core/packages.lock.json
tests/Tests.Domain/packages.lock.json
tests/Tests/Tests.csproj
tests/Tests/packages.lock.json

Fixes a DoS vulnerability in transient `System.Text.Json` dependency.

Update `Elastic.Transport` to `0.4.20`

---

benchmarks/Benchmarks/packages.lock.json
benchmarks/Profiling/packages.lock.json
src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
src/Elastic.Clients.Elasticsearch.Serverless/Client/ElasticsearchClient.cs
src/Elastic.Clients.Elasticsearch.Serverless/Elastic.Clients.Elasticsearch.Serverless.csproj
src/Elastic.Clients.Elasticsearch.Serverless/packages.lock.json
src/Elastic.Clients.Elasticsearch.Shared/Api/Esql/EsqlQueryRequest.cs
src/Elastic.Clients.Elasticsearch.Shared/Api/Esql/EsqlQueryResponse.cs
src/Elastic.Clients.Elasticsearch.Shared/Client/ElasticsearchClient.Esql.cs
src/Elastic.Clients.Elasticsearch.Shared/Client/NamespacedClientProxy.cs
src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient.cs
src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
src/Elastic.Clients.Elasticsearch/packages.lock.json
src/Playground/Playground.csproj
src/Playground/packages.lock.json
tests/Tests.ClusterLauncher/packages.lock.json
tests/Tests.Core/packages.lock.json
tests/Tests.Domain/packages.lock.json
tests/Tests/Tests.csproj
tests/Tests/packages.lock.json

This is a preparation to support ES|QL results being streamed as Arrow dataframes.

Implement `Esql.QueryAsStreamAsync` helper

---

src/Elastic.Clients.Elasticsearch.Shared/Types/Slices.cs

Fix `Slices` url parameter serialization

---

src/Elastic.Clients.Elasticsearch.Shared/Types/Core/Search/SourceConfigParam.cs

Fix `SourceConfigParam` url parameter serialization

---

src/Elastic.Clients.Elasticsearch/_Shared/Core/Infer/Id/IdResolver.cs

Improve id inference by using culture invariant formatting, if possible.

Improve id inference

---

src/Elastic.Clients.Elasticsearch/_Shared/Serialization/ObjectToInferredTypesConverter.cs

Add `DateTimeOffset` to the known types for `ObjectToInferredTypesConverter`.

Add `DateTimeOffset` to the known types for `ObjectToInferredTypesConverter`

---

.github/workflows/docfx.yml
.github/workflows/docfx_manual.yml
.github/workflows/release_stack.yml
README.md
docs/usage/index.asciidoc

Improve reference documentation.

Improve reference documentation

---

src/Elastic.Clients.Elasticsearch/_Shared/Core/Request/RequestDescriptor.cs

Fix `RequestConfiguration`

---

src/Elastic.Clients.Elasticsearch/_Shared/Core/UrlParameters/Name/Names.cs

Fix serialization of `Names`

---

docs/release-notes/deprecations.md
docs/release-notes/known-issues.md

- Specifies no known issues and deprecations for 9.0.0
- Adds short description to known issues page

[DOCS] Specifies no known issue and deprecations for 9.0.0

---

docs/release-notes/breaking-changes.md
docs/release-notes/index.md
docs/release-notes/known-issues.md
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Cluster.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Indices.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Ml.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Nodes.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.SearchableSnapshots.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Security.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Sql.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.TextStructure.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
src/Elastic.Clients.Elasticsearch/_Shared/Types/QueryDsl/RangeQuery.cs

Address 9.0-preview feedback

---

src/Elastic.Clients.Elasticsearch/_Generated/Api/MachineLearning/GetDataFrameAnalyticsStatsRequest.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Api/MachineLearning/GetDatafeedStatsRequest.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Api/MachineLearning/GetJobStatsRequest.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/RankEval/RankEvalMetricDiscountedCumulativeGain.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/RankEval/RankEvalMetricMeanReciprocalRank.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/RankEval/RankEvalMetricPrecision.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/RankEval/RankEvalMetricRecall.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Search/InnerHits.g.cs
src/Elastic.Clients.Elasticsearch/_Shared/Api/IndexManagement/GetAliasResponse.cs

9.0.1 fixes

---

src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/DeleteTemplateRequest.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/GetTemplateRequest.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/PutTemplateRequest.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Api/Inference/PutJinaaiResponse.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Indices.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Search/ShardProfile.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Inference.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/Snapshot/SnapshotShardFailure.g.cs

Regenerate client

---

src/Elastic.Clients.Elasticsearch/_Generated/Api/DeleteRequest.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Api/ExistsRequest.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Api/ExistsSourceRequest.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Api/ExplainRequest.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Api/GetRequest.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Api/GetSourceRequest.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/DateRangeQuery.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/NumberRangeQuery.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/TermRangeQuery.g.cs
src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/UntypedRangeQuery.g.cs
src/Elastic.Clients.Elasticsearch/_Shared/Api/BulkRequest.cs

Fix `IndexName` ambiguity

---

src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/PercentilesItem.g.cs

[9.1] Regenerate client

---

src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/PercentilesItem.g.cs

[8.19] Regenerate client

---

docs/reference/source-serialization.md

Add documentation for percolated query use case

---

src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Context.Converters.g.cs
src/Elastic.Clients.Elasticsearch/_Shared/Next/JsonReaderExtensions.cs
src/Elastic.Clients.Elasticsearch/_Shared/Next/JsonUnionSelector.cs

Fix deserialization of `Context`
