elastic/elasticsearch-net

- src/Nest/Aggregations/AggregateFormatter.cs
- src/Tests/Tests.Reproduce/GithubIssue4197.cs
This commit deserializes an anonymous bucket that contains only a doc_count. Existing tests cover the case where the bucket has sub-aggregations, but did not handle the case where there are none.
Fixes #4197
> Deserialize anonymous bucket with only doc_count

- docs/client-concepts/connection/configuration-options.asciidoc
- docs/client-concepts/high-level/serialization/extending-nest-types.asciidoc
- docs/high-level.asciidoc
- src/Nest/Mapping/Types/PropertyFormatter.cs
- src/Tests/Tests/ClientConcepts/HighLevel/Serialization/ExtendingNestTypes.doc.cs
- src/Tests/Tests/high-level.asciidoc
This commit fixes the ability to serialize own IProperty types within PropertyFormatter, using utf8json. Initially, this feature was not originally available in utf8json due to how enums with the same underlying values but different field names were serialized, and how this interacts with internal enums of attribute runtime types. Since this is now fixed in #elastic/elasticsearch-net/4032, custom IProperty implementations will now serialize correctly.
Closes #3655 
Closes #4217
> Serialize own IProperty implementations

- docs/client-concepts/connection-pooling/building-blocks/connection-pooling.asciidoc
- docs/client-concepts/connection-pooling/request-overrides/disable-sniff-ping-per-request.asciidoc
- docs/client-concepts/connection-pooling/sniffing/on-stale-cluster-state.asciidoc
- docs/client-concepts/connection/configuration-options.asciidoc
- docs/client-concepts/high-level/mapping/parent-child-relationships.asciidoc
- docs/client-concepts/high-level/serialization/extending-nest-types.asciidoc
- docs/client-concepts/low-level/lifetimes.asciidoc
- docs/client-concepts/low-level/post-data.asciidoc
- docs/common-options/time-unit/time-units.asciidoc
- src/Tests/Tests/ClientConcepts/Connection/ConfigurationOptions.doc.cs
- src/Tests/Tests/ClientConcepts/ConnectionPooling/BuildingBlocks/ConnectionPooling.doc.cs
- src/Tests/Tests/ClientConcepts/ConnectionPooling/RequestOverrides/DisableSniffPingPerRequest.doc.cs
- src/Tests/Tests/ClientConcepts/ConnectionPooling/Sniffing/OnStaleClusterState.doc.cs
- src/Tests/Tests/ClientConcepts/HighLevel/Mapping/ParentChildRelationships.doc.cs
- src/Tests/Tests/ClientConcepts/HighLevel/Serialization/ExtendingNestTypes.doc.cs
- src/Tests/Tests/ClientConcepts/LowLevel/Lifetimes.doc.cs
- src/Tests/Tests/ClientConcepts/LowLevel/PostData.doc.cs
- src/Tests/Tests/CommonOptions/TimeUnit/TimeUnits.doc.cs
I ran a spell check crawler over our docs and fixed up the errors it found.
Port to `master` and `7.4`.
> Fix spelling mistakes.

- contributing.md
- src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
- src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
- src/Nest/Document/Multiple/Bulk/ElasticClient-DeleteMany.cs
- src/Nest/Document/Multiple/Bulk/ElasticClient-IndexMany.cs
- src/Nest/Document/Multiple/MultiGet/ElasticClient-GetMany.cs
- src/Nest/Document/Multiple/MultiGet/ElasticClient-SourceMany.cs
- src/Nest/Document/Single/Index/ElasticClient-Index.cs
- src/Nest/Indices/MappingManagement/PutMapping/ElasticClient-Map.cs
- src/Tests/Tests/XPack/MachineLearning/MachineLearningCluster.cs
This commit replaces the remaining links to elasticsearch.org with their elastic.co counterparts.
Closes #3915
> Replace links to elasticsearch.org with elastic.co

- src/Nest/XPack/Ilm/LifecycleActions.cs
- src/Tests/Tests/XPack/Ilm/IlmApiTests.cs
Fixes #4186
Port to `master` and `7.4`
> Increment count when serialising multiple lifecycle actions.

- build/scripts/Commandline.fs
> reintroduce skipdocs for default build target

- src/Nest/QueryDsl/Geo/GeoLocation.cs
- src/Nest/QueryDsl/Geo/GeoLocationFormatter.cs
- src/Nest/QueryDsl/Geo/Shape/GeoShapeBase.cs
- src/Nest/QueryDsl/Geo/WKT/GeoWKTReader.cs
- src/Tests/Tests/CodeStandards/Serialization/GeoLocationTests.cs
Relates: https://github.com/elastic/elasticsearch/pull/44107
This commit adds support for Well Known Text (WKT) representations for GeoLocation, the type used
to represent geo_point in the client. Similar to WKT support in IGeoShape, an internal format field
is used to store whether an instance was deserialized from JSON or WKT, so that re-serialization
honours the original form deserialized from.
> Add support for WKT with GeoLocation type

- build/scripts/Differ.fs
- build/scripts/Targets.fs
- build/scripts/scripts.fsproj
This commit adds a new build target to diff the release version against the previous version on Nuget, to identify breaking API changes. This new build target is added as a dependent target of the release target.
> Diff release version against previous version from Nuget

- build/Elasticsearch.Net.VirtualizedCluster.nuspec
- build/Elasticsearch.Net.nuspec
- build/NEST.JsonNetSerializer.nuspec
- build/NEST.nuspec
- build/scripts/Commandline.fs
- build/scripts/Releasing.fs
- build/scripts/Tooling.fs
- src/PublishArtifacts.build.props
This commit reinstates sourcelinking of PDB files and including them in nuget packages.
Closes #4095
> Sourcelink and include PDBs in nuget packages

- src/Nest/QueryDsl/Geo/GeoLocation.cs
Relates: https://github.com/elastic/elasticsearch/pull/43893
This commit removes the bound checks on latitude and longitude on GeoLocation (and the derived GeoCoordinate), to allow values outside of the -90 to 90, and -180 to 180 ranges, respecitvely.
> Remove lat lon bound checks from GeoLocation

- build/scripts/Commandline.fs
- build/scripts/Targets.fs
- build/scripts/Testing.fs
Our build scripts allow you to suffix certain targets with `-one` so that they will test one TFM. 
We use this on our CI to minimize run time e.g we have multiple integration tests for each minor, we only run one random TFM per minor on each run. This is a trade-off between full coverage vs sane CI run time.
Our test framework has a lot of randomness as well and decided on a seed when run to ensure we can reproduce failures using the exact same randomness. When tests fail a reproduce line is printed (and surfaced as Github Checks).
This PR now decides the seed in the build scripts so that the randomness in the build script and test framework are both based on the same seed.
> Share random seed between test framework and build scripts

- src/CodeGeneration/ApiGenerator/Configuration/Overrides/Endpoints/SearchOverrides.cs
- src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.NoNamespace.cs
- src/Nest/Descriptors.NoNamespace.cs
- src/Nest/Requests.NoNamespace.cs
- src/Nest/Search/Search/SearchRequest.cs
This ended up on our skip list in `SearchOverrides.cs` in the code generator but other API's already expose it.
> Expose q querystring parameter on search

- src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
When using the low levelclient and asking for a DyamicResponse while the
server is unreachable you would get a NRE
>Unhandled exception. Elasticsearch.Net.UnexpectedElasticsearchClientException: Object reference not set to an instance of an object.
---> System.NullReferenceException: Object reference not set to an instance of an object.
at Elasticsearch.Net.ResponseBuilder.SetSpecialTypes[TResponse](String mimeType, Byte[] bytes, IMemoryStreamFactory memoryStreamFactory, TResponse& cs) in /home/mpdreamz/projects/elastic/net-7/src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs:line 169
This hit the sockets exception as can be seen after applying this fix:
```
Unsuccessful () low level call on GET: /
- [1] BadRequest: Node: http://localhost:9200/ Took: 00:00:00.0657238
---> …
```
> Fix null ref DynamicResponse when host not available

- docs/page_header.html
Explicitly set page_header.html for 6.x so that the default notice can be updated for OOM versions.
Prerequisite for: elastic/docs#1528
> [DOCS] Added older release notice.

- docs/client-concepts/connection-pooling/request-overrides/disable-sniff-ping-per-request.asciidoc
- docs/client-concepts/connection/configuration-options.asciidoc
- docs/client-concepts/connection/modifying-default-connection.asciidoc
- docs/client-concepts/low-level/low-level-response-types.asciidoc
- docs/query-dsl.asciidoc
- docs/query-dsl/full-text/match-bool-prefix/match-bool-prefix-usage.asciidoc
- src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
- src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
- src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
- src/Nest/QueryDsl/Abstractions/Query/QueryDescriptorBase.cs
- src/Nest/QueryDsl/FullText/MatchBoolPrefix/MatchBoolPrefixQuery.cs
- src/Nest/QueryDsl/Query.cs
- src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
- src/Nest/QueryDsl/Visitor/QueryVisitor.cs
- src/Nest/QueryDsl/Visitor/QueryWalker.cs
- src/Tests/Tests/QueryDsl/FullText/MatchBoolPrefix/MatchBoolPrefixUsageTests.cs
This commit adds the MatchBoolPrefix query.
Closes #4247
> Add MatchBoolPrefix query

- src/Nest/Analysis/TokenFilters/Synonym/SynonymGraphTokenFilter.cs
- src/Nest/Analysis/TokenFilters/Synonym/SynonymTokenFilter.cs
- src/Tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs
This commit adds the updateable property to the Synonym and
SynonymGraph token filters.
Closes #4252
> Add updateable property to Synonym token filters

- src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
- src/Nest/Mapping/Types/Properties.cs
- src/Tests/Tests/Mapping/Types/Core/SearchAsYouType/SearchAsYouTypeSingleMappingPropertyTests.cs
- src/Tests/Tests/Mapping/Types/SingleMappingPropertyTestsBase.cs
- src/Tests/Tests/Mapping/Types/Specialized/Generic/GenericPropertyTests.cs
This commit adds Search as you type property configuration to dynamic templates.
Update SingleMappingPropertyTestsBase  to use Writable cluster as it creates a
new index template.
Closes #4249
> Add Search as you type to dynamic templates

- src/Nest/Mapping/Types/PropertyFormatter.cs
This commit updates PropertyFormatter to use the interface type rather than
the type string, to determine how to serialize the IProperty.
Fixes #4248
> Serialize IProperty types based on derived interface type

- build/Elasticsearch.Net.VirtualizedCluster.nuspec
nuspec should use version as lower end so that prereleases can refere…nce it
> Fix Elasticsearch.Net.VirtualCluster lower bound version reference

- src/CodeGeneration/ApiGenerator/Configuration/CodeConfiguration.cs
- src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.SnapshotLifecycleManagement.cs
- src/Elasticsearch.Net/ElasticLowLevelClient.SnapshotLifecycleManagement.cs
- src/Nest/Descriptors.SnapshotLifecycleManagement.cs
- src/Nest/ElasticClient.SnapshotLifecycleManagement.cs
- src/Nest/Requests.SnapshotLifecycleManagement.cs
- src/Nest/XPack/Info/XPackInfo/XPackInfoResponse.cs
- src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs
- src/Nest/XPack/Slm/GetStats/GetSnapshotLifecycleStatsRequest.cs
- src/Nest/XPack/Slm/GetStats/GetSnapshotLifecycleStatsResponse.cs
- src/Nest/_Generated/ApiUrlsLookup.generated.cs
- src/Tests/Tests/XPack/Slm/SlmApiTests.cs
References: https://github.com/elastic/elasticsearch/pull/48096
> Implement Get SLM Stats API

- src/CodeGeneration/ApiGenerator/Generator/ApiEndpointFactory.cs
- src/CodeGeneration/ApiGenerator/RestSpecification/XPack/slm.execute_lifecycle.json
- src/CodeGeneration/ApiGenerator/RestSpecification/_Patches/slm.execute_lifecycle.patch.json
- src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.SnapshotLifecycleManagement.cs
- src/Elasticsearch.Net/ElasticLowLevelClient.SnapshotLifecycleManagement.cs
- src/Nest/ElasticClient.SnapshotLifecycleManagement.cs
- src/Tests/Tests/XPack/Slm/ExecuteLifecycle/ExecuteLifecycleUrlTests.cs
Local patch for implementation in https://github.com/elastic/elasticsearch/pull/47061 and subsequent PR https://github.com/elastic/elasticsearch/pull/49233
> Modify SLM execute lifecycle to use POST method as opposed to PUT.

- src/Elasticsearch.Net/Api/RuntimeInformation.cs
- src/Nest/CrossPlatform/RuntimeInformation.cs
This commit updates the FrameworkDescription logic used to determine
the .NET framework version from the AssemblyFileVersionAttribute on the
assembly containing the base object type to
1. Get all AssemblyFileVersionAttribute attributes
2. order by versioning descending
3. get the first version
This is to workaround an edge case in using this technique to get the
.NET Framework version that appears to affect running an application
under full framework in IIS.
Fixes #4189.
> Get highest AssemblyFileVersionAttribute version

- src/Nest/CommonAbstractions/Extensions/ExpressionExtensions.cs
- src/Nest/CommonAbstractions/Infer/Field/Field.cs
- src/Tests/Tests/ClientConcepts/HighLevel/Caching/FieldResolverCacheTests.cs
- src/Tests/Tests/Tests.csproj
This commit adds support for MemberExpression and specific MethodCallExpression
as Expressions that can be passed to Field and PropertyName, in order to resolve
a string value from the expression.
The specific MethodCallExpression support is to allow F# quotations enclosing
Lambda expressions to be supported, when converted using
Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.QuotationToExpression
Fixes #4240
> Support MemberExpression and specific MethodCallExpression

- src/Nest/Aggregations/Bucket/Composite/CompositeAggregationSource.cs
- src/Nest/Aggregations/Bucket/Composite/GeoTileGridCompositeAggregationSource.cs
- src/Tests/Tests/Aggregations/Bucket/Composite/CompositeAggregationUsageTests.cs
Implements https://github.com/elastic/elasticsearch/pull/45810
> Support geotile_grid aggregation in composite agg sources.

- src/Nest/IndexModules/IndexSettings/Settings/DynamicIndexSettings.cs
- src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsFormatter.cs
- src/Nest/IndexModules/IndexSettings/Settings/UpdatableIndexSettings.cs
- src/Tests/Tests/IndexModules/IndexSettings/Settings/TypedIndexSettings.cs
Implements https://github.com/elastic/elasticsearch/pull/46847
> Add the ability to require an ingest pipeline.

- src/Nest/Cluster/NodesInfo/NodeRole.cs
This commit adds the VotingOnly member to the NodeRole enum, in line
with
https://github.com/elastic/elasticsearch/blob/29f5c2d0ba0405680eb7dee806f9fa2c655932c7/x-pack/plugin/voting-only-node/src/main/java/org/elasticsearch/cluster/coordination/VotingOnlyNodePlugin.java#L63-L68
Fixes #4237
> Add VotingOnly node role

- src/Nest/CommonOptions/DateMath/DateMath.cs
- src/Tests/Tests.Reproduce/GithubIssue4228.cs
- src/Tests/Tests/CommonOptions/DateMath/DateMathTests.cs
This commit updates the ToString() implementation of DateMath to emit a value
when DateTime.MinValue is passed.
Update IsValid property to allow any DateTime to be valid.
Fixes #4228
> DateMath has ToString() value for DateTime.MinValue

- src/CodeGeneration/ApiGenerator/Domain/Specification/QueryParameters.cs
- src/CodeGeneration/ApiGenerator/Generator/CodeGenerator.cs
- src/CodeGeneration/ApiGenerator/Views/HighLevel/Requests/PlainRequestBase.cshtml
- src/CodeGeneration/ApiGenerator/Views/HighLevel/Requests/RequestImplementations.cshtml
- src/CodeGeneration/ApiGenerator/Views/LowLevel/RequestParameters/RequestParameters.cshtml
- src/Elasticsearch.Net/Api/RequestParameters/IRequestParameters.cs
- src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cat.cs
- src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.cs
- src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
- src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
- src/Nest/CommonAbstractions/Request/RequestBase.cs
- src/Nest/Requests.Cat.cs
- src/Tests/Tests.Reproduce/GithubIssue3907.cs
- src/Tests/Tests.Reproduce/GithubIssue4243.cs
- src/Tests/Tests/Cat/CatIndices/CatIndicesApiTests.cs
This commit updates the ApiGenerator to set the Accept HTTP header when the format
header is specified. To determine whether an API call is successful, the Content-Type header
of the response is checked against the Accept header of the request.
The format parameter only really makes sense for the low level client and associated
ElasticsearchResponse<T> types, as the high level client always expects to deserialize
from JSON; any other format will result in an exception at deserialization.
Fixes #4243
> Set Accept header when format set on Cat APIs

- src/CodeGeneration/ApiGenerator/Configuration/Overrides/GlobalOverrides.cs
- src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cat.cs
- src/Nest/Descriptors.Cat.cs
- src/Nest/Requests.Cat.cs
Attached are the diffs from `build.bat release 7.5.0` after this change
[Elasticsearch.Net.txt](https://github.com/elastic/elasticsearch-net/files/3974409/Elasticsearch.Net.txt)
[Nest.txt](https://github.com/elastic/elasticsearch-net/files/3974410/Nest.txt)
> Fix breaking changes on the 7.x branch before release

- src/Tests/Tests/Framework/EndpointTests/CoordinatedIntegrationTestBase.cs
- src/Tests/Tests/Framework/EndpointTests/TestState/CoordinatedUsage.cs
- src/Tests/Tests/XPack/Security/ApiKey/SecurityApiKeyTests.cs
Test to assert server returns a response when no parameters are specified.
Implements https://github.com/elastic/elasticsearch/pull/47274
> Add support to retrieve all API keys if user has privilege.

- src/CodeGeneration/ApiGenerator/Configuration/CodeConfiguration.cs
- src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.CrossClusterReplication.cs
- src/Elasticsearch.Net/ElasticLowLevelClient.CrossClusterReplication.cs
- src/Nest/Descriptors.CrossClusterReplication.cs
- src/Nest/ElasticClient.CrossClusterReplication.cs
- src/Nest/Requests.CrossClusterReplication.cs
- src/Nest/XPack/CrossClusterReplication/AutoFollow/PauseAutoFollowPattern/PauseAutoFollowPatternRequest.cs
- src/Nest/XPack/CrossClusterReplication/AutoFollow/PauseAutoFollowPattern/PauseAutoFollowPatternResponse.cs
- src/Nest/XPack/CrossClusterReplication/AutoFollow/ResumeAutoFollowPattern/ResumeAutoFollowPatternRequest.cs
- src/Nest/XPack/CrossClusterReplication/AutoFollow/ResumeAutoFollowPattern/ResumeAutoFollowPatternResponse.cs
- src/Nest/_Generated/ApiUrlsLookup.generated.cs
- src/Tests/Tests/XPack/CrossClusterReplication/AutoFollow/PauseAutoFollowPattern/PauseAutoFollowPatternUrlTests.cs
- src/Tests/Tests/XPack/CrossClusterReplication/AutoFollow/ResumeAutoFollowPattern/ResumeAutoFollowPatternUrlTests.cs
- src/Tests/Tests/XPack/CrossClusterReplication/CrossClusterReplicationAutoFollowTests .cs
Implements: https://github.com/elastic/elasticsearch/pull/47510
> Add Pause/Resume Auto Follower APIs

- src/Nest/XPack/MachineLearning/Job/Config/Job.cs
- src/Nest/XPack/MachineLearning/PutJob/PutJobRequest.cs
- src/Nest/XPack/MachineLearning/PutJob/PutJobResponse.cs
- src/Nest/XPack/MachineLearning/UpdateJob/UpdateJobRequest.cs
Implements: https://github.com/elastic/elasticsearch/pull/47726
> Add allow_lazy_open to machine learning jobs.

- src/Nest/XPack/MachineLearning/Datafeed/DatafeedConfig.cs
- src/Nest/XPack/MachineLearning/PutDatafeed/PutDatafeedRequest.cs
- src/Nest/XPack/MachineLearning/PutDatafeed/PutDatafeedResponse.cs
- src/Nest/XPack/MachineLearning/UpdateDataFeed/UpdateDatafeedRequest.cs
- src/Nest/XPack/MachineLearning/UpdateDataFeed/UpdateDatafeedResponse.cs
Implements: https://github.com/elastic/elasticsearch/pull/47922
> Add option to stop machine learning datafeed that finds no data.

- src/CodeGeneration/ApiGenerator/Domain/Specification/ApiEndpoint.cs
- src/Elasticsearch.Net/ElasticLowLevelClient.NoNamespace.cs
- src/Elasticsearch.Net/IElasticLowLevelClient.Generated.cs
- src/Tests/Tests/Document/Single/Index/IndexUrlTests.cs
- src/Tests/Tests/Framework/EndpointTests/UrlTests.cs
We used to always send POST which is not right either but the server
accepted it. Now that we have a new format and transform to the old
format in the interim we only picked up PUT for all which is not correct
for index operations without an id.
This bug affects the low level client only, NEST sends the right HttpMethod based on whether an Id is provided or not.
> Fix #4289 low level client index http method generation wrong

- .gitignore
- azure-pipelines.yml
- build/scripts/Commandline.fs
- build/scripts/Documentation.fs
- build/scripts/Paths.fs
- build/scripts/Targets.fs
- build/scripts/Tooling.fs
- src/DocGenerator/AsciiDoc/RawAsciidocVisitor.cs
- src/DocGenerator/Documentation/Files/DocumentationFile.cs
- src/DocGenerator/Documentation/Files/ImageDocumentationFile.cs
- src/DocGenerator/Documentation/Files/RawDocumentationFile.cs
- src/DocGenerator/LitUp.cs
- src/DocGenerator/Program.cs
* Generate to temp location `docs-temp` first
* This folder is gitignored
* Only if generation is succesful swap `docs-temp` to `docs` this will
make `git status` a whole less noisy on generation failures.
* Make sure IncludeFiles references the new `tests/Tests` location
* `breaking-changes` folders are still preserved
* `Litup.Go` should return an exit code
* Call `build.sh documentation` to generate only the docs
* Improve [resilience of calling the documentation generator](https://github.com/elastic/elasticsearch-net/pull/4302#discussion_r362972586) from the command line
* Add azure devops job that fails if a PR has uncommitted documentation changes, which `master` has so [it currently fails on this PR](https://github.com/elastic/elasticsearch-net/pull/4302/checks?check_run_id=37309285 …
> Documentation generation improvements 

- build/scripts/Versioning.fs
- global.json
Calling `build release <version>` would clear `doc_branch` in `global.json` causing all doc files to updated when calling the documentation generator.
> update doc_current and doc_branch when calling release

- src/Elasticsearch.Net/Extensions/ArraySegmentBytesExtensions.cs
- src/Elasticsearch.Net/Utf8Json/Formatters/PrimitiveObjectFormatter.cs
- src/Nest/Aggregations/AggregateFormatter.cs
- tests/Tests.Reproduce/GitHubIssue4285.cs
This commit updates the reading of numeric aggregation keys to read as double only when the byte representation of the value contains a decimal point, and to read it as a long otherwise. This makes the assumption that whole numbers returned are smaller than long.MaxValue. This same assumption is made in PrimitiveObjectFormatter.
Closes #4285
> Read numeric aggs keys as long or double

- docs/client-concepts/low-level/post-data.asciidoc
- src/Elasticsearch.Net/Transport/PostData.cs
- src/Elasticsearch.Net/Transport/SerializableData.cs
- src/Elasticsearch.Net/Transport/StreamableData.cs
- tests/Tests.Benchmarking/BenchmarkProgram.cs
- tests/Tests.Benchmarking/BulkBenchmarkLowLevelTests.cs
- tests/Tests.Benchmarking/BulkBenchmarkTests.cs
- tests/Tests.Benchmarking/Tests.Benchmarking.csproj
- tests/Tests/ClientConcepts/LowLevel/PostData.doc.cs
New types
* `ReadOnlyMemory`, only available in `netstandard2.1` allows you to
post `ReadOnlyMemory<byte>`
* `StreamHandler` allows you to inject a stream handler and write to the
request streams the best way you see fit yourself
Performance
* `PostData.String` now reuses bytes
* `PostData.MultiJson(string[])` uses way less allocations
Benchmarks current PR posting `10.000` objects (many megabytes overal in size) in various ways.
|                       Method |      Mean |    Error |    StdDev |    Median |      Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------- |----------:|---------:|----------:|----------:|-----------:|------:|------:|----------:|
|                ListOfObjects | 449.20 ms | 8.854 ms | 13.785 ms | 447.42 ms | 11000.0000 |     - |     - |  74.89 MB |
| …
> Several improvements to PostData

- src/Elasticsearch.Net/Serialization/DiagnosticsSerializerProxy.cs
- src/Elasticsearch.Net/Serialization/ElasticsearchSerializerExtensions.cs
- src/Elasticsearch.Net/Serialization/IInternalSerializerWithFormatter.cs
- src/Elasticsearch.Net/Serialization/LowLevelRequestResponseSerializer.cs
- src/Elasticsearch.Net/Transport/PostData.cs
- src/Elasticsearch.Net/Utf8Json/IJsonFormatterResolver.cs
- src/Elasticsearch.Net/Utf8Json/Internal/UnsafeMemory.Low.cs
- src/Elasticsearch.Net/Utf8Json/JsonWriter.cs
- src/Elasticsearch.Net/Utf8Json/Resolvers/CompositeResolver.cs
- src/Nest/CommonAbstractions/Extensions/TypeExtensions.cs
- src/Nest/CommonAbstractions/SerializationBehavior/DefaultHighLevelSerializer.cs
- src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/ProxyRequestFormatterBase.cs
- src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/SourceFormatter.cs
- src/Nest/CommonAbstractions/SerializationBehavior/SourceValueWriteConverter.cs
- src/Nest/CommonAbstractions/SerializationBehavior/StatefulSerializerExtensions.cs
- src/Nest/Document/Multiple/Bulk/BulkRequestFormatter.cs
- src/Nest/Search/MultiSearch/MultiSearchFormatter.cs
- src/Nest/Search/MultiSearchTemplate/MultiSearchTemplateJsonConverter.cs
- src/Nest/XPack/MachineLearning/PostJobData/PostJobDataRequest.cs
- tests/Tests.Benchmarking/BulkBenchmarkLowLevelTests.cs
- tests/Tests.Core/Serialization/SerializationTester.cs
Continuation of https://github.com/elastic/elasticsearch-net/pull/4312
Pulling in the bits initially opened here: https://github.com/elastic/elasticsearch-net/pull/4209
Either memory stream or to serialize on the writer.
This consolidates and funnels places that need to write bytes/streams/objects directly.
Prior:
|                       Method |      Mean |     Error |    StdDev |    Median |      Gen 0 |     Gen 1 | Gen 2 | Allocated |
|----------------------------- |----------:|----------:|----------:|----------:|-----------:|----------:|------:|----------:|
|                         NEST | 530.15 ms | 10.534 ms | 13.323 ms | 527.06 ms | 17000.0000 | 4000.0000 |     - | 197.13 MB |
|                ListOfObjects | …
> Additional UTF8Json overloads, consolidate how we tell it to write/serialize.

- docs/client-concepts/low-level/post-data.asciidoc
- src/Elasticsearch.Net/Serialization/DiagnosticsSerializerProxy.cs
- src/Elasticsearch.Net/Serialization/ElasticsearchSerializerExtensions.cs
- src/Elasticsearch.Net/Serialization/IInternalSerializerWithFormatter.cs
- src/Elasticsearch.Net/Serialization/LowLevelRequestResponseSerializer.cs
- src/Elasticsearch.Net/Transport/PostData.cs
- src/Elasticsearch.Net/Transport/SerializableData.cs
- src/Elasticsearch.Net/Transport/StreamableData.cs
- src/Elasticsearch.Net/Utf8Json/IJsonFormatterResolver.cs
- src/Elasticsearch.Net/Utf8Json/Internal/UnsafeMemory.Low.cs
- src/Elasticsearch.Net/Utf8Json/JsonWriter.cs
- src/Elasticsearch.Net/Utf8Json/Resolvers/CompositeResolver.cs
- src/Nest/CommonAbstractions/Extensions/TypeExtensions.cs
- src/Nest/CommonAbstractions/SerializationBehavior/DefaultHighLevelSerializer.cs
- src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/ProxyRequestFormatterBase.cs
- src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/SourceFormatter.cs
- src/Nest/CommonAbstractions/SerializationBehavior/SourceValueWriteConverter.cs
- src/Nest/CommonAbstractions/SerializationBehavior/StatefulSerializerExtensions.cs
- src/Nest/Document/Multiple/Bulk/BulkRequestFormatter.cs
- src/Nest/Search/MultiSearch/MultiSearchFormatter.cs
- src/Nest/Search/MultiSearchTemplate/MultiSearchTemplateJsonConverter.cs
- src/Nest/XPack/MachineLearning/PostJobData/PostJobDataRequest.cs
- tests/Tests.Benchmarking/BenchmarkProgram.cs
- tests/Tests.Benchmarking/BulkBenchmarkLowLevelTests.cs
- tests/Tests.Benchmarking/BulkBenchmarkTests.cs
- tests/Tests.Benchmarking/Tests.Benchmarking.csproj
- tests/Tests.Core/Serialization/SerializationTester.cs
- tests/Tests/ClientConcepts/LowLevel/PostData.doc.cs
> Backport PostData performance fixes and new features

- contributing.md
- readme.md
- src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
- src/Nest/Document/Multiple/MultiGet/Request/MultiGetOperation.cs
Not sure if this needs porting as there are only two code mentions.
> Replace old github organisation (elasticsearch) urls with new organisation (elastic).

- src/Nest/IndexModules/IndexSettings/Settings/DynamicIndexSettings.cs
- src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsFormatter.cs
- src/Nest/IndexModules/IndexSettings/Settings/UpdatableIndexSettings.cs
- tests/Tests/IndexModules/IndexSettings/Settings/TypedIndexSettings.cs
Relates: https://stackoverflow.com/questions/59882293/how-to-set-settings-in-elastic-search-nest-7-x/59889463#59889463
This PR adds a property/method on DynamicIndexSettings and the
respective descriptor to be able to set the index.blocks.read_only_allow_delete
setting.
> Add index setting method for index.blocks.read_only_allow_delete

- src/Nest/CommonAbstractions/SerializationBehavior/GenericJsonConverters/FromJson.cs
- src/Nest/QueryDsl/Abstractions/FieldName/FieldNameQueryJsonConverter.cs
- src/Tests/Tests/QueryDsl/FullText/Match/MatchUsageTests.cs
- src/Tests/Tests/QueryDsl/FullText/MatchPhrase/MatchPhraseUsageTests.cs
- src/Tests/Tests/QueryDsl/FullText/MatchPhrasePrefix/MatchPhrasePrefixUsageTests.cs
- src/Tests/Tests/QueryDsl/QueryDslUsageTestsBase.cs
- src/Tests/Tests/QueryDsl/TermLevel/Prefix/PrefixQueryUsageTests.cs
- src/Tests/Tests/QueryDsl/TermLevel/Term/TermQueryUsageTests.cs
This commit handles the short form of the following queries:
- term query
- match query
- prefix query
- match phrase query
- match phrase prefix query
Closes #2855
> Handle short form queries

- Directory.Build.props
- Directory.Build.targets
- build/scripts/ReposTooling.fs
- docs/client-concepts/connection/configuration-options.asciidoc
- src/DocGenerator/AsciiDoc/GeneratedAsciidocVisitor.cs
- src/Elasticsearch.Net.VirtualizedCluster/Elasticsearch.Net.VirtualizedCluster.csproj
- src/Elasticsearch.Net/Elasticsearch.Net.csproj
- src/Nest.JsonNetSerializer/Nest.JsonNetSerializer.csproj
- src/Nest/Nest.csproj
- tests/Tests/ClientConcepts/HighLevel/GettingStarted.doc.cs
* Fix typo in code that cause the docs stale check to trigger
* GenerateDocumentationFile evaluated and read before
build.targets evaluates we there for need to manually set it on the
projects with intend to publish.
Make sure the doc generator reads this file rather then always forcing
its own xmldocs emit.
(cherry picked from commit 0e739bc119375604d69f72ef573421543c1f1c5a)
> Fix typo in code that cause the docs stale check to trigger (#4343)

- src/Elasticsearch.Net/Responses/Dynamic/DynamicDictionary.cs
Isolated from: #4336
`DynamicDictionary` implemented `IEnumerable<string>` which is not very useful and takes precedence over `IEnumerable<KeyValuePair<,>>`
(cherry picked from commit 0d376ccfd23de6175ce605e3bfe280e7674aa576)
> Change IEnumerable on DynamicDictionary to enumerate over key value pairs

- docs/client-concepts/low-level/low-level-response-types.asciidoc
- src/Elasticsearch.Net/Responses/Dynamic/DynamicValue.cs
- tests/Tests/ClientConcepts/LowLevel/LowLevelResponseTypes.doc.cs
e.g `.Get<string[]>("dataframes.id")` will work even if `dataframes` is a an array of objects. This makes picking values dynamically a ton easier.
(cherry picked from commit 1218888e47afe2147ec787d87fea4a2600c80da4)
Isolated from #4336
> DynamicValue can now dispatch into arrays

- .ci/jobs/elastic+elasticsearch-net+pull-request.yml
- .ci/run-repository.sh
- .ci/test-matrix.yml
- src/Elasticsearch.Net/Responses/ServerException/Error.cs
- tests/Tests.YamlRunner/Commands.fs
- tests/Tests.YamlRunner/DoMapper.fs
- tests/Tests.YamlRunner/Models.fs
- tests/Tests.YamlRunner/OperationExecutor.fs
- tests/Tests.YamlRunner/Program.fs
- tests/Tests.YamlRunner/SkipList.fs
- tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
- tests/Tests.YamlRunner/TestsDownloader.fs
- tests/Tests.YamlRunner/TestsExporter.fs
- tests/Tests.YamlRunner/TestsLocator.fs
- tests/Tests.YamlRunner/TestsReader.fs
- tests/Tests.YamlRunner/TestsRunner.fs
Can now run the `opensource` and `xpack` test suites fully.
- Support catching of do's
- Support stashes in the form of ${var}
- Support feature `headers`
- Support proper skip version ranges
- Test/Teardown now run between test sections
- Per test suite setup
- Support `warnings`
- Introduce `NotSkipped` Execution result to indicate `skip` should continue
- Better proxy detection (only works for for oss on linux)
- TestExported now skips setup/teardown sections
- Summary reports on errors properly
- Support `ignore` parameters
- Make sure export has both DebugInformation and StackTrace info.
------
Originally opened under #4336 but that PR is too big. Split out unrelated commits into their own PR's. However this PR is depending on the features they introduce. Opening this as a draft to …
> Update rest-spec runner to completion

- src/ApiGenerator/Configuration/CodeConfiguration.cs
- src/ApiGenerator/Configuration/GeneratorLocations.cs
- src/ApiGenerator/Domain/RestApiSpec.cs
- src/ApiGenerator/Domain/Specification/ApiEndpoint.cs
- src/ApiGenerator/Generator/ApiGenerator.cs
- src/ApiGenerator/Generator/Razor/DescriptorsGenerator.cs
- src/ApiGenerator/Generator/Razor/HighLevelClientImplementationGenerator.cs
- src/ApiGenerator/Generator/Razor/LowLevelClientImplementationGenerator.cs
- src/ApiGenerator/Generator/Razor/RequestParametersGenerator.cs
- src/ApiGenerator/Generator/Razor/RequestsGenerator.cs
- src/ApiGenerator/Program.cs
- src/ApiGenerator/Views/HighLevel/Client/Implementation/ElasticClient.cshtml
- src/ApiGenerator/Views/HighLevel/Client/Interface/IElasticClient.cshtml
- src/ApiGenerator/Views/HighLevel/Client/Usings.cshtml
- src/ApiGenerator/Views/HighLevel/Requests/ApiUrlsLookup.cshtml
(cherry picked from commit fa60a8ec3b95ebd186ca182eba5d6ce6c0592b7d)
(cherry picked from commit 402c0023fd3bc34cb013f00d003173ec8cdcebef)
backport of https://github.com/elastic/elasticsearch-net/pull/4346
> [7.x] Allow the code generator to generate only the low level client

- src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
- src/Elasticsearch.Net/Connection/HttpConnection.cs
- src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
(cherry picked from commit d29292496a84faf8d11c543b6e56ccb6559d66cd)
(cherry picked from commit efb52ab4ae8b01f881101a365fb915ba67a636df)
backport https://github.com/elastic/elasticsearch-net/pull/4348
> [7.x] Allow headers to be specified on a per request basis (#4348)

- src/Elasticsearch.Net/Serialization/Formatters/DynamicDictionaryFormatter.cs
- tests/Tests.YamlRunner/Models.fs
- tests/Tests.YamlRunner/OperationExecutor.fs
- tests/Tests.YamlRunner/SkipList.fs
- tests/Tests.YamlRunner/TestsReader.fs
(cherry picked from commit cc2682b9067216f2a7a0197c285243530b54878b)
Forward port of part of the backport of #4352 to `7.x`
> Add support for multiple versions in restspec runner

- tests/Tests/Search/SearchTemplate/SearchTemplateApiTests.cs
- tests/Tests/XPack/Slm/SlmApiTests.cs
- A previous fix in 91f446d only works for `latest-7` not previous
versions
- Make SLM assertions on state less rigid
> Fix integration tests in 7.x

- src/Nest/Aggregations/Aggregation.cs
- src/Nest/Aggregations/Metric/Average/AverageAggregation.cs
- src/Nest/Aggregations/Metric/ExtendedStats/ExtendedStatsAggregation.cs
- src/Nest/Aggregations/Metric/Max/MaxAggregation.cs
- src/Nest/Aggregations/Metric/MedianAbsoluteDeviation/MedianAbsoluteDeviationAggregation.cs
- src/Nest/Aggregations/Metric/MetricAggregation.cs
- src/Nest/Aggregations/Metric/Min/MinAggregation.cs
- src/Nest/Aggregations/Metric/PercentileRanks/PercentileRanksAggregation.cs
- src/Nest/Aggregations/Metric/PercentileRanks/PercentileRanksAggregationFormatter.cs
- src/Nest/Aggregations/Metric/Percentiles/PercentilesAggregation.cs
- src/Nest/Aggregations/Metric/Percentiles/PercentilesAggregationFormatter.cs
- src/Nest/Aggregations/Metric/Stats/StatsAggregation.cs
- src/Nest/Aggregations/Metric/Sum/SumAggregation.cs
- src/Nest/Aggregations/Metric/ValueCount/ValueCountAggregation.cs
- tests/Tests/Aggregations/Metric/Min/MinAggregationUsageTests.cs
This commit adds a Format property to metrics aggregations that support it.
Closes #4327
> Add format to metric aggregations that support it

- src/Nest/Document/Multiple/ReindexOnServer/ReindexSource.cs
- tests/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerApiTests.cs
- tests/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerSliceApiTests.cs
Relates: #4341
Deprecate sorting in reindex elastic/elasticsearch#49458 (issue: elastic/elasticsearch#47567)
Closes #4356
> Deprecate sort on ReindexOnServer

- src/Nest/Analysis/Languages/Language.cs
Relates: #4341
This commit adds support for the Estonian language in the
LanguageAnalyzer.
> Add Estonian language analyzer

- src/Nest/Analysis/Tokenizers/TokenizerFormatter.cs
This commit removes the edgengram tokenizer type name, as it is
no longer a valid option:
https://github.com/elastic/elasticsearch/blob/b65e29337d0370ec1c51060c338238eea5a04d80/modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/CommonAnalysisPlugin.java#L246-L252
Closes #4354
> Remove edgengram tokenizer spelling

- src/Nest/XPack/Ilm/Actions/WaitForSnapshotLifecycleAction.cs
- src/Nest/XPack/Ilm/LifecycleActions.cs
Relates: #4341
This commit adds a wait_for_snapshot ILM lifecycle action
> Add WaitForSnapshot ILM lifecycle action

- src/Nest/Ingest/ProcessorFormatter.cs
- src/Nest/Ingest/Processors/CsvProcessor.cs
- src/Nest/Ingest/ProcessorsDescriptor.cs
- tests/Tests/Ingest/ProcessorAssertions.cs
Relates: #4341
This commit adds the Csv processor to the collection of ingest
processors.
> Add Csv processor

- examples/Docs/BulkPage/8cd00a3aba7c3c158277bc032aac2830.asciidoc
- src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdate.cs
- src/Nest/Document/Multiple/Bulk/BulkOperation/BulkUpdateBody.cs
- src/Nest/Document/Multiple/Bulk/BulkResponseItem/BulkResponseItemBase.cs
- tests/Examples/Docs/BulkPage.cs
- tests/Examples/Example.cs
- tests/Examples/ResponseExtensions.cs
- tests/Tests/Document/Multiple/Bulk/BulkSourceDeserialize.cs
The documentation (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) indicates that `_source` is valid on both the action and the doc lines (see the JSON example at the bottom of the page).
```
{ "update" : {"_id" : "3", "_index" : "index1", "_source" : true} }
{ "doc" : {"field" : "value"} }
{ "update" : {"_id" : "4", "_index" : "index1"} }
{ "doc" : {"field" : "value"}, "_source": true}
```
This PR is in draft whilst it is ratified if there is any precendence in parameters being set, or if the parameters are preferred on the action line or doc line.
> Implement _source parameter on action and doc lines.

- src/Nest/Analysis/Tokenizers/NGram/EdgeNGramTokenizer.cs
- src/Nest/Analysis/Tokenizers/NGram/NGramTokenizer.cs
- src/Nest/Analysis/Tokenizers/NGram/TokenChar.cs
- tests/Tests/Analysis/Tokenizers/TokenizerTests.cs
Relates: #4341
This commit adds support for custom token characters for
edgengram and ngram tokenizers.
> Support custom token chars in (edge)ngram tokenizer

- src/Nest/Ingest/Processors/ScriptProcessor.cs
- src/Nest/Modules/SnapshotAndRestore/Repositories/VerifyRepository/VerifyRepositoryResponse.cs
- src/Nest/XPack/MachineLearning/UpdateJob/UpdateJobRequest.cs
- src/Nest/XPack/Watcher/Action/ActionBase.cs
- src/Nest/XPack/Watcher/Action/Actions.cs
- src/Nest/XPack/Watcher/Transform/ScriptTransformBase.cs
- tests/Tests.Reproduce/GitHubIssue4382.cs
- tests/Tests/CodeStandards/Serialization/Formatters.doc.cs
This commit fixes a bug where VerifyRepositoryResponse was attributed
with the wrong formatter type in JsonFormatterAttribute applied at the type level.
Utf8Json's formatters are strongly typed for speed at the cost of less flexibility.
Fix other cases where the incorrect formatter type is used, and introduce a
convention test to assert that types and their properties attributed with
JsonFormatterAttribute use the correct formatter type.
Fixes #4382
> Use correct IJsonFormatter<T> in attributes

- src/Nest/QueryDsl/FullText/Intervals/IntervalsFuzzy.cs
- src/Nest/QueryDsl/FullText/Intervals/IntervalsQuery.cs
- tests/Tests/QueryDsl/FullText/Intervals/IntervalsUsageTests.cs
Relates: #4341
This commit adds support for fuzzy intervals source in
Intervals query
> Add support for fuzzy intervals in interval query

- src/Elasticsearch.Net/Serialization/Formatters/ExceptionFormatter.cs
- tests/Tests.Reproduce/GitHubIssue4294.cs
This commit changes the ExceptionFormatterResolver to return a new instance
of the now generic ExceptionFormatter<TException> for the type of exception.
This fixes a bug where an ExceptionFormatter of type IJsonFormatter<Exception>
is returned for derived exception types, resulting in an InvalidCastException
at runtime.
Formatter instances created are cached in ElasticsearchNetFormatterResolver
for the type T, so will be reused once created.
Fixes #4294
> Create exception formatters for different exceptions

- src/Elasticsearch.Net/Domain/RuntimeInformation.cs
- src/Nest/CrossPlatform/RuntimeInformation.cs
This commit updates the FrameworkDescription logic used to determine
the .NET framework version from the AssemblyFileVersionAttribute on the
assembly containing the base object type to
1. Get all AssemblyFileVersionAttribute attributes
2. order by versioning descending
3. get the first version
This is to workaround an edge case in using this technique to get the
.NET Framework version that appears to affect running an application
under full framework in IIS.
Fixes #4387.
> Get highest AssemblyFileVersionAttribute version (#4387)

- src/Nest/QueryDsl/Specialized/RankFeature/RankFeatureQuery.cs
- tests/Tests/QueryDsl/Specialized/RankFeature/RankFeatureQueryUsageTests.cs
This commit updates the rank_feature query to make function an optional field,
and to omit the JSON value separator when not set
Fixes #4392
> Function is optional for rank_feature query

- src/Nest/XPack/Ilm/ExplainLifecycle/ExplainLifecycleResponse.cs
Relates: #4341, elastic/elasticsearch#48256
This commit adds FailedStepRetryCount and IsAutoRetryableError
properties to ILM explain, applicable if a step fails.
> Add retry count and is retryable to ILM explain

- src/Nest/Document/Multiple/MultiGet/Request/MultiGetRequestFormatter.cs
- src/Nest/Document/Multiple/MultiGet/Request/MultiGetRequestJsonConverter.cs
- src/Nest/Document/Multiple/MultiGet/Response/MultiGetHitJsonConverter.cs
- src/Nest/Document/Multiple/MultiGet/Response/MultiGetResponse.cs
- tests/Tests/Document/Multiple/MultiGet/GetManyApiTests.cs
This commit fixes a bug where a GetMany or SourceMany API call
with a repeated id would return a cartesian product of id and documents.
Take for example the same id repeated 3 times; Elasticsearch will return
3 documents in the response, where each JSON object is a representation
of the same underlying document. Since all 3 documents have the same id,
GetMany and SourceMany would return all 3 documents as a match for the first id,
all 3 as a match for the second id, and so on.
With this fix, For each id, only the first matching document is returned.
One _could_ argue that only a single document should be returned for the same
repeated id. This fix however tries to reflect what is in the
Elasticsearch response.
Fixes #4342
> Return distinct items from GetMany and SourceMany

- docs/aggregations/bucket/terms/terms-aggregation-usage.asciidoc
- docs/search/request/suggest-usage.asciidoc
- docs/search/writing-queries.asciidoc
- src/Nest/Document/Multiple/MultiGet/ElasticClient-GetMany.cs
- src/Nest/Document/Multiple/MultiGet/ElasticClient-SourceMany.cs
- src/Nest/Document/Multiple/MultiGet/Request/MultiGetRequestJsonConverter.cs
- src/Nest/Document/Multiple/MultiGet/Response/MultiGetResponse.cs
- src/Tests/Tests/Document/Multiple/MultiGet/GetManyApiTests.cs
This commit fixes a bug where a GetMany or SourceMany API call
with a repeated id would return a cartesian product of id and documents.
- enumerate only distinct ids when retrieving hits
or source from GetMany and SourceMany, so that the same id input
to either will return only a single document per target index.
- fix a bug in the MultiGetRequestFormatter whereby
the document index is removed when a request index is specified,
without checking whether the document index matches the request index.
Fixes #4342
(cherry-picked from commit 8cbc1fe35d1d3fe618115219e9394ae0f3adc27a)
> Return distinct items from GetMany and SourceMany (#4353)

- src/Nest/XPack/License/GetLicense/GetLicenseResponse.cs
- src/Nest/XPack/License/GetLicense/LicenseType.cs
Relates: #4341, elastic/elasticsearch#49223, elastic/elasticsearch#50735
This commit adds support for Enterprise LicenseType,
and adds max_resource_units to GetLicenseResponse.
> Support Enterprise license type

- src/Nest/IndexModules/IndexSettings/Settings/DynamicIndexSettings.cs
- src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsFormatter.cs
- src/Nest/IndexModules/IndexSettings/Settings/UpdatableIndexSettings.cs
- tests/Tests/IndexModules/IndexSettings/Settings/TypedIndexSettings.cs
Relates: #4341, elastic/elasticsearch#49470
This commit adds final pipeline to index settings and deprecates
required pipeline.
> Add index.final_pipeline index setting

- src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsFormatter.cs
- src/Nest/IndexModules/IndexSettings/SoftDeletes/ISoftDeleteSettings.cs
- tests/Tests/XPack/CrossClusterReplication/CrossClusterReplicationFollowTests.cs
Relates: #4341, elastic/elasticsearch#50502
This commit marks the enabled setting on soft delete index settings
as obsolete, as setting enabled to false is deprecated.
> Deprecate index soft delete enabled setting

- src/Nest/Ingest/Processors/Plugins/GeoIpProcessor.cs
Relates: #4341, elastic/elasticsearch#49573
> Add first_only to geoip processor

- build/scripts/Commandline.fs
- tests/Tests.YamlRunner/Commands.fs
- tests/Tests.YamlRunner/Program.fs
- tests/Tests.YamlRunner/TestsRunner.fs
You can now pass -s "Test section name" to the rest-api-spec test runner
to only run a single test inside a file. Before you could only filter to
a file as whole.
This also makes sure args with spaces are quoted when passing down from
our build tooling (super rudimentary)
We now emit Skip messages during the run so we can see the test itself
skipped. Because in our current flow we run the test setup before
evaluating the `skip` block its hard to see nothing happened because
things are happening (setup requests)
Lastly the proxy detection now includes `xpack` test suite.
`mitmproxy -k` will work if we reroute https traffic to it.
> Ability to only run one test section in file in yaml test runner

- src/Nest/Aggregations/Bucket/GeoHashGrid/GeoHashGridAggregation.cs
- tests/Tests/Aggregations/Bucket/GeoHashGrid/GeoHashGridAggregationUsageTests.cs
Relates: #4341, elastic/elasticsearch#50002
This commit adds support for supplying bounds on a geohash_grid
aggregation, similar to how bounds are supplied on
geo_bounding_box query.
> Add support for bounds in geohash_grid aggregation

- src/Nest/Ingest/Processors/SplitProcessor.cs
Relates: #4341, elastic/elasticsearch#48664
Add the preserve_trailing property to split processor,
which is available in Elasticsearch 7.6.0+
> Add preserve_trailing to Split processor

- tests/Tests/Search/SearchTemplate/SearchTemplateApiTests.cs
This commit updates the version when asserting the error
message for an unknown query
> Update version for SearchTemplate error message

- src/Elasticsearch.Net/Transport/PostData.cs
This commit updates PostData to use the enumerator to
enumerate IEnumerable<string> or IEnumerable<object>,
avoiding enumerating twice, once when checking .Any() and again
when calling foreach.
Closes #4388
> Avoid multiple enumeration of IEnumerable PostData

- tests/Tests.Core/ManagedElasticsearch/Clusters/XPackCluster.cs
- tests/Tests/Ingest/PutPipeline/PutPipelineApiTests.cs
This commit changes the PutPipelineApiTests to use
an X-Pack cluster with security enabled. As part of this change,
the ingest attachment plugin must also be installed. This is deemed a
better compromise than specifying a new cluster type for this test only.
This change also fixes a NPE thrown by set_security_user processor, which
appears to happen when security is disabled. See elastic/elasticsearch#52474
Closes #4385
> Use XPackCluster for PutPipeline API tests

- build/scripts/Testing.fs
- tests/Tests.Core/ManagedElasticsearch/Clusters/XPackCluster.cs
Extend integration test run timeout to 60 minutes. They take longer than 30 minutes on my machine, ~35 minutes.
> Wait for .security index to be green

- src/Nest/CommonAbstractions/SerializationBehavior/Attributes/MachineLearningDateTimeAttribute.cs
- src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/NestFormatterResolver.cs
This commit uses the MachineLearningDateTimeFormatter when
a model property is attributed with MachineLearningDateTimeAttribute.
Without the application of the formatter, an attempt is made to deserialize
a returned timestamp numeric value as a string in PreviewDataFeedApiTests
> Use MachineLearningDateTimeFormatter

- tests/Tests.YamlRunner/Commands.fs
- tests/Tests.YamlRunner/TestSuiteBootstrap.fs
- tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
- tests/Tests.YamlRunner/TestsReader.fs
Before we were not deleting system indices only `.ml-*`
However this started to become an issue because it left closed indices
around. This might be related to .ml indices now being hidden.
Warrants more investigation as the new solution deleting all indices all
the time is definitely a bit slower
> Fix yaml tests not deleting newly defined hidden indices

- src/Nest/Document/Multiple/Bulk/ElasticClient-DeleteMany.cs
- src/Nest/Document/Multiple/MultiGet/ElasticClient-GetMany.cs
- src/Nest/Document/Multiple/MultiGet/ElasticClient-SourceMany.cs
- tests/Tests.Reproduce/GitHubIssue4462.cs
https://github.com/elastic/elasticsearch-net/pull/4353
Fixed an issue with the GetMany helpers that returned the cartesian product of all ids specified rather
then creating a distinct list if more then one index was targeted.
This PR also updated the routine in the serializer to omit the index name from each item if the index is
already specified on the url in case of multiple indices
This updated routine in the `7.6.0` could throw if you are calling:
client.GetMany<T>(ids, "indexName");
Without configuring `ConnectionSettings()` with either a default index for T or a global default index.
> Fix GetMany when no default index is set

- src/Nest/Document/Multiple/Bulk/ElasticClient-DeleteMany.cs
- src/Nest/Document/Multiple/MultiGet/ElasticClient-GetMany.cs
- src/Nest/Document/Multiple/MultiGet/ElasticClient-SourceMany.cs
- src/Tests/Tests.Reproduce/GitHubIssue4462.cs
https://github.com/elastic/elasticsearch-net/pull/4353
Fixed an issue with the GetMany helpers that returned the cartesian product of all ids specified rather
then creating a distinct list if more then one index was targeted.
This PR also updated the routine in the serializer to omit the index name from each item if the index is
already specified on the url in case of multiple indices
This updated routine in the `7.6.0` could throw if you are calling:
client.GetMany<T>(ids, "indexName");
Without configuring `ConnectionSettings()` with either a default index for T or a global default index.
(cherry picked from commit 87c8cdd05ba3ef3818e6cd3444bd71b5de84d443)
> [Backport 6.x] Fix GetMany when no default index is set (#4463)

- src/Nest/Document/Multiple/ReindexOnServer/RemoteSource.cs
- tests/Tests/Document/Multiple/ReindexOnServer/ReindexOnServerRemoteApiTests.cs
Addresses documentation of features here: https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-reindex.html#reindex-from-remote
> Adds socket timeout and connect timeout options to reindex on server.

- src/ExamplesGenerator/AsciiDocParser.cs
- src/ExamplesGenerator/CSharpGenerator.cs
- src/ExamplesGenerator/ReferenceExample.cs
- tests/Examples/Aggregations/Metrics/TopMetricsAggregationPage.cs
- tests/Examples/Analysis/Tokenfilters/TrimTokenfilterPage.cs
- tests/Examples/Ml/AnomalyDetection/Apis/GetJobStatsPage.cs
- tests/Examples/Setup/RestartClusterPage.cs
- tests/Examples/Upgrade/RollingUpgradePage.cs
This commit deduplicates the generated example method names,
when generating C# methods from the examples. The method names
follow the convention of `Line<linenum>`, where `linenum` is the
line number in the alternative report. The alternative report
can report duplicate line numbers however, as reported in
elastic/docs#1760
so deduplicate in the generator.
> Deduplicate example method names

- build/scripts/Paths.fs
- build/scripts/ReleaseNotes.fs
This commit improves the generated release notes by consolidating issues that relate to PRs as part of the PR title, reducing duplication
> Improve generated release notes

- src/Elasticsearch.Net.VirtualizedCluster/Elasticsearch.Net.VirtualizedCluster.csproj
This commit fixes the spelling in VirtualizedCluster description.
> Fix spelling of client in VirtualizedCluster

- src/ApiGenerator/Domain/RestApiSpec.cs
- src/ApiGenerator/Generator/Razor/LowLevelClientImplementationGenerator.cs
- src/ApiGenerator/Generator/Razor/RequestParametersGenerator.cs
- src/ApiGenerator/Views/LowLevel/Client/Implementation/ElasticLowLevelClient.cshtml
- src/ApiGenerator/Views/LowLevel/Client/Interface/IElasticLowLevelClient.cshtml
- src/ApiGenerator/Views/LowLevel/Client/Usings.cshtml
This commit fixes the API generator:
1. The collection of high level endpoints were being used in some
of the low level generators
2. High level endpoints excluded need to be compared to the list by filename
(cherry-picked from commit 04ed38b09519a19093d2fd2f467c2e6513fbfcc9)
> Fix API generator (#4456)

- src/Elasticsearch.Net/Utf8Json/Formatters/DateTimeFormatter.cs
- tests/Tests.Reproduce/TimeSpanSerialization.cs
The minimum buffer size that can be rented from the shared memory pool is 65535 bytes. This amount of memory for the purposes of serializing the day component of a string timespan is excessive. This commit changes the procedure to use a local byte array
Adds test for max size of 64bit value.
> ISO8601TimeSpanFormatter to use local byte[] array, as opposed to renting from pool.

- src/Nest/Cluster/NodesInfo/NodeInfo.cs
- src/Nest/Cluster/NodesInfo/NodeRole.cs
This commit adds some missing roles to NodeRole and some additional properties to NodeInfo.
Fixes broken integration test against 7.7.0-SNAPSHOT
> Fix Node Info

- tests/Tests.YamlRunner/SkipList.fs
Remove snapshot tests from YAML run. Tests fail due to this setup having a non directory location:
```
setup:
- do:
snapshot.create_repository:
repository: test_repo_create_1
body:
type: fs
settings:
location: "test_repo_create_1_loc"
```
Subsequent tests then fail as `test_repo_create_1` has not been created.
> Remove snapshot testing from YAML run

- src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/IntStringFormatter.cs
- src/Nest/Modules/SnapshotAndRestore/Snapshot/SnapshotShardFailure.cs
- tests/Tests.Reproduce/GitHubIssue4537.cs
This commit adds a formatter for converting from
int to string. Using this formatter fixes a bug
with SnapshotShardFailure that models ShardId as
a string instead of an int.
Fixes #4537
> Add formatter for int -> string

- src/Nest/Modules/SnapshotAndRestore/Snapshot/SnapshotShardFailure.cs
This commit changes the type of property ShardId
on SnapshotShardFailure to int, to match Elasticsearch.
Fixes #4537
> Change SnapshotShardFailure shard_id to int

- .gitignore
- Directory.Build.targets
- build/scripts/Versioning.fs
This commit fixes the inclusion of InternalsVisibleToAttributes for
versioned assemblies.
Directory.Build.Targets defines an AssemblyInfos target that
writes InternalsVisibleTo elements for friend assemblies and
versioned friend assemblies, based on the InternalsVisibleTo
elements in the target csproj and the version being built. This worked
fine when built from Rider IDE (and likely Visual Studio too) due to
the way in which MsBuild is invoked from IDE, but did not work as intended
when built from the commandline with the build script, which calls
dotnet build; The Nest InternalsVisibleTo was correctly written, but
none of the InternalsVisibleTo for generated Elasticsearch.Net assemblies
were. Looking at the binarylog for MsBuild with the Structured Log Viewer
indicated that the task was …
> Fix InternalsVisibleTo for versioned assemblies

- tests/Tests.Core/ManagedElasticsearch/Clusters/ClientTestClusterBase.cs
This commit updates the cluster.remote.connect setting to allow
integration tests to run against master 8.0.0 snapshots
> Update cluster.remote.connect to node.remote_cluster_client

- tests/Tests/Search/Search/InvalidSearchApiTests.cs
This commit updates the expected status code and error reason
assertion for the InvalidSearchApiTests. This has changed in 8.0.0-SNAPSHOT
> Fix InvalidSearchApiTests expected status code and message

- src/Nest/Analysis/Analyzers/NoriAnalyzer.cs
- src/Nest/Analysis/Tokenizers/NoriTokenizer.cs
- tests/Tests/Analysis/Tokenizers/TokenizerTests.cs
Implements elastic/elasticsearch/pull/53583
> Add nori_number token filter in analysis-nori and discard_punctuation to filter

- src/Nest/Aggregations/AggregateDictionary.cs
- src/Nest/Aggregations/AggregateFormatter.cs
- src/Nest/Aggregations/AggregationContainer.cs
- src/Nest/Aggregations/Metric/TopMetrics/TopMetricsAggregate.cs
- src/Nest/Aggregations/Metric/TopMetrics/TopMetricsAggregation.cs
- src/Nest/Aggregations/Metric/TopMetrics/TopMetricsValue.cs
- src/Nest/Aggregations/Visitor/AggregationVisitor.cs
- tests/Tests/Aggregations/Metric/TopMetrics/TopMetricsAggregationUsageTests.cs
Implements: https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-metrics-top-metrics.html
> Implement Top Metrics aggregation

- src/Nest/Ingest/Processors/CsvProcessor.cs
- tests/Tests/Ingest/ProcessorAssertions.cs
Adds an `empty_value` parameter to the CSV processor:
https://www.elastic.co/guide/en/elasticsearch/reference/master/csv-processor.html
> Add empty_value parameter to CSV processor

- src/Nest/Aggregations/Bucket/SignificantTerms/Heuristics/PercentageScoreHeuristic.cs
- tests/Tests.Reproduce/GitHubIssue4573.cs
This commit implements IPercentageScoreHeuristic on
PercentageScoreHeuristic in order to fix an exception
when attempting to serialize PercentageScore on
SignificantTerms aggregation.
Fixes #4573
> implement IPercentageScoreHeuristic on PercentageScoreHeuristic

- docs/search/request/sort-usage.asciidoc
- src/Nest/Search/Search/Sort/NestedSort.cs
- tests/Tests/Search/Request/SortUsageTests.cs
This commit adds max_children to nested sort.
Closes #4595
> Add max_children to Nested Sort

- src/Nest/Document/Single/TermVectors/FieldStatistics.cs
This commit changes the SumOfDocumentFrequencies and SumOfTotalTermFrequencies
on TermVector to long. These values can be bigger than int.
Fixes #4578
> Change SumOfDocumentFrequencies and SumOfTotalTermFrequencies to long

- src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
- src/Nest/Mapping/Types/FieldType.cs
- src/Nest/Mapping/Types/Properties.cs
- src/Nest/Mapping/Types/PropertyFormatter.cs
- src/Nest/Mapping/Types/Specialized/ConstantKeyword/ConstantKeywordAttribute.cs
- src/Nest/Mapping/Types/Specialized/ConstantKeyword/ConstantKeywordProperty.cs
- src/Nest/Mapping/Visitor/IMappingVisitor.cs
- src/Nest/Mapping/Visitor/IPropertyVisitor.cs
- src/Nest/Mapping/Visitor/MappingWalker.cs
- src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
- tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
- tests/Tests.Domain/Project.cs
- tests/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
- tests/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
- tests/Tests/Mapping/Types/Specialized/ConstantKeyword/ConstantKeywordAttributeTests.cs
- tests/Tests/Mapping/Types/Specialized/ConstantKeyword/ConstantKeywordPropertyTests.cs
Relates: https://github.com/elastic/elasticsearch/pull/49713
This commit adds the ConstantKeyword property to the client.
Value is exposed as type Object as it can be a string or numeric
value.
> Implement ConstantKeyword property

- src/Nest/IndexModules/IndexSettings/Settings/FixedIndexSettings.cs
- src/Nest/IndexModules/IndexSettings/Settings/IndexSettings.cs
- src/Nest/IndexModules/IndexSettings/Settings/IndexSettingsFormatter.cs
- src/Nest/Indices/AliasManagement/Alias.cs
- src/Nest/Indices/AliasManagement/Alias/Actions/AliasAdd.cs
- src/Nest/Indices/AliasManagement/Alias/Actions/AliasAddOperation.cs
- tests/Tests/Indices/IndexManagement/CreateIndex/CreateIndexApiTests.cs
Relates: elastic/elasticsearch#52547
Relates: elastic/elasticsearch#53248
This commit adds the ability to mark indices
and aliases as hidden.
> Implement hidden indices and aliases

- src/ApiGenerator/Domain/Specification/QueryParameters.cs
- src/ApiGenerator/Views/HighLevel/Descriptors/RequestDescriptorBase.cshtml
- src/Nest/Descriptors.cs
Hello!
This PR tries to fix #4471.
The only place I found to fix is `RequestDescriptorBase.FilterPath` so either this is a really low hanging fruit or I'm completely missing something.  I searched for potential places to fix with naive search for `(string[]` and with looking at usings of `TypeHighLevel` in views.
I noticed that methods in `Descriptors.*.cs` already have `params` modifier and then found that it is implemented with `.DescriptorArgumentType` in `Descriptor.cshtml`.  Looks like it is suitable for `RequestDescriptorBase` too.
I'm not sure if `Descriptors.cs` should be commited.  The whole process of testing codegen is a little bit confusing and I didn't figured out the right way to run tests locally for my changes (and will be glad if someone teach me).  Anyway it was a very …
> Use `params` modifier for methods in RequestDescriptorBase

- src/ApiGenerator/RestSpecDownloader.cs
Alternative approach to #4638, keeping it isolated to RestSpecDownloader
> Clean spec folder before downloading a fresh copy

- tests/Tests.Core/ManagedElasticsearch/Clusters/XPackCluster.cs
> Attempting to apply a license file to a snapshot build results in an invalid license file response.

- src/Elasticsearch.Net/Utf8Json/Formatters/PrimitiveObjectFormatter.cs
- tests/Tests.YamlRunner/Commands.fs
A bug in `PrimitiveObjectFormatter` which is used when deserializing
`object` was eagerly reading doubles as integers. This was flagged in
failing yaml test reproduce:
> ./build.sh rest-spec-tests xpack -f analytics -t t_test.yml -s "heteroscedastic t-test"
Scrollbars now also collapse when running the yaml tests now that
ShellProgressbar properly scrolls children into view this got to be a
tad excessive
> PrimitiveObjectFormatter eagerly reads integer where double could be preferred.

- src/Elasticsearch.Net/Extensions/ArraySegmentBytesExtensions.cs
- src/Elasticsearch.Net/Utf8Json/Formatters/PrimitiveObjectFormatter.cs
- tests/Tests/CodeStandards/Serialization/PrimitiveObjectFormatterTests.cs
Relates: #4649
This commit fixes a bug in the IsLong implementation, and prefers
reading long values over double values in PrimitiveObjectFormatter
when the bytes represent a valid long value, to avoid floating
point rounding errors that may happen when parsing a double from
a long value.
The bug in IsLong was that the loop over the array segment bytes was
exiting early when the count of bytes was the same as long.Min/MaxValue
length, and the current loop byte is less than the byte at index in
long.Min/MaxValue. In this scenario, it should not exit early, but
not continue to check following loop bytes against byte at index in
long.Min/MaxValue. Following loop iterations still need to check
whether remaining bytes are numbers.
> Fix bug in IsLong implementation

- src/Elasticsearch.Net/ElasticLowLevelClient.cs
- src/Elasticsearch.Net/NamespacedClientProxy.cs
This commit adds back a RequestParams overload on NamespacedClientProxy
in Elasticsearch.Net that does not accept a content type
optional parameter, and removes the optional part
of the parameter on the other overload, for backwards
binary compatibility.
> Add RequestParams overload without optional content type

- src/Nest/Aggregations/Bucket/Filters/FiltersAggregate.cs
- tests/Tests.Reproduce/GithubIssue4582.cs
This commit fixes a bug where the keys in the dictionary passed
to filters aggregation are sanitized when copying to the backing
dictionary. Keys in this scenario are the keys for named buckets
which should never be sanitized.
Fixes #4582
> Don't sanitize the keys for Filters aggregation named buckets

- src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
In https://github.com/dotnet/runtime/issues/22366 we found that if
HttpClient is using the curl handler it will lead to TCP connections
bleeding. Our DefaultConnectionLimit is very restrictive if this is
true. Our check however is too lenient and will default to true always
on .NET core since netcoreapp still ships with CurlHandler as recent as
`3.1.x`
> Fix check for agressive connectionlimit

- tests/Tests/Ingest/ProcessorAssertions.cs
- tests/Tests/Ingest/PutPipeline/PutPipelineApiTests.cs
Relates: https://github.com/elastic/elasticsearch/issues/55643
Mute CsvProcessor tests, until upstream bug is fixed.
> Mute CsvProcessor tests

- tests/Tests/XPack/MachineLearning/GetJobStats/GetJobStatsApiTests.cs
- tests/Tests/XPack/MachineLearning/MachineLearningCluster.cs
This commit updates the GetJobStatsApiTests to make
assertions on the job configured for the integration test.
This avoids grabbing a random job that may exist in the cluster
at the time the test concurrently runs.
The machine memory available to ML is also increased from
the default 30% to 50%, to avoid exceptions in running out
of memory, which have occurred locally on a machine with
32GB RAM when running all integration tests.
> Make assertions on job created in test

- src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
In dotnet/runtime#22366 we found that if
`HttpClient` is using the curl handler it will lead to TCP connections
bleeding. Our DefaultConnectionLimit is very restrictive if this is
true. Our check however is too lenient and will default to true always
on .NET core since netcoreapp still ships with CurlHandler as recent as
`3.1.x`
> [Backport 6x] Fix check for agressive connectionlimit

- src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
- src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
- src/Elasticsearch.Net/Connection/HandlerTracking/ActiveHandlerTrackingEntry.cs
- src/Elasticsearch.Net/Connection/HandlerTracking/ExpiredHandlerTrackingEntry.cs
- src/Elasticsearch.Net/Connection/HandlerTracking/LifetimeTrackingHttpMessageHandler.cs
- src/Elasticsearch.Net/Connection/HandlerTracking/RequestDataHttpClientFactory.cs
- src/Elasticsearch.Net/Connection/HandlerTracking/ValueStopWatch.cs
- src/Elasticsearch.Net/Connection/HttpConnection.cs
- src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
- src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
- tests/Tests.Configuration/tests.default.yaml
- tests/Tests.ScratchPad/Program.cs
- tests/Tests/ClientConcepts/Connection/HttpConnectionTests.cs
- tests/Tests/Framework/EndpointTests/ApiIntegrationTestBase.cs
- tests/Tests/Search/Search/InvalidSearchApiTests.cs
This PR fixes a longstanding wish to be able to recycle `HttpClient` instances periodically. We reuse HttpClient/HttpMessageHandler's to prevent TCP leakage but  [infamously this does not take DNS changes into account](https://github.com/dotnet/runtime/issues/18348).
`IHttpClientFactory` from [Microsoft.Extensions.Http](https://www.nuget.org/packages/Microsoft.Extensions.Http/) solves this but the nuget package depends on too many things we don't want to depend on OOTB like Dependency Injection.  This copies parts of this code (now MIT licensed as of February) so we can reuse the same strategy in the client. 
Starting with `netstandard2.1` `SocketsHttpHander` also supports `PooledConnectionLifetime` this however has a bug in corrolation with …
> Allow HttpClient instances to be refreshed periodically

- dotnet-tools.json
- src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
- src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
- src/Elasticsearch.Net/Connection/HandlerTracking/ActiveHandlerTrackingEntry.cs
- src/Elasticsearch.Net/Connection/HandlerTracking/ExpiredHandlerTrackingEntry.cs
- src/Elasticsearch.Net/Connection/HandlerTracking/LifetimeTrackingHttpMessageHandler.cs
- src/Elasticsearch.Net/Connection/HandlerTracking/RequestDataHttpClientFactory.cs
- src/Elasticsearch.Net/Connection/HandlerTracking/ValueStopWatch.cs
- src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
- src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
6.x does not follow the new layout so a cherry-pick is too involved.
Manually reimplemented the same logic that introduces
`RequestDataHttpClientFactory` to periodically recycle HttpClient
instances.
> [Backport 6.x] Reimplement #4673 manually

- build/add-headers.sh
- build/file-header.txt
`master` and `7.x` now set `$HEADER` properly in `.DotSettings` so new files will always have the license. Its also part of the silent code cleanup.
Experimented with a new code clean up profile that just does adding file headers but it needs code clean up too so would be even noisier. Doing this through code clean up is also wayy to slow. 
This PR therefor adds a one-off script to inject the license to all `cs` and `fs` files.
It does a quick check to see if the file does not already start with `/` or `#`. It's easier to fix up false negative then true positives after running the tool. 
Adding this PR in isolation but will run the tool on the branches itself directly. Nothing worse then having a 4000 file PR pending 😸 
cc @russcam
> Add script to add file license headers

- src/Elasticsearch.Net/Utf8Json/Resolvers/DynamicGenericResolver.cs
- tests/Tests.Reproduce/GithubIssue4703.cs
This PR adds special serialization handling for nullable `ValueTuple`s. Specialized handling is required as without, a nullable `ValueTuple` type ends up falling into `CustomDynamicObjectResolver` inside of
`NestFormatterResolver`, which will build a dynamic formatter using `MetaType` et.al, which enumerates interfaces and can cause a CLR error when calling `System.Runtime.CompilerServices.ITuple.get_Length()`.
Fixes #4703
> Add special serialization handling for nullable ValueTuples

- src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
- src/Nest/QueryDsl/FullText/Match/MatchQuery.cs
Replace "can skips" with "can skip" in the four instances of the `MatchQuery.CutoffFrequency` Obsolete attributes in the MatchQuery class.
This is a documentation-only correction and there are **no** modifications to the code.
I also confirm that I have read, understood, and signed the CLA.
> Correct grammar on MatchQuery CutoffFrequency

- azure-pipelines.yml
- tests/Tests/Search/Search/InvalidSearchApiTests.cs
This simplifies our assertions and broadens them to hopefully fail less.
Added 7.8.0 SNAPSHOT and `7.7.0` to the test matrix now that `latest-7` resolves to `7.9.0-SNAPSHOT`
> Elasticsearch always returns a 400 now for our invalid search

- tests/Tests/Ingest/ProcessorAssertions.cs
- tests/Tests/Ingest/PutPipeline/PutPipelineApiTests.cs
Relates: #4718.
Unmute CsvProcessot tests for 7.8.0 now that empty_value is fixed.
> Unmute CsvProcessor

- src/Nest/Analysis/TokenFilters/EdgeNGram/EdgeNGramTokenFilter.cs
- tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs
> Add PreserveOriginal to EdgeNgramTokenFilter

- src/Nest/XPack/Info/XPackUsage/XPackUsageResponse.cs
- tests/Tests/XPack/Info/XPackInfoApiTests.cs
> Add analytics to xpack usage

- src/Nest/Cluster/NodesUsage/NodeUsageInformation.cs
- tests/Tests/Cluster/NodesUsage/NodesUsageApiTests.cs
Relates: #4718, elastic/elasticsearch#55732
> Add aggregation usage to nodes usage

- src/Nest/QueryDsl/Specialized/Pinned/PinnedQuery.cs
- tests/Tests.Reproduce/GithubIssue4733.cs
This commit fixes the Ids overloads on PinnedQuery by
performing the conversion to IEnumerable<Id> on each
overload and assigning to the Ids value.
Fixes #4733
> Fix Ids overloads on PinnedQuery

- src/Nest/Cluster/NodesStats/NodeStats.cs
- tests/Tests/Cluster/NodesStats/NodesStatsApiTests.cs
Relates: #4718
This commit adds the script_cache to node stats
API response.
> Add script_cache to Node Stats API

- src/Nest/Cluster/VotingConfigExclusions/DeleteVotingConfigExclusions/DeleteVotingConfigExclusionsRequest.cs
- src/Nest/Cluster/VotingConfigExclusions/DeleteVotingConfigExclusions/DeleteVotingConfigExclusionsResponse.cs
- src/Nest/Cluster/VotingConfigExclusions/PostVotingConfigExclusions/PostVotingConfigExclusionsRequest.cs
- src/Nest/Cluster/VotingConfigExclusions/PostVotingConfigExclusions/PostVotingConfigExclusionsResponse.cs
- src/Nest/Descriptors.Cluster.cs
- src/Nest/ElasticClient.Cluster.cs
- src/Nest/Requests.Cluster.cs
- tests/Tests/Cluster/VotingConfigExclusions/DeleteVotingConfigExclusions/DeleteVotingConfigExclusionsApiTests.cs
- tests/Tests/Cluster/VotingConfigExclusions/DeleteVotingConfigExclusions/DeleteingVotingConfigExclusionsTests.cs
- tests/Tests/Cluster/VotingConfigExclusions/PostVotingConfigExclusions/PostVotingConfigExclusionsApiTests.cs
- tests/Tests/Cluster/VotingConfigExclusions/PostVotingConfigExclusions/PostingVotingConfigExclusionsTests.cs
Relates: #4718, elastic/elasticsearch#55760
This commit adds the voting config exclusions APIs to the high level client.
Custom response builder types are required because the APIs return
\n as the response, which the client will attempt to deserialize to a
response object.
> Add Voting Config Exclusions APIs

- src/Nest/Aggregations/AggregateFormatter.cs
- src/Nest/Aggregations/Bucket/AutoDateHistogram/AutoDateHistogramBucket.cs
- src/Nest/Aggregations/Bucket/BucketAggregate.cs
- tests/Tests.Reproduce/GitHubIssue4333.cs
This commit fixes a bug with AutoDateHistogramAggregate Interval
property that uses the Time type to represent valid intervals. The Time
type however does not support Months and Years, which are valid units
for the AutoDateHistogram interval.
Fixes #4333
> AutoDateHistogramAggregate Interval should be DateMathTime

- src/Nest/Aggregations/AggregateFormatter.cs
- src/Nest/Aggregations/Metric/ExtendedStats/ExtendedStatsAggregate.cs
This commit updates the deserialization of
ExtendedStatsAggregate to make it more lenient to
the introduction of new fields.
Closes #4773
> More lenient extended_stats deserialization

- src/Elasticsearch.Net/Connection/CertificateValidations.cs
This commit fixes a bug when validating an intermediate CA
to remove the increment inside of the loop, since it
is incremented outside the loop already.
Don't check the certificate thumbprint against
the CA thumbprint if it's already been found.
Fixes #4717
> Remove increment inside loop when validating intermediate CA

- src/ApiGenerator/RestSpecification/Core/indices.simulate_index_template.json
- src/ApiGenerator/RestSpecification/Core/root.html
- src/ApiGenerator/RestSpecification/XPack/ml.delete_data_frame_analytics.json
- src/ApiGenerator/RestSpecification/XPack/root.html
- src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.MachineLearning.cs
- src/Elasticsearch.Net/ElasticLowLevelClient.Indices.cs
This commit runs the ApiGenerator to update the client
with the latest changes on 7.8 branch
> Update with latest 7.8 REST specs

- tests/Tests/XPack/MachineLearning/GetJobs/GetJobsApiTests.cs
- tests/Tests/XPack/MachineLearning/MachineLearningInfo/MachineLearningInfoApiTests.cs
- tests/Tests/XPack/MachineLearning/PutJob/PutJobApiTests.cs
This commit fixes assertions on ModelSnapshotRetentionDays
as the default days has changed from 1 to 10.
> Change default ModelSnapshotRetentionDays

- src/Nest/Mapping/Types/Specialized/Attachment/Attachment.cs
- src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
This commit adds `[Ignore]` attribute to the `ContainsMetadata`
field to ignore the field when automapping an Attachment.
`[IgnoreDataMember]` ignores the value when serializing an
instance of Attachment, but `NoopPropertyVisitor` does not
take into account `[IgnoreDataMember]` when mapping properties.
> Ignore ContainsMetadata field when automapping Attachment

- src/Elasticsearch.Net/Patch.ElasticLowLevelClient.MachineLearning.cs
This commit removes the MapsApiAttribute from the DeleteExpiredData overloads, so that the overload with a body are used for yaml tests
> Remove MapsApi from DeleteExpiredData overload

- src/Elasticsearch.Net/Connection/HttpConnection.cs
Relates: #4673
This commit adds the Clients property back to HttpConnection
,for binary compatibility, with an ObsoleteAttribute applied
to indicate that the property is no longer used.
> Obsolete Clients property on HttpConnection

- tests/Tests/Mapping/Types/Core/Date/DateAttributeTests.cs
- tests/Tests/Mapping/Types/Core/Date/DatePropertyTests.cs
- tests/Tests/Mapping/Types/Core/DateNanos/DateNanosAttributeTests.cs
- tests/Tests/Mapping/Types/Core/DateNanos/DateNanosPropertyTests.cs
This commit updates the Format used in Date[Nanos]PropertyTests
to one that can be used to parse the null_value.
Closes #4781
> Use format that null_value conforms to

- src/Nest/XPack/MachineLearning/MachineLearningInfo/MachineLearningInfoResponse.cs
- tests/Tests/XPack/MachineLearning/MachineLearningInfo/MachineLearningInfoApiTests.cs
Relates: elastic/elasticsearch#55529, #4803
> Add effective max model memory limit to ML info

- docs/client-concepts/high-level/mapping/parent-child-relationships.asciidoc
- tests/Tests/ClientConcepts/HighLevel/Mapping/ParentChildRelationships.doc.cs
Minor change
Many of the code blocks under the "Routing parent-child documents" header contain a spelling and continuity error on the variable "ndexResponse"
Presumably, this should be "indexResponse" as to be in line with the rest of this readme, so this commit is fixing the incorrect variables to reflect the correct name.
> Parent-Child Documentation: Fixed spelling error on "IndexResponse"

- src/Nest/Search/Search/SearchRequest.cs
- tests/Tests.Reproduce/GithubIssue4787.cs
This commit updates the .Source() method
to not wrap a null ISourceFilter in Union<bool,ISourceFilter>, so
that it is not serialized in the request.
Fixes #4787
> Do not wrap null ISourceFilter in Union

- src/Nest/XPack/MachineLearning/Job/Config/JobStats.cs
- src/Nest/XPack/MachineLearning/Job/Process/ModelSizeStats.cs
Relates: elastic/elasticsearch#55716, #4803
This commit adds FailedCategoryCount to ModelSizeStats
and adds other missing fields to JobStats
> Add FailedCategoryCount to ModelSizeStats

- src/Nest/CommonOptions/Sorting/SortFormatter.cs
- tests/Tests.Reproduce/GitHubIssue4797.cs
This commit updates SortFormatter to be able
to deserialize sorts that specify only the field
name as a string, or only specify a sort order
value.
Fixes #4797
> Deserialize sort short forms

- src/Nest/XPack/MachineLearning/Job/Config/Job.cs
- src/Nest/XPack/MachineLearning/MachineLearningInfo/MachineLearningInfoResponse.cs
- src/Nest/XPack/MachineLearning/PutJob/PutJobRequest.cs
- src/Nest/XPack/MachineLearning/UpdateJob/UpdateJobRequest.cs
- tests/Tests/XPack/MachineLearning/MachineLearningInfo/MachineLearningInfoApiTests.cs
Relates: elastic/elasticsearch#56125, #4803
This commit adds the DailyModelSnapshotRetentionAfterDays
to ML jobs. It also updates the XML comment for
ModelSnapshotRetentionDays to align with the new default in
Elasticsearch 7.8.
> Add DailyModelSnapshotRetentionAfterDays to ml jobs

- docs/client-concepts/connection/configuration-options.asciidoc
Changes to remove duplicates on https://github.com/elastic/elasticsearch-net/blob/master/docs/client-concepts/connection/configuration-options.asciidoc.
> Remove duplicated properties

- src/Elasticsearch.Net/Connection/HandlerTracking/RequestDataHttpClientFactory.cs
- tests/Tests.Reproduce/GitHubIssue4818.cs
This commit checks that _cleanupTimer is not null
when disposing, which it may be if no requests have
been made.
Fixes #4818
> Check _cleanupTimer is not null when disposing

- src/Elasticsearch.Net/Utf8Json/Formatters/EnumFormatter.cs
- tests/Tests.Reproduce/GitHubIssue4817.cs
This commit updates the EnumFormatter to parse case-insensitive
when falling back to the Enum.Parse method, which happens when
a value is not found in a mapping built from EnumMember/DataMember
value or field name.
Fixes #4817
> Deserialize enums in fallback Enum.Parse as case insensitive

- tests/Tests.Core/ManagedElasticsearch/Clusters/ClientTestClusterBase.cs
Relates: https://github.com/elastic/elasticsearch/pull/58283
This commit updates integration test cluster
settings to use disable_max_compilations_rate for
7.9.0-SNAPSHOT and above, and remove using
max_compilations_rate which is deprecated (and removed in 8.0.0-SNAPSHOT)
> Fix script compilation settings

- docs/aggregations/bucket/date-histogram/date-histogram-aggregation-usage.asciidoc
- src/Nest/Aggregations/Bucket/DateHistogram/DateHistogramAggregation.cs
- tests/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs
This commit fixes FixedInterval and CalendarInterval on
DateHistogram aggregation to
1. For FixedInterval to accept only Time
2. For CalendarInterval to accept DateInterval or DateMathTime
This aligns with DateHistogramCompositeAggregationSource.
Fixes #4839
> Fix DateHistogram aggregation intervals

- src/Nest/Cluster/NodesStats/NodeStats.cs
- tests/Tests/Cluster/NodesStats/NodesStatsApiTests.cs
This commit fixes the response type for node stats script_cache
to a type with "sum" and "contexts" fields, to match the shape of returned JSON
> Fix ScriptCacheStats

- tests/Tests/Mapping/Types/Core/Date/DateAttributeTests.cs
- tests/Tests/Mapping/Types/Core/Date/DatePropertyTests.cs
- tests/Tests/Mapping/Types/Core/DateNanos/DateNanosAttributeTests.cs
- tests/Tests/Mapping/Types/Core/DateNanos/DateNanosPropertyTests.cs
This commit removes the Similarity property usage from the
Date and DateNanos property integration tests.
Similarity is not a valid property and should be
removed as part of #3145
> Remove similarity from Date property integration tests

- src/Nest/Ingest/Processor.cs
- tests/Tests/Ingest/ProcessorAssertions.cs
This commit adds description to ingest processors to allow
users to explain the purpose of a specific processor instance.
> Add description to ingest processors

- .ci/DockerFile
- .ci/Jenkins.csproj
- .ci/make.sh
- .dockerignore
- .gitignore
- build/scripts/Commandline.fs
- build/scripts/ReposTooling.fs
- build/scripts/Targets.fs
- build/scripts/Versioning.fs
- build/scripts/scripts.fsproj
- dotnet-tools.json
Initial stab at common entry script for all the Elasticsearch clients.
This puts our build through a docker container so that folks & CI do not need
to install dependencies on their machines to build artifacts.
> ./.ci/make.sh release VERSION
will output our packages, release notes, API reports in `.ci/output`.
This also updates our build to use: https://github.com/nullean/nupkg-validator
This is the tool version of our build script targets that
- validate the dlls are build in release mode
- validate the dll version numbers
- validate the dll assemly identity
- validate the dll assembly names.
With the added benefit that the dependency on `sn` is gone which is not
available on the dotnet base docker images that we use.
`.ci/make.sh` is not done yet, will iterate on this as the flow in …
> Introduce .ci/make.sh

- .ci/DockerFile
- .ci/Jenkins.csproj
- .ci/make.sh
- .dockerignore
- .gitignore
- build/scripts/Commandline.fs
- build/scripts/ReposTooling.fs
- build/scripts/Targets.fs
- build/scripts/Versioning.fs
- build/scripts/scripts.fsproj
- dotnet-tools.json
(cherry picked from commit 7085a90144e64e288ffd926678a1f961e3c7572f)
> [Backport 7.x] Introduce .ci/make.sh (#4838)

- src/Nest/Document/Multiple/Bulk/BulkOperation/BulkOperationsCollection.cs
- src/Nest/Document/Multiple/Bulk/BulkRequest.cs
- tests/Tests.Benchmarking/BulkCreationBenchmarkTests.cs
- tests/Tests.Benchmarking/BulkSerializationBenchmarkTests.cs
`IBulkRequest` dictated that operations should be implemented using `BulkOperationsCollection` which effectively is a `SynchronizedCollection`. We did this back in 2013 because concurrent producers calling `.IndexMany()` were expected to be threadsafe. 
Since then we also introduced the object inititalizer syntax. Here we can push back on this requirement. This PR fixes that so that users using that syntax are not forced to use the `BulkOperationsCollection`.
Some performance numbers attached:
|                  Method |     Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------ |---------:|----------:|----------:|------:|------:|------:|----------:|
|          Descriptors.V8 | 2.581 ms | 0.0529 ms | 0.1383 ms |     - |     - |     - |    1.7 MB |
| …
> Fix #4298 be less strict about `Operations` on `IBulkRequest`

- docs/aggregations.asciidoc
- docs/aggregations/pipeline/normalize/normalize-aggregation-usage.asciidoc
- docs/code-standards/descriptors.asciidoc
- src/Nest/Aggregations/AggregateDictionary.cs
- src/Nest/Aggregations/AggregationContainer.cs
- src/Nest/Aggregations/Pipeline/Normalize/NormalizeAggregation.cs
- src/Nest/Aggregations/Visitor/AggregationVisitor.cs
- src/Nest/Aggregations/Visitor/AggregationWalker.cs
- tests/Tests/Aggregations/Pipeline/Normalize/NormalizeAggregationUsageTests.cs
- tests/Tests/CodeStandards/Descriptors.doc.cs
Relates: elastic/elasticsearch#56399
This commit adds the normalize aggregation to
the high level client.
> Add normalize aggregation

- src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
- src/Nest/Mapping/Types/FieldType.cs
- src/Nest/Mapping/Types/Properties.cs
- src/Nest/Mapping/Types/PropertyFormatter.cs
- src/Nest/Mapping/Types/Specialized/Wildcard/WildcardAttribute.cs
- src/Nest/Mapping/Types/Specialized/Wildcard/WildcardProperty.cs
- tests/Tests/Mapping/Types/Specialized/Wildcard/WildcardAttributeTests.cs
- tests/Tests/Mapping/Types/Specialized/Wildcard/WildcardPropertyTests.cs
Relates: elastic/elasticsearch#49993
> Add support for wildcard property

- docs/aggregations.asciidoc
- docs/query-dsl.asciidoc
- src/DocGenerator/AsciiDoc/RawAsciidocVisitor.cs
`anchor-list` output was not explicitly ordered causing issues with different itteration orders of files/directories between OS's.
> [Docs] order `anchor-list` output explicitly.

- src/Nest/Modules/SnapshotAndRestore/Repositories/S3Repository.cs
- tests/Tests/Modules/SnapshotAndRestore/Repositories/CreateRepository/CreateRepositoryApiTests.cs
This commit adds additional settings to s3 repository
settings:
- max_restore_bytes_per_sec
- max_snapshot_bytes_per_sec
- readonly
Closes #4889
> Add addition settings to s3 repository

- src/Elasticsearch.Net/Utf8Json/Formatters/DateTimeFormatter.cs
- tests/Tests.Reproduce/GitHubIssue4876.cs
This commit handles ISO8601 basic format offsets
of the form:
- [+-]hh
- [+-]hhmm
in addition to the extended format offset form
- [+-]hh:mm
Fixes #4876
> Handle ISO8601 basic format offsets

- src/Nest/Analysis/Tokenizers/CharGroupTokenizer.cs
- tests/Tests/Analysis/Tokenizers/TokenizerTests.cs
Relates: elastic/elasticsearch#56860
> Add max_token_length to chargroup tokenizer

- src/Nest/CommonOptions/Stats/StoreStats.cs
- tests/Tests/Cluster/NodesStats/NodesStatsApiTests.cs
Relates: elastic/elasticsearch#58029
> Add reserved, reserved_in_bytes to node stats response

- tests/Tests/Search/Search/SearchApiTests.cs
Relates: elastic/elasticsearch#60044
This commit updates the SearchApiDocValueFieldsTests to use
a different date format.
Fixes #4920
> Fix date format use in SearchApiDocValueFieldsTests

- tests/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs
This commit skips running DateHistogram aggregations
for versions <7.2.0 as they use calendar_interval and
fixed_interval, which were introduced in 7.2.0.
> Skip DateHistogram aggregations for <7.2.0

- docs/aggregations.asciidoc
- docs/query-dsl.asciidoc
- src/DocGenerator/AsciiDoc/RawAsciidocVisitor.cs
- src/DocGenerator/Program.cs
- src/DocGenerator/StringExtensions.cs
- src/DocGenerator/SyntaxNodeExtensions.cs
This commit fixes a difference in the default string comparison
on .NET core across Windows and Linux which was causing the
Stale docs github action to fail on CI because generated documentation
was ordering asciidoc includes and list items in a different order.
This fix sets a specific culture to use and uses ordinal string
comparison. Tested on Windows and Ubuntu 18.04 WSL 2.
> Consistent file string comparison across Windows and Linux

- docs/search/scrolling-documents.asciidoc
- tests/Tests/Search/ScrollingDocuments.doc.cs
Related to https://github.com/elastic/docs/pull/1932
This PR fixes the following links that will break when the "current" documentation branch becomes 7.9:
````
13:54:52 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/net-api/7.x/scrolling-documents.html:
13:54:52 INFO:build_docs:   - en/elasticsearch/reference/current/search-request-body.html#sliced-scroll
13:54:52 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/net-api/current/scrolling-documents.html:
13:54:52 INFO:build_docs:   - en/elasticsearch/reference/current/search-request-body.html#sliced-scroll
13:54:52 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/net-api/master/scrolling-documents.html:
13:54:52 INFO:build_docs:   - …
```
> [DOCS] Fixes broken link to sliced scroll

- src/Elasticsearch.Net/Elasticsearch.Net.csproj
- src/Elasticsearch.Net/Extensions/NameValueCollectionExtensions.cs
- tests/Tests/Extensions/NameValueCollectionExtensionsTests.cs
This commit optimises the internal `ToQueryString` extension method on the `NameValueCollection` type. It avoids some intermediate string allocations by using a zero-alloc buffer to format the final query string.
- Adds a test for the extension method to validate existing behaviour is unaffected by the change of implementation.
- Adds the `System.Memory` package to support `Span<T>` usage across all target frameworks. This is registered conditionally for targets before NetStandard 2.1. I had some downgrade errors when using the latest package version, so I've aligned with the existing `System.Buffers` version for the time being.
I've opened this against master although it may be valuable to back port to existing supported versions?
The exact performance improvement varies based on the …
> NameValueCollection.ToQueryString performance optimisation

- src/Nest/XPack/CrossClusterReplication/AutoFollow/CreateAutoFollowPattern/CreateAutoFollowPatternRequest.cs
- src/Nest/XPack/CrossClusterReplication/AutoFollow/GetAutoFollowPattern/GetAutoFollowPatternResponse.cs
- src/Nest/XPack/CrossClusterReplication/Follow/CreateFollowIndex/CreateFollowIndexRequest.cs
- tests/Tests/XPack/CrossClusterReplication/AutoFollow/CreateAutoFollowPattern/CreateAutoFollowPatternApiTests.cs
- tests/Tests/XPack/CrossClusterReplication/AutoFollow/CreateAutoFollowPattern/CreateAutoFollowPatternUrlTests.cs
- tests/Tests/XPack/CrossClusterReplication/Follow/CreateFollowIndex/CreateFollowIndexApiTests.cs
- tests/Tests/XPack/CrossClusterReplication/Follow/CreateFollowIndex/CreateFollowIndexUrlTests.cs
Relates: elastic/elasticsearch#58103
> Add settings to create follow index and create auto follow pattern APIs

- src/Nest/Mapping/Types/Specialized/Ip/IpAttribute.cs
- src/Nest/Mapping/Types/Specialized/Ip/IpProperty.cs
- tests/Tests/ClientConcepts/Troubleshooting/DebuggerDisplayTests.cs
- tests/Tests/Mapping/Types/Specialized/Ip/IpAttributeTests.cs
- tests/Tests/Mapping/Types/Specialized/Ip/IpPropertyTests.cs
This commit removes the Boost property from Ip field mappings.
Fixes #4957
> Remove Boost from IpProperty

- src/Nest/QueryDsl/Compound/FunctionScore/Functions/ScoreFunctionJsonFormatter.cs
- tests/Tests/QueryDsl/Compound/FunctionScore/FunctionScoreQueryUsageTests.cs
Relates: https://stackoverflow.com/questions/63502401/elasticsearch-nest-incorrect-function-score-json-generation
This commit fixes the serialization of IFieldValueFactorFunction whereby
filter and weight were being serialized twice, once inside of
field_value_factor and once outside.
> Fix field value factor serialization

- src/Elasticsearch.Net/Serialization/CustomResponseBuilderBase.cs
- src/Nest/Document/Single/Source/SourceRequestResponseBuilder.cs
- tests/Tests/Document/Single/Source/SourceApiTests.cs
This commit uses the SourceSerializer to deserialize the source API response.
Fixes #4970
> Use SourceSerializer when deserializing Source API response

- tests/Tests/Mapping/Types/Core/Number/NumberPropertyTests.cs
This commit removes use of fields that now cause a 400 response from Elasticsearch. These fields will be refactored as part of #3145
> Remove use of similarity and boost from number mappings

- src/ApiGenerator/Configuration/CodeConfiguration.cs
- src/ApiGenerator/Domain/RestApiSpec.cs
- src/ApiGenerator/Generator/ApiGenerator.cs
- src/ApiGenerator/Program.cs
- src/ApiGenerator/Views/HighLevel/Requests/ApiUrlsLookup.cshtml
- src/Nest/Cluster/Ping/PingRequest.cs
- src/Nest/Document/Multiple/Bulk/BulkRequest.cs
- src/Nest/Document/Multiple/DeleteByQuery/DeleteByQueryRequest.cs
- src/Nest/Document/Multiple/ReindexRethrottle/ReindexRethrottleRequest.cs
- src/Nest/Document/Multiple/UpdateByQuery/UpdateByQueryRequest.cs
- src/Nest/Document/Single/Get/GetRequest.cs
- src/Nest/Document/Single/Index/IndexRequest.cs
- src/Nest/Document/Single/Update/UpdateRequest.cs
- src/Nest/Search/Scroll/Scroll/ScrollRequest.cs
- src/Nest/Search/Search/SearchRequest.cs
- src/Nest/Search/SearchShards/SearchShardsRequest.cs
- src/Nest/Search/SearchTemplate/RenderSearchTemplate/RenderSearchTemplateRequest.cs
- src/Nest/Search/SearchTemplate/SearchTemplateRequest.cs
Updates the high level codegeneration so that new API's, those not mapped and not explicitly ignored, require confirmation before generating.
> Selective inclusion of new API's in the high level code generator

- src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/DateTimeOffsetEpochMillisecondsFormatter.cs
- tests/Tests/XPack/MachineLearning/GetAnomalyRecords/GetAnomalyRecordsApiTests.cs
- tests/Tests/XPack/MachineLearning/GetInfluencers/GetInfluencersApiTests.cs
- tests/Tests/XPack/MachineLearning/GetModelSnapshots/GetModelSnapshotsApiTests.cs
- tests/Tests/XPack/MachineLearning/StartDatafeed/StartDatafeedApiTests.cs
This commit updates the DateTimeOffsetEpochMillisecondsFormatter
and NullableDateTimeOffsetEpochMillisecondsFormatter to serialize
epoch milliseconds as a string instead of a number. Add additional
parameters to integration tests to assert the change is valid
where used.
> Serialize Epoch milliseconds as a string

- src/Nest/CommonAbstractions/Request/UrlLookup.cs
In the process of going through the code, I spotted a fairly trivial change which can reduce allocations during URL generation for endpoints where no route values need to be applied.
`UrlLookup.ToUrl` can short-circuit in such cases to avoid duplicating the string and allocating a StringBuilder. For requests where no index is supplied, the allocations can be entirely removed and an 87% reduction in execution time can be achieved.
The examples below test with the cluster health endpoints.
**Before:**
```
|      Method |     Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------ |---------:|---------:|---------:|-------:|------:|------:|----------:|
|      Health | 41.60 ns | 0.637 ns | 0.596 ns | 0.0381 |     - |     - |     160 B |
| HealthIndex | 85.60 ns | 0.851 …
```
> Short circuit in ToUrl to remove allocations when possible.

- docs/client-concepts/connection/configuration-options.asciidoc
- docs/client-concepts/troubleshooting/debug-information.asciidoc
- docs/client-concepts/troubleshooting/debug-mode.asciidoc
- docs/troubleshooting.asciidoc
- src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
- src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
- src/Elasticsearch.Net/Configuration/RequestConfiguration.cs
- src/Elasticsearch.Net/Connection/HttpConnection.cs
- src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
- src/Elasticsearch.Net/Diagnostics/TcpStats.cs
- src/Elasticsearch.Net/Diagnostics/ThreadpoolStats.cs
- src/Elasticsearch.Net/Responses/ElasticsearchResponse.cs
- src/Elasticsearch.Net/Responses/HttpDetails/ApiCallDetails.cs
- src/Elasticsearch.Net/Responses/HttpDetails/IApiCallDetails.cs
- src/Elasticsearch.Net/Responses/ResponseStatics.cs
- src/Elasticsearch.Net/Stats/TcpStats.cs
- src/Elasticsearch.Net/Stats/ThreadpoolStats.cs
- src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
- tests/Tests/ClientConcepts/Troubleshooting/DebugInformation.doc.cs
- tests/Tests/ClientConcepts/Troubleshooting/DebugMode.doc.cs
- tests/Tests/Framework/DocumentationTests/IntegrationDocumentationTestBase.cs
- tests/Tests/troubleshooting.asciidoc
This commit adds the ability to enable TCP and ThreadPool
statistics to be collected when making a request, exposing
these statistics on the IApiCallDetails on the response, as
well as including in the debug information.
Add documentation explaining how to include these statistics
either on a global or per request basis.
> Enable TCP states and ThreadPool stats

- tests/Tests/Mapping/Types/Core/DateNanos/DateNanosPropertyTests.cs
This commit fixes a new failure with the date_nanos
property tests, updating the null_value to use
the unix epoch as opposed to DateTime.MinValue,
which now throws an error.
> Fix date_nanos null_value integration test

- src/Nest/Mapping/Visitor/IPropertyVisitor.cs
- src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
- tests/Tests/CodeStandards/Parity/ParityTests.cs
This commit adds missing Visit methods for IProperty types to IPropertyVisitor. Add unit test to ensure that visitor
contains a Visit method for derived IProperty types.
> Add Visit methods for derived IProperty types

- src/Nest.JsonNetSerializer/Converters/HandleNestTypesOnSourceJsonConverter.cs
- src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
- src/Nest/Mapping/Types/FieldType.cs
- src/Nest/Mapping/Types/Properties.cs
- src/Nest/Mapping/Types/PropertyFormatter.cs
- src/Nest/Mapping/Types/Specialized/Point/PointAttribute.cs
- src/Nest/Mapping/Types/Specialized/Point/PointProperty.cs
- src/Nest/Mapping/Visitor/IMappingVisitor.cs
- src/Nest/Mapping/Visitor/IPropertyVisitor.cs
- src/Nest/Mapping/Visitor/MappingWalker.cs
- src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
- src/Nest/QueryDsl/Geo/Shape/GeoShapeBase.cs
- src/Nest/QueryDsl/Geo/WKT/GeoWKTException.cs
- src/Nest/QueryDsl/Geo/WKT/GeoWKTReader.cs
- src/Nest/QueryDsl/Specialized/Shape/CartesianPoint.cs
- tests/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
- tests/Tests/Mapping/Types/Specialized/Point/CartesianPointSerializationTests.cs
- tests/Tests/Mapping/Types/Specialized/Point/PointAttributeTests.cs
- tests/Tests/Mapping/Types/Specialized/Point/PointPropertyTests.cs
Relates: #4718, elastic/elasticsearch#53804
This commit adds a Point property to map the new point data type.
A CartesianPoint type is introduced to model points.
> Add Point property for mapping point datatype

- src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
- tests/Tests/CodeStandards/Parity/ParityTests.cs
This commit marks all  Visit methods virtual on `NoopPropertyVisitor` to allow overriding only specific methods.
Add unit test to verify that methods are virtual, now and in the future.
> Mark all Visit methods virtual on NoopPropertyVisitor

- build/scripts/Building.fs
- build/scripts/Tooling.fs
- build/scripts/scripts.fsproj
- dotnet-tools.json
This commit removes ILRepack from the build. ILRepack is used in
the 6.x branch to internalize Json.NET into the Nest assembly, and
was being used in 7.x and master branch **only** to sign the versioned
canary packages. Since assembly-rewriter can now sign a rewritten
assembly (works cross-platform) in nullean/assembly-rewriter#7,
there is no need for ILRepack at all.
> Remove ILRepack

- docs/index.asciidoc
- tests/Tests/index.asciidoc
This PR adds the reference of the shared/attribute.asciidoc file to the index.asciidoc, so abbreviations in the attributes file can be used across the .NET documentation.
> [DOCS] Adds shared/attributes.asciidoc to index

- src/Nest/Aggregations/AggregateDictionary.cs
- src/Nest/Aggregations/AggregationContainer.cs
- src/Nest/Aggregations/Bucket/DiversifiedSampler/DiversifiedSamplerAggregation.cs
- src/Nest/Aggregations/Bucket/DiversifiedSampler/DiversifiedSamplerAggregationExecutionHint.cs
- src/Nest/Aggregations/Visitor/AggregationVisitor.cs
- tests/Examples/Aggregations/Bucket/DiversifiedSamplerAggregationPage.cs
- tests/Tests/Aggregations/Bucket/DiversifiedSampler/DiversifiedSamplerAggregationUsageTests.cs
DiversifiedSamplerAggregation added with ExecutionHint, Field, MaxDocsPerValue, Script and ShardSize.
> Added diversified sampler aggregation

- src/Nest/Aggregations/Bucket/Sampler/SamplerAggregation.cs
> Obsolete options on SamplerAggregation

- src/Nest/Analysis/Tokenizers/TokenizerFormatter.cs
- tests/Tests.Reproduce/GithubPR5039.cs
Continuation of #5039
The orignal PR adds support for user defined `ITokenizer` implementation to be serialized correctly
This extends the work already done for v7.6.0 by @russcam https://github.com/elastic/elasticsearch-net/pull/5062
> Allow custom tokenizers to be serialized fully

- src/Nest/Cluster/NodesInfo/NodeRole.cs
Our integration tests were failing calling the `nodes.info` API because
it could not map `data_cold` to this enum.
> Add support for the new `data_*` roles.

- src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
Ensure BulkAll() is aborted properly if the whole bulk request keeps returning a bad statuscode and ContinueOnDroppedDocuments is true. This was introduced in #4014 when trying to address a similar issue with backOffTries being ignored.
> Fixing BulkAll indefinitely hanging when failing

- src/Nest/Mapping/Types/Core/Number/NumberAttribute.cs
- src/Nest/Mapping/Types/Core/Number/NumberProperty.cs
- src/Nest/Mapping/Types/Core/Range/RangePropertyAttributeBase.cs
- src/Nest/Mapping/Types/Core/Range/RangePropertyBase.cs
- src/Nest/Mapping/Types/Specialized/Ip/IpAttribute.cs
- src/Nest/Mapping/Types/Specialized/Ip/IpProperty.cs
- src/Nest/Mapping/Types/Specialized/TokenCount/TokenCountAttribute.cs
- src/Nest/Mapping/Types/Specialized/TokenCount/TokenCountProperty.cs
- tests/Tests/ClientConcepts/Troubleshooting/DebuggerDisplayTests.cs
- tests/Tests/Mapping/Types/Core/Number/NumberPropertyTests.cs
- tests/Tests/Mapping/Types/Core/Range/DateRange/DateRangePropertyTests.cs
- tests/Tests/Mapping/Types/Core/Range/DoubleRange/DoubleRangePropertyTests.cs
- tests/Tests/Mapping/Types/Core/Range/FloatRange/FloatRangePropertyTests.cs
- tests/Tests/Mapping/Types/Core/Range/IntegerRange/IntegerRangePropertyTests.cs
- tests/Tests/Mapping/Types/Core/Range/IpRange/IpRangePropertyTests.cs
- tests/Tests/Mapping/Types/Core/Range/LongRange/LongRangePropertyTests.cs
- tests/Tests/Mapping/Types/Specialized/Ip/IpAttributeTests.cs
- tests/Tests/Mapping/Types/Specialized/Ip/IpPropertyTests.cs
- tests/Tests/Mapping/Types/Specialized/TokenCount/TokenCountPropertyTests.cs
This was always a NOOP on the server and was removed from the server.
Here we obsolete them with a compiler warning
> Mapping time boost was removed in 7.10

- src/Elasticsearch.Net/Providers/RecyclableMemoryStreamManager-Events.cs
- src/Elasticsearch.Net/Providers/RecyclableMemoryStreamManager.cs
We received a report that the finalizer of `EventPipeEventProvider` for a customer was failing on disposing the `Elasticsearch-Net-RecyclableMemoryStream`. 
By power of elimination we localized it to our counters. Initially we suspected the `instance` reference to be the problem but only removing those counters did not fix the problem.
> Remove performance counters from RecyclableMemoryStream

- src/Elasticsearch.Net/Utf8Json/JsonReader.cs
Removes a potentially breaking change for7.10 release.
> Reintroduce set for JsonParsingException.ActualChar

- src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
> [Backport 7.10] Fixing BulkAll indefinitely hanging when failing (#5077)

- src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs
> [Backport 7.x] Fixing BulkAll indefinitely hanging when failing (#5077)

- .ci/DockerFile
- .ci/Jenkins.csproj
- .ci/make.sh
- .ci/readme.md
- .ci/run-repository.ps1
- .ci/run-repository.sh
- .ci/run-tests.ps1
- .ci/test-matrix.yml
- Directory.Build.targets
- appveyor.yml
- azure-pipelines.yml
- build/scripts/Benchmarking.fs
- build/scripts/Documentation.fs
- build/scripts/ReposTooling.fs
- build/scripts/scripts.fsproj
- dotnet-tools.json
- global.json
- src/ApiGenerator/ApiGenerator.csproj
- src/DocGenerator/DocGenerator.csproj
- src/Elastic.Transport/Responses/ServerException/ServerError.cs
- src/ExamplesGenerator/ExamplesGenerator.csproj
- src/Nest/Nest.csproj
- tests/Elastic.Transport.Tests/Elastic.Transport.Tests.csproj
- tests/Examples/Examples.csproj
- tests/Tests.Benchmarking/Tests.Benchmarking.csproj
- tests/Tests.ClusterLauncher/Tests.ClusterLauncher.csproj
- tests/Tests.Reproduce/Tests.Reproduce.csproj
- tests/Tests.ScratchPad/Tests.ScratchPad.csproj
- tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
- tests/Tests/Tests.csproj
One interesting side-effect is a change to `System.Text.Json` which meant that `ErrorWithNullRootCausesTests` in the Tests project broke. Deserialisation now attempts to use ctors with parameters. The parameterless ctor is internal, and despite being reachable `System.Text.Json` is still preferring the ctor with params. However, it expects these to match the property names in the JSON so throws an exception.
A downside of this is we open up the parameterless constructor. Open to other suggestions here. A wider concern may be how this deserialisation behaves today for anyone using the library in a 5.0 runtime.
> Update to .NET 5 SDK

- src/Nest/Aggregations/Bucket/DateHistogram/DateHistogramAggregation.cs
- src/Nest/Aggregations/Bucket/Histogram/HardBounds.cs
- src/Nest/Aggregations/Bucket/Histogram/HistogramAggregation.cs
- tests/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs
- tests/Tests/Aggregations/Bucket/Histogram/HistogramAggregationUsageTests.cs
Please consider this a WIP for review to check I'm on the best track.
Adds hard_bounds parameter to histogram aggregations per https://github.com/elastic/elasticsearch/pull/59175.
Questions:
For now, I've made `HardBounds` a copy of `ExtendedBounds`. I suspect we can't safely rename this public type to something more general. An option would be to define the properties in a base class from which these two could derive. Perhaps overkill here though.
I've updated two usage tests to confirm that the final JSON is built as expected. Are there any further tests we should be considering on additional such as this one?
> Add hard_bounds for histograms

- appveyor.yml
Suggest we merge this and allow backport after backporting is complete for the main update to .NET 5 to 7.x and 7.10.
> Update VS image for AppVeyor

- .ci/DockerFile
- .ci/Jenkins.csproj
- .ci/make.sh
- .ci/readme.md
- .ci/run-repository.ps1
- .ci/run-repository.sh
- .ci/run-tests.ps1
- .ci/test-matrix.yml
- Directory.Build.targets
- appveyor.yml
- azure-pipelines.yml
- build/scripts/Benchmarking.fs
- build/scripts/Documentation.fs
- build/scripts/ReposTooling.fs
- build/scripts/scripts.fsproj
- dotnet-tools.json
- global.json
- src/ApiGenerator/ApiGenerator.csproj
- src/DocGenerator/DocGenerator.csproj
- src/Elasticsearch.Net/Elasticsearch.Net.csproj
- src/Elasticsearch.Net/Responses/ServerException/ServerError.cs
- src/Nest/Nest.csproj
- tests/Tests.Benchmarking/Tests.Benchmarking.csproj
- tests/Tests.ClusterLauncher/Tests.ClusterLauncher.csproj
- tests/Tests.Reproduce/Tests.Reproduce.csproj
- tests/Tests.ScratchPad/Tests.ScratchPad.csproj
- tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
- tests/Tests/Tests.csproj
* Update to .NET 5 SDK
* Update InternalsVisibleTo as .NET 5 SDK now supports passing a key
* Fix test after upgrading tests to net5.0
In .NET 5, System.Text.Json added support for creating types using a
constructor with parameters. Despite the internal parameterless ctor
being accessible, STJ is not using it. The solution for now seems to be
to make this public.
(cherry picked from commit fa2edcc)
> [Backport 7.x] Update to .NET 5 SDK (#5099)

- .ci/DockerFile
- .ci/Jenkins.csproj
- .ci/make.sh
- .ci/readme.md
- .ci/run-repository.ps1
- .ci/run-repository.sh
- .ci/run-tests.ps1
- .ci/test-matrix.yml
- Directory.Build.targets
- appveyor.yml
- azure-pipelines.yml
- build/scripts/Benchmarking.fs
- build/scripts/Documentation.fs
- build/scripts/ReposTooling.fs
- build/scripts/scripts.fsproj
- dotnet-tools.json
- global.json
- src/ApiGenerator/ApiGenerator.csproj
- src/DocGenerator/DocGenerator.csproj
- src/Elasticsearch.Net/Elasticsearch.Net.csproj
- src/Elasticsearch.Net/Responses/ServerException/ServerError.cs
- src/Nest/Nest.csproj
- tests/Tests.Benchmarking/Tests.Benchmarking.csproj
- tests/Tests.ClusterLauncher/Tests.ClusterLauncher.csproj
- tests/Tests.Reproduce/Tests.Reproduce.csproj
- tests/Tests.ScratchPad/Tests.ScratchPad.csproj
- tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
- tests/Tests/Tests.csproj
Includes manual fixup to account for some divergence of master and 7.10 project files.
@Mpdreamz Could we get away with labelling this with a backport 7.x label to backport the backport? I can manually apply the same changes to 7.x and open a separate PR if preferred?
> [Backport 7.10] Update to .NET 5 SDK (#5099)

- src/DocGenerator/AsciiDoc/GeneratedAsciidocVisitor.cs
- src/DocGenerator/Documentation/Blocks/CSharpBlock.cs
Exclude matching \r\n
When generating docs locally, on Windows, after running the tool, all files which include callouts then showed as modified, making review very difficult. I noticed that some of the callouts only included a newline (\n) and were missing the carriage return (\r). 
Upon investigation, I found that the regex used for callout replacement was catching and removing the \r character. This change fixes the two places such replacement may occur and ensures we stop matching before the \r\n.
I'm not super hot on Regex so welcome opinions on the approach!
> Docs generator producing bad line endings

- src/Nest/XPack/Security/Authenticate/AuthenticateResponse.cs
https://github.com/elastic/elasticsearch/pull/61247 added a new "authentication_type" field to the response of "GET _security/_authenticate". This commit adds this as a property of the `AuthenticateResponse` type.
Contributes to meta issue #5096
> Add authentication type to  AuthenticateResponse

- src/ApiGenerator/RestSpecification/_Patches/indices.flush_synced.patch.json
- src/Nest/Descriptors.Security.cs
- src/Nest/ElasticClient.Security.cs
- src/Nest/Requests.Security.cs
Adds patch for flush_synced specification.
Includes update to get-role after change to API spec identifying this is actually a comma separated list.
> Generate initial NEST code for 7.10.1

- src/Nest/Analysis/TokenFilters/WordDelimiterGraph/WordDelimiterGraphTokenFilter.cs
- tests/Tests/Analysis/TokenFilters/TokenFilterTests.cs
- tests/Tests/Analysis/TokenFilters/TokenFilterUsageTests.cs
This introduces a new property for the word delimiter graph token filter to configure ignoring of keywords.
It relates to this change https://github.com/elastic/elasticsearch/pull/59563
Contributes to #5096 
@Mpdreamz - I included more verbose XML comments for this to make usage via the Fluent API easier. I noticed that currently all descriptor methods use `/// <inheritdoc />` which seems to have no effect. Is there a reason for the existing comments? If this format is reasonable, I'd propose to spend some time updating other comments for the `WordDelimiterGraphTokenFilterDescriptor` and as I come to them, other descriptors.
> Add ignore_keywords flag to word delimiter graph

- docs/aggregations/bucket/date-histogram/date-histogram-aggregation-usage.asciidoc
Update date histogram documentation to include hard_bounds in the formatting note.
@Mpdreamz - Generated this manually on master since the ref header is expected to be different. Is this the correct approach?
> [DOCS] Update date histogram doc

- src/ApiGenerator/ApiGenerator.csproj
- src/ApiGenerator/Domain/Specification/UrlInformation.cs
- src/ApiGenerator/Program.cs
Identified a bug after creating a patch and regenerating code where the low level generate code was not rendering deprecated attributes for some methods.
The deduping logic handles aliases but does not handle non-aliased paths which is corrected by doing a final check to prefer the deprecated versions.
As far as I can tell by running the generator locally, this change doesn't seem to negatively affect any other parts of the code generation.
Additional:
- Updated the version of Spectre.Console
- Fixed breaking change from Spectre.Console
- Fixed typo
> Fix missing deprecated attributes on low-level

- src/Nest/Cat/CatNodes/CatNodesRecord.cs
Adds missing QueryCache properties to CatNodesRecord to align with the possible columns which will be returned by _cat/nodes.
There are potentially other missing columns which we'll tackle in a future issue.
For now this at least contributes to #5096
> Add QueryCache columns to CatNodesRecord

- src/Nest/Aggregations/AggregateFormatter.cs
- src/Nest/Aggregations/Metric/Boxplot/BoxplotAggregate.cs
- tests/Tests/Aggregations/Metric/Boxplot/BoxplotAggregationUsageTests.cs
In 7.11 the boxplot aggregation response includes two additional properties, lower and upper. I've added these to our type and updated the deserialization to handle these when present.
> Update BoxplotAggregate response

- src/Nest/Aggregations/AggregateFormatter.cs
The current deserialization logic does not handle additional JSON properties, being added for Elasticsearch 7.11.
This PR reads over them, if they are present to avoid an exception. Since these are not available in 7.10, we do not use the values.
> Handle additional JSON properties

- src/Nest/Descriptors.Security.cs
- src/Nest/ElasticClient.Security.cs
- src/Nest/Requests.Security.cs
- src/Nest/XPack/Security/ApiKey/GrantApiKey/ApiKey.cs
- src/Nest/XPack/Security/ApiKey/GrantApiKey/GrantApiKeyRequest.cs
- src/Nest/XPack/Security/ApiKey/GrantApiKey/GrantApiKeyResponse.cs
- src/Nest/XPack/Security/ApiKey/GrantApiKey/GrantType.cs
- src/Nest/_Generated/ApiUrlsLookup.generated.cs
- tests/Tests/XPack/Security/ApiKey/GrantApiKey/GrantApiKeyTests.cs
- tests/Tests/XPack/Security/ApiKey/GrantApiKey/GrantApiKeyUrlTests.cs
Contributes to #5096
Perhaps requires a simple test derived from `ApiTestBase` to assert on the expected JSON, URL etc? These are pretty much exercised by the main coordinated test.
> Implement grant API key

- src/Nest/Cluster/NodesStats/NodeStats.cs
- tests/Tests/Cluster/NodesStats/NodesStatsApiTests.cs
Indexing pressure stats were added in 7.9.0
https://github.com/elastic/elasticsearch/pull/59467
They were updated to include memory limit stats in 7.10.0
https://github.com/elastic/elasticsearch/pull/60342
Contributes to #5096
> Support indexing pressure on NodeStats

- src/Elastic.Transport/Diagnostics/Diagnostic.cs
- src/Elastic.Transport/Elastic.Transport.csproj
- tests/Tests.ScratchPad/Tests.ScratchPad.csproj
- tests/Tests/Search/PointInTime/Close/ClosePointInTimeApiTests.cs
- tests/Tests/Search/PointInTime/Open/OpenPointInTimeApiTests.cs
* Update `System.Diagnostics.DiagnosticSource` to use the latest 5.0.0 version which supports all targets.
* Implement `IDisposable`
* Includes fixes to point in time tests due to different transport namespace.
> [Master] Port update DiagnosticSource to 5.0.0 (#5140)

- src/ApiGenerator/Domain/Specification/UrlPart.cs
- src/ApiGenerator/RestSpecification/_Patches/security.clear_api_key_cache.patch.json
- src/Elasticsearch.Net/ElasticLowLevelClient.Security.cs
- src/Nest/Descriptors.Security.cs
- src/Nest/ElasticClient.Security.cs
- src/Nest/Requests.Security.cs
- src/Nest/XPack/Security/ApiKey/ClearApiKeyCache/ClearApiKeyCacheRequest.cs
- src/Nest/XPack/Security/ApiKey/ClearApiKeyCache/ClearApiKeyCacheResponse.cs
- src/Nest/_Generated/ApiUrlsLookup.generated.cs
- tests/Tests/XPack/Security/ApiKey/SecurityApiKeyTests.cs
- tests/Tests/XPack/Security/ApiKey/SecurityApiKeyUrlTests.cs
I updated `UrlPart` to support the use of the `Ids` type which seemed appropriate.
One query for review... The [docs for this API](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/security-api-clear-api-key-cache.html) suggest that the ids in the path can be empty to clear cache for all keys. The generated code requires the presence of an ID part and I'm not sure if this is okay or how best to address it?
Contributes to #5096
> Support clear api key cache

- src/Nest/Cluster/NodesStats/NodeStats.cs
- tests/Tests/Cluster/NodesStats/NodesStatsApiTests.cs
Manual backport of #5148 due to conflicts.
* Support indexing pressure on NodeStats
Indexing pressure stats were added in 7.9.0 https://github.com/elastic/elasticsearch/pull/59467
They were updated to include memory limit stats in 7.10.0 https://github.com/elastic/elasticsearch/pull/60342
> [Backport master] Support indexing pressure on NodeStats (#5148)

- tests/Tests/Search/PointInTime/PointInTimeApiTests.cs
Sometimes this can run with a the "took" value returning "0".
> Fix flaky test assertion for pit search

- build/scripts/Versioning.fs
Without affecting the version number stored in global.json
`.ci/make.sh` is the common entry for all clients builds and one of its
jobs is to build SNAPSHOT builds.
Long term we want to move to minver which means we no longer need to
store the version in global.json to begin with.
> Introduce assemble of SNAPSHOT builds

- .ci/make.sh
- Directory.Build.props
- appveyor.yml
- build/scripts/Building.fs
- build/scripts/Paths.fs
- build/scripts/Targets.fs
- build/scripts/Testing.fs
- build/scripts/Versioning.fs
- build/scripts/scripts.fsproj
- Tweaks to .ci/make.sh
Now also removes the specified output path, not just the hardcoded version.
Publishing nuget packages now no longer uses a special subfolder `_packages` to publish.
This to fall in line with how other clients  will use `.ci/make.sh`.
- remove references to _packages from other targets
> Tweaks .ci/make.sh to clean up after itself

- build/scripts/Versioning.fs
After adding rollForward and allowPreRelease to the global.json, this change ensures they remain present after building a release.
> Update with additional sdk version properties

- src/DocGenerator/DocGenerator.csproj
- src/DocGenerator/Documentation/Blocks/BlockCallOutHelper.cs
- src/DocGenerator/Documentation/Blocks/CSharpBlock.cs
- src/DocGenerator/Documentation/Blocks/JavaScriptBlock.cs
- src/DocGenerator/Walkers/Constants.cs
- src/DocGenerator/Walkers/JsonCallOutHelper.cs
- src/DocGenerator/Walkers/UsageTestsWalker.cs
This isn't fully featured but supports doc generation call outs for properties of JSON defined using anonymous types.
For example, the following code is defined in `DateHistogramAggregationUsageTests`:
```c#
projects_started_per_month = new
{
date_histogram = new
{
field = "startedOn",
calendar_interval = "month",
min_doc_count = 2,
format = "yyyy-MM-dd'T'HH:mm:ss||date_optional_time", // <1> Note the inclusion of `date_optional_time` to `format`
order = new { _count = "asc" },
extended_bounds = new
{
min = FixedDate.AddYears(-1),
max = FixedDate.AddYears(1)
},
missing = FixedDate
},
...
```
Currently, this callout is not rendered to the asciidoc.
This PR adds rough parsing of the code above to identify lines where a property is defined and includes a callout. This is then matched to the …
> Support call outs in JSON (JavaScript) blocks.

- docs/analysis/token-filters/token-filter-usage.asciidoc
- docs/client-concepts/troubleshooting/debug-information.asciidoc
- docs/search.asciidoc
- docs/search/request/point-in-time-usage.asciidoc
- src/Elastic.Transport/Diagnostics/TcpStats.cs
- tests/Tests/ClientConcepts/Troubleshooting/DebugInformation.doc.cs
Hi! 👋 Long time consumer, first time contributor 😊 
I had a quick look at what uses these stats, and it appears the code can handle not having any stats, so I though this was the most reasonable approach.
But happy to update with whatever you guys prefer, equally happy to close this PR and leave to the experts if I'm way off! But, thought i'd try and give back if I can.
Fixes https://github.com/elastic/elasticsearch-net/issues/5176
Thanks!
> TcpStats.GetStats() now handles error when host cannot disclose information

- src/Nest/Mapping/Types/Specialized/TokenCount/TokenCountAttribute.cs
- src/Nest/Mapping/Types/Specialized/TokenCount/TokenCountProperty.cs
- tests/Tests/Mapping/Types/Specialized/TokenCount/TokenCountAttributeTests.cs
- tests/Tests/Mapping/Types/Specialized/TokenCount/TokenCountPropertyTests.cs
This PR adds the provisioning of enable_position_increments on `ITokenCountProperty` and `ITokenCountPropertyDescriptor` The problem this PR is solving is described in detail in this Issue: https://github.com/elastic/elasticsearch-net/issues/5186
> adding support for enable_position_increments property on ITokenCountProperty

- docs/analysis/token-filters/token-filter-usage.asciidoc
- docs/client-concepts/troubleshooting/debug-information.asciidoc
- docs/search.asciidoc
- docs/search/request/point-in-time-usage.asciidoc
- src/Elasticsearch.Net/Diagnostics/TcpStats.cs
- tests/Tests/ClientConcepts/Troubleshooting/DebugInformation.doc.cs
Backport e777c37c25c0d18a8a908830b81dc5dc2a5a406e from #5177
> [Backport 7.11] TcpStats.GetStats() now handles error when host cannot disclose information

- docs/analysis/token-filters/token-filter-usage.asciidoc
- docs/client-concepts/troubleshooting/debug-information.asciidoc
- docs/search.asciidoc
- docs/search/request/point-in-time-usage.asciidoc
- src/Elasticsearch.Net/Diagnostics/TcpStats.cs
- tests/Tests/ClientConcepts/Troubleshooting/DebugInformation.doc.cs
Backport e777c37c25c0d18a8a908830b81dc5dc2a5a406e from #5177
> [Backport 7.x] TcpStats.GetStats() now handles error when host cannot disclose information

- src/Nest/Mapping/Types/Specialized/TokenCount/TokenCountAttribute.cs
- src/Nest/Mapping/Types/Specialized/TokenCount/TokenCountProperty.cs
- tests/Tests/Mapping/Types/Specialized/TokenCount/TokenCountAttributeTests.cs
- tests/Tests/Mapping/Types/Specialized/TokenCount/TokenCountPropertyTests.cs
Backport 70f9b5d8b9d84037beaf08fb0f6b948520b10111from #5188
> [Backport 7.11] Add support for enable_position_increments property on ITokenCountProperty (#5188)

- src/Nest/Mapping/Types/Specialized/TokenCount/TokenCountAttribute.cs
- src/Nest/Mapping/Types/Specialized/TokenCount/TokenCountProperty.cs
- tests/Tests/Mapping/Types/Specialized/TokenCount/TokenCountAttributeTests.cs
- tests/Tests/Mapping/Types/Specialized/TokenCount/TokenCountPropertyTests.cs
Backport 70f9b5d8b9d84037beaf08fb0f6b948520b10111from #5188
> [Backport 7.x] Add support for enable_position_increments property on ITokenCountProperty (#5188)

- src/Nest/XPack/Transform/TransformSettings.cs
- tests/Tests.Domain/Project.cs
- tests/Tests/XPack/Transform/TransformApiTests.cs
- tests/Tests/XPack/Transform/TransformApiWithSettingsTests.cs
Tests were failing due to a change in the transform API which now prefers ISO dates, rather than epoch milliseconds for dates. This resulted in a serialisation failure.
This commit addresses that by conditionally producing the requests based on the version of ES being tested, so that a property of the appropriate type is used for deserialisation of the preview.
This also adds support for the now dates_as_epoch_millis setting which allows the original epoch millisecond format to be returned for ES 7.11 requests, when the option is true.
Fixes #5185
Contributes to #5198
> Fix failing transform tests and support dates_as_epoch_millis

- docs/client-concepts/high-level/getting-started.asciidoc
- docs/client-concepts/high-level/inference/document-paths.asciidoc
- tests/Tests/ClientConcepts/HighLevel/GettingStarted.doc.cs
- tests/Tests/ClientConcepts/HighLevel/Inference/DocumentPaths.doc.cs
This commit removes the mention of document types from the Getting Started docs.
> Remove mention of type from Getting Started docs

- src/Nest/XPack/Transform/TransformSettings.cs
- tests/Tests.Domain/Project.cs
- tests/Tests/XPack/Transform/TransformApiTests.cs
- tests/Tests/XPack/Transform/TransformApiWithSettingsTests.cs
Tests were failing due to a change in the transform API which now
prefers ISO dates, rather than epoch milliseconds for dates. This
resulted in a serialisation failure.
This commit addresses that by conditionally producing the requests
based on the version of ES being tested, so that a property of the
appropriate type is used for deserialisation of the preview.
This also adds support for the now dates_as_epoch_millis setting which
allows the original epoch millisecond format to be returned for ES 7.11
requests, when the option is true.
(cherry picked from commit 7994d6fdf7734a5cb7b774e80dfc463fefd2b9cb)
Backport 7994d6fdf7734a5cb7b774e80dfc463fefd2b9cb from #5209
> [Backport master] Fix failing transform tests and support dates_as_epoch_millis

- tests/Tests.YamlRunner/SkipList.fs
Already fixed upstream but needs to find its way to the docker images.
Relates: elastic/elasticsearch#66794
> Skip 20_fvh.yml temporarily while we wait for the fix to land

- src/Nest/IndexModules/IndexSettings/Settings/AutoExpandReplicas.cs
Tiny correction to what looks like a copy-paste issue
> use correct parameter name in ArgumentException

- src/Nest/Aggregations/AggregationContainer.cs
- src/Nest/Search/Search/SearchRequest.cs
- tests/Tests.Reproduce/GithubIssue5201.cs
The Translate API in Elasticsearch returns aggregations using the key "aggregations" rather than "aggs". This results in aggregations not appearing in the `SearchRequest` instance.
This fix adds a field so that aggregations deserialise correctly using UTF8Json in the `DefaultHighLevelSerializer`.
I'll open an issue in Elasticsearch to review whether in 8.0, it should prefer "aggs" by default.
Fixes #5201
> Fix deserialisation of aggs in Translate response

- src/Nest/Indices/MappingManagement/PutMapping/PutMappingRequest.cs
- src/Nest/Mapping/Mappings.cs
- src/Nest/Mapping/RuntimeFields/RuntimeField.cs
- src/Nest/Mapping/RuntimeFields/RuntimeFields.cs
- src/Nest/Mapping/TypeMapping.cs
- src/Nest/Search/Search/SearchRequest.cs
- tests/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
- tests/Tests/Mapping/RuntimeFields/RuntimeFieldsTests.cs
This PR adds support to map runtime fields on CREATE index and PUT mapping requests. Support for searches using runtime fields will follow in another PR.
@Mpdreamz I made RuntimeFieldsDescriptor non-generic as it doesn't need anything from TDocument. This seems to work fine but I noticed that some other descriptors are generic without accessing `T` so I wanted to check if this is problematic here?
Contributes to #5198
> Support mapping runtime fields

- src/Nest/Ingest/Processors/AppendProcessor.cs
- tests/Tests/Ingest/ProcessorAssertions.cs
Related to https://github.com/elastic/elasticsearch/pull/61916
Contributes to #5198
> Support allow_duplicates on append processor

- src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
- src/Nest/Mapping/Types/FieldType.cs
- src/Nest/Mapping/Types/Properties.cs
- src/Nest/Mapping/Types/PropertyFormatter.cs
- src/Nest/Mapping/Types/Specialized/Version/VersionAttribute.cs
- src/Nest/Mapping/Types/Specialized/Version/VersionProperty.cs
- src/Nest/Mapping/Visitor/IMappingVisitor.cs
- src/Nest/Mapping/Visitor/IPropertyVisitor.cs
- src/Nest/Mapping/Visitor/MappingWalker.cs
- src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
- src/Nest/Search/FieldCapabilities/FieldCapabilitiesResponse.cs
- tests/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
- tests/Tests/Mapping/Types/Specialized/Version/VersionAttributeTests.cs
- tests/Tests/Mapping/Types/Specialized/Version/VersionPropertyTests.cs
@Mpdreamz I've attempted this by reviewing previous PRs and a bit of sleuthing! Please let me know if I've missed anything. I've been able to use the mapping on a test project.
Main challenge in naming in `FieldCapabilities` since that already has the concept of the "_version" field. I welcome opinions on the naming. Perhaps in 8.0 we can consider renaming both of these so that `Version` becomes `DocVersion`?
> Implement version field type

- src/ApiGenerator/Views/HighLevel/Descriptors/Descriptors.cshtml
- src/ApiGenerator/Views/HighLevel/Requests/Requests.cshtml
When generating code for NEST the code had numerous errors due to missing using statements. This PR fixes this for master.
> Add Nest.Utf8Json using directives to razor files

- src/Nest/IndexModules/IndexSettings/Settings/AutoExpandReplicas.cs
- tests/Tests/CommonOptions/AutoExpandReplicas/AutoExpandReplicasTests.cs
The create method was not allowing the valid value of "false".
Fixes #5258
> Fix bug in AutoExpandReplicas.Create

- tests/Tests/XPack/Sql/TranslateSql/TranslateSqlQueryApiTests.cs
Due to a [regression in 7.11](https://github.com/elastic/elasticsearch/issues/67163) currently this test fails. Once the server is fixed we can re-enable this test.
Fixes #5185
> Disable translate API test

- src/Nest/Ingest/Processors/Plugins/AttachmentProcessor.cs
- tests/Tests/Ingest/ProcessorAssertions.cs
Contributes to #5198
Relates to https://github.com/elastic/elasticsearch/pull/64389
> Support resource_name on AttachmentProcessor

- src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.AsyncSearch.cs
- src/Elasticsearch.Net/ElasticLowLevelClient.AsyncSearch.cs
- src/Nest/Descriptors.AsyncSearch.cs
- src/Nest/ElasticClient.AsyncSearch.cs
- src/Nest/Requests.AsyncSearch.cs
- src/Nest/XPack/AsyncSearch/AsyncSearch.cs
- src/Nest/XPack/AsyncSearch/Delete/AsyncSearchDeleteRequest.cs
- src/Nest/XPack/AsyncSearch/Delete/AsyncSearchDeleteResponse.cs
- src/Nest/XPack/AsyncSearch/Get/AsyncSearchGetRequest.cs
- src/Nest/XPack/AsyncSearch/Get/AsyncSearchGetResponse.cs
- src/Nest/XPack/AsyncSearch/Status/AsyncSearchStatusRequest.cs
- src/Nest/XPack/AsyncSearch/Status/AsyncSearchStatusResponse.cs
- src/Nest/XPack/AsyncSearch/Submit/AsyncSearchSubmitRequest.cs
- src/Nest/XPack/AsyncSearch/Submit/AsyncSearchSubmitResponse.cs
- src/Nest/_Generated/ApiUrlsLookup.generated.cs
- tests/Tests/XPack/AsyncSearch/AsyncSearchApiTests.cs
- tests/Tests/XPack/AsyncSearch/Status/AsyncSearchStatusUrlTests.cs
Main change to existing is removing `Response` from `AsyncSearchResponseBase` and making `AsyncSearchResponseBase` non-generic as a result. This allows the base to be used for the status response which differs by not include the response itself.
> Implement AsyncSearch Status API

- src/Nest/XPack/Security/RoleMapping/Rules/Field/DistinguishedNameRule.cs
- src/Nest/XPack/Security/RoleMapping/Rules/Field/FieldRuleBase.cs
- src/Nest/XPack/Security/RoleMapping/Rules/Field/FieldRuleBaseFormatter.cs
- src/Nest/XPack/Security/RoleMapping/Rules/Role/RoleMappingRulesDescriptor.cs
- tests/Tests.Reproduce/GitHubIssue5270.cs
- tests/Tests/XPack/Security/RoleMapping/DistinguishedNamesRoleMappingsTests.cs
When an array of DNs is returned, the array is deserialised into a new property `DistinguishedNames` on `FieldRuleBase` and the `IEnumerable<string>` is added to the backing dictionary under the key "dns".
Fixes #5270
> Fix GetRoleMappings when multiple distinguished names returned

- src/Nest/XPack/Security/RoleMapping/Rules/Field/DistinguishedNameRule.cs
- src/Nest/XPack/Security/RoleMapping/Rules/Field/FieldRuleBase.cs
- src/Nest/XPack/Security/RoleMapping/Rules/Field/FieldRuleBaseFormatter.cs
- src/Nest/XPack/Security/RoleMapping/Rules/Role/RoleMappingRulesDescriptor.cs
- tests/Tests.Reproduce/GitHubIssue5270.cs
- tests/Tests/XPack/Security/RoleMapping/DistinguishedNamesRoleMappingsTests.cs
Backport c1316d32bc749c35a5ea45f2e74553561d901bd6 from #5271
> [Backport master] Fix GetRoleMappings when multiple distinguished names returned

- src/Nest/Mapping/Types/Core/Number/NumberType.cs
- src/Nest/Mapping/Types/FieldType.cs
- src/Nest/Mapping/Types/PropertyFormatter.cs
- tests/Tests/Mapping/Types/Core/Number/NumberPropertyTests.cs
Add support for mapping an unsigned_long field. There is an issue currently with any mapping where the `null_value` needs to be provided. This is because we store that value in a `double?` property and currently, this causes a mapper_parser_exception. This has been raised for the ES team in https://github.com/elastic/elasticsearch/issues/67565
Contributes #5198
> Implement unsigned long numeric field

- src/Elasticsearch.Net/Utf8Json/Internal/DoubleConversion/StringToDoubleConverter.cs
Original code resized the static if too small but doesn't use the resized array.
Thanks to @benaadams for reporting this bug.
> Fix size overflow in StringToDoubleConverter

- src/Nest/CommonAbstractions/Request/RouteValues.cs
- src/Nest/Document/Single/Index/IndexRequest.cs
Adds a reusable `ResolvedRouteValues` instance for all requests where there are no `RouteValues`. 
This reduces allocs and improves perf slightly.
```
|           Method |      Mean |    Error |    StdDev |    Median |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------- |----------:|---------:|----------:|----------:|-------:|------:|------:|----------:|
|              Old | 222.59 ns | 9.174 ns | 26.616 ns | 212.48 ns | 0.0496 |     - |     - |     208 B |
| OldParameterless |  88.45 ns | 1.761 ns |  2.582 ns |  88.09 ns | 0.0172 |     - |     - |      72 B |
|              New | 202.92 ns | 5.285 ns |  9.117 ns | 201.08 ns | 0.0496 |     - |     - |     208 B |
| NewParameterless |  11.94 ns | 0.273 ns |  0.570 ns |  11.79 ns |      - |     - |     - |         - |
```
Gets rid of …
> Optimise RouteValues

- src/Nest/Utf8Json/Internal/DoubleConversion/StringToDoubleConverter.cs
Backport a6c529b299ee03823e530df292c70389c3d677f7 from #5294
> [Backport master] Fix size overflow in StringToDoubleConverter

- src/Nest/CommonAbstractions/Request/RouteValues.cs
- src/Nest/Document/Single/Index/IndexRequest.cs
Backport 46caff6d1b5a7cdecb39a962df0fcfdfbd132a41 from #5293
> [Backport master] Optimise RouteValues

- .ci/make.sh
- .ci/readme.md
- .ci/run-repository.ps1
- .ci/run-repository.sh
- .ci/run-tests.ps1
- .ci/test-matrix.yml
- appveyor.yml
- azure-pipelines.yml
- Update .NET SDK to latest 5.1.102
> Add missing integration test versions

- tests/Tests.YamlRunner/Models.fs
- tests/Tests.YamlRunner/SkipList.fs
- tests/Tests.YamlRunner/TestsReader.fs
- Skip cat template YAML test (#5313)
- No longer fail to parse when allowed_warnings is last in the do operation definition
> Fix parsing of some yaml tests on master

- src/Nest/XPack/Watcher/Input/ExpandWildcardsFormatter.cs
- src/Nest/XPack/Watcher/Input/IndicesOptions.cs
- tests/Tests/XPack/Watcher/GetWatch/GetWatchApiTests.cs
- tests/Tests/XPack/Watcher/PutWatch/PutWatchApiTests.cs
Since 7.10.1 the watcher expand_wildcards property has accepted and returns an array for expanded_wildcards. This broke in our existing representation of IndicesOptions during deserialisation. This change is breaking but now supports either a single string value or an array in the JSON response.
I've added an additional test to run on 7.10.1 and later to PUT and GET a watch with multiple `expand_wildcards`.
I've updated existing tests to add the optional `allow_no_indices` property due to a regression in 7.10.1 and 7.10.2 which meant missing optional fields caused a validation error on the server. This ensures the tests can run against any 7.10.x version.
> Support multiple expand_wildcards

- src/Elasticsearch.Net/Utf8Json/JsonReader.cs
(cherry picked from commit 5f937c1b3f8196306a2dbdd66ac8c66b2a9418b9)
NOTE: This should have been backported to 7.x (after fixing for 7.10) but got missed and brought back into 7.11 when I cut the branch. Will also backport to 7.x this time!
> Reintroduce set for JsonParsingException.ActualChar (#5090)

- src/Elasticsearch.Net/Diagnostics/Diagnostic.cs
Relates: elastic/apm-agent-dotnet#1094
This commit fixes a rather pernicious bug with Diagnostics from the clients,
following the upgrade to System.Diagnostics.DiagnosticSource 5.0.0.
`Diagnostic` and `Diagnostic<TState, TStateEnd>` derived from
System.Diagnostics.Activity, implementing IDisposable to make them
nicer to work with. In System.Diagnostics.DiagnosticSource 5.0.0, Activity now
implements IDisposable, so the impl was updated to override `Dispose(bool)`.
A problem arises from now deriving from Activity in that for an activity that is not finished,
`Dispose()` calls `Stop()` which in turn will notify the ActivitySource that it has stopped
**and** sets `Activity.Current` to the parent Activity (null if there's no parent). Now,
when calling into overridden `Dispose(bool)`, the …
> Fix Client Diagnostics following upgrade to DiagnosticSource 5.0.0

- build/scripts/Paths.fs
- build/scripts/ReposTooling.fs
- build/scripts/scripts.fsproj
- nuget.config
- tests/Tests.ClusterLauncher/ClusterLaunchProgram.cs
- tests/Tests.Configuration/Tests.Configuration.csproj
- tests/Tests.Core/Tests.Core.csproj
- tests/Tests.Domain/Tests.Domain.csproj
- update to latest libs from elastic/elasticsearch-net-abstractions and remove nightlies from nuget.config
- Update cluster build command so you can run clusters
You should now be able to call e.g `./build.sh cluster readonly latest-7` in a terminal and use as the cluster to run your scoped integration tests against as your developing them.
Greatly reducing the time you have to wait for the cluster to start.
> Bump testing abstraction and fix cluster run command

- tests/Tests.Core/Client/Settings/TestConnectionSettings.cs
- tests/Tests.Core/Xunit/NestXunitRunOptions.cs
Dumps all the configuration bits at the beginning of the run including
test mode and random seed information.
At the end of the run this now again produces an overview of how long
testing each cluster took.
And produce a reproduce command line that you can use to only rerun
failed collections/tests using the exact same configuration.
> Adds back additional information when running our tests

- .ci/DockerFile
- .ci/make.sh
- .ci/readme.md
- .ci/run-repository.ps1
- .ci/run-repository.sh
- .ci/run-tests.ps1
- .ci/test-matrix.yml
- appveyor.yml
- azure-pipelines.yml
- build/scripts/Commandline.fs
- build/scripts/Testing.fs
- build/scripts/Tooling.fs
- Updates the Linux and Windows VMs for Azure Pipelines to use the latest versions.
- Removes UseDotNet@2 step from Windows jobs as this is already installed
- Bumps .NET SDK to the latest patch.
> Update Azure Pipelines VMs to latest

- src/Nest/Ingest/ProcessorFormatter.cs
- src/Nest/Ingest/Processors/FingerprintProcessor.cs
- src/Nest/Ingest/ProcessorsDescriptor.cs
- tests/Tests/Ingest/ProcessorAssertions.cs
Backport 604822c5d85a5ecc77fad482028c7441058578ed from #5345
> [Backport master] Add Fingerprint ingest processor

- src/Nest/Cluster/ClusterStats/ClusterNodesStats.cs
- tests/Tests/Cluster/ClusterStats/ClusterStatsApiTests.cs
Backport e635a2b0a7503305e3f061c21a6d7fc953fe9fcf from #5338
> [Backport master] Add architecture stats to cluster node stats

- .ci/packages.lock.json
- Directory.Build.props
- build/scripts/packages.lock.json
- src/ApiGenerator/packages.lock.json
- src/DocGenerator/packages.lock.json
- tests/Tests.Benchmarking/packages.lock.json
- tests/Tests.ClusterLauncher/packages.lock.json
- tests/Tests.Configuration/packages.lock.json
- tests/Tests.Core/packages.lock.json
- tests/Tests.Domain/packages.lock.json
- tests/Tests.Reproduce/packages.lock.json
- tests/Tests.ScratchPad/packages.lock.json
- tests/Tests.YamlRunner/packages.lock.json
- tests/Tests/packages.lock.json
Due to difference in how design time and the dotnet CLI produce
package.json files.
This stabalizes the package json between builds
> Always include ReferenceAssemblies

- src/Nest/Search/Search/Sort/FieldSort.cs
- src/Nest/Search/Search/Sort/SortSpecialField.cs
- tests/Tests/Search/PointInTime/PointInTimeApiTests.cs
- tests/Tests/Search/Request/SortUsageTests.cs
> Add support for _shard_doc sort with pit

- src/Nest/XPack/Transform/TransformSource.cs
- tests/Tests/XPack/Transform/TransformApiWithSettingsTests.cs
> Support runtime fields on transforms

- src/Nest/XPack/Security/User/GetUserAccessToken/GetUserAccessTokenResponse.cs
- tests/Tests/XPack/Security/User/GetUserAccessToken/GetUserAccessTokenApiTests.cs
Updates the response as a result of this enhancement - https://github.com/elastic/elasticsearch/pull/62490
I've taken a similar approach as the server-side implementation by reusing the `AuthenticateResponse` type.
> Update get token response to include auth info

- .ci/make.sh
- .github/workflows/unified-release.yml
- build/scripts/Targets.fs
- build/scripts/scripts.fsproj
(cherry picked from commit f6cee9c417ece15fb4ed9c9eadfbd40ca20572ff)
(cherry picked from commit 67a1a5f8c49d3a1ec65a98a54c46d33444e9422f)
> [Backport 7.12] Fix make assemble to produce zip #5409

- src/Elasticsearch.Net/Auditing/Auditable.cs
- src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
- tests/Tests.Reproduce/GitHubIssue5363.cs
Resolves #5363
Allows consumers of `Auditable` to explicitly call `Stop` to set the ended `DateTime` on the `Audit` object. This ensures that by the time this is available in a DiagnosticsListener `Audit` has a valid end `DateTime` set. Otherwise, it is the default until the Auditable is disposed.
> Add explicit stop method to Auditable

- docs/aggregations.asciidoc
- docs/aggregations/bucket/multi-terms/multi-terms-aggregation-usage.asciidoc
- docs/aggregations/bucket/variable-width-histogram/variable-width-histogram-usage.asciidoc
- src/Nest/Aggregations/AggregateDictionary.cs
- src/Nest/Aggregations/AggregateFormatter.cs
- src/Nest/Aggregations/AggregationContainer.cs
- src/Nest/Aggregations/Bucket/VariableWidthHistogram/VariableWidthHistogramAggregation.cs
- src/Nest/Aggregations/Bucket/VariableWidthHistogram/VariableWidthHistogramBucket.cs
- src/Nest/Aggregations/Visitor/AggregationVisitor.cs
- src/Nest/Aggregations/Visitor/AggregationWalker.cs
- tests/Tests/Aggregations/Bucket/MultiTerms/MultiTermsAggregationUsageTests.cs
- tests/Tests/Aggregations/Bucket/VariableWidthHistogram/VariableWidthHistogramUsageTests.cs
> Add variable width histogram aggregation

- src/Nest/QueryDsl/Span/Term/SpanTermQuery.cs
- src/Nest/QueryDsl/TermLevel/Prefix/PrefixQuery.cs
- src/Nest/QueryDsl/TermLevel/Term/TermQuery.cs
- src/Nest/QueryDsl/TermLevel/Wildcard/WildcardQuery.cs
- tests/Tests/QueryDsl/TermLevel/Term/TermQueryUsageTests.cs
Resolves #5407
Note that `ISpanTermQuery` can no longer derive from `ITermQuery` as it doesn't support the `case_insenstive` option. This now manually includes and implements the value property.
> Support case_insensitive on term-based queries

- tests/Tests/Modules/SnapshotAndRestore/Snapshot/CoordinatedSnapshotTests.cs
A change in 7.12 may result in system indices such as ".tasks" being included in the snapshot which makes the assertions less deterministic. The best option is to disable the global state so that only our expected index is in the snapshot.
> Avoid global state in snapshot

- src/Nest/Analysis/Analyzers/AnalyzerFormatter.cs
- tests/Tests.Reproduce/GitHubIssue5432.cs
Fixes #5435 
Although it is recommended to define custom analyzers with `"type": "custom"` it's possible to not provide a type. This resulted in the `AnalyzerFormatter` skipping the deserialisation. This change removes the type check so that we deserialise such analyzers as custom.
> Deserialise analyzers without a type

- .ci/make.sh
- .github/workflows/make-codegen.yml
- build/scripts/Commandline.fs
- build/scripts/ReposTooling.fs
- build/scripts/Targets.fs
- build/scripts/scripts.fsproj
- src/ApiGenerator/Configuration/GeneratorLocations.cs
- src/ApiGenerator/Configuration/ViewLocations.cs
- Allow codegenerator to be run from the root
- Allow codegen to be controlled through build.sh
- update command line argument parsing
- Paths are resolved relative so make sure we have a trailing / for absolute root
- Add github scheduled tasks to regenerate integration branches
- experiment with dynamic matrix
> Introduce automated scheduled codegeneration

- .ci/DockerFile
- .ci/make.sh
- .ci/run-repository.sh
- .github/workflows/make-codegen.yml
- src/ApiGenerator/Configuration/GeneratorLocations.cs
- src/ApiGenerator/last_downloaded_version.txt
- check codegen again
- update to version of pull-request that no longer uses set-env
- remove_last_downloaded_version.txt and move it into temp directory
- run in docker as user not root so we do not have chown issues later
- update ownership in docker and no longer run as root
> Update DockerFile so that ownership of new files does not default to root

- tests/Tests/Search/Search/SearchApiTests.cs
Backport 26ccb7fb305bbc41688fa39f215760b751b7a0ad from #5462
> [Backport master] Less flaky test assertions

- .ci/make.sh
- .github/workflows/unified-release.yml
The difference a character makes.
Also added an assertion to our github action that `.ci/output` is
actually created
> Fixes the passing of args to assemble

- src/ApiGenerator/RestSpecification/_Patches/ml.preview_datafeed.patch.json
- src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.MachineLearning.cs
- src/Elasticsearch.Net/ElasticLowLevelClient.MachineLearning.cs
This was failing in YAML tests after the recent code-gen. The API supports only get but the spec included POST which was being preferred by the generator. If this all works locally I will submit a PR to fix the main spec.
We will also need to port the patch to master.
> Patch preview ML datafeed spec and re-gen code

- src/Nest/Indices/Analyze/AnalyzeToken.cs
Fixes #5498.
After [checking the ES repo](https://github.com/elastic/elasticsearch/blob/780f27306777399db574b9f9a9f44e77f41779f3/server/src/main/java/org/elasticsearch/action/admin/indices/analyze/AnalyzeAction.java#L387), this looks like it will always be returned as `positionLength`.
> Correct the JSON name for the position length on tokens

- .ci/test-matrix.yml
We previously hardcoded this due to a bug that prevented tagging the Docker images with the branch name. This has been resolved so we can return to using 7.x for this integration branch.
> Reset to branch based test matrix

- .ci/test-matrix.yml
- readme.md
- src/Nest/Cluster/NodesInfo/NodeRole.cs
- tests/Tests/Search/Search/SearchApiTests.cs
Not sure we want these lock changes but without them, it wouldn't compile locally for me.
Addresses #5484
> Update 7.11 to support tests against latest-7

- src/Elasticsearch.Net/Connection/HandlerTracking/RequestDataHttpClientFactory.cs
Backporting fix for #4818
This commit checks that _cleanupTimer is not null when disposing, which it may be if no requests have been made.
Fixes #5529
> Check _cleanupTimer is not null when disposing (backport fix/4818 to 6.x)

- tests/Tests.YamlRunner/SkipList.fs
- tests/Tests.YamlRunner/TestSuiteBootstrap.fs
Backport ddc280194c1dd122f05f980aabc774c25325a14e from #5527
> [Backport 7.x] Implement wipe cluster settings for YAML tests 

- src/ApiGenerator/Configuration/CodeConfiguration.cs
This spec was reintroduced as the API technically still exists but was deprecated before GA of 7.12.0. Since we have generated the newer API already, skipping the generation of the ML endpoint for LL code-gen.
> Skip ml.find_file_structure.json

- nuget.config
- src/Elasticsearch.Net.VirtualizedCluster/Rules/RuleBase.cs
- src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
- src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
- src/Elasticsearch.Net/Connection/Content/RequestDataContent.cs
- src/Elasticsearch.Net/Connection/HttpConnection.cs
- src/Elasticsearch.Net/Connection/InMemoryConnection.cs
- src/Elasticsearch.Net/Connection/MetaData/ClientVersionInfo.cs
- src/Elasticsearch.Net/Responses/ElasticsearchResponse.cs
- src/Elasticsearch.Net/Responses/Special/BytesResponse.cs
- src/Elasticsearch.Net/Responses/Special/StringResponse.cs
- src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
- src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
- src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
- src/Nest/ElasticClient.cs
- tests/Tests.Configuration/EnvironmentConfiguration.cs
- tests/Tests.Configuration/TestConfigurationBase.cs
- tests/Tests.Configuration/TestConfigurationExtensions.cs
- tests/Tests.Configuration/YamlConfiguration.cs
- tests/Tests.Configuration/tests.default.yaml
- tests/Tests.Core/Client/FixedResponseClient.cs
- tests/Tests.Core/Client/Settings/TestConnectionSettings.cs
- tests/Tests.Core/Xunit/NestXunitRunOptions.cs
- tests/Tests.YamlRunner/OperationExecutor.fs
- tests/Tests/ClientConcepts/Connection/HttpConnectionTests.cs
- tests/Tests/MetaHeader/MetaHeaderHelperTests.cs
- tests/Tests/XPack/Watcher/GetWatch/GetWatchApiTests.cs
- tests/Tests/XPack/Watcher/PutWatch/PutWatchApiTests.cs
Changes our default `Accept` and `Content-Type` request headers over to
the new vendor specific headers that includes compatible with
informations to start powering structurally versioned API's
```
Accept:       application/vnd.elasticsearch+json;compatible-with=7
Content-Type: application/vnd.elasticsearch+json; compatible-with=7
```
On 7.x Elasticsearch does not return the vendor type we send for
`Accept` but is still hardwired to return:
```
content-type: application/json; charset=UTF-8
```
We are therefor lenient in our Accept to Response ContentType
validations.
We do these assertions to prevent the client from de-serializing HTML
from possible proxies in the middle of the client and server.
NOTE this is for `7.13`
> Introduce compatibility header

- src/Nest/CommonOptions/Scripting/InlineScript.cs
- src/Nest/Mapping/RuntimeFields/RuntimeField.cs
- tests/Tests/ClientConcepts/HighLevel/Mapping/FluentMapping.doc.cs
- tests/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
- tests/Tests/Mapping/RuntimeFields/RuntimeFieldsTests.cs
- tests/Tests/Search/Search/SearchApiTests.cs
- tests/Tests/Search/SearchingRuntimeFields.doc.cs
- tests/Tests/XPack/Transform/TransformApiWithSettingsTests.cs
Runtime fields now support parameters in their scripts which the current `IStoredScript` interface does not support. This change updates to prefer `IInlineScript` which better aligns to the functionality of scripts in runtime fields.
This is a breaking change but should have a limited impact on existing users and ultimately is worth making to allow consumers to fully utilise runtime fields. Only code currently using runtime fields and the object initialiser syntax will need to be updated. The change is required is to create an instance of `InlineScript` rather than `PainlessScript`.
> Update RuntimeField to use IInlineScript

- NOTICE.txt
We already have license headers for the MIT projects we source includes
This PR adds a NOTICE.txt for our code and the code we source included
> Add NOTICE file

- tests/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs
When running on my PC after daylight saving changes, this sometimes fails as it sends the bounds with +01:00 which affects the assertion intermittently.
> Improve date histogram hard bounds test reliability on non-UTC systems

- tests/Tests/Aggregations/Bucket/DateHistogram/DateHistogramAggregationUsageTests.cs
Backport c1d9aea1cc36502599f73c51e212c53f15a4030d from #5547
> [Backport 7.x] Improve reliability on non-UTC systems

- docs/client-concepts/high-level/serialization/custom-serialization.asciidoc
- tests/Tests/ClientConcepts/HighLevel/Serialization/CustomSerialization.doc.cs
Fixes incorrect reference to "MyFirstCustomJsonNetSerializer" in documentation
> Fixes incorrect reference in documentation

- src/ApiGenerator/Domain/Code/LowLevel/LowLevelClientMethod.cs
- src/ApiGenerator/Domain/Specification/UrlPart.cs
- src/ApiGenerator/Domain/Specification/UrlPath.cs
- src/ApiGenerator/Extensions.cs
Some recent additions to the API spec (for example security.clear_cached_service_tokens.json), include a path part named `namespace`. Since this is a C# keyword, the generated code does not compile. This change addresses this and provides a mechanism for this and future replacements via an extension method. This method adjusts the name if it matches any reserved keywords defined in the dictionary. The variable name and the URL code call this extension to adjust accordingly.
> [Api Generator] Add mechanism to escape C# keywords for path parts

- src/DocGenerator/LitUp.cs
We now have a GitHub action that generates release notes inside the docs folder. This change ensures that the contents of this folder are preserved when the doc generator runs.
> [Docs Generator] Add step to preserve release notes folder during doc gen

- src/Elasticsearch.Net/Connection/MetaData/RuntimeVersionInfo.cs
Fixes #5575 which affects usage on Xamarin forms.
> Catch exceptions when detecting runtime version

- tests/Tests/ClientConcepts/Troubleshooting/DebugMode.doc.cs
Attempting to reduce the number of intermittent test failures from the `EnableDebugMode` tests by extending the ping timeout.
> Extend ping timeout in EnableDebugMode test

- src/Nest/Mapping/Types/Core/RankFeatures/RankFeaturesAttribute.cs
- src/Nest/Mapping/Types/Core/RankFeatures/RankFeaturesProperty.cs
> Add positive_score_impact to rank_features property

- src/Nest/Search/Search/Sort/SortBase.cs
- tests/Tests/Search/Search/SearchApiTests.cs
Includes a little whitespace cleanup.
Contributes to #5584
> Allow formatting of sort values

- src/Nest/Mapping/Types/Core/RankFeatures/RankFeaturesAttribute.cs
- src/Nest/Mapping/Types/Core/RankFeatures/RankFeaturesProperty.cs
Backport e2b2eda27bbc13d15a84e6cf9b1ce17085c97429 from #5607
> [Backport master] Add positive_score_impact to rank_features property

- src/Nest/Ingest/ProcessorFormatter.cs
- src/Nest/Ingest/Processors/NetworkDirectionProcessor.cs
- src/Nest/Ingest/Processors/RegisteredDomainProcoessor.cs
- src/Nest/Ingest/ProcessorsDescriptor.cs
- tests/Tests/Ingest/ProcessorAssertions.cs
> Add registered domain ingest processor

- src/Nest/QueryDsl/Abstractions/Container/IQueryContainer.cs
- src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
- src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
- src/Nest/QueryDsl/FullText/CombinedFields/CombinedFieldsQuery.cs
- src/Nest/QueryDsl/Query.cs
- src/Nest/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
- src/Nest/QueryDsl/Visitor/QueryVisitor.cs
- src/Nest/QueryDsl/Visitor/QueryWalker.cs
- tests/Tests/QueryDsl/FullText/CombinedFields/CombinedFieldsUsageTests.cs
> Add support for combined fields query

- src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Eql.cs
- src/Elasticsearch.Net/ElasticLowLevelClient.Eql.cs
- src/Nest/Descriptors.Eql.cs
- src/Nest/ElasticClient.Eql.cs
- src/Nest/Requests.Eql.cs
- src/Nest/XPack/Eql/Delete/EqlDeleteRequest.cs
- src/Nest/XPack/Eql/Delete/EqlDeleteResponse.cs
- src/Nest/_Generated/ApiUrlsLookup.generated.cs
- tests/Tests/XPack/Eql/Delete/EqlDeleteUrlTests.cs
- tests/Tests/XPack/Eql/EqlSearchApiCoordinatedTests.cs
Adds support for deleting a running search using EQL via the NEST client.
Contributes to #5584
> Add NEST support for EQL delete API

- .editorconfig
The `.editorconfig` change is applied by ReSharper code cleanup and avoid BOM changes affecting the check license headers action.
> Set no BOM in editorconfig

- src/Nest/Descriptors.Watcher.cs
- src/Nest/ElasticClient.Watcher.cs
- src/Nest/Requests.Watcher.cs
- src/Nest/XPack/Watcher/Query/QueryWatchesRequest.cs
- src/Nest/XPack/Watcher/Query/QueryWatchesResponse.cs
- src/Nest/_Generated/ApiUrlsLookup.generated.cs
- tests/Tests/XPack/Watcher/QueryWatches/QueryWatchesApiTests.cs
- tests/Tests/XPack/Watcher/QueryWatches/QueryWatchesUrlTests.cs
Adds support for querying watches via the NEST client.
Contributes to #5584
> Add NEST support for Query Watcher API

- .ci/test-matrix.yml
- tests/Tests/ClientConcepts/Troubleshooting/DebugMode.doc.cs
- tests/Tests/XPack/Info/XPackInfoApiTests.cs
In 7.13, flattened fields were moved to core and no longer report in the responses from the X-Pack APIs.
This PR skips those assertions when testing against 7.13.0 and higher.
> Removed flattened assertion from xpack usage tests

- src/Elasticsearch.Net/Utf8Json/Resolvers/DynamicObjectResolver.cs
When the IL generated serializer throws, we don't have a particularly useful exception for the caller. This PR addresses this with an initial improvement to throw a more specialised `AnonymousTypeSerializationException` which includes the property names and types in the message, and a `AnonymousType` property to access the original type.
Fixes #5702
> Improve anonymous serialization exception message

- nuget.config
Some CI builds and unified builds failed due to missing packages in Feedz.io after a cleanup there. These should default to restoring from NuGet.org so this adds that package source explicitly before Feedz.io.
> Add NuGet.org to package sources

- tests/Tests.YamlRunner/TestSuiteBootstrap.fs
7.x CI builds started failing due to snapshot deletion with an existing index. Moved snapshot cleanup below index and datastream cleanup.
> Reorder cleanup steps for YAML tests

- tests/Tests.YamlRunner/TestSuiteBootstrap.fs
Backport 6399e07e1c1738b0606fb7f05d10648266a6fb91 from #5729
> [Backport master] Reorder cleanup steps for YAML tests

- src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
- tests/Tests.Reproduce/GitHubIssue5730.cs
This skips MIME type validation for 204 responses and responses to HEAD requests. Elastic Cloud responses to HEAD requests strip the content-type header and this causes validation issues.
We also skip setting the body based on this same check.
Fixes #5730
> Skip MIME type validation when no body

- tests/Tests/Indices/AliasManagement/DeleteAlias/AliasDeleteApiTests.cs
With the addition of aliases for data streams, the server validates whether the index expression. If the expression matches both data streams and regular indices then a validation error is returned. This behaviour may yet be adjusted but these changes limit the test such that it targets a specific index.
> Adjust delete alias test to specify the index

- src/Nest/XPack/Watcher/Schedule/Day.cs
- src/Nest/XPack/Watcher/Watch.cs
- tests/Tests/XPack/Watcher/PutWatch/PutWatchApiTests.cs
- tests/Tests/XPack/Watcher/WatcherCluster.cs
- tests/Tests/XPack/Watcher/WatcherCoordinatedTests.cs
Relates to #5725 by fixing the `Day` enum JSON strings such that they can be deserialised correctly. Watcher in general may need more work to make working with the `GetWatch` response easier but that is difficult without breaking the models. This will be improved in vNext with code-gen.
> Fix weekly schedule deserialisation

- azure-pipelines.yml
- src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs
- src/Elasticsearch.Net/Configuration/IConnectionConfigurationValues.cs
- src/Elasticsearch.Net/Providers/MemoryStreamFactory.cs
- src/Elasticsearch.Net/Providers/RecyclableMemoryStreamFactory.cs
Port of change from 7.x.
Provides a saner, more predictable default value that can be configured to enable pooling if the consumer desires.
> [6.x] Switch default memory stream factory

- .ci/run-elasticsearch.ps1
- .ci/run-elasticsearch.sh
When Elasticsearch CI runs, the geoip database downloader is disabled and as a result, the index is not created. This change matches the configuration when running the .NET YAML tests to avoid assertion failures due to the `.geoip_database` index appearing in `/_cat/*` responses.
> Disable GeoIP database

- docs/client-concepts/high-level/mapping/fluent-mapping.asciidoc
- docs/query-dsl.asciidoc
- docs/query-dsl/full-text/combined-fields/combined-fields-usage.asciidoc
- docs/query-dsl/geo/bounding-box/geo-bounding-box-query-usage.asciidoc
- docs/search/request/search-after-usage.asciidoc
- docs/search/searching-runtime-fields.asciidoc
- src/Nest/Indices/MappingManagement/GetMapping/GetMappingResponse.cs
- src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
- src/Nest/Mapping/Types/Core/DenseVector/DenseVectorAttribute.cs
- src/Nest/Mapping/Types/Core/DenseVector/DenseVectorProperty.cs
- src/Nest/Mapping/Types/FieldType.cs
- src/Nest/Mapping/Types/Properties.cs
- src/Nest/Mapping/Types/PropertyFormatter.cs
- src/Nest/Mapping/Visitor/IMappingVisitor.cs
- src/Nest/Mapping/Visitor/IPropertyVisitor.cs
- src/Nest/Mapping/Visitor/MappingWalker.cs
- src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
- src/Nest/Search/FieldCapabilities/FieldCapabilitiesResponse.cs
- tests/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
- tests/Tests/Mapping/Types/Core/DenseVector/DenseVectorAttributeTests.cs
- tests/Tests/Mapping/Types/Core/DenseVector/DenseVectorPropertyTests.cs
Backport 94be96ed6d613b8aceac5d55287eb5e56a550489 from #5780
> [Backport master] Add support for dense vector field

- src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
- src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
Repeat calls to ExistsAsync can cause the connection limit to be reached as the optimized code which ensures we correctly handle cloud responses may not always run, leaving the response stream and therefore the connection open. This causes the default connection limit of 80 to be reached.
This fix ensures we correctly dispose of the response stream in all code paths.
Fixes #5775
> Ensure we dispose of the response stream in all cases

- src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
- src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
Backport 364ca23274e891edbca6473290100bbfc521dbbd from #5785
> [Backport 7.13] Ensure we dispose of the response stream in all cases

- src/Nest/Mapping/DynamicTemplate/SingleMapping.cs
- src/Nest/Mapping/Types/Core/MatchOnlyText/MatchOnlyTextAttribute.cs
- src/Nest/Mapping/Types/Core/MatchOnlyText/MatchOnlyTextProperty.cs
- src/Nest/Mapping/Types/FieldType.cs
- src/Nest/Mapping/Types/Properties.cs
- src/Nest/Mapping/Types/PropertyFormatter.cs
- src/Nest/Mapping/Visitor/IMappingVisitor.cs
- src/Nest/Mapping/Visitor/IPropertyVisitor.cs
- src/Nest/Mapping/Visitor/MappingWalker.cs
- src/Nest/Mapping/Visitor/NoopPropertyVisitor.cs
- src/Nest/Search/FieldCapabilities/FieldCapabilitiesResponse.cs
- tests/Tests/Indices/MappingManagement/GetMapping/GetMappingApiTest.cs
- tests/Tests/Mapping/Types/Core/DenseVector/DenseVectorPropertyTests.cs
- tests/Tests/Mapping/Types/Core/MatchOnlyText/MatchOnlyTextAttributeTests.cs
- tests/Tests/Mapping/Types/Core/MatchOnlyText/MatchOnlyTextPropertyTests.cs
> Add match_only_text field

- src/Nest/Cluster/TaskManagement/GetTask/TaskInfo.cs
- tests/Tests/Cluster/TaskManagement/GetTask/GetTaskApiTests.cs
> Add cancelled property to taskinfo

- src/Nest/XPack/Ilm/Policy.cs
- tests/Tests/XPack/Ilm/IlmApiTests.cs
> Support _meta on ILM policy

- tests/Tests.YamlRunner/SkipList.fs
This test uses set operations as a way to alias into the response, however, the YAML runner doesn't handle this right now as it stores the Dictionary of entries from that location resulting in an invalid path string that cannot be resolved from the response.
We may be able to tweak the runner to handle this but this needs further review.
> Skip disk usage test

- src/ApiGenerator/Configuration/SkippedUrls.cs
- src/ApiGenerator/Domain/Code/HighLevel/Requests/Constructor.cs
- src/ApiGenerator/Domain/Specification/ApiEndpoint.cs
- src/ApiGenerator/Domain/Specification/UrlInformation.cs
Now that we generate deprecated URLs to avoid breaking changes in minors, this adds a quite low-tech way to skip URLs that were ignored since 7.0.0 and for which we don't want to re-add actors and properties.
This could have been bolted onto the overrides but I decided on a simpler approach since we expect to replace this code-gen for vNext anyway.
> Tweak code-gen to skip historically ignored URLs

- src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Sql.cs
- src/Elasticsearch.Net/ElasticLowLevelClient.Sql.cs
- src/Nest/Descriptors.Sql.cs
- src/Nest/ElasticClient.Sql.cs
- src/Nest/Requests.Sql.cs
- src/Nest/XPack/Sql/Get/SqlGetRequest.cs
- src/Nest/XPack/Sql/Get/SqlGetResponse.cs
- src/Nest/XPack/Sql/Status/SqlSearchStatusRequest.cs
- src/Nest/_Generated/ApiUrlsLookup.generated.cs
- tests/Tests/XPack/Sql/Get/SqlGetUrlTests.cs
Manual backport (with fresh code gen) of #5861
> [master] Support get async SQL search API

- src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
Lazily caches the Uri on RequestData since this property is accessed at least three times and each time was allocating a new Uri. This saves 192 bytes per request.
This optimisation is one of three added to the new `Elastic.Transport` project that was suitable to backport to 7.x.
> [perf] Reduce allocations on some transport paths

- src/Nest/XPack/Sql/QuerySql/QuerySqlRequest.cs
- src/Nest/XPack/Sql/QuerySql/QuerySqlResponse.cs
- src/Nest/XPack/Sql/Status/SqlSearchStatusResponse.cs
- tests/Tests/XPack/Sql/SqlSearchApiCoordinatedTests.cs
Allows SQL searches to be made asynchronous and accepts the ID so that the status API can be used to check when complete.
> Support async SQL searches

- tests/Tests/XPack/MachineLearning/MachineLearningInfo/MachineLearningInfoApiTests.cs
7.14.0 has switched to using the `ml_standard` by default.
> Update ML info assertion

- tests/Tests/XPack/Sql/SqlSearchApiCoordinatedTests.cs
This ensures that if the search has completed by the time the status check runs, we validate accordingly.
> Add conditional test assertions to SQL async search status check

- src/Nest/XPack/Watcher/Schedule/ScheduleContainer.cs
- tests/Tests/XPack/Watcher/WatcherScheduleCoordinatedTests.cs
A previous PR #5761 improved serialisation and deserialisation of watcher trigger schedules. However, I missed the hourly case which this PR addresses.
> Fix hourly watcher scheduler serialisation

- tests/Tests.YamlRunner/SkipList.fs
These are failing in CI for the same reason as disk usage. They use set in a way that the YAML runner is not able to handle.
> Skip field usage YAML tests

- src/Elasticsearch.Net/Transport/Pipeline/ProductCheckStatus.cs
- src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs
When a transient error occurs during the product check, we add a warning to the debug information. This PR makes the warning clearer and explains the actual failure.
> Improve warning for transient product check failures

- tests/Tests/Modules/SnapshotAndRestore/Repositories/CoordinatedRepositoryTests.cs
In some cases the reads may be empty and the assertion should handle that.
> Improve repository analyse assertions

- tests/Tests.YamlRunner/SkipList.fs
Backport e366a817034d05cf35b533b7a3c03ffe5afef58d from #5894
> Skip field usage YAML tests (#5894)

- src/Elasticsearch.Net.VirtualizedCluster/VirtualCluster.cs
- src/Elasticsearch.Net.VirtualizedCluster/VirtualClusterWith.cs
- src/Elasticsearch.Net/Connection/HttpConnection.cs
- src/Elasticsearch.Net/Connection/HttpWebRequestConnection.cs
- src/Elasticsearch.Net/Connection/InMemoryConnection.cs
- src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
- src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs
- tests/Tests.Core/Client/FixedResponseClient.cs
- tests/Tests.Reproduce/GitHubIssue5730.cs
- tests/Tests/ClientConcepts/ConnectionPooling/ProductChecking/ProductCheckAtStartup.doc.cs
- tests/Tests/MetaHeader/MetaHeaderHelperTests.cs
Adds method overloads rather than new optional parameters.
> Refactor product check changes to avoid binary breaks

- readme.md
Backport 683ee4a30daf66110b36a4f3be2300a49edade4d from #5932
> [Backport 7.14] Update compatibility matrix to reflect supported version

- src/Nest.JsonNetSerializer/packages.lock.json
- tests/Tests.Benchmarking/packages.lock.json
Regenerated all package lock files after the hash for `7.13.0-ci20210301T140449` seems to have changed.
> Regenerate package lock files

- src/DocGenerator/packages.lock.json
- src/Nest.JsonNetSerializer/packages.lock.json
- src/Nest/Aggregations/AggregateFormatter.cs
- tests/Tests.Benchmarking/BulkBenchmarkTests.cs
- tests/Tests.Benchmarking/Tests.Benchmarking.csproj
- tests/Tests.Benchmarking/packages.lock.json
- tests/Tests.ClusterLauncher/packages.lock.json
- tests/Tests.Core/packages.lock.json
- tests/Tests.Domain/packages.lock.json
- tests/Tests.Reproduce/GitHubIssue5962.cs
- tests/Tests.Reproduce/packages.lock.json
- tests/Tests.ScratchPad/packages.lock.json
- tests/Tests/packages.lock.json
Fixes #5962 by ensuring that a multi-terms bucket containing a boolean value can be read correctly.
> Fix AggregateFormatter to read boolean values

- src/Nest/Search/Search/SearchRequest.cs
- src/Nest/XPack/AsyncSearch/Submit/AsyncSearchSubmitRequest.cs
Async search should accept the same options as regular search and is missing support for PIT, Fields and Runtime fields. This PR ports those to AsyncSearch.
Skipped ISlicedScroll Slice as this is a deprecated choice going forward.
Closes #5988
> Support PIT, Fields and RuntimeFields on AsyncSearch

- tests/Tests/XPack/Info/XPackInfoApiTests.cs
This is removed in 7.15.0 - See https://github.com/elastic/elasticsearch/pull/76068
> Remove vectors feature check in 7.15+

- build/scripts/ReleaseNotes.fs
- build/scripts/XmlDocPatcher.fs
- src/Nest/Ingest/Pipeline.cs
- src/Nest/Ingest/Processor.cs
- src/Nest/Ingest/PutPipeline/PutPipelineRequest.cs
- tests/Tests.Configuration/tests.default.yaml
- tests/Tests.YamlRunner/SkipList.fs
- tests/Tests/Ingest/PipelineCrudTests.cs
Fixes #6082
The version field was missing from our `IPipeline` model.
- Unrelated F# cleanup to fix compiler errors
- Support version of ingest pipelines
- Skip YAML test which cannot be parsed
> Support version on ingest pipelines

- src/Nest/CommonOptions/Scripting/ScriptFormatter.cs
- tests/Tests.Reproduce/GitHubIssue5684.cs
Fixes #5684
Some basic scripts are stored and returned as a string, rather than an object. This change ensures we can deserialise such scripts.
> Support deserialisation of simple scripts

- src/Nest/Aggregations/AggregateFormatter.cs
- src/Nest/Aggregations/Metric/Boxplot/BoxplotAggregate.cs
- src/Nest/CommonAbstractions/SerializationBehavior/JsonFormatters/NullableStringBooleanFormatter.cs
- tests/Tests.Reproduce/GitHubIssue6050.cs
Fixes #6050
Adds a double formatter that can handle non-numeric values of "NaN", "Infinity" and "-Infinity" that may be returned for the `double` values of the `BoxplotAggregate".
> Update boxplot to handle non-numeric values

- src/ApiGenerator/Configuration/Overrides/Endpoints/SearchTemplateOverrides.cs
- src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.NoNamespace.cs
- src/Nest/Descriptors.NoNamespace.cs
- src/Nest/Requests.NoNamespace.cs
- src/Nest/Search/SearchTemplate/SearchTemplateRequest.cs
> Move explain to body in search template API

- .github/workflows/integration-jobs.yml
Historically in v7 we only ran read-only and writeable tests in CI. Other test clusters tended to be too brittle but ran fine locally. This PR re-enables all tests in CI as we're adding things back and can hopefully remove/fix unstable tests.
> Enable more CI integration test clusters

- docs/connecting.asciidoc
- docs/high-level.asciidoc
- docs/index.asciidoc
This PR adds a `Connecting` section to the documentation.
[Connecting](https://elasticsearch-net_6183.docs-preview.app.elstc.co/guide/en/elasticsearch/client/net-api/master/connecting.html)
> [DOCS] Adds Connecting section to docs

- docs/connecting.asciidoc
- docs/high-level.asciidoc
- docs/index.asciidoc
This PR backports the following changes to the 8.0 branch: 
[DOCS] Adds Connecting section to docs #6183
> [8.0][DOCS] Adds Connecting section to docs (#6183)

- src/Elastic.Clients.Elasticsearch/Helpers/BulkAllObservable.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Indices.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
- tests/Tests.Core/ManagedElasticsearch/NodeSeeders/DefaultSeeder.cs
While the IndexManagement namespace is still required to avoid type/namespace conflicts from code generation, this PR ensures that we maintain better compatibility with the naming of the client property used to access the indices APIs. Previously this picked up the "IndexManagement" naming but now matches `7.x` using "Indices".
> Rename `IndexManagement` client property to `Indices`

- src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
Fixes #6260 
**Fix content-type validation for API versioning on NETFX**
HttpWebResponse strips whitespace from headers such as `Content-Type` which causes the validation of responses from `8.x` servers to be considered invalid and potentially fail. This fix ensures we fall back to comparing the header against a version with the whitespace removed.
> Fix API versioning validation on NETFX

- src/Elasticsearch.Net/Transport/Pipeline/RequestData.cs
Backports 3b1c7f8ced16b750e3cc89733b9e571996228cdd from #6263
> [Backport 7.x] Fix content-type validation for API versioning on NETFX

- docs/client-concepts/connection/connecting-to-elasticsearch-v8.asciidoc
- tests/Tests/ClientConcepts/Connection/ConnectingToElasticsearchV8.doc.cs
> Minor corrections to v8 compatibility doc

- tests/Tests.ClusterLauncher/packages.lock.json
- tests/Tests.Configuration/Tests.Configuration.csproj
- tests/Tests.Configuration/packages.lock.json
- tests/Tests.Core/Tests.Core.csproj
- tests/Tests.Core/packages.lock.json
- tests/Tests.Domain/Tests.Domain.csproj
- tests/Tests.Domain/packages.lock.json
- tests/Tests/packages.lock.json
The v0.3.1 `Elastic.Elasticsearch.Managed` library includes a change to account for a change in the 8.3.0 log messages that resulted in a started node not being identified during integration testing. This PR updates the tests to use the fixed version.
> Update to 0.3.1 abstractions

- src/Nest/Indices/Analyze/AnalyzeToken.cs
api return positionLength but nest is expecting a different name, so it is always null on nest response.
> Fix PositionLength JSON name on AnalyzeToken

- src/Nest/XPack/Ilm/Actions/SearchableSnapshotAction.cs
- src/Nest/XPack/Ilm/LifecycleActions.cs
Fixes #6262 by adding the missing `searchable_snapshot` index lifecycle action.
> Add searchable snapshot action for ILM

- Directory.Build.targets
This target was [removed](https://github.com/elastic/elasticsearch-net/commit/900088a947a461fcd64a891694c09ec385bc8a26#diff-50e91c82311ea26f2a73202525dfdf2b0a89c178ee666b2bf3ad4c84ac4c06dc) as part of the .NET 5 upgrade which appears to be an error. Reintroducing the target which should hopefully resolve the issue.
> Reintroduce AssemblyInfos target

- build/scripts/scripts.fsproj
- src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
- src/Elastic.Clients.Elasticsearch/Helpers/BulkAllObservable.cs
- src/Elastic.Clients.Elasticsearch/packages.lock.json
Adds async analyzer and applies fixes.
> Async fixes

- docs/client-concepts/connection-pooling/exceptions/unrecoverable-exceptions.asciidoc
- docs/client-concepts/high-level/getting-started.asciidoc
- docs/configuration.asciidoc
- docs/high-level.asciidoc
- docs/index.asciidoc
- docs/redirects.asciidoc
This PR adds a `Configuration` section to the .NET docs with some configuration options.
Improved version of [DOCS] Adds Configuration section to the client docs #6387
> [DOCS] Adds Configuration section to the client docs

- docs/client-concepts/connection/connecting-to-elasticsearch-v8.asciidoc
- tests/Tests/ClientConcepts/Certificates/WorkingWithCertificates.doc.cs
- tests/Tests/ClientConcepts/Connection/ConnectingToElasticsearchV8.doc.cs
Use HTTPS URL in connecting to v8 documentation.
> Fix code snippet in documentation

- src/Nest/Aggregations/AggregationContainer.cs
- src/Nest/Search/Search/SearchRequest.cs
- src/Nest/XPack/AsyncSearch/Submit/AsyncSearchSubmitRequest.cs
- tests/Tests.Configuration/tests.default.yaml
- tests/Tests/Aggregations/SearchAggregationSerializationTests.cs
When using the object initializer syntax, aggregations can appear in the request twice. This is harmless but wastes bytes and has an added serialization overhead.
This PR ensures we retain the ability to deserialize from either name ("aggs" or "aggregations") but all serialization using "aggs" as standard.
> Fix duplicate object serialization of aggregations

- src/Elastic.Clients.Elasticsearch/Common/Infer/IndexName/IndexName.cs
- src/Elastic.Clients.Elasticsearch/Common/UrlParameters/Username/Username.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/ScrollResponse.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchResponse.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/AsyncSearch/AsyncSearch.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Security.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Migration/MigrationFeature.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/ResponseBody.g.cs
- tests/Tests/AsyncSearch/AsyncSearchApiTests.cs
- tests/Tests/Common/Infer/Indices/IndicesTests.cs
- tests/Tests/Serialization/Documents/MGetSerialization.cs
- tests/Tests/_VerifySnapshots/IndicesSerializationTests.Deserializes_All_Correctly.verified.txt
- tests/Tests/_VerifySnapshots/MGetSerialization.DeserializesError.verified.txt
- Update to latest schema
- Don't simplify ScrollId on responses
> Avoid simplifying scroll IDs on responses

- src/Elastic.Clients.Elasticsearch/Types/Bulk/BulkUpdateOperation.cs
- src/Elastic.Clients.Elasticsearch/Types/Bulk/BulkUpdateOperationDescriptor.cs
- tests/Tests/Serialization/Bulk/BulkOperationCollectionSerializationTests.cs
- tests/Tests/Serialization/Bulk/BulkUpdateOperationSerializationTests.cs
- tests/Tests/_VerifySnapshots/BulkUpdateOperationSerializationTests.Serializes_With_StoredScriptId.verified.txt
Adds overload to the update operation descriptor to support providing an `Action<StoredScriptIdDescriptor>`.
Fixes #6554
> Support stored scripts for update

- build/scripts/Versioning.fs
The existing logic and branching strategy leads to some confusing versioning on CI packages. When the current version in `global.json` is `8.0.0-beta.1`, the CI package is pushed as `8.1.0-CI{TIMESTAMP}`. Similarly, if the 8.1 branch version were `8.1.0` then the CI package would be `8.2.0-CI{TIMESTAMP}` which would actually belong to the 8.2 branch.
This PR adjusts the logic for canary packages to increment the patch number for standard releases. For pre-releases it removes the pre-release element, keeping the version the same. So if the current release is `8.0.0-beta.1`, the CI package would be `8.0.0-CI{TIMESTAMP}`.
> Adjust logic for CI versioning

- src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient.cs
- src/Elastic.Clients.Elasticsearch/Serialization/CustomizedNamingPolicy.cs
- src/Elastic.Clients.Elasticsearch/Serialization/DefaultRequestResponseSerializer.cs
- src/Elastic.Clients.Elasticsearch/Serialization/FieldNameQueryConverterBase.cs
- src/Elastic.Clients.Elasticsearch/Serialization/JsonSerializerOptionsExtensions.cs
- tests/Tests/Serialization/Queries/SearchSerializationTests.cs
- tests/Tests/_VerifySnapshots/SearchSerializationTests.Search_WithMatchQuery_SerializesInferredField_ForObjectInitializer.verified.txt
Fixes #6557 
- Add `ConditionalWeakTable` to client.
- Updates `FieldNameQueryConverterBase` to use inferrer from settings, retrieved from `ConditionalWeakTable`.
> Fix field name query converter

- docs/install.asciidoc
Backport #6558 from ebde26a32101cc2cc6cf8006f594bfcea06f3d21
> [Backport 8.0] Command line to add package is incorrect.

- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/AdjacencyMatrixAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/AggregationContainer.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/AutoDateHistogramAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/ChildrenAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/CompositeAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/DateHistogramAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/DateRangeAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/FiltersAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/GlobalAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/HistogramAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/IpRangeAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/MissingAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/MultiTermsAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/NestedAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/ParentAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/RangeAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/ReverseNestedAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/SamplerAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/TermsAggregation.g.cs
- tests/Tests/Aggregations/Bucket/DateHistogramAggregationUsageTests.cs
After the inheritance work, sub-aggregations for bucket aggregations were missing. The code-generator has been updated to copy these up from inherited classes.
> Reintroduce sub-aggregations for bucket aggs

- src/Elastic.Clients.Elasticsearch/Types/Aggregations/AggregateDictionary.cs
- src/Elastic.Clients.Elasticsearch/Types/Aggregations/TermsAggregate.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/AdjacencyMatrixAggregate.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/AutoDateHistogramAggregate.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/CompositeAggregate.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/DateHistogramAggregate.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/DateRangeAggregate.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/DoubleTermsAggregate.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/FiltersAggregate.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/HistogramAggregate.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/IpRangeAggregate.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/LongTermsAggregate.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/MultiTermsAggregate.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/RangeAggregate.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/StringTermsAggregate.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/VariableWidthHistogramAggregate.g.cs
- tests/Tests/Aggregations/Bucket/TermsAggregationUsageTests.cs
- tests/Tests/Serialization/Aggregations/BucketSubAggregationSerializationTests.cs
- tests/Tests/Serialization/Aggregations/ChildrenAggregateSerializationTests.cs
- tests/Tests/Serialization/Aggregations/TermsAggregateDeserializationTests.cs
After flattening the inheritance hierarchy for types, multi-bucket aggregates lost their derived manual handling for the buckets property which opts to avoid the use of a union by preventing the use of keyed buckets. This PR reapplies the fixup for these types as part of code generation.
> Fix buckets type for multi-bucket aggregates

- docs/connecting.asciidoc
- docs/index.asciidoc
- docs/redirects.asciidoc
This PR backports the changes of https://github.com/elastic/elasticsearch-net/pull/6655 to the 8.5 branch.
> [Backport 8.5][DOCS] Removes outdated pages from docs

- docs/connecting.asciidoc
- docs/index.asciidoc
- docs/redirects.asciidoc
This PR backports the changes of https://github.com/elastic/elasticsearch-net/pull/6655 to the 8.3 branch.
> [Backport 8.3][DOCS] Removes outdated pages from docs

- docs/connecting.asciidoc
- docs/index.asciidoc
- docs/redirects.asciidoc
This PR backports the changes of https://github.com/elastic/elasticsearch-net/pull/6655 to the 8.2 branch.
> [Backport 8.2][DOCS] Removes outdated pages from docs

- docs/connecting.asciidoc
- docs/index.asciidoc
- docs/redirects.asciidoc
This PR backports the changes of https://github.com/elastic/elasticsearch-net/pull/6655 to the 8.1 branch.
> [Backport 8.1][DOCS] Removes outdated pages from docs

- docs/connecting.asciidoc
- docs/index.asciidoc
- docs/redirects.asciidoc
This PR backports the changes of https://github.com/elastic/elasticsearch-net/pull/6655 to the 8.0 branch.
> [Backport 8.0][DOCS] Removes outdated pages from docs

- docs/connecting.asciidoc
- docs/index.asciidoc
- docs/redirects.asciidoc
This PR backports the changes of https://github.com/elastic/elasticsearch-net/pull/6655 to the 8.4 branch.
> [Backport 8.4][DOCS] Removes outdated pages from docs

- src/Elastic.Clients.Elasticsearch/Common/Aggregations/AggregationDictionary.cs
- tests/Tests/Serialization/Aggregations/WritingAggregationsTests.cs
Simplify add method to avoid duplication of the name.
> Refine AggregationDictionary

- src/Elastic.Clients.Elasticsearch/Serialization/EnumStructConverter.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchResponse.g.cs
- tests/Tests/IndexManagement/CreateIndexSerializationTests.cs
- tests/Tests/IndexManagement/IndexSettingsSerializationTests.cs
- tests/Tests/_VerifySnapshots/CreateIndexSerializationTests.CreateIndexWithAliases_SerializesCorrectly.verified.txt
> Fix dictionary key serialization for Name type

- src/Nest/Aggregations/Bucket/VariableWidthHistogram/VariableWidthHistogramAggregation.cs
- tests/Tests/Aggregations/Bucket/VariableWidthHistogram/VariableWidthHistogramUsageTests.cs
A very minor feature enhancement. ElasticSearch supports an inline script property on the VariableWidthHistogram. This PR makes this supported by the high level NEST client.
This is already supported by the `MultiTermsAggregation` https://github.com/elastic/elasticsearch-net/blob/96f36d0bbd47aefd781502cf0373df81ad686602/src/Nest/Aggregations/Bucket/MultiTerms/MultiTermsAggregation.cs#L54
--
There is a useful use-case for this enhancement which is to bucket ranges on the log scale on the VariableWidthHistogram. This results in a more even distribution.
Example of use case
```
GET arc-37-5/_search
{
"aggs": {
"prices": {
"variable_width_histogram": {
"field": "lot.sold_prices_usd",
"script": {
"source": "Math.log10(_value)"
},
"buckets": 300
}
}
},
"size": 0
}
```
```
{
"took" : 0, …
```
> Add script property to variable width histogram

- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/Buckets.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/FieldDateMath.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/Percentiles.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/CharFilter.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/TokenFilter.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/Tokenizer.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/RequestItem.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/ResponseItem.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/SearchResponseItem.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/SourceConfig.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/SourceConfigParam.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/TrackHits.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/GeoHashPrecision.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/Like.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/RangeQuery.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/SimpleQueryStringFlags.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/TermsQueryField.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Script.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Slices.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Tasks/TaskInfos.g.cs
> Apply codegenNames for union parameters

- src/Elastic.Clients.Elasticsearch/Types/Mapping/Properties.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/Analyzers.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/CharFilterDefinitions.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/Normalizers.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/TokenFilterDefinitions.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/TokenizerDefinitions.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Mapping/Properties.g.cs
Adds TryGet methods to access the variant of internally tagged unions.
> Add TryGet methods for internally tagged unions

- Directory.Build.targets
- src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient-BulkAll.cs
- src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient-Manual.cs
- src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient.cs
- src/Elastic.Clients.Elasticsearch/Client/IndicesNamespace.cs
- src/Elastic.Clients.Elasticsearch/Client/NamespacedClientProxy.cs
- src/Elastic.Clients.Elasticsearch/Core/Exceptions/ThrowHelper.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.AsyncSearch.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Cluster.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Eql.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Indices.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Sql.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
- src/Playground/Playground.csproj
- src/Playground/Program.cs
- src/Playground/packages.lock.json
- src/PlaygroundV7x/PlaygroundV7x.csproj
- src/PlaygroundV7x/packages.lock.json
- tests/Tests.ClusterLauncher/Tests.ClusterLauncher.csproj
Improves user testing in scenarios where no consumer abstraction exists.
> Make ElasticsearchClient more mockable

- docs/release-notes/release-notes-8.0.2.asciidoc
- docs/release-notes/release-notes.asciidoc
> Add 8.0.2 release notes

- benchmarks/Benchmarks/packages.lock.json
- benchmarks/Profiling/packages.lock.json
- src/Elastic.Clients.Elasticsearch.JsonNetSerializer/packages.lock.json
- src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient.cs
- src/Elastic.Clients.Elasticsearch/Client/ElasticsearchResponseBaseExtensions.cs
- src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
- src/Elastic.Clients.Elasticsearch/Helpers/BulkAllObservable.cs
- src/Elastic.Clients.Elasticsearch/packages.lock.json
- src/Playground/packages.lock.json
- tests/Tests.ClusterLauncher/packages.lock.json
- tests/Tests.Core/Client/FixedResponseClient.cs
- tests/Tests.Core/Extensions/ShouldExtensions.cs
- tests/Tests.Core/packages.lock.json
- tests/Tests.Domain/packages.lock.json
- tests/Tests/Tests.csproj
- tests/Tests/packages.lock.json
Update to transport which includes sending rest API compatibility headers.
> Update to Elastic.Transport 0.4.5

- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/MultiTermLookup.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.IndexManagement.g.cs
> Update generated code with fixes from 8.6 specification

- src/Elastic.Clients.Elasticsearch/Types/SourceConfig.cs
- tests/Tests/Search/Search/SearchRequestSerialization.cs
- tests/Tests/_VerifySnapshots/SearchRequestSerialization.SearchRequestWithSourceProperty_SerializesCorrectly.verified.txt
> Implement Write method on SourceConfigConverter

- .github/workflows/auto-label.yml
- .github/workflows/integration-jobs.yml
- .github/workflows/license.yml
- .github/workflows/make-bump.yml
- .github/workflows/make-codegen.yml
- .github/workflows/make-release-notes.yml
- .github/workflows/stale-jobs.yml
- .github/workflows/test-jobs.yml
- .github/workflows/unified-release.yml
Backport 1aa68e7c4d407d70a903bbde63471e7d02800238 from #7412
> [Backport 8.2] Update GitHub action versions in workflows.

- src/Elastic.Clients.Elasticsearch/Types/QueryDsl/FunctionScore.cs
- src/Elastic.Clients.Elasticsearch/Types/Scripting/InlineScript.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/Aggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/InferenceConfig.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Search/FieldSuggester.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Search/SmoothingModel.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/Action.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Ingest/InferenceConfig.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Ingest/Processor.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/InferenceConfigCreate.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/InferenceConfigUpdate.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Ml/TokenizationConfig.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/FunctionScore.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/Intervals.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/IntervalsFilter.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/IntervalsQuery.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/Query.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/SpanQuery.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/TransformManagement/PivotGroupBy.g.cs
- tests/Tests/Framework/EndpointTests/ApiTestBase.cs
- tests/Tests/QueryDsl/Compound/BoolQueryUsageTests.cs
- tests/Tests/QueryDsl/Compound/FunctionScoreQueryUsageTests.cs
- tests/Tests/_VerifySnapshots/FunctionScoreQueryUsageTests.VerifyDescriptorJson.verified.txt
- tests/Tests/_VerifySnapshots/FunctionScoreQueryUsageTests.VerifyInitializerJson.verified.txt
> Support weight score on FunctionScore.

- exclusion.dic
- src/Elastic.Clients.Elasticsearch/Serialization/DefaultSourceSerializer.cs
- src/Elastic.Clients.Elasticsearch/Serialization/DoubleWithFractionalPortionConverter.cs
- src/Elastic.Clients.Elasticsearch/Serialization/FloatWithFractionalPortionConverter.cs
- src/Elastic.Clients.Elasticsearch/Serialization/JsonConstants.cs
- tests/Tests/Serialization/SerializerTestBase.cs
- tests/Tests/Serialization/SourceSerializationForNumericPropertiesTests.cs
> Source serialization always sends fractional format for double and floats.

- src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryCacheStats.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/SegmentsStats.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/StoreStats.g.cs
Backport d6c0eace281a71074ac754cff4e23b2d5a85b56b from #7446
> [Backport 8.0] Fix byte properties in index stats types. 

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.7`:
> [8.7] [DOCS] Creates custom landing page for the .NET client book

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.3`:
> [8.3] [DOCS] Creates custom landing page for the .NET client book

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.4`:
> [8.4] [DOCS] Creates custom landing page for the .NET client book

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.5`:
> [8.5] [DOCS] Creates custom landing page for the .NET client book

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.6`:
> [8.6] [DOCS] Creates custom landing page for the .NET client book

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.6`:
- [[DOCS] Changes hero image to contain .NET logo](https://github.com/elastic/elasticsearch-net/pull/7507)
> [8.6] [DOCS] Changes hero image to contain .NET logo

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.5`:
- [[DOCS] Changes hero image to contain .NET logo](https://github.com/elastic/elasticsearch-net/pull/7507)
> [8.5] [DOCS] Changes hero image to contain .NET logo

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.4`:
- [[DOCS] Changes hero image to contain .NET logo](https://github.com/elastic/elasticsearch-net/pull/7507)
> [8.4] [DOCS] Changes hero image to contain .NET logo

- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.AsyncSearch.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Cluster.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.DanglingIndices.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Enrich.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Eql.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Graph.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Indices.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Ingest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Sql.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.Tasks.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
> Ensure async client methods pass through cancellation token

- src/Elastic.Clients.Elasticsearch/Serialization/Stringified.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/AsyncSearch/SubmitAsyncSearchRequest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/LimitTokenCountTokenFilter.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/StemmerTokenFilter.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/MSearch/MultisearchBody.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndexSettingBlocks.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndexSettings.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/MergeScheduler.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/SettingsAnalyze.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/SettingsQueryString.g.cs
> Regenerate with latest spec fixes for 8.7

- src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndexSettingBlocks.g.cs
> Regen index setting blocks based on fixed spec

- src/Elastic.Clients.Elasticsearch/Serialization/DoubleWithFractionalPortionConverter.cs
- src/Elastic.Clients.Elasticsearch/Serialization/FloatWithFractionalPortionConverter.cs
In both `DoubleWithFractionalPortionConverter` and `FloatWithFractionalPortionConverter`, when building for non NETCore there is a missing `return` statement that makes the code always fall through into `ThrowHelper.ThrowJsonException($"Unable to serialize float value.");`
This fix just adds the missing `return` statements. I can't find that tests are run for net4x (which I guess is how this was unnoticed) so I haven't tried adding any new tests to cover this case.
Fixes #7757
>  Number converters should not fall through and throw exceptions in non NETCore builds

- src/Elastic.Clients.Elasticsearch/Serialization/UnionConverter.cs
> Complted buckets JSON converter

- src/Elastic.Clients.Elasticsearch/Core/Infer/Field/FieldConverter.cs
This pull request has three commits:
1. Optimizes read and writes using prencoded property names:
1.1. Reading doesn't allocate and decode a JSON property name.
1.2. Writing doesn't encode property names.
2. Writing has two length checks less, one for each property name write since there's a limit for non-encoded literals.
3. Since any interpolated string using static values is preprocessed and turned into a constant string type names where replaced by `nameof(Field)` expressions.
4. `null` values are handled by the writer itself ([see this](https://github.com/dotnet/runtime/blob/bdf5df39c4749dd88cf45de008f9f3c2d5905fba/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs#L188-L189)).
> Optimized `FieldConverter`

- src/Elastic.Clients.Elasticsearch/Core/Infer/Field/Field.cs
Since the `Field` type has a JSON converter specified through an attribute, member attributes are ignored. Therefore, `JsonIgnore` has no effect at all and can be removed.
> Removed unused `JsonIgnore`

- src/Elastic.Clients.Elasticsearch/Core/Infer/Metric/Metrics.cs
`HashSet<T>` doesn't override `GetHashCode`. Therefore, the default provided algorithm for reference types is used which doesn't take fields into account as it happens for value types. That breaks the equality contracts on Metrics.
Ideally `HashCode` type should be used for more correct computations with less number of collisions, but that requires increasing the minimal target framework.
`SetEqual` is available since .NET Fx 3.5 and is destined for equality comparison of two different hash set instances. Since both instances of the `Metrics` type has the same default comparer, the method works as a sugar over a length check followed by iteration over one set and probing the second one for containing the current element through the `Contains` method.
> Fixed the equality contract on Metrics type

- src/Elastic.Clients.Elasticsearch/Core/Infer/Id/Ids.cs
- src/Elastic.Clients.Elasticsearch/Core/Infer/Id/IdsConverter.cs
This pull request:
* fixes `null` handling contradiction between `Ids` constructors;
* moves `IdsConverter` to a separate file as its for `IdConverter`.
> Refactoring and tiny behavior fix for Ids

- src/Elastic.Clients.Elasticsearch/Core/Fields/FieldValue.cs
- src/Elastic.Clients.Elasticsearch/Serialization/DoubleWithFractionalPortionConverter.cs
- src/Elastic.Clients.Elasticsearch/Serialization/FloatWithFractionalPortionConverter.cs
Fixes deserialization of "floating-point strings" on machines with German localization:
```
FAIL  Tests.Serialization.SourceSerializationForNumericPropertiesTests.DoubleAsString_DeserializesCorrectly
Expected deserialized.Double to be 1.0, but found 10.0.
..........................................................................
FAIL  Tests.Common.Fields.FieldValueTests.CanSerialize_DoubleFieldValueKind
Expected result.FieldValue.ToString() to be "1.1", but "1,1" differs near ",1" (index 1).
```
> Fix localization issue with floating-point deserialization from string

- README.md
- docs/getting-started.asciidoc
This PR adds links to the different sections of the README file that point to the corresponding section of the getting started page. This way only the getting started documentation needs to be maintained and it will be the source of truth.
Should be backported to 8.1.
> [DOCS] Restructures repo README

- src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/TextExpansionQuery.g.cs
Regenerated the client to apply the recent specification changes regarding `text_expansion`.
> Fix `TextExpansionQuery` definition

- src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient.cs
- src/Elastic.Clients.Elasticsearch/Client/NamespacedClientProxy.cs
- Simplify overloads and avoid repeated code
- Ensure we pass the cancellation token to transport
We had a chunk of repeated code which was hard to keep in sync. As these are all internal methods, I've restructured the overloads and removed a redundant one. Currently, we don't use the `forceConfiguration` overload, which we should probably review and either remove those overloads or reintroduce NEST force config behaviour.
This also fixes a bug where we don't always pass the cancellation token on transport calls making it impossible for some requests to be cooperatively cancelled.
> Refactor client overloads

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.10`:
> [8.10] [DOCS] Fix `welcome-to-elastic` link (#7932)

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.9`:
> [8.9] [DOCS] Fix `welcome-to-elastic` link (#7932)

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.8`:
> [8.8] [DOCS] Fix `welcome-to-elastic` link (#7932)

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.7`:
> [8.7] [DOCS] Fix `welcome-to-elastic` link (#7932)

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.6`:
> [8.6] [DOCS] Fix `welcome-to-elastic` link (#7932)

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.5`:
> [8.5] [DOCS] Fix `welcome-to-elastic` link (#7932)

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.4`:
> [8.4] [DOCS] Fix `welcome-to-elastic` link (#7932)

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.3`:
> [8.3] [DOCS] Fix `welcome-to-elastic` link (#7932)

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.2`:
> [8.2] [DOCS] Fix `welcome-to-elastic` link (#7932)

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.1`:
> [8.1] [DOCS] Fix `welcome-to-elastic` link (#7932)

- docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.0`:
> [8.0] [DOCS] Fix `welcome-to-elastic` link (#7932)

- docs/release-notes/release-notes.asciidoc
This PR adds the `release-notes-8.10.0` file to the list of included files in the `release-notes.asciidoc` index to fix a broken docs build.
> [DOCS] Includes 8.10.0 release note file in index

- src/Elastic.Clients.Elasticsearch.Shared/Serialization/Stringified.cs
Fix `Stringified` converters to allow them being used on non-nullable types.
As, for example, `Nullable<int>` and `int` are distinct types, STJ refused to work with the `StringifiedInt<int?>` converter if used on a simple `int` property.
STJ does not invoke custom converters for `null` values unless the converter opts-in by returning `true` in the `HandleNull` method. As we don't do this, we don't have to care about `null` in the converter itself.
Handling e.g. just `int` instead of `int?` in the stringified converter, allows us to annotate `int` and `int?` properties correctly without having to introduce another converter type.
Closes #7870
> Fix `Stringified` converters

- src/Elastic.Clients.Elasticsearch.Shared/Serialization/DefaultRequestResponseSerializer.cs
> Add workaround for stringified properties which are not marked properly in specification

- README.md
- docs/install.asciidoc
This PR adds a compatibility matrix to the Installation section of the .NET book and the repo readme.
[Compatibility](https://elasticsearch-net_bk_8045.docs-preview.app.elstc.co/guide/en/elasticsearch/client/net-api/master/installation.html#compatibility)
> [DOCS] Adds compatibility matrix to the docs and readme

- .github/.editorconfig
- .github/.gitattributes
- .github/workflows/release.yml
- .github/workflows/release_serverless.yml
- .github/workflows/release_stack.yml
- Packages.Serverless.slnf
- Packages.Stack.slnf
Adds a bassic release workflow that is triggered by publishing releases on GitHub.
- Automatically convert the Markdown release notes to the AsciiDocs format and push to the correct branches (e.g. `serverless` or `main` and `8.x`
- Automatically create reference documentation for new versions using DocFX and publish to a central place (e.g. GitHub Pages)
> Add basic CD workflow

- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Api/AsyncSearch/SubmitAsyncSearchRequest.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Api/Eql/EqlSearchRequest.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Api/SearchMvtRequest.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Api/SearchRequest.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/Aggregations/BucketSortAggregation.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/Aggregations/TopHitsAggregation.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/Aggregations/TopMetricsAggregation.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/Core/Reindex/Source.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/Core/Search/FieldCollapse.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/Core/Search/InnerHits.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/KnnQuery.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/QueryDsl/BoolQuery.g.cs
- src/Elastic.Clients.Elasticsearch.Shared/Core/Infer/Fields/FieldsConverter.cs
- src/Elastic.Clients.Elasticsearch.Shared/Serialization/SingleOrManySerializationHelper.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/AsyncSearch/SubmitAsyncSearchRequest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/Eql/EqlSearchRequest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchMvtRequest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchRequest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/BucketSortAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/TopHitsAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/TopMetricsAggregation.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Reindex/Source.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Search/FieldCollapse.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Search/InnerHits.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/KnnQuery.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/BoolQuery.g.cs
> Improve serialization of "single-or-many" properties

- src/Elastic.Clients.Elasticsearch.Shared/Types/QueryDsl/RangeQuery.cs
Closes #8080
This is just a temporary workaround that will be removed as soon as we implement generation of descriptors for union types.
> Reintroduce fluent API for `RangeQuery`

- src/Elastic.Clients.Elasticsearch.Shared/Serialization/SystemTextJsonSerializer.cs
> Fix serializer indentation

- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Api/DeleteRequest.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Api/ExistsRequest.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Api/ExistsSourceRequest.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Api/ExplainRequest.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Api/GetRequest.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Api/GetSourceRequest.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Api/TermVectorsRequest.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Api/UpdateRequest.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Client/ElasticsearchClient.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/DeleteRequest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/ExistsRequest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/ExistsSourceRequest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/ExplainRequest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/GetRequest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/GetSourceRequest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/TermVectorsRequest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/UpdateRequest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Client/ElasticsearchClient.g.cs
Generate missing inference constructor overloads.
> Generate inference constructor overloads

- src/Elastic.Clients.Elasticsearch.Shared/Core/Extensions/Extensions.cs
- src/Elastic.Clients.Elasticsearch.Shared/Core/Infer/Field/Field.cs
- src/Elastic.Clients.Elasticsearch.Shared/Core/Infer/Fields/Fields.cs
- src/Elastic.Clients.Elasticsearch.Shared/Core/Infer/Id/Ids.cs
- src/Elastic.Clients.Elasticsearch.Shared/Core/Infer/Indices/Indices.cs
- src/Elastic.Clients.Elasticsearch.Shared/Core/Infer/JoinFieldRouting/Routing.cs
- src/Elastic.Clients.Elasticsearch.Shared/Core/UrlParameters/DataStreamNames/DataStreamNames.cs
- src/Elastic.Clients.Elasticsearch.Shared/Core/UrlParameters/Name/Names.cs
- src/Elastic.Clients.Elasticsearch.Shared/Core/UrlParameters/NodeIds/NodeIds.cs
- src/Elastic.Clients.Elasticsearch.Shared/Core/UrlParameters/ScrollIds/ScrollIds.cs
Adds correct nullability annotations and static factory methods as an alternative for each implicit conversion operator.
Closes #8152
> Refactor `Field` and `Fields`

- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/IndexManagement/MappingLimitSettingsDepth.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/IndexManagement/MappingLimitSettingsDimensionFields.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/IndexManagement/MappingLimitSettingsNestedFields.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/IndexManagement/MappingLimitSettingsNestedObjects.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/IndexManagement/MappingLimitSettingsTotalFields.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/MappingLimitSettingsDepth.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/MappingLimitSettingsDimensionFields.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/MappingLimitSettingsNestedFields.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/MappingLimitSettingsNestedObjects.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/MappingLimitSettingsTotalFields.g.cs
> Change mapping limit type from `int` -> `long`

- src/Elastic.Clients.Elasticsearch.Shared/Client/ElasticsearchClient.Esql.cs
- src/Elastic.Clients.Elasticsearch.Shared/Client/NamespacedClientProxy.cs
Implements the `QueryAsObjects` high level API. This API allows ESQL query results to be consumed in a similar way to the regular QueryDSL.
> Add `Esql.QueryAsObjects` high level API

- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/QueryDsl/IntervalsQuery.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/QueryDsl/IntervalsQuery.g.cs
> Add missing `Field` property to `IntervalsQuery`

- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/Core/MSearch/MultisearchBody.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/IndexManagement/IndexSettings.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/MachineLearning/InferenceResponseResult.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/Inference/DeleteInferenceRequest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/Inference/DeleteInferenceResponse.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/MSearch/MultisearchBody.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/IndexManagement/IndexSettings.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/MachineLearning/InferenceResponseResult.g.cs
> Regenerate client using the latest spec

- src/Elastic.Clients.Elasticsearch.Shared/Client/ElasticsearchClient.cs
> Do not check product status for non-success responses

- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Api/AsyncSearch/SubmitAsyncSearchRequest.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Api/SearchRequest.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/Core/MSearch/MultisearchBody.g.cs
- src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/Core/Search/SourceFilter.g.cs
- src/Elastic.Clients.Elasticsearch.Shared/Core/Infer/Field/Field.cs
- src/Elastic.Clients.Elasticsearch.Shared/Core/Infer/Fields/Fields.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/AsyncSearch/SubmitAsyncSearchRequest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/SearchRequest.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/MSearch/MultisearchBody.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Core/Search/SourceFilter.g.cs
Fix (de-)serialization of `Fields` in custom converters.
Performance can be improved in a second step by reusing a static instance of the converters.
> Fix (de-)serialization of `Fields` in custom converters

- src/Elastic.Clients.Elasticsearch.Shared/Core/Response/DictionaryResponse.cs
This is an intermediate fix that allows access to the protected `DictionaryResponse.BackingDictionary` field to allow using the results of e.g. `Indices.GetSettings` or `Snapshot.GetRepository`.
Closes #8352
Closes #8266
Closes #8115
> Introduce `DictionaryResponse.Values`

- src/Elastic.Clients.Elasticsearch.Shared/Core/Configuration/ElasticsearchClientSettings.cs
Configure `DefaultFieldNameInferrer` to use `JsonSerializerOptions.PropertyNamingPolicy`, if the `DefaultSourceSerializer` is used.
The other way around is already implemented. If the `DefaultSourceSerializer` is used and the `DefaultFieldNameInferrer`  is changed, the `JsonSerializerOptions.PropertyNamingPolicy` gets configured to use a custom `PropertyNamingPolicy` that applies the `DefaultFieldNameInferrer` transformations.
Closes #8357
> Synchronize `DefaultFieldNameInferrer` and `JsonSerializerOptions.PropertyNamingPolicy`

- docs/intro.asciidoc
- Fix egregious typos and grammar issues
- Edits for style; more idiomatic expressions
- Shorter is better
> [DOCS] Spruce up the Introduction

- docs/index.asciidoc
- docs/usage/aggregations.asciidoc
- docs/usage/index.asciidoc
- docs/usage/mappings.asciidoc
- docs/usage/query.asciidoc
Adds copy/paste-able examples for very common use-cases.
> Add more examples to the documentation

- src/Elastic.Clients.Elasticsearch.Shared/Api/Extensions/CreateIndexRequestDescriptorExtensions.cs
- src/Elastic.Clients.Elasticsearch/_Shared/Api/IndexManagement/ExistsAliasResponse.cs
- src/Elastic.Clients.Elasticsearch/_Shared/Api/IndexManagement/ExistsIndexTemplateResponse.cs
- src/Elastic.Clients.Elasticsearch/_Shared/Api/IndexManagement/ExistsTemplateResponse.cs
This improves the developer experience with extension methods to simplify adding alias(es) to an index at creation time using the `CreateIndexRequestDescriptor` and `CreateIndexRequestDescriptor<T>`.
This also fixes up some incorrect namespaces in some of the manual files.
> Add `WithAlias` extensions for CreateIndexRequestDescriptor

- docs/migration-guide.asciidoc
- docs/usage/index.asciidoc
- docs/usage/transport.asciidoc
- src/Elastic.Clients.Elasticsearch.Serverless/Core/ElasticsearchClientProductRegistration.cs
- src/Elastic.Clients.Elasticsearch.Serverless/Elastic.Clients.Elasticsearch.Serverless.csproj
- src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
- src/Elastic.Clients.Elasticsearch/_Shared/Api/Esql/EsqlQueryRequest.cs
- src/Elastic.Clients.Elasticsearch/_Shared/Client/ElasticsearchClient.cs
- src/Playground/Playground.csproj
- tests/Tests.Core/Client/FixedResponseClient.cs
- tests/Tests/ClientConcepts/OpenTelemetry/OpenTelemetryTests.cs
Update `Elastic.Transport` to `0.5.4`.
> Update `Elastic.Transport` to `0.5.4`

- src/Elastic.Clients.Elasticsearch.Serverless/Elastic.Clients.Elasticsearch.Serverless.csproj
- src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
- src/Playground/Playground.csproj
Fixes a `NullReferenceException` when instrumentation is used.
> Update `Elastic.Transport` to `0.5.6`

- src/Elastic.Clients.Elasticsearch.Serverless/Elastic.Clients.Elasticsearch.Serverless.csproj
- src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
- src/Playground/Playground.csproj
Fixes `PostData.MultiJson` not working correctly when `DisableDirectStreaming` is used.
> Update `Elastic.Transport` to `0.5.7`

- src/Elastic.Clients.Elasticsearch/_Shared/Serialization/DefaultRequestResponseSerializer.cs
- src/Elastic.Clients.Elasticsearch/_Shared/Serialization/DefaultSourceSerializer.cs
In some rare occasions, we are observing `System.ArgumentException: An item with the same key has already been added. at System.Runtime.CompilerServices.ConditionalWeakTable``2.Add(TKey key, TValue value)`  when adding entries to `SettingsTable`.
I added a lock similar to https://github.com/elastic/apm-agent-dotnet/blob/c4c0649dc18ad15fd89f9a878db8c1b80a103dab/src/Elastic.Apm/Logging/ScopedLogger.cs#L15 to address this issue.
> Fix potential ArgumentException with ConditionalWeakTable

- src/Elastic.Clients.Elasticsearch/_Shared/Serialization/DefaultRequestResponseSerializer.cs
- src/Elastic.Clients.Elasticsearch/_Shared/Serialization/DefaultSourceSerializer.cs
> Fix potential ArgumentException with ConditionalWeakTable (#8444)

- docs/reference/migration-guide.md
- docs/reference/using-net-client.md
Follow up to #8460 
When using cross-repo links, the path should be relative to the `docset.yml` not the full path within the repo ([updated docs-builder docs](https://elastic.github.io/docs-builder/syntax/links/#cross-repository-links)).
> [docs] Clean up cross-repo links

- docs/release-notes/breaking-changes.md
- docs/release-notes/index.md
https://github.com/elastic/elasticsearch-net/pull/8485 has broken our documentation build. This PR fixes broken links.
> fix doc build

- docs/reference/getting-started.md
- docs/reference/troubleshoot/logging-with-fiddler.md
Fixes image paths to work with docs-assembler.
Notes for the reviewer:
* I was not able to get images in reference, extend, or release-notes to work using the `:::{image}` syntax because it seems to resolve differently than the Markdown `![]()` syntax. We should address this in docs-builder, but in order to get images working as soon as possible, I've used Markdown syntax and left us a `TO DO` in a code comment to add back the `screenshot` class where applicable. 
* Can you please add the appropriate labels needed for backporting?
> [docs] Fix image paths for docs-assembler

- src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
- src/Elastic.Clients.Elasticsearch/_Shared/Client/ElasticsearchClient.cs
- src/Elastic.Clients.Elasticsearch/_Shared/Client/NamespacedClientProxy.cs
- src/Elastic.Clients.Elasticsearch/_Shared/Core/Configuration/ElasticsearchClientSettings.cs
- src/Elastic.Clients.Elasticsearch/_Shared/Core/Configuration/IElasticsearchClientSettings.cs
- src/Elastic.Clients.Elasticsearch/_Shared/Core/Request/Request.cs
- src/Playground/Playground.csproj
> [Backport] Add `OnBeforeRequest` callback (#8541)

- src/Elastic.Clients.Elasticsearch/_Generated/Api/IndexManagement/GetAliasResponse.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Api/Inference/PutAlibabacloudResponse.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Enums/Enums.Inference.g.cs
- src/Elastic.Clients.Elasticsearch/_Generated/Types/Inference/CohereServiceSettings.g.cs
> Regenerate client

- src/Elastic.Clients.Elasticsearch/_Shared/Serialization/KeyValuePairConverter.cs
> Allow `KeyValuePairConverter` to work with non `IUrlParameter` keys

- README.md
- docs/reference/breaking-changes-policy.md
- docs/reference/index.md
- docs/reference/toc.yml
> Add versioning section to readme and docs

- README.md
> [8.19] Add versioning section to readme and docs

- src/Elastic.Clients.Elasticsearch/_Shared/Core/UrlParameters/Username/Username.cs
- src/Elastic.Clients.Elasticsearch/_Shared/Types/GeoBounds.cs
- src/Elastic.Clients.Elasticsearch/_Shared/Types/GeoLocation.cs
As titled. As well fixes deserialization of `Username`.
> Add deserialization support for `GeoBounds` and `GeoLocation`

- src/Elastic.Clients.Elasticsearch/_Shared/Api/BulkRequest.cs
- src/Elastic.Clients.Elasticsearch/_Shared/Api/MultiSearchRequest.cs
- src/Elastic.Clients.Elasticsearch/_Shared/Api/MultiSearchTemplateRequest.cs
It would be nice to enable NetAnalyzers to flag such cases.
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1826
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1829
> Use Count instead of Count()

- docs/reference/transport.md
Fixes a missing quote reported in https://github.com/elastic/docs-content/issues/2164
Closes: https://github.com/elastic/docs-content/issues/2164
> Fix missing quote in docs example

- .buildkite/DockerFile
- .ci/DockerFile
- Elasticsearch.sln
- examples/aot/Program.cs
- examples/aot/aot.csproj
- src/Elastic.Clients.Elasticsearch/Elastic.Clients.Elasticsearch.csproj
- src/Elastic.Clients.Elasticsearch/_Shared/Core/Infer/DynamicPropertyAccessor.cs
- src/Playground/Person.cs
- src/Playground/Playground.csproj
> Add AOT example

- docs/reference/request-response-serialization.md
- docs/reference/serialization.md
- docs/reference/toc.yml
> Add documentation for client type serialization

- src/Elastic.Clients.Elasticsearch/_Shared/Client/ElasticsearchClient.Esql.cs
> Allow `Esql.QueryAsObjects()` to work with nested types
